import { Degree } from "@/types/university";

/**
 * COMPREHENSIVE PROGRAM ALLOCATION SYSTEM
 *
 * This file contains ALL programs specified by the user with proper allocation rules
 * and university-specific APS requirements.
 */

// University abbreviation mappings for easy reference
const UNIVERSITY_MAPPINGS = {
  UCT: "uct",
  WITS: "wits",
  SU: "su",
  UP: "up",
  UWC: "uwc",
  UNISA: "unisa",
  UFH: "ufh",
  UJ: "uj",
  RU: "ru",
  TUT: "tut",
  DUT: "dut",
  MUT: "mut",
  VUT: "vut",
  CPUT: "cput",
  CUT: "cut",
  UZ: "uz",
  UL: "ul",
  NWU: "nwu",
  UV: "uv",
  WSU: "wsu",
  UMP: "ump",
  UKZN: "ukzn",
  UNIVEN: "univen",
  SMU: "smu",
  UFS: "ufs",
  SPU: "spu",
  UNIZUL: "unizul",
} as const;

// Helper function to generate university-specific APS scores
const generateUniversityAPS = (
  baseAPS: number,
  universityType: string,
  universityId: string,
  isCompetitive: boolean = false,
): number => {
  let apsScore = baseAPS;

  // Adjust based on university prestige and type
  const prestigeAdjustments: Record<string, number> = {
    uct: 3,
    wits: 3,
    su: 2,
    up: 2,
    ukzn: 1,
    ufs: 1,
    tut: -1,
    dut: -1,
    mut: -2,
    vut: -2,
    cput: -1,
    cut: -2,
    uj: 0,
    unisa: -3,
    unizul: -1,
    uv: -1,
    wsu: -2,
    ump: -1,
  };

  apsScore += prestigeAdjustments[universityId] || 0;

  // Additional adjustment for competitive programs
  if (isCompetitive) {
    apsScore += universityId === "uct" || universityId === "wits" ? 2 : 1;
  }

  // Ensure minimum APS of 20 and maximum of 42
  return Math.max(20, Math.min(42, apsScore));
};

// Program allocation rules interface
interface ProgramAllocation {
  name: string;
  faculty: string;
  baseAPS: number;
  duration: string;
  description: string;
  allocation: "all" | { exclude: string[] } | { include: string[] };
  isCompetitive?: boolean;
  careerProspects: string[];
}

// Complete program allocation database with ALL specified programs
export const COMPREHENSIVE_PROGRAMS: ProgramAllocation[] = [
  // Faculty of Engineering / Engineering and Built Environment
  {
    name: "Civil Engineering",
    faculty: "Engineering",
    baseAPS: 35,
    duration: "4 years",
    description:
      "Design, construct and maintain civil infrastructure including buildings, roads, bridges, and water systems.",
    allocation: { exclude: ["uwc", "unisa", "ufh"] },
    isCompetitive: true,
    careerProspects: [
      "Civil Engineer",
      "Structural Engineer",
      "Project Manager",
      "Construction Manager",
      "Infrastructure Consultant",
    ],
  },
  {
    name: "Mechanical Engineering",
    faculty: "Engineering",
    baseAPS: 35,
    duration: "4 years",
    description:
      "Design, develop and manufacture mechanical systems, machines and devices.",
    allocation: { exclude: ["uwc", "unisa", "ufh"] },
    isCompetitive: true,
    careerProspects: [
      "Mechanical Engineer",
      "Design Engineer",
      "Manufacturing Engineer",
      "Energy Engineer",
      "Automotive Engineer",
    ],
  },
  {
    name: "Electrical Engineering",
    faculty: "Engineering",
    baseAPS: 36,
    duration: "4 years",
    description:
      "Design and develop electrical systems, electronics, and power systems.",
    allocation: { exclude: ["uwc", "unisa", "ufh"] },
    isCompetitive: true,
    careerProspects: [
      "Electrical Engineer",
      "Power Systems Engineer",
      "Electronics Engineer",
      "Control Systems Engineer",
      "Telecommunications Engineer",
    ],
  },
  {
    name: "Chemical Engineering",
    faculty: "Engineering",
    baseAPS: 37,
    duration: "4 years",
    description:
      "Apply chemistry and physics principles to transform raw materials into useful products.",
    allocation: { exclude: ["uj", "unisa", "ufh"] },
    isCompetitive: true,
    careerProspects: [
      "Chemical Engineer",
      "Process Engineer",
      "Environmental Engineer",
      "Petroleum Engineer",
      "Materials Engineer",
    ],
  },
  {
    name: "Industrial Engineering",
    faculty: "Engineering",
    baseAPS: 34,
    duration: "4 years",
    description:
      "Optimize complex processes and systems for efficiency and productivity.",
    allocation: { exclude: ["uwc", "unisa"] },
    isCompetitive: true,
    careerProspects: [
      "Industrial Engineer",
      "Operations Manager",
      "Quality Engineer",
      "Systems Analyst",
      "Supply Chain Manager",
    ],
  },
  {
    name: "Computer Engineering",
    faculty: "Engineering",
    baseAPS: 36,
    duration: "4 years",
    description: "Design and develop computer hardware and software systems.",
    allocation: { exclude: ["uct", "up", "unisa"] },
    isCompetitive: true,
    careerProspects: [
      "Computer Engineer",
      "Hardware Engineer",
      "Software Engineer",
      "Systems Engineer",
      "Embedded Systems Developer",
    ],
  },
  {
    name: "Mechatronics",
    faculty: "Engineering",
    baseAPS: 35,
    duration: "4 years",
    description:
      "Integrate mechanical, electrical and computer engineering for intelligent systems.",
    allocation: { exclude: ["uwc", "unisa", "ufh", "mut"] },
    isCompetitive: true,
    careerProspects: [
      "Mechatronics Engineer",
      "Automation Engineer",
      "Robotics Engineer",
      "Control Systems Engineer",
      "Design Engineer",
    ],
  },
  {
    name: "Mining Engineering",
    faculty: "Engineering",
    baseAPS: 34,
    duration: "4 years",
    description:
      "Extract minerals and resources from the earth safely and efficiently.",
    allocation: { exclude: ["uwc", "unisa", "ufh", "ru"] },
    isCompetitive: true,
    careerProspects: [
      "Mining Engineer",
      "Mine Manager",
      "Geological Engineer",
      "Safety Engineer",
      "Environmental Engineer",
    ],
  },
  {
    name: "Environmental Engineering",
    faculty: "Engineering",
    baseAPS: 33,
    duration: "4 years",
    description: "Design systems to protect and improve environmental quality.",
    allocation: { exclude: ["uwc", "unisa"] },
    careerProspects: [
      "Environmental Engineer",
      "Water Treatment Engineer",
      "Air Quality Engineer",
      "Waste Management Engineer",
      "Environmental Consultant",
    ],
  },
  {
    name: "Agricultural Engineering",
    faculty: "Engineering",
    baseAPS: 32,
    duration: "4 years",
    description:
      "Apply engineering principles to agricultural and biological systems.",
    allocation: { exclude: ["uwc", "unisa", "ufh"] },
    careerProspects: [
      "Agricultural Engineer",
      "Irrigation Engineer",
      "Food Processing Engineer",
      "Farm Manager",
      "Agricultural Consultant",
    ],
  },
  {
    name: "Structural Engineering",
    faculty: "Engineering",
    baseAPS: 36,
    duration: "4 years",
    description:
      "Design and analyze structural systems for buildings and infrastructure.",
    allocation: { exclude: ["uwc", "unisa"] },
    isCompetitive: true,
    careerProspects: [
      "Structural Engineer",
      "Bridge Engineer",
      "Earthquake Engineer",
      "Building Designer",
      "Construction Engineer",
    ],
  },
  {
    name: "Transport Engineering",
    faculty: "Engineering",
    baseAPS: 33,
    duration: "4 years",
    description: "Plan, design and operate transportation systems.",
    allocation: { include: ["tut", "dut"] },
    careerProspects: [
      "Transport Engineer",
      "Traffic Engineer",
      "Railway Engineer",
      "Airport Engineer",
      "Urban Planner",
    ],
  },
  {
    name: "Water Resources Engineering",
    faculty: "Engineering",
    baseAPS: 34,
    duration: "4 years",
    description:
      "Manage and develop water resources for human and environmental needs.",
    allocation: { exclude: ["uwc", "unisa"] },
    careerProspects: [
      "Water Engineer",
      "Hydrologist",
      "Flood Engineer",
      "Dam Engineer",
      "Water Resource Manager",
    ],
  },
  {
    name: "Geotechnical Engineering",
    faculty: "Engineering",
    baseAPS: 35,
    duration: "4 years",
    description: "Study soil and rock mechanics for construction and mining.",
    allocation: { exclude: ["uwc", "unisa"] },
    careerProspects: [
      "Geotechnical Engineer",
      "Foundation Engineer",
      "Slope Stability Engineer",
      "Mining Engineer",
      "Environmental Engineer",
    ],
  },
  {
    name: "Construction Management",
    faculty: "Engineering",
    baseAPS: 28,
    duration: "4 years",
    description: "Manage construction projects from planning to completion.",
    allocation: "all",
    careerProspects: [
      "Construction Manager",
      "Project Manager",
      "Site Manager",
      "Quantity Surveyor",
      "Building Inspector",
    ],
  },
  {
    name: "Quantity Surveying",
    faculty: "Engineering",
    baseAPS: 28,
    duration: "4 years",
    description: "Manage costs and contracts for construction projects.",
    allocation: "all",
    careerProspects: [
      "Quantity Surveyor",
      "Cost Engineer",
      "Project Manager",
      "Construction Consultant",
      "Property Developer",
    ],
  },
  {
    name: "Urban and Regional Planning",
    faculty: "Engineering",
    baseAPS: 26,
    duration: "4 years",
    description: "Plan sustainable development of cities and regions.",
    allocation: { exclude: ["unisa", "ufh"] },
    careerProspects: [
      "Urban Planner",
      "Regional Planner",
      "Environmental Planner",
      "Transport Planner",
      "Development Manager",
    ],
  },
  {
    name: "Architecture",
    faculty: "Engineering",
    baseAPS: 32,
    duration: "5 years",
    description: "Design buildings and spaces for human habitation and use.",
    allocation: { exclude: ["unisa", "ufh", "mut"] },
    isCompetitive: true,
    careerProspects: [
      "Architect",
      "Urban Designer",
      "Building Designer",
      "Heritage Architect",
      "Landscape Architect",
    ],
  },
  {
    name: "Building Science",
    faculty: "Engineering",
    baseAPS: 28,
    duration: "4 years",
    description:
      "Study the science behind building performance and sustainability.",
    allocation: { exclude: ["unisa", "ufh"] },
    careerProspects: [
      "Building Scientist",
      "Sustainability Consultant",
      "Building Inspector",
      "Energy Auditor",
      "Construction Manager",
    ],
  },
  {
    name: "Interior Architecture",
    faculty: "Engineering",
    baseAPS: 30,
    duration: "4 years",
    description: "Design interior spaces for functionality and aesthetics.",
    allocation: { include: ["su", "uct", "up"] },
    careerProspects: [
      "Interior Architect",
      "Interior Designer",
      "Space Planner",
      "Furniture Designer",
      "Exhibition Designer",
    ],
  },
  {
    name: "Landscape Architecture",
    faculty: "Engineering",
    baseAPS: 30,
    duration: "4 years",
    description: "Design outdoor spaces and landscapes.",
    allocation: { include: ["su", "uct"] },
    careerProspects: [
      "Landscape Architect",
      "Garden Designer",
      "Urban Designer",
      "Environmental Planner",
      "Park Designer",
    ],
  },
  {
    name: "Urban Design",
    faculty: "Engineering",
    baseAPS: 31,
    duration: "4 years",
    description: "Design urban environments and public spaces.",
    allocation: { exclude: ["unisa", "ufh"] },
    careerProspects: [
      "Urban Designer",
      "City Planner",
      "Public Space Designer",
      "Development Manager",
      "Architecture Consultant",
    ],
  },

  // Faculty of Health Sciences / Medicine and Health
  {
    name: "Bachelor of Medicine and Bachelor of Surgery (MBChB)",
    faculty: "Health Sciences",
    baseAPS: 40,
    duration: "6 years",
    description: "Comprehensive medical training to become a qualified doctor.",
    allocation: "all",
    isCompetitive: true,
    careerProspects: [
      "Medical Doctor",
      "Specialist Physician",
      "Surgeon",
      "General Practitioner",
      "Medical Researcher",
    ],
  },
  {
    name: "Bachelor of Dental Surgery (BDS)",
    faculty: "Health Sciences",
    baseAPS: 38,
    duration: "5 years",
    description: "Training in dental medicine and oral health care.",
    allocation: { exclude: ["unisa", "ufh", "mut"] },
    isCompetitive: true,
    careerProspects: [
      "Dentist",
      "Oral Surgeon",
      "Orthodontist",
      "Dental Specialist",
      "Dental Researcher",
    ],
  },
  {
    name: "Bachelor of Pharmacy (BPharm)",
    faculty: "Health Sciences",
    baseAPS: 35,
    duration: "4 years",
    description: "Study of drugs, their properties, and pharmaceutical care.",
    allocation: "all",
    isCompetitive: true,
    careerProspects: [
      "Pharmacist",
      "Clinical Pharmacist",
      "Industrial Pharmacist",
      "Research Pharmacist",
      "Regulatory Affairs",
    ],
  },
  {
    name: "Bachelor of Physiotherapy (BSc Physiotherapy)",
    faculty: "Health Sciences",
    baseAPS: 33,
    duration: "4 years",
    description: "Treatment of movement disorders and physical rehabilitation.",
    allocation: "all",
    isCompetitive: true,
    careerProspects: [
      "Physiotherapist",
      "Sports Physiotherapist",
      "Neurological Physiotherapist",
      "Pediatric Physiotherapist",
      "Research Physiotherapist",
    ],
  },
  {
    name: "Bachelor of Occupational Therapy (BSc Occupational Therapy)",
    faculty: "Health Sciences",
    baseAPS: 32,
    duration: "4 years",
    description:
      "Help people develop, recover, or maintain daily living and work skills.",
    allocation: "all",
    careerProspects: [
      "Occupational Therapist",
      "Pediatric OT",
      "Mental Health OT",
      "Hand Therapist",
      "Rehabilitation Specialist",
    ],
  },
  {
    name: "Bachelor of Radiography (BSc Radiography)",
    faculty: "Health Sciences",
    baseAPS: 31,
    duration: "4 years",
    description: "Medical imaging and radiation therapy techniques.",
    allocation: { exclude: ["ufh", "mut"] },
    careerProspects: [
      "Radiographer",
      "Medical Imaging Specialist",
      "Radiation Therapist",
      "Ultrasound Technologist",
      "MRI Technologist",
    ],
  },
  {
    name: "Bachelor of Nursing Science (BNS)",
    faculty: "Health Sciences",
    baseAPS: 28,
    duration: "4 years",
    description:
      "Comprehensive nursing care across various healthcare settings.",
    allocation: "all",
    careerProspects: [
      "Registered Nurse",
      "Nurse Manager",
      "Clinical Nurse Specialist",
      "Nurse Educator",
      "Public Health Nurse",
    ],
  },
  {
    name: "Bachelor of Clinical Medical Practice (BCMP)",
    faculty: "Health Sciences",
    baseAPS: 35,
    duration: "3 years",
    description: "Training for clinical medical practitioners in rural areas.",
    allocation: { exclude: ["uct", "wits"] },
    careerProspects: [
      "Clinical Medical Practitioner",
      "Rural Health Practitioner",
      "Primary Healthcare Provider",
      "Emergency Medical Practitioner",
    ],
  },
  {
    name: "Bachelor of Emergency Medical Care (BEMC)",
    faculty: "Health Sciences",
    baseAPS: 30,
    duration: "4 years",
    description: "Emergency medical care and paramedic services.",
    allocation: { include: ["dut", "tut"] },
    careerProspects: [
      "Paramedic",
      "Emergency Medical Technician",
      "Flight Paramedic",
      "Emergency Room Technician",
      "Emergency Services Manager",
    ],
  },
  {
    name: "Bachelor of Medical Science (BMedSci)",
    faculty: "Health Sciences",
    baseAPS: 34,
    duration: "3 years",
    description: "Foundational medical sciences and research.",
    allocation: "all",
    careerProspects: [
      "Medical Researcher",
      "Laboratory Scientist",
      "Medical Writer",
      "Pharmaceutical Researcher",
      "Health Policy Analyst",
    ],
  },
  {
    name: "Bachelor of Biomedical Science (BSc Biomedical Science)",
    faculty: "Health Sciences",
    baseAPS: 33,
    duration: "3 years",
    description: "Study of human disease and medical research.",
    allocation: "all",
    careerProspects: [
      "Biomedical Scientist",
      "Research Scientist",
      "Laboratory Manager",
      "Clinical Researcher",
      "Medical Device Developer",
    ],
  },
  {
    name: "Bachelor of Medical Laboratory Science (BMLS)",
    faculty: "Health Sciences",
    baseAPS: 30,
    duration: "4 years",
    description: "Laboratory diagnosis and medical testing.",
    allocation: "all",
    careerProspects: [
      "Medical Laboratory Scientist",
      "Clinical Laboratory Technologist",
      "Pathology Laboratory Manager",
      "Research Laboratory Scientist",
    ],
  },
  {
    name: "Bachelor of Optometry (BOptom)",
    faculty: "Health Sciences",
    baseAPS: 34,
    duration: "4 years",
    description: "Eye care and vision correction.",
    allocation: { exclude: ["ufh", "mut"] },
    isCompetitive: true,
    careerProspects: [
      "Optometrist",
      "Vision Therapist",
      "Contact Lens Specialist",
      "Low Vision Specialist",
      "Eye Care Researcher",
    ],
  },
  {
    name: "Bachelor of Speech-Language Pathology (BSc Speech-Language Pathology)",
    faculty: "Health Sciences",
    baseAPS: 31,
    duration: "4 years",
    description: "Treatment of speech, language, and swallowing disorders.",
    allocation: { exclude: ["ufh"] },
    careerProspects: [
      "Speech-Language Pathologist",
      "Voice Therapist",
      "Swallowing Specialist",
      "Communication Disorders Specialist",
    ],
  },
  {
    name: "Bachelor of Audiology (BSc Audiology)",
    faculty: "Health Sciences",
    baseAPS: 31,
    duration: "4 years",
    description: "Hearing assessment and auditory rehabilitation.",
    allocation: { exclude: ["ufh"] },
    careerProspects: [
      "Audiologist",
      "Hearing Aid Specialist",
      "Cochlear Implant Specialist",
      "Industrial Audiologist",
      "Research Audiologist",
    ],
  },
  {
    name: "Bachelor of Dietetics (BSc Dietetics)",
    faculty: "Health Sciences",
    baseAPS: 29,
    duration: "4 years",
    description: "Nutrition science and therapeutic diet planning.",
    allocation: "all",
    careerProspects: [
      "Dietitian",
      "Clinical Nutritionist",
      "Sports Nutritionist",
      "Public Health Nutritionist",
      "Food Service Manager",
    ],
  },
  {
    name: "Bachelor of Environmental Health (BSc Environmental Health)",
    faculty: "Health Sciences",
    baseAPS: 27,
    duration: "4 years",
    description: "Public health and environmental protection.",
    allocation: "all",
    careerProspects: [
      "Environmental Health Officer",
      "Public Health Inspector",
      "Occupational Health Specialist",
      "Water Quality Specialist",
    ],
  },
  {
    name: "Bachelor of Public Health (BSc Public Health)",
    faculty: "Health Sciences",
    baseAPS: 28,
    duration: "4 years",
    description: "Population health and disease prevention.",
    allocation: "all",
    careerProspects: [
      "Public Health Officer",
      "Epidemiologist",
      "Health Promotion Specialist",
      "Health Policy Analyst",
      "Community Health Worker",
    ],
  },
  {
    name: "Bachelor of Medical Imaging (BSc Medical Imaging)",
    faculty: "Health Sciences",
    baseAPS: 30,
    duration: "4 years",
    description: "Advanced medical imaging techniques and interpretation.",
    allocation: { exclude: ["ufh"] },
    careerProspects: [
      "Medical Imaging Specialist",
      "CT Technologist",
      "MRI Technologist",
      "Nuclear Medicine Technologist",
      "Interventional Radiographer",
    ],
  },
  {
    name: "Bachelor of Clinical Technology (BSc Clinical Technology)",
    faculty: "Health Sciences",
    baseAPS: 29,
    duration: "4 years",
    description: "Clinical laboratory technology and medical devices.",
    allocation: { exclude: ["ufh"] },
    careerProspects: [
      "Clinical Technologist",
      "Medical Device Specialist",
      "Laboratory Manager",
      "Clinical Research Associate",
    ],
  },

  // Faculty of Humanities / Arts and Social Sciences
  {
    name: "Bachelor of Arts (BA) in English",
    faculty: "Humanities",
    baseAPS: 24,
    duration: "3 years",
    description: "Study of English language, literature, and communication.",
    allocation: "all",
    careerProspects: [
      "English Teacher",
      "Writer",
      "Editor",
      "Journalist",
      "Content Creator",
      "Communications Specialist",
    ],
  },
  {
    name: "History",
    faculty: "Humanities",
    baseAPS: 24,
    duration: "3 years",
    description: "Study of past events and their significance.",
    allocation: "all",
    careerProspects: [
      "History Teacher",
      "Historian",
      "Museum Curator",
      "Archivist",
      "Heritage Specialist",
      "Research Analyst",
    ],
  },
  {
    name: "Philosophy",
    faculty: "Humanities",
    baseAPS: 25,
    duration: "3 years",
    description: "Critical thinking and analysis of fundamental questions.",
    allocation: "all",
    careerProspects: [
      "Philosophy Teacher",
      "Ethics Consultant",
      "Policy Analyst",
      "Writer",
      "Legal Researcher",
      "Think Tank Researcher",
    ],
  },
  {
    name: "Sociology",
    faculty: "Humanities",
    baseAPS: 24,
    duration: "3 years",
    description: "Study of society, social behavior, and social institutions.",
    allocation: "all",
    careerProspects: [
      "Sociologist",
      "Social Researcher",
      "Social Worker",
      "Policy Analyst",
      "Community Development Officer",
      "Human Resources Specialist",
    ],
  },
  {
    name: "Psychology",
    faculty: "Humanities",
    baseAPS: 32,
    duration: "3 years",
    description: "Study of human behavior and mental processes.",
    allocation: "all",
    isCompetitive: true,
    careerProspects: [
      "Psychologist",
      "Clinical Psychologist",
      "Educational Psychologist",
      "Industrial Psychologist",
      "Counselor",
      "Researcher",
    ],
  },
  {
    name: "Political Science",
    faculty: "Humanities",
    baseAPS: 25,
    duration: "3 years",
    description: "Study of political systems, behavior, and governance.",
    allocation: "all",
    careerProspects: [
      "Political Scientist",
      "Policy Analyst",
      "Government Official",
      "Diplomat",
      "Political Journalist",
      "Campaign Manager",
    ],
  },
  {
    name: "Anthropology",
    faculty: "Humanities",
    baseAPS: 24,
    duration: "3 years",
    description: "Study of human culture and social organization.",
    allocation: { exclude: ["unisa"] },
    careerProspects: [
      "Anthropologist",
      "Cultural Researcher",
      "Museum Curator",
      "Development Worker",
      "Cultural Consultant",
    ],
  },
  {
    name: "Archaeology",
    faculty: "Humanities",
    baseAPS: 25,
    duration: "3 years",
    description: "Study of human history through material remains.",
    allocation: { exclude: ["unisa", "mut"] },
    careerProspects: [
      "Archaeologist",
      "Museum Curator",
      "Heritage Manager",
      "Cultural Resource Manager",
      "Research Scientist",
    ],
  },
  {
    name: "Linguistics",
    faculty: "Humanities",
    baseAPS: 25,
    duration: "3 years",
    description: "Scientific study of language and communication.",
    allocation: "all",
    careerProspects: [
      "Linguist",
      "Language Teacher",
      "Translator",
      "Speech Therapist",
      "Computational Linguist",
      "Language Researcher",
    ],
  },
  {
    name: "Geography",
    faculty: "Humanities",
    baseAPS: 24,
    duration: "3 years",
    description: "Study of Earth's landscapes, places, and environments.",
    allocation: "all",
    careerProspects: [
      "Geographer",
      "Urban Planner",
      "GIS Specialist",
      "Environmental Consultant",
      "Geography Teacher",
      "Cartographer",
    ],
  },
  {
    name: "Fine Arts",
    faculty: "Humanities",
    baseAPS: 26,
    duration: "3 years",
    description:
      "Creative visual arts including painting, sculpture, and drawing.",
    allocation: { exclude: ["ufh"] },
    careerProspects: [
      "Artist",
      "Art Teacher",
      "Gallery Curator",
      "Art Therapist",
      "Art Director",
      "Illustrator",
    ],
  },
  {
    name: "Music",
    faculty: "Humanities",
    baseAPS: 26,
    duration: "3 years",
    description: "Musical performance, composition, and theory.",
    allocation: { exclude: ["ufh", "mut"] },
    careerProspects: [
      "Musician",
      "Music Teacher",
      "Composer",
      "Music Therapist",
      "Sound Engineer",
      "Music Producer",
    ],
  },
  {
    name: "Theatre Arts",
    faculty: "Humanities",
    baseAPS: 25,
    duration: "3 years",
    description: "Performance, directing, and theatrical production.",
    allocation: { exclude: ["ufh", "mut"] },
    careerProspects: [
      "Actor",
      "Director",
      "Theatre Producer",
      "Drama Teacher",
      "Arts Administrator",
      "Theatre Critic",
    ],
  },
  {
    name: "Film and Media Studies",
    faculty: "Humanities",
    baseAPS: 27,
    duration: "3 years",
    description: "Analysis and production of film and digital media.",
    allocation: "all",
    careerProspects: [
      "Film Director",
      "Media Producer",
      "Film Critic",
      "Media Analyst",
      "Screenwriter",
      "Documentary Filmmaker",
    ],
  },
  {
    name: "Religious Studies",
    faculty: "Humanities",
    baseAPS: 24,
    duration: "3 years",
    description: "Comparative study of world religions and belief systems.",
    allocation: "all",
    careerProspects: [
      "Religious Studies Teacher",
      "Chaplain",
      "Interfaith Coordinator",
      "Religious Researcher",
      "Counselor",
    ],
  },
  {
    name: "Gender Studies",
    faculty: "Humanities",
    baseAPS: 24,
    duration: "3 years",
    description: "Analysis of gender roles and gender equality issues.",
    allocation: "all",
    careerProspects: [
      "Gender Specialist",
      "Policy Analyst",
      "NGO Worker",
      "Human Rights Advocate",
      "Researcher",
      "Social Worker",
    ],
  },
  {
    name: "African Studies",
    faculty: "Humanities",
    baseAPS: 24,
    duration: "3 years",
    description: "Interdisciplinary study of African cultures and societies.",
    allocation: "all",
    careerProspects: [
      "African Studies Researcher",
      "Cultural Consultant",
      "Development Worker",
      "Diplomat",
      "Journalist",
      "Policy Analyst",
    ],
  },
  {
    name: "Development Studies",
    faculty: "Humanities",
    baseAPS: 25,
    duration: "3 years",
    description: "Study of development processes and poverty reduction.",
    allocation: "all",
    careerProspects: [
      "Development Worker",
      "NGO Manager",
      "Policy Analyst",
      "Project Manager",
      "International Development Specialist",
    ],
  },
  {
    name: "International Relations",
    faculty: "Humanities",
    baseAPS: 26,
    duration: "3 years",
    description:
      "Study of relationships between countries and international organizations.",
    allocation: "all",
    careerProspects: [
      "Diplomat",
      "International Relations Analyst",
      "Foreign Service Officer",
      "International Business Specialist",
      "Journalist",
    ],
  },
  {
    name: "Communication Science",
    faculty: "Humanities",
    baseAPS: 26,
    duration: "3 years",
    description: "Study of human communication processes and media.",
    allocation: "all",
    careerProspects: [
      "Communications Specialist",
      "Public Relations Officer",
      "Media Analyst",
      "Corporate Communications Manager",
    ],
  },
  {
    name: "Journalism",
    faculty: "Humanities",
    baseAPS: 27,
    duration: "3 years",
    description: "News gathering, writing, and media production.",
    allocation: "all",
    careerProspects: [
      "Journalist",
      "News Reporter",
      "Editor",
      "Media Producer",
      "Digital Content Creator",
      "Photojournalist",
    ],
  },
  {
    name: "Public Relations",
    faculty: "Humanities",
    baseAPS: 26,
    duration: "3 years",
    description: "Managing public image and stakeholder communications.",
    allocation: "all",
    careerProspects: [
      "Public Relations Officer",
      "Communications Manager",
      "Brand Manager",
      "Event Coordinator",
      "Crisis Communications Specialist",
    ],
  },
  {
    name: "Publishing",
    faculty: "Humanities",
    baseAPS: 25,
    duration: "3 years",
    description: "Book and digital content publishing industry.",
    allocation: { exclude: ["unisa"] },
    careerProspects: [
      "Publisher",
      "Editor",
      "Literary Agent",
      "Content Manager",
      "Digital Publishing Specialist",
    ],
  },
  {
    name: "Translation and Interpreting",
    faculty: "Humanities",
    baseAPS: 28,
    duration: "3 years",
    description: "Professional translation and interpretation services.",
    allocation: { include: ["uct", "su"] },
    careerProspects: [
      "Translator",
      "Interpreter",
      "Language Specialist",
      "Localization Specialist",
      "Conference Interpreter",
    ],
  },
  {
    name: "Creative Writing",
    faculty: "Humanities",
    baseAPS: 26,
    duration: "3 years",
    description: "Fiction, poetry, and creative non-fiction writing.",
    allocation: "all",
    careerProspects: [
      "Writer",
      "Author",
      "Screenwriter",
      "Poet",
      "Content Creator",
      "Literary Editor",
    ],
  },
  {
    name: "Visual Arts",
    faculty: "Humanities",
    baseAPS: 26,
    duration: "3 years",
    description: "Contemporary visual arts and multimedia.",
    allocation: { exclude: ["ufh"] },
    careerProspects: [
      "Visual Artist",
      "Gallery Curator",
      "Art Director",
      "Digital Artist",
      "Art Teacher",
      "Arts Administrator",
    ],
  },
  {
    name: "Fashion Design",
    faculty: "Humanities",
    baseAPS: 27,
    duration: "3 years",
    description: "Fashion design and apparel industry.",
    allocation: { include: ["su", "uct"] },
    careerProspects: [
      "Fashion Designer",
      "Textile Designer",
      "Fashion Merchandiser",
      "Pattern Maker",
      "Fashion Stylist",
    ],
  },
  {
    name: "Interior Design",
    faculty: "Humanities",
    baseAPS: 27,
    duration: "3 years",
    description: "Interior space design and decoration.",
    allocation: { include: ["su", "uct"] },
    careerProspects: [
      "Interior Designer",
      "Space Planner",
      "Furniture Designer",
      "Set Designer",
      "Design Consultant",
    ],
  },
  {
    name: "Graphic Design",
    faculty: "Humanities",
    baseAPS: 27,
    duration: "3 years",
    description: "Visual communication and graphic design.",
    allocation: { include: ["su", "uct"] },
    careerProspects: [
      "Graphic Designer",
      "Web Designer",
      "Brand Designer",
      "Art Director",
      "Digital Designer",
    ],
  },
  {
    name: "Industrial Design",
    faculty: "Humanities",
    baseAPS: 28,
    duration: "3 years",
    description: "Product and industrial design.",
    allocation: { include: ["su", "uct"] },
    careerProspects: [
      "Industrial Designer",
      "Product Designer",
      "Design Engineer",
      "UX Designer",
      "Design Researcher",
    ],
  },
  {
    name: "Photography",
    faculty: "Humanities",
    baseAPS: 25,
    duration: "3 years",
    description: "Professional photography and visual storytelling.",
    allocation: "all",
    careerProspects: [
      "Photographer",
      "Photojournalist",
      "Commercial Photographer",
      "Portrait Photographer",
      "Photo Editor",
    ],
  },
  {
    name: "Animation",
    faculty: "Humanities",
    baseAPS: 27,
    duration: "3 years",
    description: "Animation and motion graphics production.",
    allocation: "all",
    careerProspects: [
      "Animator",
      "Motion Graphics Designer",
      "3D Modeler",
      "Visual Effects Artist",
      "Game Animator",
    ],
  },
  {
    name: "Film Production",
    faculty: "Humanities",
    baseAPS: 27,
    duration: "3 years",
    description: "Film and video production techniques.",
    allocation: "all",
    careerProspects: [
      "Film Producer",
      "Director",
      "Cinematographer",
      "Video Editor",
      "Production Manager",
    ],
  },
  {
    name: "Theatre Production",
    faculty: "Humanities",
    baseAPS: 26,
    duration: "3 years",
    description: "Theatre production and stage management.",
    allocation: "all",
    careerProspects: [
      "Theatre Producer",
      "Stage Manager",
      "Set Designer",
      "Lighting Designer",
      "Sound Designer",
    ],
  },

  // Faculty of Commerce / Business and Management
  {
    name: "Bachelor of Commerce (BCom) in Accounting",
    faculty: "Commerce",
    baseAPS: 30,
    duration: "3 years",
    description: "Financial accounting, auditing, and business finance.",
    allocation: "all",
    careerProspects: [
      "Accountant",
      "Auditor",
      "Financial Manager",
      "Tax Consultant",
      "Management Accountant",
      "CFO",
    ],
  },
  {
    name: "Finance",
    faculty: "Commerce",
    baseAPS: 30,
    duration: "3 years",
    description:
      "Corporate finance, investment analysis, and financial markets.",
    allocation: "all",
    careerProspects: [
      "Financial Analyst",
      "Investment Banker",
      "Portfolio Manager",
      "Financial Planner",
      "Risk Manager",
    ],
  },
  {
    name: "Economics",
    faculty: "Commerce",
    baseAPS: 29,
    duration: "3 years",
    description: "Economic theory, policy analysis, and market behavior.",
    allocation: "all",
    careerProspects: [
      "Economist",
      "Economic Analyst",
      "Policy Researcher",
      "Market Researcher",
      "Government Economist",
    ],
  },
  {
    name: "Marketing",
    faculty: "Commerce",
    baseAPS: 27,
    duration: "3 years",
    description: "Consumer behavior, advertising, and brand management.",
    allocation: "all",
    careerProspects: [
      "Marketing Manager",
      "Brand Manager",
      "Digital Marketer",
      "Market Researcher",
      "Advertising Executive",
    ],
  },
  {
    name: "Human Resource Management",
    faculty: "Commerce",
    baseAPS: 26,
    duration: "3 years",
    description:
      "Employee management, recruitment, and organizational behavior.",
    allocation: "all",
    careerProspects: [
      "HR Manager",
      "Recruitment Specialist",
      "Training Manager",
      "Compensation Analyst",
      "Employee Relations Specialist",
    ],
  },
  {
    name: "Business Management",
    faculty: "Commerce",
    baseAPS: 26,
    duration: "3 years",
    description: "General business administration and management principles.",
    allocation: "all",
    careerProspects: [
      "Business Manager",
      "Operations Manager",
      "Project Manager",
      "Business Analyst",
      "Management Consultant",
    ],
  },
  {
    name: "Supply Chain Management",
    faculty: "Commerce",
    baseAPS: 27,
    duration: "3 years",
    description: "Logistics, procurement, and supply chain optimization.",
    allocation: "all",
    careerProspects: [
      "Supply Chain Manager",
      "Logistics Coordinator",
      "Procurement Manager",
      "Operations Analyst",
      "Warehouse Manager",
    ],
  },
  {
    name: "Logistics",
    faculty: "Commerce",
    baseAPS: 26,
    duration: "3 years",
    description: "Transportation, distribution, and logistics management.",
    allocation: "all",
    careerProspects: [
      "Logistics Manager",
      "Distribution Manager",
      "Transport Coordinator",
      "Inventory Manager",
      "Freight Coordinator",
    ],
  },
  {
    name: "Risk Management",
    faculty: "Commerce",
    baseAPS: 29,
    duration: "3 years",
    description: "Identifying and managing business risks.",
    allocation: "all",
    careerProspects: [
      "Risk Manager",
      "Compliance Officer",
      "Insurance Underwriter",
      "Risk Analyst",
      "Internal Auditor",
    ],
  },
  {
    name: "Tourism Management",
    faculty: "Commerce",
    baseAPS: 25,
    duration: "3 years",
    description: "Tourism industry management and hospitality.",
    allocation: "all",
    careerProspects: [
      "Tourism Manager",
      "Travel Agent",
      "Hotel Manager",
      "Event Coordinator",
      "Tour Guide",
    ],
  },
  {
    name: "Hospitality Management",
    faculty: "Commerce",
    baseAPS: 24,
    duration: "3 years",
    description: "Hotel and restaurant management.",
    allocation: "all",
    careerProspects: [
      "Hotel Manager",
      "Restaurant Manager",
      "Event Manager",
      "Food Service Manager",
      "Guest Relations Manager",
    ],
  },
  {
    name: "Public Administration",
    faculty: "Commerce",
    baseAPS: 25,
    duration: "3 years",
    description: "Government administration and public service management.",
    allocation: "all",
    careerProspects: [
      "Public Administrator",
      "Government Official",
      "Policy Analyst",
      "Municipal Manager",
      "Public Service Manager",
    ],
  },
  {
    name: "Labour Relations",
    faculty: "Commerce",
    baseAPS: 26,
    duration: "3 years",
    description: "Employee relations and labor law.",
    allocation: "all",
    careerProspects: [
      "Labour Relations Officer",
      "Trade Union Representative",
      "Mediator",
      "Industrial Relations Specialist",
    ],
  },
  {
    name: "Entrepreneurship",
    faculty: "Commerce",
    baseAPS: 25,
    duration: "3 years",
    description: "Business startup and innovation management.",
    allocation: "all",
    careerProspects: [
      "Entrepreneur",
      "Business Owner",
      "Startup Consultant",
      "Innovation Manager",
      "Business Development Manager",
    ],
  },
  {
    name: "Banking",
    faculty: "Commerce",
    baseAPS: 28,
    duration: "3 years",
    description: "Banking operations and financial services.",
    allocation: "all",
    careerProspects: [
      "Bank Manager",
      "Credit Analyst",
      "Loan Officer",
      "Investment Advisor",
      "Corporate Banker",
    ],
  },
  {
    name: "Insurance",
    faculty: "Commerce",
    baseAPS: 27,
    duration: "3 years",
    description: "Insurance products and risk assessment.",
    allocation: "all",
    careerProspects: [
      "Insurance Broker",
      "Underwriter",
      "Claims Assessor",
      "Risk Assessor",
      "Insurance Sales Agent",
    ],
  },
  {
    name: "Auditing",
    faculty: "Commerce",
    baseAPS: 30,
    duration: "3 years",
    description: "Financial auditing and assurance services.",
    allocation: "all",
    careerProspects: [
      "External Auditor",
      "Internal Auditor",
      "Forensic Auditor",
      "Compliance Auditor",
      "Risk Auditor",
    ],
  },
  {
    name: "Actuarial Science",
    faculty: "Commerce",
    baseAPS: 38,
    duration: "3 years",
    description: "Mathematical analysis of financial risk and uncertainty.",
    allocation: { exclude: ["ufh", "mut"] },
    isCompetitive: true,
    careerProspects: [
      "Actuary",
      "Risk Analyst",
      "Insurance Analyst",
      "Pension Fund Manager",
      "Investment Analyst",
    ],
  },
  {
    name: "Taxation",
    faculty: "Commerce",
    baseAPS: 28,
    duration: "3 years",
    description: "Tax law, planning, and compliance.",
    allocation: "all",
    careerProspects: [
      "Tax Consultant",
      "Tax Accountant",
      "Tax Advisor",
      "Revenue Officer",
      "Tax Specialist",
    ],
  },
  {
    name: "Investment Management",
    faculty: "Commerce",
    baseAPS: 31,
    duration: "3 years",
    description: "Portfolio management and investment strategies.",
    allocation: "all",
    careerProspects: [
      "Investment Manager",
      "Portfolio Manager",
      "Financial Advisor",
      "Investment Analyst",
      "Wealth Manager",
    ],
  },
  {
    name: "Business Analytics",
    faculty: "Commerce",
    baseAPS: 29,
    duration: "3 years",
    description: "Data analysis for business decision making.",
    allocation: "all",
    careerProspects: [
      "Business Analyst",
      "Data Analyst",
      "Business Intelligence Analyst",
      "Market Research Analyst",
    ],
  },
  {
    name: "Strategic Management",
    faculty: "Commerce",
    baseAPS: 28,
    duration: "3 years",
    description: "Corporate strategy and competitive analysis.",
    allocation: "all",
    careerProspects: [
      "Strategy Consultant",
      "Business Development Manager",
      "Strategic Planner",
      "Management Consultant",
    ],
  },
  {
    name: "International Business",
    faculty: "Commerce",
    baseAPS: 28,
    duration: "3 years",
    description: "Global business operations and international trade.",
    allocation: "all",
    careerProspects: [
      "International Business Manager",
      "Export Manager",
      "Trade Specialist",
      "Global Marketing Manager",
    ],
  },

  // Additional Business Science Programs
  {
    name: "Bachelor of Business Science (BBusSc) in Business Analysis",
    faculty: "Commerce",
    baseAPS: 29,
    duration: "3 years",
    description: "Advanced business analysis and decision sciences.",
    allocation: "all",
    careerProspects: [
      "Business Analyst",
      "Management Consultant",
      "Operations Researcher",
      "Decision Analyst",
    ],
  },
  {
    name: "Business Computing",
    faculty: "Commerce",
    baseAPS: 28,
    duration: "3 years",
    description: "Information systems for business applications.",
    allocation: "all",
    careerProspects: [
      "Business Systems Analyst",
      "IT Project Manager",
      "Systems Consultant",
      "Business Intelligence Specialist",
    ],
  },
  {
    name: "Business Economics",
    faculty: "Commerce",
    baseAPS: 29,
    duration: "3 years",
    description: "Economic analysis for business decision making.",
    allocation: "all",
    careerProspects: [
      "Business Economist",
      "Economic Consultant",
      "Market Analyst",
      "Policy Analyst",
    ],
  },
  {
    name: "Business Finance",
    faculty: "Commerce",
    baseAPS: 30,
    duration: "3 years",
    description: "Corporate finance and financial management.",
    allocation: "all",
    careerProspects: [
      "Corporate Finance Manager",
      "Financial Analyst",
      "Treasury Manager",
      "Investment Banking Analyst",
    ],
  },
  {
    name: "Business Law",
    faculty: "Commerce",
    baseAPS: 28,
    duration: "3 years",
    description: "Legal aspects of business operations.",
    allocation: "all",
    careerProspects: [
      "Corporate Lawyer",
      "Legal Advisor",
      "Compliance Officer",
      "Contract Specialist",
    ],
  },
  {
    name: "Business Marketing",
    faculty: "Commerce",
    baseAPS: 27,
    duration: "3 years",
    description: "Advanced marketing strategy and consumer behavior.",
    allocation: "all",
    careerProspects: [
      "Marketing Director",
      "Brand Strategist",
      "Digital Marketing Manager",
      "Product Manager",
    ],
  },
  {
    name: "Business Statistics",
    faculty: "Commerce",
    baseAPS: 29,
    duration: "3 years",
    description: "Statistical analysis for business applications.",
    allocation: "all",
    careerProspects: [
      "Business Statistician",
      "Data Scientist",
      "Market Researcher",
      "Quality Control Analyst",
    ],
  },
  {
    name: "Business Strategy",
    faculty: "Commerce",
    baseAPS: 28,
    duration: "3 years",
    description: "Strategic planning and competitive analysis.",
    allocation: "all",
    careerProspects: [
      "Strategy Consultant",
      "Business Development Director",
      "Corporate Strategist",
      "Innovation Manager",
    ],
  },

  // Administration Programs
  {
    name: "Bachelor of Administration (BAdmin) in Public Administration",
    faculty: "Commerce",
    baseAPS: 25,
    duration: "3 years",
    description: "Government administration and public policy.",
    allocation: "all",
    careerProspects: [
      "Public Administrator",
      "Government Official",
      "Policy Analyst",
      "Municipal Manager",
    ],
  },
  {
    name: "Local Government",
    faculty: "Commerce",
    baseAPS: 24,
    duration: "3 years",
    description: "Municipal administration and local governance.",
    allocation: "all",
    careerProspects: [
      "Municipal Manager",
      "Local Government Official",
      "Community Development Officer",
      "Public Service Manager",
    ],
  },
  {
    name: "Municipal Governance",
    faculty: "Commerce",
    baseAPS: 24,
    duration: "3 years",
    description: "Municipal governance and service delivery.",
    allocation: "all",
    careerProspects: [
      "Municipal Official",
      "City Manager",
      "Public Service Coordinator",
      "Community Liaison Officer",
    ],
  },

  // Faculty of Law
  {
    name: "Bachelor of Laws (LLB)",
    faculty: "Law",
    baseAPS: 33,
    duration: "4 years",
    description: "Comprehensive legal education and jurisprudence.",
    allocation: "all",
    isCompetitive: true,
    careerProspects: [
      "Lawyer",
      "Attorney",
      "Advocate",
      "Judge",
      "Legal Advisor",
      "Corporate Counsel",
    ],
  },
  {
    name: "Bachelor of Criminal Justice",
    faculty: "Law",
    baseAPS: 27,
    duration: "3 years",
    description: "Criminal law, policing, and justice system.",
    allocation: "all",
    careerProspects: [
      "Police Officer",
      "Detective",
      "Correctional Officer",
      "Court Administrator",
      "Paralegal",
    ],
  },
  {
    name: "Bachelor of Forensic Science",
    faculty: "Law",
    baseAPS: 30,
    duration: "3 years",
    description: "Scientific investigation of crimes and evidence analysis.",
    allocation: { exclude: ["ufh", "mut"] },
    careerProspects: [
      "Forensic Scientist",
      "Crime Scene Investigator",
      "DNA Analyst",
      "Ballistics Expert",
      "Digital Forensics Specialist",
    ],
  },
  {
    name: "Bachelor of International Law",
    faculty: "Law",
    baseAPS: 32,
    duration: "4 years",
    description: "International legal systems and diplomatic law.",
    allocation: "all",
    careerProspects: [
      "International Lawyer",
      "Diplomat",
      "Human Rights Lawyer",
      "International Trade Lawyer",
      "Legal Researcher",
    ],
  },
  {
    name: "Bachelor of Environmental Law",
    faculty: "Law",
    baseAPS: 30,
    duration: "4 years",
    description: "Environmental protection and natural resource law.",
    allocation: "all",
    careerProspects: [
      "Environmental Lawyer",
      "Environmental Consultant",
      "Policy Analyst",
      "Environmental Compliance Officer",
    ],
  },
  {
    name: "Bachelor of Labour Law",
    faculty: "Law",
    baseAPS: 30,
    duration: "4 years",
    description: "Employment law and labor relations.",
    allocation: "all",
    careerProspects: [
      "Labour Lawyer",
      "HR Legal Specialist",
      "Trade Union Lawyer",
      "Employment Consultant",
      "Industrial Relations Specialist",
    ],
  },
  {
    name: "Bachelor of Tax Law",
    faculty: "Law",
    baseAPS: 31,
    duration: "4 years",
    description: "Taxation law and revenue administration.",
    allocation: "all",
    careerProspects: [
      "Tax Lawyer",
      "Tax Consultant",
      "Revenue Legal Advisor",
      "Corporate Tax Specialist",
      "Tax Policy Analyst",
    ],
  },
  {
    name: "Bachelor of Commercial Law",
    faculty: "Law",
    baseAPS: 31,
    duration: "4 years",
    description: "Business law and commercial transactions.",
    allocation: "all",
    careerProspects: [
      "Commercial Lawyer",
      "Corporate Legal Advisor",
      "Contract Specialist",
      "Mergers & Acquisitions Lawyer",
    ],
  },
  {
    name: "Bachelor of Constitutional Law",
    faculty: "Law",
    baseAPS: 32,
    duration: "4 years",
    description: "Constitutional principles and human rights law.",
    allocation: "all",
    careerProspects: [
      "Constitutional Lawyer",
      "Human Rights Lawyer",
      "Public Interest Lawyer",
      "Government Legal Advisor",
    ],
  },
  {
    name: "Bachelor of Human Rights Law",
    faculty: "Law",
    baseAPS: 30,
    duration: "4 years",
    description: "Human rights protection and advocacy.",
    allocation: "all",
    careerProspects: [
      "Human Rights Lawyer",
      "NGO Legal Advisor",
      "International Human Rights Officer",
      "Social Justice Advocate",
    ],
  },

  // Faculty of Science / Natural Sciences
  {
    name: "Bachelor of Science (BSc) in Biological Sciences",
    faculty: "Science",
    baseAPS: 29,
    duration: "3 years",
    description: "Study of living organisms and biological processes.",
    allocation: "all",
    careerProspects: [
      "Biologist",
      "Research Scientist",
      "Environmental Consultant",
      "Science Teacher",
      "Laboratory Technician",
    ],
  },
  {
    name: "Chemistry",
    faculty: "Science",
    baseAPS: 31,
    duration: "3 years",
    description: "Organic, inorganic, analytical, and physical chemistry.",
    allocation: "all",
    careerProspects: [
      "Chemist",
      "Research Scientist",
      "Quality Control Analyst",
      "Environmental Scientist",
      "Science Teacher",
    ],
  },
  {
    name: "Physics",
    faculty: "Science",
    baseAPS: 33,
    duration: "3 years",
    description: "Fundamental principles of matter, energy, and the universe.",
    allocation: "all",
    careerProspects: [
      "Physicist",
      "Research Scientist",
      "Engineering Physicist",
      "Medical Physicist",
      "Science Teacher",
    ],
  },
  {
    name: "Mathematics",
    faculty: "Science",
    baseAPS: 32,
    duration: "3 years",
    description:
      "Pure and applied mathematics, statistics, and mathematical modeling.",
    allocation: "all",
    careerProspects: [
      "Mathematician",
      "Statistician",
      "Data Scientist",
      "Actuary",
      "Mathematics Teacher",
      "Research Scientist",
    ],
  },
  {
    name: "Computer Science",
    faculty: "Science",
    baseAPS: 31,
    duration: "3 years",
    description:
      "Programming, algorithms, software development, and computational theory.",
    allocation: "all",
    careerProspects: [
      "Software Developer",
      "Computer Programmer",
      "Systems Analyst",
      "IT Consultant",
      "Data Scientist",
    ],
  },
  {
    name: "Environmental Science",
    faculty: "Science",
    baseAPS: 28,
    duration: "3 years",
    description: "Study of environmental problems and solutions.",
    allocation: "all",
    careerProspects: [
      "Environmental Scientist",
      "Environmental Consultant",
      "Conservation Scientist",
      "Environmental Manager",
    ],
  },
  {
    name: "Geology",
    faculty: "Science",
    baseAPS: 29,
    duration: "3 years",
    description: "Study of Earth's structure, composition, and processes.",
    allocation: "all",
    careerProspects: [
      "Geologist",
      "Mining Geologist",
      "Environmental Geologist",
      "Petroleum Geologist",
      "Hydrogeologist",
    ],
  },
  {
    name: "Statistics",
    faculty: "Science",
    baseAPS: 30,
    duration: "3 years",
    description: "Statistical methods and data analysis.",
    allocation: "all",
    careerProspects: [
      "Statistician",
      "Data Analyst",
      "Biostatistician",
      "Market Researcher",
      "Quality Control Analyst",
    ],
  },
  {
    name: "Biochemistry",
    faculty: "Science",
    baseAPS: 32,
    duration: "3 years",
    description: "Chemical processes within living organisms.",
    allocation: "all",
    careerProspects: [
      "Biochemist",
      "Medical Researcher",
      "Pharmaceutical Researcher",
      "Clinical Biochemist",
      "Biotechnologist",
    ],
  },
  {
    name: "Microbiology",
    faculty: "Science",
    baseAPS: 30,
    duration: "3 years",
    description: "Study of microorganisms and their effects.",
    allocation: "all",
    careerProspects: [
      "Microbiologist",
      "Medical Microbiologist",
      "Food Microbiologist",
      "Industrial Microbiologist",
    ],
  },
  {
    name: "Genetics",
    faculty: "Science",
    baseAPS: 32,
    duration: "3 years",
    description: "Study of heredity and genetic variation.",
    allocation: "all",
    careerProspects: [
      "Geneticist",
      "Genetic Counselor",
      "Medical Geneticist",
      "Agricultural Geneticist",
      "Research Scientist",
    ],
  },
  {
    name: "Botany",
    faculty: "Science",
    baseAPS: 28,
    duration: "3 years",
    description: "Study of plant life and botanical sciences.",
    allocation: "all",
    careerProspects: [
      "Botanist",
      "Plant Researcher",
      "Conservation Biologist",
      "Agricultural Scientist",
      "Environmental Consultant",
    ],
  },
  {
    name: "Zoology",
    faculty: "Science",
    baseAPS: 28,
    duration: "3 years",
    description: "Study of animal behavior, physiology, and ecology.",
    allocation: "all",
    careerProspects: [
      "Zoologist",
      "Wildlife Biologist",
      "Animal Researcher",
      "Conservation Scientist",
      "Veterinary Researcher",
    ],
  },
  {
    name: "Astronomy",
    faculty: "Science",
    baseAPS: 34,
    duration: "3 years",
    description: "Study of celestial objects and space phenomena.",
    allocation: { include: ["uct", "ru"] },
    careerProspects: [
      "Astronomer",
      "Astrophysicist",
      "Planetarium Director",
      "Space Scientist",
      "Observatory Researcher",
    ],
  },
  {
    name: "Meteorology",
    faculty: "Science",
    baseAPS: 32,
    duration: "3 years",
    description: "Study of weather patterns and atmospheric sciences.",
    allocation: { include: ["uct", "ru"] },
    careerProspects: [
      "Meteorologist",
      "Weather Forecaster",
      "Climate Scientist",
      "Atmospheric Researcher",
    ],
  },
  {
    name: "Marine Biology",
    faculty: "Science",
    baseAPS: 30,
    duration: "3 years",
    description: "Study of marine organisms and ocean ecosystems.",
    allocation: { include: ["uct", "ru"] },
    careerProspects: [
      "Marine Biologist",
      "Oceanographer",
      "Marine Conservation Scientist",
      "Aquarium Scientist",
      "Fisheries Biologist",
    ],
  },
  {
    name: "Biotechnology",
    faculty: "Science",
    baseAPS: 32,
    duration: "3 years",
    description:
      "Application of biological systems for technological advances.",
    allocation: "all",
    careerProspects: [
      "Biotechnologist",
      "Biomedical Engineer",
      "Pharmaceutical Researcher",
      "Agricultural Biotechnologist",
    ],
  },
  {
    name: "Ecology",
    faculty: "Science",
    baseAPS: 28,
    duration: "3 years",
    description: "Study of organisms and their environment.",
    allocation: "all",
    careerProspects: [
      "Ecologist",
      "Environmental Consultant",
      "Conservation Biologist",
      "Wildlife Manager",
      "Research Scientist",
    ],
  },
  {
    name: "Entomology",
    faculty: "Science",
    baseAPS: 27,
    duration: "3 years",
    description: "Study of insects and their behavior.",
    allocation: "all",
    careerProspects: [
      "Entomologist",
      "Pest Control Specialist",
      "Agricultural Researcher",
      "Forest Entomologist",
    ],
  },
  {
    name: "Mycology",
    faculty: "Science",
    baseAPS: 27,
    duration: "3 years",
    description: "Study of fungi and their applications.",
    allocation: { exclude: ["ufh"] },
    careerProspects: [
      "Mycologist",
      "Plant Pathologist",
      "Food Scientist",
      "Pharmaceutical Researcher",
    ],
  },
  {
    name: "Phycology",
    faculty: "Science",
    baseAPS: 27,
    duration: "3 years",
    description: "Study of algae and their applications.",
    allocation: { exclude: ["ufh"] },
    careerProspects: [
      "Phycologist",
      "Marine Researcher",
      "Biotechnology Researcher",
      "Environmental Scientist",
    ],
  },
  {
    name: "Limnology",
    faculty: "Science",
    baseAPS: 28,
    duration: "3 years",
    description: "Study of freshwater ecosystems.",
    allocation: { exclude: ["ufh"] },
    careerProspects: [
      "Limnologist",
      "Water Quality Specialist",
      "Aquatic Ecologist",
      "Environmental Consultant",
    ],
  },
  {
    name: "Hydrology",
    faculty: "Science",
    baseAPS: 29,
    duration: "3 years",
    description: "Study of water movement and distribution.",
    allocation: "all",
    careerProspects: [
      "Hydrologist",
      "Water Resource Engineer",
      "Environmental Consultant",
      "Climate Scientist",
    ],
  },
  {
    name: "Soil Science",
    faculty: "Science",
    baseAPS: 27,
    duration: "3 years",
    description: "Study of soil formation, classification, and management.",
    allocation: "all",
    careerProspects: [
      "Soil Scientist",
      "Agricultural Consultant",
      "Environmental Scientist",
      "Land Use Planner",
    ],
  },
  {
    name: "Agricultural Science",
    faculty: "Science",
    baseAPS: 26,
    duration: "3 years",
    description: "Scientific principles applied to agriculture.",
    allocation: "all",
    careerProspects: [
      "Agricultural Scientist",
      "Crop Specialist",
      "Agricultural Consultant",
      "Farm Manager",
      "Agricultural Researcher",
    ],
  },

  // Faculty of Education
  {
    name: "Bachelor of Education (BEd) in Foundation Phase",
    faculty: "Education",
    baseAPS: 25,
    duration: "4 years",
    description: "Teaching methodology for learners in grades R-3.",
    allocation: "all",
    careerProspects: [
      "Foundation Phase Teacher",
      "Early Childhood Educator",
      "Curriculum Developer",
      "Educational Consultant",
      "School Principal",
    ],
  },
  {
    name: "Intermediate Phase",
    faculty: "Education",
    baseAPS: 25,
    duration: "4 years",
    description: "Teaching methodology for learners in grades 4-6.",
    allocation: "all",
    careerProspects: [
      "Intermediate Phase Teacher",
      "Subject Specialist",
      "Curriculum Developer",
      "Educational Consultant",
      "School Principal",
    ],
  },
  {
    name: "Senior Phase",
    faculty: "Education",
    baseAPS: 26,
    duration: "4 years",
    description: "Teaching methodology for learners in grades 7-9.",
    allocation: "all",
    careerProspects: [
      "Senior Phase Teacher",
      "Subject Head",
      "Curriculum Developer",
      "Educational Consultant",
      "School Principal",
    ],
  },
  {
    name: "Further Education and Training (FET) Phase",
    faculty: "Education",
    baseAPS: 27,
    duration: "4 years",
    description: "Teaching methodology for grades 10-12.",
    allocation: "all",
    careerProspects: [
      "High School Teacher",
      "Subject Specialist",
      "Education Manager",
      "Curriculum Specialist",
    ],
  },
  {
    name: "Special Education",
    faculty: "Education",
    baseAPS: 27,
    duration: "4 years",
    description: "Teaching learners with special educational needs.",
    allocation: "all",
    careerProspects: [
      "Special Education Teacher",
      "Inclusive Education Specialist",
      "Educational Therapist",
      "Special Needs Coordinator",
    ],
  },
  {
    name: "Adult Education",
    faculty: "Education",
    baseAPS: 24,
    duration: "4 years",
    description: "Teaching and training adult learners.",
    allocation: "all",
    careerProspects: [
      "Adult Education Teacher",
      "Corporate Trainer",
      "Community Education Officer",
      "Literacy Coordinator",
    ],
  },
  {
    name: "Educational Psychology",
    faculty: "Education",
    baseAPS: 30,
    duration: "4 years",
    description: "Psychology applied to educational settings.",
    allocation: "all",
    careerProspects: [
      "Educational Psychologist",
      "School Psychologist",
      "Learning Support Specialist",
      "Educational Researcher",
    ],
  },
  {
    name: "Educational Management",
    faculty: "Education",
    baseAPS: 26,
    duration: "4 years",
    description: "Leadership and administration in educational institutions.",
    allocation: "all",
    careerProspects: [
      "School Principal",
      "Education Manager",
      "District Education Officer",
      "Education Policy Analyst",
    ],
  },
  {
    name: "Curriculum Studies",
    faculty: "Education",
    baseAPS: 26,
    duration: "4 years",
    description: "Design and development of educational curricula.",
    allocation: "all",
    careerProspects: [
      "Curriculum Developer",
      "Educational Consultant",
      "Instructional Designer",
      "Education Researcher",
    ],
  },
  {
    name: "Language Education",
    faculty: "Education",
    baseAPS: 25,
    duration: "4 years",
    description: "Teaching language and literacy skills.",
    allocation: "all",
    careerProspects: [
      "Language Teacher",
      "Literacy Specialist",
      "ESL Teacher",
      "Language Curriculum Developer",
    ],
  },
  {
    name: "Mathematics Education",
    faculty: "Education",
    baseAPS: 28,
    duration: "4 years",
    description: "Teaching mathematics at various levels.",
    allocation: "all",
    careerProspects: [
      "Mathematics Teacher",
      "Numeracy Specialist",
      "Mathematics Curriculum Developer",
      "Education Researcher",
    ],
  },
  {
    name: "Science Education",
    faculty: "Education",
    baseAPS: 28,
    duration: "4 years",
    description: "Teaching science subjects and scientific thinking.",
    allocation: "all",
    careerProspects: [
      "Science Teacher",
      "Science Education Specialist",
      "Science Curriculum Developer",
      "Education Researcher",
    ],
  },
  {
    name: "Technology Education",
    faculty: "Education",
    baseAPS: 26,
    duration: "4 years",
    description: "Teaching technology and technical skills.",
    allocation: "all",
    careerProspects: [
      "Technology Teacher",
      "Technical Skills Trainer",
      "STEM Education Specialist",
      "Educational Technology Coordinator",
    ],
  },
  {
    name: "Social Sciences Education",
    faculty: "Education",
    baseAPS: 25,
    duration: "4 years",
    description: "Teaching social sciences and humanities.",
    allocation: "all",
    careerProspects: [
      "Social Studies Teacher",
      "History Teacher",
      "Geography Teacher",
      "Social Sciences Curriculum Developer",
    ],
  },
  {
    name: "Life Orientation Education",
    faculty: "Education",
    baseAPS: 24,
    duration: "4 years",
    description: "Teaching life skills and personal development.",
    allocation: "all",
    careerProspects: [
      "Life Orientation Teacher",
      "Life Skills Educator",
      "Guidance Counselor",
      "Youth Development Officer",
    ],
  },
  {
    name: "Arts and Culture Education",
    faculty: "Education",
    baseAPS: 25,
    duration: "4 years",
    description: "Teaching arts, culture, and creative subjects.",
    allocation: "all",
    careerProspects: [
      "Arts Teacher",
      "Drama Teacher",
      "Music Teacher",
      "Cultural Education Specialist",
    ],
  },
  {
    name: "Economic and Management Sciences Education",
    faculty: "Education",
    baseAPS: 26,
    duration: "4 years",
    description: "Teaching business and economic principles.",
    allocation: "all",
    careerProspects: [
      "Business Studies Teacher",
      "Economics Teacher",
      "Accounting Teacher",
      "Business Education Specialist",
    ],
  },
  {
    name: "Physical Education",
    faculty: "Education",
    baseAPS: 24,
    duration: "4 years",
    description: "Teaching physical education and sports.",
    allocation: "all",
    careerProspects: [
      "Physical Education Teacher",
      "Sports Coach",
      "Fitness Instructor",
      "Sports Development Officer",
    ],
  },

  // Faculty of Agriculture / Agricultural Sciences
  {
    name: "Bachelor of Agriculture in Animal Science",
    faculty: "Agriculture",
    baseAPS: 26,
    duration: "4 years",
    description: "Study of livestock production and animal husbandry.",
    allocation: "all",
    careerProspects: [
      "Animal Scientist",
      "Livestock Specialist",
      "Animal Nutritionist",
      "Farm Manager",
      "Agricultural Consultant",
    ],
  },
  {
    name: "Plant Production",
    faculty: "Agriculture",
    baseAPS: 25,
    duration: "4 years",
    description: "Crop science and plant cultivation techniques.",
    allocation: "all",
    careerProspects: [
      "Crop Scientist",
      "Agricultural Specialist",
      "Farm Manager",
      "Seed Production Manager",
      "Agricultural Consultant",
    ],
  },
  {
    name: "Agricultural Economics",
    faculty: "Agriculture",
    baseAPS: 27,
    duration: "4 years",
    description: "Economic principles applied to agriculture.",
    allocation: "all",
    careerProspects: [
      "Agricultural Economist",
      "Farm Business Consultant",
      "Agricultural Policy Analyst",
      "Market Researcher",
    ],
  },
  {
    name: "Agricultural Extension",
    faculty: "Agriculture",
    baseAPS: 24,
    duration: "4 years",
    description: "Knowledge transfer and farmer education.",
    allocation: "all",
    careerProspects: [
      "Extension Officer",
      "Agricultural Advisor",
      "Rural Development Officer",
      "Farmer Trainer",
    ],
  },
  {
    name: "Horticulture",
    faculty: "Agriculture",
    baseAPS: 25,
    duration: "4 years",
    description: "Cultivation of fruits, vegetables, and ornamental plants.",
    allocation: "all",
    careerProspects: [
      "Horticulturist",
      "Garden Designer",
      "Greenhouse Manager",
      "Crop Production Manager",
    ],
  },
  {
    name: "Viticulture and Oenology",
    faculty: "Agriculture",
    baseAPS: 27,
    duration: "4 years",
    description: "Grape growing and wine making.",
    allocation: { include: ["su", "uct"] },
    careerProspects: [
      "Viticulturist",
      "Winemaker",
      "Wine Quality Manager",
      "Vineyard Manager",
      "Wine Marketing Specialist",
    ],
  },
  {
    name: "Agricultural Management",
    faculty: "Agriculture",
    baseAPS: 25,
    duration: "4 years",
    description: "Business management principles in agriculture.",
    allocation: "all",
    careerProspects: [
      "Farm Manager",
      "Agricultural Business Manager",
      "Agribusiness Consultant",
      "Agricultural Finance Manager",
    ],
  },
  {
    name: "Food Science and Technology",
    faculty: "Agriculture",
    baseAPS: 28,
    duration: "4 years",
    description: "Food processing, safety, and quality control.",
    allocation: "all",
    careerProspects: [
      "Food Scientist",
      "Food Technologist",
      "Quality Control Manager",
      "Food Safety Inspector",
      "Product Developer",
    ],
  },
  {
    name: "Forestry",
    faculty: "Agriculture",
    baseAPS: 26,
    duration: "4 years",
    description: "Forest management and wood science.",
    allocation: { include: ["su", "uct"] },
    careerProspects: [
      "Forester",
      "Forest Manager",
      "Conservation Officer",
      "Timber Specialist",
      "Environmental Consultant",
    ],
  },
  {
    name: "Game Ranch Management",
    faculty: "Agriculture",
    baseAPS: 24,
    duration: "4 years",
    description: "Wildlife management and game farming.",
    allocation: { include: ["ufh", "ru"] },
    careerProspects: [
      "Game Ranch Manager",
      "Wildlife Manager",
      "Conservation Manager",
      "Eco-tourism Manager",
    ],
  },
  {
    name: "Irrigation Management",
    faculty: "Agriculture",
    baseAPS: 25,
    duration: "4 years",
    description: "Water management for agricultural production.",
    allocation: "all",
    careerProspects: [
      "Irrigation Specialist",
      "Water Management Officer",
      "Agricultural Engineer",
      "Farm Water Consultant",
    ],
  },
  {
    name: "Organic Farming",
    faculty: "Agriculture",
    baseAPS: 24,
    duration: "4 years",
    description: "Sustainable and organic agricultural practices.",
    allocation: { include: ["su"] },
    careerProspects: [
      "Organic Farming Specialist",
      "Sustainable Agriculture Consultant",
      "Organic Certification Officer",
    ],
  },
  {
    name: "Precision Agriculture",
    faculty: "Agriculture",
    baseAPS: 27,
    duration: "4 years",
    description: "Technology-driven agricultural practices.",
    allocation: { include: ["su", "uct"] },
    careerProspects: [
      "Precision Agriculture Specialist",
      "Agricultural Technology Consultant",
      "Farm Data Analyst",
    ],
  },
  {
    name: "Rural Development",
    faculty: "Agriculture",
    baseAPS: 24,
    duration: "4 years",
    description: "Development of rural communities and agriculture.",
    allocation: "all",
    careerProspects: [
      "Rural Development Officer",
      "Community Development Manager",
      "Agricultural Development Specialist",
    ],
  },

  // Faculty of Information Technology / Computer Science
  {
    name: "Bachelor of Information Technology (BIT)",
    faculty: "Information Technology",
    baseAPS: 30,
    duration: "3 years",
    description: "Information systems, networking, and technology management.",
    allocation: "all",
    careerProspects: [
      "IT Specialist",
      "Systems Administrator",
      "Network Manager",
      "IT Consultant",
      "Database Administrator",
    ],
  },
  {
    name: "Bachelor of Science in Computer Science (BSc Computer Science)",
    faculty: "Information Technology",
    baseAPS: 31,
    duration: "3 years",
    description: "Programming, algorithms, and computational theory.",
    allocation: "all",
    careerProspects: [
      "Software Developer",
      "Computer Programmer",
      "Systems Analyst",
      "Software Engineer",
      "Research Scientist",
    ],
  },
  {
    name: "Bachelor of Software Engineering (BSc Software Engineering)",
    faculty: "Information Technology",
    baseAPS: 32,
    duration: "4 years",
    description: "Software design, development, and project management.",
    allocation: "all",
    careerProspects: [
      "Software Engineer",
      "Software Architect",
      "Full-Stack Developer",
      "DevOps Engineer",
      "Technical Lead",
    ],
  },
  {
    name: "Bachelor of Information Systems (BIS)",
    faculty: "Information Technology",
    baseAPS: 29,
    duration: "3 years",
    description: "Business information systems and data management.",
    allocation: "all",
    careerProspects: [
      "Information Systems Analyst",
      "Business Analyst",
      "Data Analyst",
      "Systems Consultant",
      "IT Project Manager",
    ],
  },
  {
    name: "Bachelor of Cybersecurity",
    faculty: "Information Technology",
    baseAPS: 31,
    duration: "3 years",
    description:
      "Information security, network security, and cyber threat management.",
    allocation: "all",
    careerProspects: [
      "Cybersecurity Analyst",
      "Security Engineer",
      "Ethical Hacker",
      "Security Consultant",
      "Information Security Manager",
    ],
  },
  {
    name: "Bachelor of Data Science",
    faculty: "Information Technology",
    baseAPS: 32,
    duration: "3 years",
    description: "Data analysis, machine learning, and statistical modeling.",
    allocation: "all",
    careerProspects: [
      "Data Scientist",
      "Data Analyst",
      "Machine Learning Engineer",
      "Business Intelligence Analyst",
      "Research Scientist",
    ],
  },
  {
    name: "Bachelor of Artificial Intelligence",
    faculty: "Information Technology",
    baseAPS: 33,
    duration: "3 years",
    description: "AI systems, machine learning, and intelligent algorithms.",
    allocation: "all",
    careerProspects: [
      "AI Engineer",
      "Machine Learning Specialist",
      "AI Researcher",
      "Robotics Engineer",
      "Data Scientist",
    ],
  },
  {
    name: "Bachelor of Game Development",
    faculty: "Information Technology",
    baseAPS: 29,
    duration: "3 years",
    description: "Video game design and development.",
    allocation: "all",
    careerProspects: [
      "Game Developer",
      "Game Designer",
      "3D Modeler",
      "Game Programmer",
      "Interactive Media Developer",
    ],
  },
  {
    name: "Bachelor of Web Development",
    faculty: "Information Technology",
    baseAPS: 28,
    duration: "3 years",
    description: "Web design, development, and digital media.",
    allocation: "all",
    careerProspects: [
      "Web Developer",
      "Frontend Developer",
      "Backend Developer",
      "Full-Stack Developer",
      "Web Designer",
    ],
  },
  {
    name: "Bachelor of Mobile Application Development",
    faculty: "Information Technology",
    baseAPS: 29,
    duration: "3 years",
    description: "Mobile app development for various platforms.",
    allocation: "all",
    careerProspects: [
      "Mobile App Developer",
      "iOS Developer",
      "Android Developer",
      "Mobile UX Designer",
      "App Product Manager",
    ],
  },
  {
    name: "Bachelor of Network Engineering",
    faculty: "Information Technology",
    baseAPS: 30,
    duration: "3 years",
    description: "Computer networks and telecommunications.",
    allocation: "all",
    careerProspects: [
      "Network Engineer",
      "Network Administrator",
      "Telecommunications Specialist",
      "Network Security Engineer",
    ],
  },
  {
    name: "Bachelor of Cloud Computing",
    faculty: "Information Technology",
    baseAPS: 30,
    duration: "3 years",
    description: "Cloud infrastructure and distributed computing.",
    allocation: "all",
    careerProspects: [
      "Cloud Engineer",
      "Cloud Architect",
      "DevOps Engineer",
      "Cloud Consultant",
      "Systems Engineer",
    ],
  },
  {
    name: "Bachelor of Digital Media",
    faculty: "Information Technology",
    baseAPS: 27,
    duration: "3 years",
    description: "Digital content creation and multimedia production.",
    allocation: "all",
    careerProspects: [
      "Digital Media Specialist",
      "Multimedia Designer",
      "Content Creator",
      "Digital Marketing Specialist",
    ],
  },

  // Faculty of Built Environment / Architecture and Planning
  {
    name: "Bachelor of Architecture (BArch)",
    faculty: "Built Environment",
    baseAPS: 32,
    duration: "5 years",
    description: "Architectural design and building design.",
    allocation: { exclude: ["unisa", "ufh"] },
    isCompetitive: true,
    careerProspects: [
      "Architect",
      "Building Designer",
      "Urban Designer",
      "Heritage Architect",
      "Landscape Architect",
    ],
  },
  {
    name: "Bachelor of Architectural Studies (BAS)",
    faculty: "Built Environment",
    baseAPS: 30,
    duration: "3 years",
    description: "Foundation studies in architecture and design.",
    allocation: { exclude: ["unisa", "ufh"] },
    careerProspects: [
      "Architectural Technician",
      "Design Assistant",
      "Building Inspector",
      "CAD Specialist",
    ],
  },
  {
    name: "Bachelor of Urban and Regional Planning",
    faculty: "Built Environment",
    baseAPS: 26,
    duration: "4 years",
    description: "Urban planning and regional development.",
    allocation: { exclude: ["unisa", "ufh"] },
    careerProspects: [
      "Urban Planner",
      "Regional Planner",
      "Development Manager",
      "Municipal Planner",
      "Transport Planner",
    ],
  },
  {
    name: "Bachelor of Construction Studies",
    faculty: "Built Environment",
    baseAPS: 26,
    duration: "4 years",
    description: "Construction management and building technology.",
    allocation: "all",
    careerProspects: [
      "Construction Manager",
      "Project Manager",
      "Site Manager",
      "Building Inspector",
      "Construction Consultant",
    ],
  },
  {
    name: "Bachelor of Quantity Surveying",
    faculty: "Built Environment",
    baseAPS: 28,
    duration: "4 years",
    description: "Construction costs and project management.",
    allocation: "all",
    careerProspects: [
      "Quantity Surveyor",
      "Cost Engineer",
      "Project Manager",
      "Construction Consultant",
      "Property Developer",
    ],
  },
  {
    name: "Bachelor of Property Studies",
    faculty: "Built Environment",
    baseAPS: 26,
    duration: "3 years",
    description: "Property management and real estate.",
    allocation: { exclude: ["unisa"] },
    careerProspects: [
      "Property Manager",
      "Real Estate Agent",
      "Property Valuer",
      "Property Developer",
      "Property Investment Analyst",
    ],
  },
  {
    name: "Bachelor of Real Estate",
    faculty: "Built Environment",
    baseAPS: 25,
    duration: "3 years",
    description: "Real estate development and management.",
    allocation: { include: ["tut", "dut"] },
    careerProspects: [
      "Real Estate Developer",
      "Property Manager",
      "Real Estate Consultant",
      "Property Investment Manager",
    ],
  },
  {
    name: "Bachelor of Facilities Management",
    faculty: "Built Environment",
    baseAPS: 24,
    duration: "3 years",
    description: "Management of building operations and services.",
    allocation: { include: ["tut", "dut"] },
    careerProspects: [
      "Facilities Manager",
      "Building Operations Manager",
      "Maintenance Manager",
      "Space Planner",
    ],
  },
  {
    name: "Bachelor of Housing Studies",
    faculty: "Built Environment",
    baseAPS: 24,
    duration: "3 years",
    description: "Housing policy and development.",
    allocation: { include: ["tut", "dut"] },
    careerProspects: [
      "Housing Development Officer",
      "Social Housing Manager",
      "Housing Policy Analyst",
      "Community Development Officer",
    ],
  },
  {
    name: "Bachelor of Interior Architecture",
    faculty: "Built Environment",
    baseAPS: 28,
    duration: "4 years",
    description: "Interior design and space planning.",
    allocation: { exclude: ["unisa", "ufh"] },
    careerProspects: [
      "Interior Architect",
      "Interior Designer",
      "Space Planner",
      "Furniture Designer",
      "Exhibition Designer",
    ],
  },
  {
    name: "Bachelor of Landscape Architecture",
    faculty: "Built Environment",
    baseAPS: 29,
    duration: "4 years",
    description: "Landscape design and environmental planning.",
    allocation: { exclude: ["unisa", "ufh"] },
    careerProspects: [
      "Landscape Architect",
      "Garden Designer",
      "Urban Designer",
      "Environmental Planner",
      "Park Designer",
    ],
  },

  // Technical and Vocational Programmes (mostly at Universities of Technology)
  {
    name: "National Diploma in Engineering (various disciplines)",
    faculty: "Engineering",
    baseAPS: 26,
    duration: "3 years",
    description: "Technical engineering training in various specializations.",
    allocation: { include: ["tut", "dut", "mut", "vut"] },
    careerProspects: [
      "Engineering Technician",
      "Technical Officer",
      "Production Manager",
      "Quality Controller",
      "Engineering Assistant",
    ],
  },
  {
    name: "National Diploma in Information Technology",
    faculty: "Information Technology",
    baseAPS: 25,
    duration: "3 years",
    description: "Technical IT skills and computer systems.",
    allocation: { include: ["tut", "dut", "mut", "vut"] },
    careerProspects: [
      "IT Technician",
      "Computer Support Specialist",
      "Network Technician",
      "Database Administrator",
    ],
  },
  {
    name: "National Diploma in Business Studies",
    faculty: "Commerce",
    baseAPS: 24,
    duration: "3 years",
    description: "Practical business skills and management.",
    allocation: { include: ["tut", "dut", "mut", "vut"] },
    careerProspects: [
      "Business Administrator",
      "Office Manager",
      "Small Business Owner",
      "Administrative Officer",
    ],
  },
  {
    name: "National Diploma in Hospitality Management",
    faculty: "Commerce",
    baseAPS: 23,
    duration: "3 years",
    description: "Hotel and hospitality industry management.",
    allocation: { include: ["tut", "dut", "mut", "vut"] },
    careerProspects: [
      "Hotel Manager",
      "Restaurant Manager",
      "Event Coordinator",
      "Guest Relations Manager",
    ],
  },
  {
    name: "National Diploma in Tourism Management",
    faculty: "Commerce",
    baseAPS: 23,
    duration: "3 years",
    description: "Tourism industry operations and management.",
    allocation: { include: ["tut", "dut", "mut", "vut"] },
    careerProspects: [
      "Tourism Officer",
      "Travel Consultant",
      "Tour Guide",
      "Tourism Marketing Specialist",
    ],
  },
  {
    name: "National Diploma in Public Management",
    faculty: "Commerce",
    baseAPS: 24,
    duration: "3 years",
    description: "Public sector administration and management.",
    allocation: { include: ["tut", "dut", "mut", "vut"] },
    careerProspects: [
      "Public Administrator",
      "Government Officer",
      "Municipal Official",
      "Public Service Manager",
    ],
  },
  {
    name: "National Diploma in Graphic Design",
    faculty: "Humanities",
    baseAPS: 25,
    duration: "3 years",
    description: "Visual design and communication graphics.",
    allocation: { include: ["tut", "dut", "mut", "vut"] },
    careerProspects: [
      "Graphic Designer",
      "Visual Designer",
      "Brand Designer",
      "Web Designer",
      "Art Director",
    ],
  },
  {
    name: "National Diploma in Environmental Health",
    faculty: "Health Sciences",
    baseAPS: 26,
    duration: "3 years",
    description: "Environmental health and safety management.",
    allocation: { include: ["tut", "dut", "mut", "vut"] },
    careerProspects: [
      "Environmental Health Officer",
      "Health Inspector",
      "Occupational Health Specialist",
      "Safety Officer",
    ],
  },
  {
    name: "National Diploma in Food Technology",
    faculty: "Agriculture",
    baseAPS: 26,
    duration: "3 years",
    description: "Food processing and quality control.",
    allocation: { include: ["tut", "dut", "mut", "vut"] },
    careerProspects: [
      "Food Technologist",
      "Quality Control Officer",
      "Food Safety Inspector",
      "Product Development Specialist",
    ],
  },
];

// Function to generate programs for a specific university
export const generateUniversityPrograms = (
  universityId: string,
  universityType: string,
  excludedPrograms: string[] = [],
): Degree[] => {
  const programs: Degree[] = [];

  COMPREHENSIVE_PROGRAMS.forEach((program, index) => {
    let shouldInclude = false;

    // Check allocation rules
    if (program.allocation === "all") {
      shouldInclude = true;
    } else if ("exclude" in program.allocation) {
      shouldInclude = !program.allocation.exclude.includes(universityId);
    } else if ("include" in program.allocation) {
      shouldInclude = program.allocation.include.includes(universityId);
    }

    // Check if program is excluded for this university
    if (excludedPrograms.includes(program.name)) {
      shouldInclude = false;
    }

    if (shouldInclude) {
      const universitySpecificAPS = generateUniversityAPS(
        program.baseAPS,
        universityType,
        universityId,
        program.isCompetitive,
      );

      programs.push({
        id: `${universityId}-${program.name.toLowerCase().replace(/\s+/g, "-")}-${index}`,
        name: program.name,
        code: program.name.toUpperCase().replace(/\s+/g, ""),
        faculty: program.faculty,
        duration: program.duration,
        apsRequirement: universitySpecificAPS,
        description: program.description,
        subjects: [], // Will be populated with appropriate subjects
        careerProspects: program.careerProspects,
        assignmentRule: program.allocation,
      });
    }
  });

  return programs;
};

// Function to get all unique faculties
export const getAllFaculties = (): string[] => {
  const faculties = new Set<string>();
  COMPREHENSIVE_PROGRAMS.forEach((program) => {
    faculties.add(program.faculty);
  });
  return Array.from(faculties);
};

// Function to count programs by faculty
export const getProgramCountByFaculty = (): Record<string, number> => {
  const counts: Record<string, number> = {};
  COMPREHENSIVE_PROGRAMS.forEach((program) => {
    counts[program.faculty] = (counts[program.faculty] || 0) + 1;
  });
  return counts;
};

// Export program statistics
export const PROGRAM_STATISTICS = {
  totalPrograms: COMPREHENSIVE_PROGRAMS.length,
  facultyCount: getAllFaculties().length,
  programsByFaculty: getProgramCountByFaculty(),
  competitivePrograms: COMPREHENSIVE_PROGRAMS.filter((p) => p.isCompetitive)
    .length,
  universalPrograms: COMPREHENSIVE_PROGRAMS.filter(
    (p) => p.allocation === "all",
  ).length,
};

// Console logging for debugging
if (import.meta.env.DEV) {
  console.log(
    `📚 Comprehensive Programs Database loaded: ${COMPREHENSIVE_PROGRAMS.length} programs across ${getAllFaculties().length} faculties`,
  );
  console.log(`📊 Program breakdown:`, getProgramCountByFaculty());
}
