// This file contains comprehensive program data for major South African universities
// Based on 2024/2025 admission requirements and APS scores

import { University } from "@/types/university";

// Common APS Requirements (researched from university admission offices):
// Medicine: 40-45 (depends on NBT and additional requirements)
// Engineering: 35-42
// Law: 32-38
// Commerce: 28-36
// Science: 30-38
// Humanities: 24-32
// Education: 22-28

export const COMPREHENSIVE_UNIVERSITY_PROGRAMS = {
  // Common Faculty Templates
  COMMON_SCIENCE_PROGRAMS: [
    {
      id: "bsc-biological-sciences",
      name: "BSc Biological Sciences",
      faculty: "Science",
      duration: "3 years",
      apsRequirement: 35,
      description:
        "Comprehensive study of living organisms from molecular to ecosystem levels.",
      subjects: [
        { name: "Life Sciences", level: 6, isRequired: true },
        { name: "Mathematics", level: 5, isRequired: true },
        { name: "English", level: 5, isRequired: true },
      ],
      careerProspects: [
        "Biologist",
        "Research Scientist",
        "Conservation Scientist",
        "Biotechnologist",
        "Environmental Consultant",
      ],
    },
    {
      id: "bsc-chemistry",
      name: "BSc Chemistry",
      faculty: "Science",
      duration: "3 years",
      apsRequirement: 36,
      description: "Study of matter, its properties, and chemical reactions.",
      subjects: [
        { name: "Physical Sciences", level: 6, isRequired: true },
        { name: "Mathematics", level: 6, isRequired: true },
        { name: "English", level: 5, isRequired: true },
      ],
      careerProspects: [
        "Chemist",
        "Pharmaceutical Researcher",
        "Quality Control Analyst",
        "Chemical Engineer",
        "Forensic Scientist",
      ],
    },
    {
      id: "bsc-physics",
      name: "BSc Physics",
      faculty: "Science",
      duration: "3 years",
      apsRequirement: 38,
      description: "Study of fundamental laws governing the universe.",
      subjects: [
        { name: "Physical Sciences", level: 6, isRequired: true },
        { name: "Mathematics", level: 7, isRequired: true },
        { name: "English", level: 5, isRequired: true },
      ],
      careerProspects: [
        "Physicist",
        "Research Scientist",
        "Data Analyst",
        "Engineering Physicist",
        "Quantitative Analyst",
      ],
    },
    {
      id: "bsc-environmental-science",
      name: "BSc Environmental Science",
      faculty: "Science",
      duration: "3 years",
      apsRequirement: 32,
      description: "Interdisciplinary study of environmental systems.",
      subjects: [
        { name: "Life Sciences", level: 5, isRequired: true },
        { name: "Mathematics", level: 5, isRequired: true },
        { name: "Geography", level: 4, isRequired: false },
        { name: "English", level: 5, isRequired: true },
      ],
      careerProspects: [
        "Environmental Consultant",
        "Conservation Scientist",
        "Environmental Impact Assessor",
        "Sustainability Specialist",
        "Climate Change Analyst",
      ],
    },
    {
      id: "bsc-mathematical-sciences",
      name: "BSc Mathematical Sciences",
      faculty: "Science",
      duration: "3 years",
      apsRequirement: 38,
      description: "Pure and applied mathematics with analytical focus.",
      subjects: [
        { name: "Mathematics", level: 7, isRequired: true },
        { name: "Physical Sciences", level: 5, isRequired: false },
        { name: "English", level: 5, isRequired: true },
      ],
      careerProspects: [
        "Mathematician",
        "Actuary",
        "Data Scientist",
        "Financial Analyst",
        "Research Scientist",
      ],
    },
    {
      id: "bsc-computer-science",
      name: "BSc Computer Science",
      faculty: "Science",
      duration: "3 years",
      apsRequirement: 42,
      description: "Comprehensive computer science program.",
      subjects: [
        { name: "Mathematics", level: 6, isRequired: true },
        { name: "English", level: 5, isRequired: true },
        { name: "Physical Sciences", level: 5, isRequired: false },
      ],
      careerProspects: [
        "Software Developer",
        "Data Scientist",
        "Systems Analyst",
        "Research Scientist",
        "AI Specialist",
      ],
    },
  ],

  COMMON_HUMANITIES_PROGRAMS: [
    {
      id: "ba-psychology",
      name: "BA Psychology",
      faculty: "Humanities",
      duration: "3 years",
      apsRequirement: 30,
      description: "Study of human behavior, cognition, and mental processes.",
      subjects: [
        { name: "English", level: 5, isRequired: true },
        { name: "Mathematics", level: 4, isRequired: true },
        { name: "Life Sciences", level: 4, isRequired: false },
      ],
      careerProspects: [
        "Clinical Psychologist",
        "Counselor",
        "Human Resources Specialist",
        "Research Psychologist",
        "Educational Psychologist",
      ],
    },
    {
      id: "ba-sociology",
      name: "BA Sociology",
      faculty: "Humanities",
      duration: "3 years",
      apsRequirement: 28,
      description: "Study of society, social behavior, and social structures.",
      subjects: [
        { name: "English", level: 5, isRequired: true },
        { name: "History", level: 4, isRequired: false },
        { name: "Geography", level: 4, isRequired: false },
      ],
      careerProspects: [
        "Social Worker",
        "Community Development Worker",
        "Policy Analyst",
        "Research Analyst",
        "Social Consultant",
      ],
    },
    {
      id: "ba-political-science",
      name: "BA Political Science",
      faculty: "Humanities",
      duration: "3 years",
      apsRequirement: 30,
      description: "Study of political systems, governance, and public policy.",
      subjects: [
        { name: "English", level: 5, isRequired: true },
        { name: "History", level: 4, isRequired: false },
        { name: "Geography", level: 4, isRequired: false },
      ],
      careerProspects: [
        "Policy Analyst",
        "Political Consultant",
        "Government Official",
        "Diplomat",
        "Political Journalist",
      ],
    },
    {
      id: "ba-history",
      name: "BA History",
      faculty: "Humanities",
      duration: "3 years",
      apsRequirement: 28,
      description: "Study of past events, cultures, and civilizations.",
      subjects: [
        { name: "English", level: 5, isRequired: true },
        { name: "History", level: 5, isRequired: true },
        { name: "Geography", level: 4, isRequired: false },
      ],
      careerProspects: [
        "Historian",
        "Museum Curator",
        "Archivist",
        "Teacher",
        "Cultural Heritage Specialist",
      ],
    },
    {
      id: "ba-english",
      name: "BA English",
      faculty: "Humanities",
      duration: "3 years",
      apsRequirement: 28,
      description: "Study of English literature, language, and communication.",
      subjects: [
        { name: "English", level: 6, isRequired: true },
        { name: "History", level: 4, isRequired: false },
      ],
      careerProspects: [
        "Writer",
        "Editor",
        "Teacher",
        "Journalist",
        "Communications Specialist",
      ],
    },
    {
      id: "ba-philosophy",
      name: "BA Philosophy",
      faculty: "Humanities",
      duration: "3 years",
      apsRequirement: 30,
      description:
        "Study of fundamental questions about existence, knowledge, and ethics.",
      subjects: [
        { name: "English", level: 5, isRequired: true },
        { name: "Mathematics", level: 4, isRequired: false },
      ],
      careerProspects: [
        "Philosophy Professor",
        "Ethics Consultant",
        "Policy Analyst",
        "Writer",
        "Legal Advisor",
      ],
    },
    {
      id: "ba-media-communication",
      name: "BA Media & Communication",
      faculty: "Humanities",
      duration: "3 years",
      apsRequirement: 30,
      description:
        "Study of media, journalism, and communication in the digital age.",
      subjects: [
        { name: "English", level: 5, isRequired: true },
        { name: "History", level: 4, isRequired: false },
      ],
      careerProspects: [
        "Journalist",
        "Media Producer",
        "Communications Manager",
        "Digital Content Creator",
        "Public Relations Specialist",
      ],
    },
  ],

  COMMON_COMMERCE_PROGRAMS: [
    {
      id: "bcom-accounting",
      name: "BCom Accounting",
      faculty: "Commerce",
      duration: "3 years",
      apsRequirement: 36,
      description: "Professional accounting education with CA(SA) pathway.",
      subjects: [
        { name: "Mathematics", level: 5, isRequired: true },
        { name: "English", level: 5, isRequired: true },
        { name: "Accounting", level: 5, isRequired: false },
      ],
      careerProspects: [
        "Chartered Accountant",
        "Financial Manager",
        "Auditor",
        "Tax Consultant",
        "Financial Analyst",
      ],
    },
    {
      id: "bcom-economics",
      name: "BCom Economics",
      faculty: "Commerce",
      duration: "3 years",
      apsRequirement: 34,
      description:
        "Economic theory and analysis for policy and business applications.",
      subjects: [
        { name: "Mathematics", level: 6, isRequired: true },
        { name: "English", level: 5, isRequired: true },
        { name: "Economics", level: 4, isRequired: false },
      ],
      careerProspects: [
        "Economist",
        "Policy Analyst",
        "Financial Analyst",
        "Research Economist",
        "Investment Analyst",
      ],
    },
    {
      id: "bcom-business-management",
      name: "BCom Business Management",
      faculty: "Commerce",
      duration: "3 years",
      apsRequirement: 32,
      description: "Comprehensive business management and leadership training.",
      subjects: [
        { name: "Mathematics", level: 5, isRequired: true },
        { name: "English", level: 5, isRequired: true },
        { name: "Business Studies", level: 4, isRequired: false },
      ],
      careerProspects: [
        "Business Manager",
        "Management Consultant",
        "Operations Manager",
        "Project Manager",
        "Entrepreneur",
      ],
    },
    {
      id: "bcom-human-resources",
      name: "BCom Human Resource Management",
      faculty: "Commerce",
      duration: "3 years",
      apsRequirement: 30,
      description: "Human resource management and organizational behavior.",
      subjects: [
        { name: "Mathematics", level: 4, isRequired: true },
        { name: "English", level: 5, isRequired: true },
        { name: "Business Studies", level: 4, isRequired: false },
      ],
      careerProspects: [
        "HR Manager",
        "Recruitment Specialist",
        "Training Manager",
        "Employee Relations Specialist",
        "Organizational Development Consultant",
      ],
    },
    {
      id: "bcom-marketing",
      name: "BCom Marketing",
      faculty: "Commerce",
      duration: "3 years",
      apsRequirement: 30,
      description:
        "Marketing strategy, consumer behavior, and digital marketing.",
      subjects: [
        { name: "Mathematics", level: 4, isRequired: true },
        { name: "English", level: 5, isRequired: true },
        { name: "Business Studies", level: 4, isRequired: false },
      ],
      careerProspects: [
        "Marketing Manager",
        "Digital Marketing Specialist",
        "Brand Manager",
        "Market Research Analyst",
        "Advertising Executive",
      ],
    },
    {
      id: "bcom-finance",
      name: "BCom Finance",
      faculty: "Commerce",
      duration: "3 years",
      apsRequirement: 34,
      description:
        "Financial management, investment analysis, and corporate finance.",
      subjects: [
        { name: "Mathematics", level: 6, isRequired: true },
        { name: "English", level: 5, isRequired: true },
        { name: "Accounting", level: 4, isRequired: false },
      ],
      careerProspects: [
        "Financial Analyst",
        "Investment Banker",
        "Portfolio Manager",
        "Risk Manager",
        "Corporate Finance Manager",
      ],
    },
  ],

  COMMON_EDUCATION_PROGRAMS: [
    {
      id: "bed-foundation-phase",
      name: "BEd Foundation Phase",
      faculty: "Education",
      duration: "4 years",
      apsRequirement: 26,
      description: "Teacher training for Grade R to Grade 3.",
      subjects: [
        { name: "English", level: 5, isRequired: true },
        { name: "Mathematics", level: 4, isRequired: true },
        { name: "Life Sciences", level: 4, isRequired: false },
      ],
      careerProspects: [
        "Foundation Phase Teacher",
        "Education Specialist",
        "Curriculum Developer",
        "Educational Consultant",
        "School Principal",
      ],
    },
    {
      id: "bed-intermediate-phase",
      name: "BEd Intermediate Phase",
      faculty: "Education",
      duration: "4 years",
      apsRequirement: 26,
      description: "Teacher training for Grade 4 to Grade 6.",
      subjects: [
        { name: "English", level: 5, isRequired: true },
        { name: "Mathematics", level: 5, isRequired: true },
        { name: "Life Sciences", level: 4, isRequired: false },
      ],
      careerProspects: [
        "Intermediate Phase Teacher",
        "Education Specialist",
        "Curriculum Developer",
        "Educational Consultant",
        "School Principal",
      ],
    },
    {
      id: "bed-senior-fet-phase",
      name: "BEd Senior & FET Phase",
      faculty: "Education",
      duration: "4 years",
      apsRequirement: 28,
      description: "Teacher training for Grade 7 to Grade 12.",
      subjects: [
        { name: "English", level: 5, isRequired: true },
        { name: "Mathematics", level: 5, isRequired: true },
        { name: "Teaching Subject", level: 5, isRequired: true },
      ],
      careerProspects: [
        "High School Teacher",
        "Subject Specialist",
        "Curriculum Developer",
        "Educational Consultant",
        "School Principal",
      ],
    },
    {
      id: "pgce",
      name: "PGCE (Postgraduate Certificate in Education)",
      faculty: "Education",
      duration: "1 year",
      apsRequirement: 30,
      description: "Professional teacher qualification for degree holders.",
      subjects: [
        { name: "Bachelor's Degree", level: 0, isRequired: true },
        { name: "English", level: 5, isRequired: true },
      ],
      careerProspects: [
        "Professional Teacher",
        "Education Specialist",
        "Training Manager",
        "Educational Consultant",
        "Corporate Trainer",
      ],
    },
  ],

  COMMON_ENGINEERING_PROGRAMS: [
    {
      id: "beng-mechanical",
      name: "BEng Mechanical Engineering",
      faculty: "Engineering",
      duration: "4 years",
      apsRequirement: 42,
      description: "Design and development of mechanical systems and machines.",
      subjects: [
        { name: "Mathematics", level: 6, isRequired: true },
        { name: "Physical Sciences", level: 6, isRequired: true },
        { name: "English", level: 5, isRequired: true },
      ],
      careerProspects: [
        "Mechanical Engineer",
        "Design Engineer",
        "Manufacturing Engineer",
        "Project Manager",
        "Research Engineer",
      ],
    },
    {
      id: "beng-civil",
      name: "BEng Civil Engineering",
      faculty: "Engineering",
      duration: "4 years",
      apsRequirement: 42,
      description:
        "Infrastructure design, construction, and environmental engineering.",
      subjects: [
        { name: "Mathematics", level: 6, isRequired: true },
        { name: "Physical Sciences", level: 6, isRequired: true },
        { name: "English", level: 5, isRequired: true },
      ],
      careerProspects: [
        "Civil Engineer",
        "Structural Engineer",
        "Water Resources Engineer",
        "Transportation Engineer",
        "Construction Manager",
      ],
    },
    {
      id: "beng-electrical",
      name: "BEng Electrical Engineering",
      faculty: "Engineering",
      duration: "4 years",
      apsRequirement: 42,
      description: "Electrical systems, electronics, and power engineering.",
      subjects: [
        { name: "Mathematics", level: 6, isRequired: true },
        { name: "Physical Sciences", level: 6, isRequired: true },
        { name: "English", level: 5, isRequired: true },
      ],
      careerProspects: [
        "Electrical Engineer",
        "Electronics Engineer",
        "Power Systems Engineer",
        "Control Systems Engineer",
        "Telecommunications Engineer",
      ],
    },
    {
      id: "beng-chemical",
      name: "BEng Chemical Engineering",
      faculty: "Engineering",
      duration: "4 years",
      apsRequirement: 42,
      description:
        "Chemical processes, materials engineering, and biotechnology.",
      subjects: [
        { name: "Mathematics", level: 6, isRequired: true },
        { name: "Physical Sciences", level: 6, isRequired: true },
        { name: "English", level: 5, isRequired: true },
      ],
      careerProspects: [
        "Chemical Engineer",
        "Process Engineer",
        "Environmental Engineer",
        "Biotechnology Engineer",
        "Materials Engineer",
      ],
    },
    {
      id: "beng-industrial",
      name: "BEng Industrial Engineering",
      faculty: "Engineering",
      duration: "4 years",
      apsRequirement: 40,
      description: "Optimization of systems, processes, and operations.",
      subjects: [
        { name: "Mathematics", level: 6, isRequired: true },
        { name: "Physical Sciences", level: 5, isRequired: true },
        { name: "English", level: 5, isRequired: true },
      ],
      careerProspects: [
        "Industrial Engineer",
        "Operations Manager",
        "Quality Manager",
        "Supply Chain Manager",
        "Management Consultant",
      ],
    },
  ],

  COMMON_HEALTH_SCIENCES_PROGRAMS: [
    {
      id: "mbchb-medicine",
      name: "MBChB (Medicine)",
      faculty: "Health Sciences",
      duration: "6 years",
      apsRequirement: 42,
      description: "Medical degree with comprehensive clinical training.",
      subjects: [
        { name: "Mathematics", level: 6, isRequired: true },
        { name: "Physical Sciences", level: 6, isRequired: true },
        { name: "Life Sciences", level: 6, isRequired: true },
        { name: "English", level: 5, isRequired: true },
      ],
      careerProspects: [
        "Medical Doctor",
        "Specialist Physician",
        "General Practitioner",
        "Medical Researcher",
        "Public Health Officer",
      ],
    },
    {
      id: "bnurs-nursing",
      name: "BNurs (Nursing)",
      faculty: "Health Sciences",
      duration: "4 years",
      apsRequirement: 32,
      description: "Professional nursing education with clinical practice.",
      subjects: [
        { name: "Mathematics", level: 4, isRequired: true },
        { name: "Life Sciences", level: 5, isRequired: true },
        { name: "English", level: 5, isRequired: true },
      ],
      careerProspects: [
        "Professional Nurse",
        "Nurse Manager",
        "Clinical Nurse Specialist",
        "Community Health Nurse",
        "Nursing Educator",
      ],
    },
    {
      id: "bsc-physiotherapy",
      name: "BSc Physiotherapy",
      faculty: "Health Sciences",
      duration: "4 years",
      apsRequirement: 38,
      description: "Physical rehabilitation and movement therapy.",
      subjects: [
        { name: "Mathematics", level: 5, isRequired: true },
        { name: "Life Sciences", level: 6, isRequired: true },
        { name: "Physical Sciences", level: 5, isRequired: true },
        { name: "English", level: 5, isRequired: true },
      ],
      careerProspects: [
        "Physiotherapist",
        "Sports Therapist",
        "Rehabilitation Specialist",
        "Private Practice Owner",
        "Research Physiotherapist",
      ],
    },
    {
      id: "bsc-occupational-therapy",
      name: "BSc Occupational Therapy",
      faculty: "Health Sciences",
      duration: "4 years",
      apsRequirement: 36,
      description:
        "Helping people participate in daily activities through therapy.",
      subjects: [
        { name: "Mathematics", level: 4, isRequired: true },
        { name: "Life Sciences", level: 6, isRequired: true },
        { name: "English", level: 5, isRequired: true },
      ],
      careerProspects: [
        "Occupational Therapist",
        "Rehabilitation Specialist",
        "Pediatric Therapist",
        "Mental Health Therapist",
        "Community Health Worker",
      ],
    },
    {
      id: "bsc-dietetics",
      name: "BSc Dietetics",
      faculty: "Health Sciences",
      duration: "4 years",
      apsRequirement: 34,
      description:
        "Nutrition science and dietary therapy for health promotion.",
      subjects: [
        { name: "Mathematics", level: 5, isRequired: true },
        { name: "Life Sciences", level: 6, isRequired: true },
        { name: "Physical Sciences", level: 5, isRequired: true },
        { name: "English", level: 5, isRequired: true },
      ],
      careerProspects: [
        "Dietitian",
        "Nutritionist",
        "Sports Nutritionist",
        "Clinical Dietitian",
        "Public Health Nutritionist",
      ],
    },
    {
      id: "bsc-medical-laboratory-sciences",
      name: "BSc Medical Laboratory Sciences",
      faculty: "Health Sciences",
      duration: "4 years",
      apsRequirement: 34,
      description: "Laboratory diagnostics and medical testing.",
      subjects: [
        { name: "Mathematics", level: 5, isRequired: true },
        { name: "Life Sciences", level: 6, isRequired: true },
        { name: "Physical Sciences", level: 6, isRequired: true },
        { name: "English", level: 5, isRequired: true },
      ],
      careerProspects: [
        "Medical Technologist",
        "Laboratory Manager",
        "Research Technician",
        "Quality Control Specialist",
        "Diagnostic Specialist",
      ],
    },
  ],

  COMMON_LAW_PROGRAMS: [
    {
      id: "llb-law",
      name: "LLB (Bachelor of Laws)",
      faculty: "Law",
      duration: "4 years",
      apsRequirement: 38,
      description: "Comprehensive legal education covering all areas of law.",
      subjects: [
        { name: "English", level: 6, isRequired: true },
        { name: "Mathematics", level: 4, isRequired: true },
        { name: "History", level: 4, isRequired: false },
      ],
      careerProspects: [
        "Advocate",
        "Attorney",
        "Legal Advisor",
        "Magistrate",
        "Corporate Lawyer",
      ],
    },
  ],

  // Specialized Programs by University
  UCT_SPECIALIZED: [
    {
      id: "bsw-social-work",
      name: "Bachelor of Social Work",
      faculty: "Humanities",
      duration: "4 years",
      apsRequirement: 28,
      description:
        "Professional social work training with practical experience (UCT specialty).",
      subjects: [
        { name: "English", level: 5, isRequired: true },
        { name: "Mathematics", level: 4, isRequired: true },
        { name: "Life Sciences", level: 4, isRequired: false },
      ],
      careerProspects: [
        "Social Worker",
        "Community Development Worker",
        "Family Counselor",
        "Child Protection Officer",
        "NGO Program Manager",
      ],
    },
    {
      id: "bfa-fine-art",
      name: "Bachelor of Fine Art",
      faculty: "Humanities",
      duration: "4 years",
      apsRequirement: 26,
      description:
        "Creative arts education with studio practice (UCT specialty).",
      subjects: [
        { name: "English", level: 4, isRequired: true },
        { name: "Visual Arts", level: 5, isRequired: false },
      ],
      careerProspects: [
        "Fine Artist",
        "Art Curator",
        "Art Therapist",
        "Gallery Manager",
        "Art Teacher",
      ],
    },
  ],
};
