import { Bursary } from "@/types/university";

export const BURSARIES: Bursary[] = [
  {
    id: "nsfas",
    name: "NSFAS (National Student Financial Aid Scheme)",
    provider: "Department of Higher Education and Training",
    description:
      "Government financial aid for South African students from poor and working-class families.",
    amount:
      "Full tuition + accommodation + meal allowance + book allowance + transport allowance",
    eligibilityCriteria: [
      "South African citizen",
      "Combined annual household income ≤ R350,000",
      "SASSA grant recipient qualifies regardless of household income",
      "Must be studying at a public university or TVET college",
      "Must pass at least 75% of modules per year to continue funding",
    ],
    applicationDeadline: "31 January annually",
    applicationProcess: "Apply online at www.nsfas.org.za",
    contactInfo: "08000 67327 | info@nsfas.org.za",
    website: "https://www.nsfas.org.za",
    fieldsOfStudy: ["All fields"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "NSC pass with admission to higher education",
      financialNeed: true,
    },
  },
  {
    id: "funza-lushaka",
    name: "Funza Lushaka Bursary",
    provider: "Department of Basic Education",
    description:
      "Bursary for students studying to become teachers in public schools.",
    amount:
      "Full tuition + accommodation + meal allowance + book allowance + transport allowance",
    eligibilityCriteria: [
      "South African citizen",
      "Studying Initial Teacher Education qualifications",
      "Agree to teach in public schools for same number of years as bursary received",
      "Maintain good academic standing",
    ],
    applicationDeadline: "31 January annually",
    applicationProcess: "Apply online at www.funzalushaka.doe.gov.za",
    contactInfo: "0800 202 933 | bursaries@dbe.gov.za",
    website: "https://www.funzalushaka.doe.gov.za",
    fieldsOfStudy: ["Education", "Teaching"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "NSC pass with admission to education programs",
      financialNeed: false,
    },
  },
  {
    id: "sasol-bursary",
    name: "Sasol Bursary Programme",
    provider: "Sasol",
    description:
      "Comprehensive bursary for engineering, science, and technology students.",
    amount:
      "Full tuition + accommodation + meals + books + transport + personal allowance",
    eligibilityCriteria: [
      "South African citizen",
      "Studying chemical, mechanical, electrical, or industrial engineering",
      "Chemistry, Mathematics, Physics, Computer Science",
      "Minimum 65% average in Grade 11 and 12",
      "Agree to work for Sasol after graduation",
    ],
    applicationDeadline: "30 April annually",
    applicationProcess: "Apply online at www.sasol.com/careers/bursaries",
    contactInfo: "bursaries@sasol.com",
    website: "https://www.sasol.com",
    fieldsOfStudy: ["Engineering", "Science", "Technology", "Chemistry"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
  },
  {
    id: "eskom-bursary",
    name: "Eskom Development Foundation Bursary",
    provider: "Eskom",
    description:
      "Bursary for students in engineering and scarce skills fields.",
    amount: "Tuition + accommodation + meals + books + transport",
    eligibilityCriteria: [
      "South African citizen",
      "Studying engineering (electrical, mechanical, civil, industrial)",
      "Science, technology, and other scarce skills",
      "Good academic performance",
      "Financial need",
    ],
    applicationDeadline: "31 March annually",
    applicationProcess: "Apply online through university financial aid offices",
    contactInfo: "011 800 8111 | bursaries@eskom.co.za",
    website: "https://www.eskom.co.za",
    fieldsOfStudy: ["Engineering", "Science", "Technology"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Good academic performance",
      financialNeed: true,
    },
  },
  {
    id: "canon-collins-trust",
    name: "Canon Collins Trust Bursary",
    provider: "Canon Collins Trust",
    description:
      "Bursaries for academically strong students from disadvantaged backgrounds.",
    amount: "R40,000 - R80,000 per year",
    eligibilityCriteria: [
      "South African citizen",
      "From disadvantaged background",
      "Academic excellence",
      "Leadership potential",
      "Community involvement",
    ],
    applicationDeadline: "31 May annually",
    applicationProcess: "Apply online at www.canoncollins.org.za",
    contactInfo: "021 467 1681 | admin@canoncollins.org.za",
    website: "https://www.canoncollins.org.za",
    fieldsOfStudy: ["All fields"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic excellence",
      financialNeed: true,
    },
  },
  {
    id: "iscor-bursary",
    name: "ArcelorMittal South Africa Bursary",
    provider: "ArcelorMittal South Africa",
    description: "Bursary for engineering and metallurgy students.",
    amount: "Full tuition + accommodation + allowances",
    eligibilityCriteria: [
      "South African citizen",
      "Studying metallurgical, mechanical, electrical, industrial, or mining engineering",
      "Good academic performance",
      "Agree to work for ArcelorMittal after graduation",
    ],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply through company website",
    contactInfo: "016 889 9111",
    website: "https://www.arcelormittal.com",
    fieldsOfStudy: ["Engineering", "Metallurgy", "Mining"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Good academic performance",
      financialNeed: false,
    },
  },
  {
    id: "absa-bursary",
    name: "Absa Group Bursary",
    provider: "Absa Group",
    description:
      "Bursary for students in banking, finance, and related fields.",
    amount: "Tuition + accommodation + study material + transport",
    eligibilityCriteria: [
      "South African citizen",
      "Studying BCom (Accounting, Finance, Economics, Business Management)",
      "IT, Mathematics, Statistics",
      "Good academic performance",
      "Leadership potential",
    ],
    applicationDeadline: "30 September annually",
    applicationProcess: "Apply online at www.absa.co.za/careers",
    contactInfo: "bursaries@absa.co.za",
    website: "https://www.absa.co.za",
    fieldsOfStudy: ["Commerce", "Finance", "IT", "Mathematics"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Good academic performance",
      financialNeed: false,
    },
  },
  {
    id: "nedbank-bursary",
    name: "Nedbank Bursary Programme",
    provider: "Nedbank",
    description:
      "Bursary for students in banking, finance, and technology fields.",
    amount: "Tuition + accommodation + study allowance",
    eligibilityCriteria: [
      "South African citizen",
      "Studying BCom, BBA, IT, Computer Science",
      "Mathematics, Statistics, Economics",
      "Good academic performance",
      "Leadership qualities",
    ],
    applicationDeadline: "31 October annually",
    applicationProcess: "Apply online through Nedbank careers portal",
    contactInfo: "bursaries@nedbank.co.za",
    website: "https://www.nedbank.co.za",
    fieldsOfStudy: ["Commerce", "Technology", "Mathematics", "Economics"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Good academic performance",
      financialNeed: false,
    },
  },
  {
    id: "transnet-bursary",
    name: "Transnet Bursary Programme",
    provider: "Transnet",
    description: "Bursary for engineering and logistics students.",
    amount: "Full tuition + accommodation + allowances",
    eligibilityCriteria: [
      "South African citizen",
      "Studying engineering (civil, electrical, mechanical, industrial)",
      "Supply chain management, logistics",
      "Good academic performance",
      "Agree to work for Transnet after graduation",
    ],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply online at www.transnet.net",
    contactInfo: "bursaries@transnet.net",
    website: "https://www.transnet.net",
    fieldsOfStudy: ["Engineering", "Logistics", "Supply Chain"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Good academic performance",
      financialNeed: false,
    },
  },
  {
    id: "anglo-american-bursary",
    name: "Anglo American Bursary Programme",
    provider: "Anglo American",
    description: "Bursary for mining, engineering, and science students.",
    amount: "Full tuition + accommodation + allowances",
    eligibilityCriteria: [
      "South African citizen",
      "Studying mining, metallurgical, mechanical, electrical engineering",
      "Geology, Chemistry, Mathematics",
      "Good academic performance",
      "From communities where Anglo American operates",
    ],
    applicationDeadline: "30 June annually",
    applicationProcess: "Apply through Anglo American website",
    contactInfo: "bursaries@angloamerican.com",
    website: "https://www.angloamerican.com",
    fieldsOfStudy: ["Engineering", "Mining", "Geology", "Science"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Good academic performance",
      financialNeed: true,
    },
  },
];

export const BURSARY_FIELDS_OF_STUDY = [
  "All fields",
  "Engineering",
  "Science",
  "Technology",
  "Commerce",
  "Finance",
  "Education",
  "Medicine",
  "Law",
  "Humanities",
  "Mining",
  "Agriculture",
];

export const PROVINCES = [
  "Eastern Cape",
  "Free State",
  "Gauteng",
  "KwaZulu-Natal",
  "Limpopo",
  "Mpumalanga",
  "Northern Cape",
  "North West",
  "Western Cape",
];

export const RACE_CATEGORIES = [
  "African",
  "Coloured",
  "Indian/Asian",
  "White",
  "Any",
];

export const GENDER_CATEGORIES = ["Male", "Female", "Any"];
