import { CourseTemplate } from "./courseAssignmentSystem";

// Helper function to parse assignment rules
function parseRule(ruleText: string): any {
  if (
    ruleText.includes("all") &&
    !ruleText.includes("except") &&
    !ruleText.includes("exclude")
  ) {
    return { type: "all" };
  }

  if (ruleText.includes("exclude:") || ruleText.includes("except")) {
    const abbrevs =
      ruleText
        .match(/(?:exclude:|except)\s*([^)]+)/i)?.[1]
        ?.split(/[,\s]+/)
        ?.map((s) => s.trim())
        ?.filter((s) => s) || [];

    // Map abbreviations to university IDs
    const universityMap: Record<string, string> = {
      UCT: "uct",
      Wits: "wits",
      SU: "sun",
      UP: "up",
      UKZN: "ukzn",
      Rhodes: "ru",
      RU: "ru",
      NWU: "nwu",
      UFS: "ufs",
      UWC: "uwc",
      UFH: "ufh",
      WSU: "wsu",
      UNIVEN: "univen",
      SMU: "smu",
      UniZulu: "unizulu",
      UJ: "uj",
      UMP: "ump",
      UNISA: "unisa",
      CPUT: "cput",
      DUT: "dut",
      TUT: "tut",
      VUT: "vut",
      CUT: "cut",
      MUT: "mut",
    };

    const universities = abbrevs
      .map((abbrev) => universityMap[abbrev])
      .filter(Boolean);
    return { type: "exclude", universities };
  }

  if (ruleText.includes("Most except") || ruleText.includes("mostly at")) {
    const abbrevs =
      ruleText
        .match(/(?:Most except|mostly at)\s+([^)]+)/i)?.[1]
        ?.split(/[,\s]+/)
        ?.map((s) => s.trim())
        ?.filter((s) => s) || [];

    const universityMap: Record<string, string> = {
      UCT: "uct",
      Wits: "wits",
      SU: "sun",
      UP: "up",
      UKZN: "ukzn",
      Rhodes: "ru",
      RU: "ru",
      NWU: "nwu",
      UFS: "ufs",
      UWC: "uwc",
      UFH: "ufh",
      WSU: "wsu",
      UNIVEN: "univen",
      SMU: "smu",
      UniZulu: "unizulu",
      UJ: "uj",
      UMP: "ump",
      UNISA: "unisa",
      CPUT: "cput",
      DUT: "dut",
      TUT: "tut",
      VUT: "vut",
      CUT: "cut",
      MUT: "mut",
    };

    const universities = abbrevs
      .map((abbrev) => universityMap[abbrev])
      .filter(Boolean);
    return { type: "include_only", universities };
  }

  return { type: "all" };
}

export const COMPREHENSIVE_COURSE_TEMPLATES: CourseTemplate[] = [
  // Faculty of Engineering / Engineering and Built Environment
  {
    id: "bsc-eng-civil",
    name: "BSc Engineering (Civil)",
    faculty: "Engineering",
    duration: "4 years",
    baseApsRequirement: 35,
    description: "Civil engineering with infrastructure development focus.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Civil Engineer",
      "Structural Engineer",
      "Project Manager",
      "Construction Manager",
      "Infrastructure Planner",
    ],
    assignmentRule: parseRule("exclude: UWC, UNISA, UFH"),
  },
  {
    id: "bsc-eng-mechanical",
    name: "BSc Engineering (Mechanical)",
    faculty: "Engineering",
    duration: "4 years",
    baseApsRequirement: 35,
    description: "Mechanical engineering with design and manufacturing focus.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Mechanical Engineer",
      "Design Engineer",
      "Manufacturing Engineer",
      "Automotive Engineer",
      "HVAC Engineer",
    ],
    assignmentRule: parseRule("exclude: UWC, UNISA, UFH"),
  },
  {
    id: "bsc-eng-electrical",
    name: "BSc Engineering (Electrical)",
    faculty: "Engineering",
    duration: "4 years",
    baseApsRequirement: 35,
    description:
      "Electrical engineering with power systems and electronics focus.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Electrical Engineer",
      "Power Systems Engineer",
      "Electronics Engineer",
      "Control Systems Engineer",
      "Telecommunications Engineer",
    ],
    assignmentRule: parseRule("exclude: UWC, UNISA, UFH"),
  },
  {
    id: "bsc-eng-chemical",
    name: "BSc Engineering (Chemical)",
    faculty: "Engineering",
    duration: "4 years",
    baseApsRequirement: 35,
    description:
      "Chemical engineering with process design and optimization focus.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Chemical Engineer",
      "Process Engineer",
      "Plant Manager",
      "Environmental Engineer",
      "Petrochemical Engineer",
    ],
    assignmentRule: parseRule("exclude: UJ, UNISA, UFH"),
  },
  {
    id: "bsc-eng-industrial",
    name: "BSc Engineering (Industrial)",
    faculty: "Engineering",
    duration: "4 years",
    baseApsRequirement: 34,
    description: "Industrial engineering with systems optimization focus.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Industrial Engineer",
      "Systems Analyst",
      "Operations Manager",
      "Quality Engineer",
      "Process Improvement Specialist",
    ],
    assignmentRule: parseRule("exclude: UWC, UNISA"),
  },
  {
    id: "bsc-eng-computer",
    name: "BSc Engineering (Computer)",
    faculty: "Engineering",
    duration: "4 years",
    baseApsRequirement: 36,
    description:
      "Computer engineering with hardware and software integration focus.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Computer Engineer",
      "Embedded Systems Engineer",
      "Hardware Engineer",
      "Software Engineer",
      "Systems Architect",
    ],
    assignmentRule: parseRule("exclude: UCT, UP, UNISA"),
  },
  {
    id: "bsc-eng-mining",
    name: "BSc Engineering (Mining)",
    faculty: "Engineering",
    duration: "4 years",
    baseApsRequirement: 34,
    description: "Mining engineering with resource extraction focus.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Mining Engineer",
      "Mine Manager",
      "Resource Evaluation Specialist",
      "Safety Engineer",
      "Geological Engineer",
    ],
    assignmentRule: parseRule("exclude: UWC, UNISA, UFH, RU"),
  },
  {
    id: "bsc-construction-management",
    name: "BSc Construction Management",
    faculty: "Engineering",
    duration: "3 years",
    baseApsRequirement: 30,
    description: "Construction management with project leadership focus.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Construction Manager",
      "Project Manager",
      "Site Manager",
      "Quantity Surveyor",
      "Construction Consultant",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bsc-quantity-surveying",
    name: "BSc Quantity Surveying",
    faculty: "Engineering",
    duration: "3 years",
    baseApsRequirement: 30,
    description: "Quantity surveying with cost management focus.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Quantity Surveyor",
      "Cost Estimator",
      "Project Manager",
      "Construction Economist",
      "Contract Administrator",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bsc-urban-planning",
    name: "BSc Urban and Regional Planning",
    faculty: "Engineering",
    duration: "4 years",
    baseApsRequirement: 28,
    description: "Urban planning with sustainable development focus.",
    subjects: [
      { name: "Geography", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
    ],
    careerProspects: [
      "Urban Planner",
      "Regional Planner",
      "Development Consultant",
      "Municipal Planner",
      "Environmental Planner",
    ],
    assignmentRule: parseRule("exclude: UNISA, UFH"),
  },
  {
    id: "bachelor-architecture",
    name: "Bachelor of Architecture",
    faculty: "Engineering",
    duration: "5 years",
    baseApsRequirement: 32,
    description: "Architectural design with sustainable building focus.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Visual Arts", level: 4, isRequired: false },
    ],
    careerProspects: [
      "Architect",
      "Design Consultant",
      "Project Architect",
      "Urban Designer",
      "Sustainable Design Specialist",
    ],
    assignmentRule: parseRule("exclude: UNISA, UFH, MUT"),
  },

  // Faculty of Health Sciences / Medicine and Health
  {
    id: "mbchb",
    name: "Bachelor of Medicine and Bachelor of Surgery (MBChB)",
    faculty: "Health Sciences",
    duration: "6 years",
    baseApsRequirement: 40,
    description: "Medical degree with comprehensive clinical training.",
    subjects: [
      { name: "Life Sciences", level: 7, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "English", level: 6, isRequired: true },
    ],
    careerProspects: [
      "Medical Doctor",
      "Specialist Physician",
      "General Practitioner",
      "Medical Researcher",
      "Clinical Director",
    ],
    assignmentRule: parseRule("all"),
    universitySpecificAps: {
      uct: 45,
      wits: 44,
      up: 42,
      ukzn: 40,
      sun: 44,
      ufs: 38,
      smu: 40,
      wsu: 38,
    },
  },
  {
    id: "bds",
    name: "Bachelor of Dental Surgery (BDS)",
    faculty: "Health Sciences",
    duration: "5 years",
    baseApsRequirement: 38,
    description: "Dental surgery with comprehensive oral healthcare focus.",
    subjects: [
      { name: "Life Sciences", level: 7, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "English", level: 6, isRequired: true },
    ],
    careerProspects: [
      "Dentist",
      "Oral Surgeon",
      "Dental Specialist",
      "Dental Practice Owner",
      "Oral Health Researcher",
    ],
    assignmentRule: parseRule("exclude: UNISA, UFH, MUT"),
  },
  {
    id: "bpharm",
    name: "Bachelor of Pharmacy (BPharm)",
    faculty: "Health Sciences",
    duration: "4 years",
    baseApsRequirement: 34,
    description: "Pharmacy education with clinical practice focus.",
    subjects: [
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Pharmacist",
      "Clinical Pharmacist",
      "Hospital Pharmacist",
      "Industrial Pharmacist",
      "Pharmaceutical Researcher",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bsc-physiotherapy",
    name: "BSc Physiotherapy",
    faculty: "Health Sciences",
    duration: "4 years",
    baseApsRequirement: 32,
    description: "Physiotherapy with movement rehabilitation focus.",
    subjects: [
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 5, isRequired: true },
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Physiotherapist",
      "Sports Therapist",
      "Rehabilitation Specialist",
      "Orthopedic Therapist",
      "Community Physiotherapist",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bsc-occupational-therapy",
    name: "BSc Occupational Therapy",
    faculty: "Health Sciences",
    duration: "4 years",
    baseApsRequirement: 32,
    description: "Occupational therapy with rehabilitation focus.",
    subjects: [
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Occupational Therapist",
      "Rehabilitation Specialist",
      "Community Health Worker",
      "Mental Health Therapist",
      "Pediatric Therapist",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bns-nursing",
    name: "Bachelor of Nursing Science",
    faculty: "Health Sciences",
    duration: "4 years",
    baseApsRequirement: 28,
    description: "Professional nursing with clinical excellence focus.",
    subjects: [
      { name: "Life Sciences", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
    ],
    careerProspects: [
      "Professional Nurse",
      "Clinical Nurse Specialist",
      "Nurse Manager",
      "Community Health Nurse",
      "Nursing Researcher",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bemc",
    name: "Bachelor of Emergency Medical Care (BEMC)",
    faculty: "Health Sciences",
    duration: "4 years",
    baseApsRequirement: 30,
    description: "Emergency medical care with pre-hospital focus.",
    subjects: [
      { name: "Life Sciences", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Emergency Medical Technician",
      "Paramedic",
      "Emergency Care Practitioner",
      "Ambulance Service Manager",
      "Emergency Response Coordinator",
    ],
    assignmentRule: parseRule("Most except DUT, TUT"),
  },

  // Faculty of Humanities / Arts and Social Sciences
  {
    id: "ba-english",
    name: "BA English",
    faculty: "Humanities",
    duration: "3 years",
    baseApsRequirement: 24,
    description: "English literature and language studies.",
    subjects: [{ name: "English", level: 5, isRequired: true }],
    careerProspects: [
      "Teacher",
      "Writer",
      "Editor",
      "Journalist",
      "Content Creator",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "ba-history",
    name: "BA History",
    faculty: "Humanities",
    duration: "3 years",
    baseApsRequirement: 24,
    description: "Historical studies with research focus.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "History", level: 4, isRequired: true },
    ],
    careerProspects: [
      "Historian",
      "Archivist",
      "Museum Curator",
      "Research Analyst",
      "Heritage Specialist",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "ba-psychology",
    name: "BA Psychology",
    faculty: "Humanities",
    duration: "3 years",
    baseApsRequirement: 26,
    description: "Psychology with human behavior focus.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
    ],
    careerProspects: [
      "Psychologist",
      "Counselor",
      "Researcher",
      "HR Specialist",
      "Social Worker",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "ba-sociology",
    name: "BA Sociology",
    faculty: "Humanities",
    duration: "3 years",
    baseApsRequirement: 24,
    description: "Sociology with social dynamics focus.",
    subjects: [{ name: "English", level: 5, isRequired: true }],
    careerProspects: [
      "Sociologist",
      "Social Researcher",
      "Community Developer",
      "Policy Analyst",
      "Social Worker",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "ba-political-science",
    name: "BA Political Science",
    faculty: "Humanities",
    duration: "3 years",
    baseApsRequirement: 26,
    description: "Political science with governance focus.",
    subjects: [{ name: "English", level: 5, isRequired: true }],
    careerProspects: [
      "Political Analyst",
      "Policy Researcher",
      "Government Official",
      "Diplomat",
      "Journalist",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "ba-fine-arts",
    name: "BA Fine Arts",
    faculty: "Humanities",
    duration: "3 years",
    baseApsRequirement: 22,
    description: "Fine arts with creative expression focus.",
    subjects: [
      { name: "English", level: 4, isRequired: true },
      { name: "Visual Arts", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Artist",
      "Gallery Curator",
      "Art Teacher",
      "Art Therapist",
      "Creative Director",
    ],
    assignmentRule: parseRule("exclude: UFH"),
  },
  {
    id: "ba-journalism",
    name: "BA Journalism",
    faculty: "Humanities",
    duration: "3 years",
    baseApsRequirement: 26,
    description: "Journalism with media communication focus.",
    subjects: [{ name: "English", level: 5, isRequired: true }],
    careerProspects: [
      "Journalist",
      "News Reporter",
      "Editor",
      "Media Researcher",
      "Communications Specialist",
    ],
    assignmentRule: parseRule("all"),
  },

  // Faculty of Commerce / Business and Management
  {
    id: "bcom-accounting",
    name: "BCom Accounting",
    faculty: "Commerce",
    duration: "3 years",
    baseApsRequirement: 28,
    description: "Accounting education with professional qualification focus.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Chartered Accountant",
      "Financial Manager",
      "Auditor",
      "Tax Consultant",
      "Management Accountant",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bcom-finance",
    name: "BCom Finance",
    faculty: "Commerce",
    duration: "3 years",
    baseApsRequirement: 28,
    description: "Finance with investment and banking focus.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Financial Analyst",
      "Investment Advisor",
      "Bank Manager",
      "Financial Planner",
      "Risk Manager",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bcom-economics",
    name: "BCom Economics",
    faculty: "Commerce",
    duration: "3 years",
    baseApsRequirement: 26,
    description: "Economics with policy analysis focus.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Economist",
      "Policy Analyst",
      "Research Economist",
      "Economic Consultant",
      "Development Economist",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bcom-marketing",
    name: "BCom Marketing",
    faculty: "Commerce",
    duration: "3 years",
    baseApsRequirement: 26,
    description: "Marketing with digital strategy focus.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Marketing Manager",
      "Digital Marketer",
      "Brand Manager",
      "Market Researcher",
      "Advertising Executive",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bcom-business-management",
    name: "BCom Business Management",
    faculty: "Commerce",
    duration: "3 years",
    baseApsRequirement: 26,
    description: "Business management with entrepreneurship focus.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Business Manager",
      "Entrepreneur",
      "Project Manager",
      "Business Analyst",
      "Operations Manager",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bcom-actuarial-science",
    name: "BCom Actuarial Science",
    faculty: "Commerce",
    duration: "3 years",
    baseApsRequirement: 36,
    description: "Actuarial science with risk assessment focus.",
    subjects: [
      { name: "Mathematics", level: 7, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Actuary",
      "Risk Analyst",
      "Insurance Specialist",
      "Pension Fund Manager",
      "Investment Analyst",
    ],
    assignmentRule: parseRule("exclude: UFH, MUT"),
  },

  // Faculty of Law
  {
    id: "llb",
    name: "Bachelor of Laws (LLB)",
    faculty: "Law",
    duration: "4 years",
    baseApsRequirement: 30,
    description: "Legal education with comprehensive law focus.",
    subjects: [{ name: "English", level: 5, isRequired: true }],
    careerProspects: [
      "Attorney",
      "Advocate",
      "Legal Advisor",
      "Magistrate",
      "Corporate Legal Counsel",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bachelor-criminal-justice",
    name: "Bachelor of Criminal Justice",
    faculty: "Law",
    duration: "3 years",
    baseApsRequirement: 26,
    description: "Criminal justice with law enforcement focus.",
    subjects: [{ name: "English", level: 5, isRequired: true }],
    careerProspects: [
      "Police Officer",
      "Detective",
      "Correctional Officer",
      "Security Manager",
      "Crime Analyst",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bsc-forensic-science",
    name: "BSc Forensic Science",
    faculty: "Law",
    duration: "3 years",
    baseApsRequirement: 30,
    description: "Forensic science with criminal investigation focus.",
    subjects: [
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Forensic Scientist",
      "Crime Scene Investigator",
      "Laboratory Analyst",
      "Digital Forensics Specialist",
      "Expert Witness",
    ],
    assignmentRule: parseRule("exclude: UFH, MUT"),
  },

  // Faculty of Science / Natural Sciences
  {
    id: "bsc-computer-science",
    name: "BSc Computer Science",
    faculty: "Science",
    duration: "3 years",
    baseApsRequirement: 30,
    description: "Computer science with software development focus.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Software Developer",
      "Systems Analyst",
      "Database Administrator",
      "IT Specialist",
      "Web Developer",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bsc-mathematics",
    name: "BSc Mathematics",
    faculty: "Science",
    duration: "3 years",
    baseApsRequirement: 32,
    description: "Pure and applied mathematics.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Mathematician",
      "Statistician",
      "Data Analyst",
      "Actuary",
      "Research Scientist",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bsc-physics",
    name: "BSc Physics",
    faculty: "Science",
    duration: "3 years",
    baseApsRequirement: 32,
    description: "Physics with theoretical and applied focus.",
    subjects: [
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Physicist",
      "Research Scientist",
      "Laboratory Technician",
      "Science Teacher",
      "Technical Consultant",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bsc-chemistry",
    name: "BSc Chemistry",
    faculty: "Science",
    duration: "3 years",
    baseApsRequirement: 30,
    description: "Chemistry with laboratory and research focus.",
    subjects: [
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 4, isRequired: true },
    ],
    careerProspects: [
      "Chemist",
      "Research Scientist",
      "Quality Control Analyst",
      "Environmental Scientist",
      "Laboratory Manager",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bsc-biology",
    name: "BSc Biological Sciences",
    faculty: "Science",
    duration: "3 years",
    baseApsRequirement: 28,
    description: "Biological sciences with life systems focus.",
    subjects: [
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 4, isRequired: true },
    ],
    careerProspects: [
      "Biologist",
      "Research Scientist",
      "Conservation Scientist",
      "Biotechnologist",
      "Environmental Consultant",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bsc-environmental-science",
    name: "BSc Environmental Science",
    faculty: "Science",
    duration: "3 years",
    baseApsRequirement: 28,
    description: "Environmental science with sustainability focus.",
    subjects: [
      { name: "Life Sciences", level: 5, isRequired: true },
      { name: "Geography", level: 4, isRequired: true },
      { name: "English", level: 4, isRequired: true },
    ],
    careerProspects: [
      "Environmental Scientist",
      "Conservation Officer",
      "Environmental Consultant",
      "Research Scientist",
      "Environmental Manager",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bsc-astronomy",
    name: "BSc Astronomy",
    faculty: "Science",
    duration: "3 years",
    baseApsRequirement: 34,
    description: "Astronomy with astrophysics focus.",
    subjects: [
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Astronomer",
      "Astrophysicist",
      "Planetarium Director",
      "Science Educator",
      "Research Scientist",
    ],
    assignmentRule: parseRule("Most except UCT, RU"),
  },

  // Faculty of Education
  {
    id: "bed-foundation-phase",
    name: "BEd Foundation Phase",
    faculty: "Education",
    duration: "4 years",
    baseApsRequirement: 22,
    description: "Teacher training for Grade R to Grade 3.",
    subjects: [
      { name: "English", level: 4, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
    ],
    careerProspects: [
      "Foundation Phase Teacher",
      "Early Childhood Educator",
      "Primary School Teacher",
      "Curriculum Developer",
      "Educational Coordinator",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bed-intermediate-phase",
    name: "BEd Intermediate Phase",
    faculty: "Education",
    duration: "4 years",
    baseApsRequirement: 24,
    description: "Teacher training for Grade 4 to Grade 6.",
    subjects: [
      { name: "English", level: 4, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
    ],
    careerProspects: [
      "Intermediate Phase Teacher",
      "Primary School Teacher",
      "Subject Specialist",
      "Educational Coordinator",
      "Curriculum Advisor",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bed-senior-phase",
    name: "BEd Senior Phase",
    faculty: "Education",
    duration: "4 years",
    baseApsRequirement: 26,
    description: "Teacher training for Grade 7 to Grade 9.",
    subjects: [
      { name: "English", level: 4, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "Teaching Subject", level: 4, isRequired: true },
    ],
    careerProspects: [
      "Senior Phase Teacher",
      "Subject Head",
      "Educational Manager",
      "Curriculum Specialist",
      "Academic Coordinator",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bed-fet-phase",
    name: "BEd FET Phase",
    faculty: "Education",
    duration: "4 years",
    baseApsRequirement: 26,
    description: "Teacher training for Grade 10 to Grade 12.",
    subjects: [
      { name: "English", level: 4, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "Teaching Subject", level: 5, isRequired: true },
    ],
    careerProspects: [
      "High School Teacher",
      "Subject Head",
      "Educational Manager",
      "Curriculum Specialist",
      "Academic Coordinator",
    ],
    assignmentRule: parseRule("all"),
  },

  // Faculty of Agriculture / Agricultural Sciences
  {
    id: "bsc-agriculture",
    name: "BSc Agriculture",
    faculty: "Agriculture",
    duration: "4 years",
    baseApsRequirement: 24,
    description: "Agricultural sciences with sustainable farming focus.",
    subjects: [
      { name: "Life Sciences", level: 4, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 4, isRequired: true },
    ],
    careerProspects: [
      "Agricultural Scientist",
      "Farm Manager",
      "Extension Officer",
      "Agricultural Consultant",
      "Rural Development Officer",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bsc-animal-science",
    name: "BSc Animal Science",
    faculty: "Agriculture",
    duration: "3 years",
    baseApsRequirement: 24,
    description: "Animal science with livestock management focus.",
    subjects: [
      { name: "Life Sciences", level: 4, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 4, isRequired: true },
    ],
    careerProspects: [
      "Animal Scientist",
      "Livestock Specialist",
      "Veterinary Technician",
      "Feed Consultant",
      "Animal Nutritionist",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bsc-viticulture",
    name: "BSc Viticulture and Oenology",
    faculty: "Agriculture",
    duration: "4 years",
    baseApsRequirement: 26,
    description: "Wine science with production and management focus.",
    subjects: [
      { name: "Life Sciences", level: 5, isRequired: true },
      { name: "Physical Sciences", level: 4, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 4, isRequired: true },
    ],
    careerProspects: [
      "Viticulturist",
      "Winemaker",
      "Wine Consultant",
      "Vineyard Manager",
      "Wine Marketing Specialist",
    ],
    assignmentRule: parseRule("Most except SU, UCT"),
  },

  // Faculty of Information Technology / Computer Science
  {
    id: "bit",
    name: "Bachelor of Information Technology (BIT)",
    faculty: "Information Technology",
    duration: "3 years",
    baseApsRequirement: 26,
    description: "Information technology with practical focus.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "IT Specialist",
      "Systems Administrator",
      "Network Engineer",
      "IT Support",
      "Database Developer",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bsc-software-engineering",
    name: "BSc Software Engineering",
    faculty: "Information Technology",
    duration: "3 years",
    baseApsRequirement: 30,
    description: "Software engineering with development methodologies focus.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Software Engineer",
      "Systems Architect",
      "Software Developer",
      "Technical Lead",
      "Product Manager",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bsc-cybersecurity",
    name: "BSc Cybersecurity",
    faculty: "Information Technology",
    duration: "3 years",
    baseApsRequirement: 30,
    description: "Cybersecurity with threat prevention focus.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Cybersecurity Analyst",
      "Security Engineer",
      "Penetration Tester",
      "Security Consultant",
      "Information Security Manager",
    ],
    assignmentRule: parseRule("all"),
  },
  {
    id: "bsc-data-science",
    name: "BSc Data Science",
    faculty: "Information Technology",
    duration: "3 years",
    baseApsRequirement: 32,
    description: "Data science with analytics and machine learning focus.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Data Scientist",
      "Data Analyst",
      "Machine Learning Engineer",
      "Business Intelligence Analyst",
      "Research Scientist",
    ],
    assignmentRule: parseRule("all"),
  },

  // Technical and Vocational Programmes
  {
    id: "nd-engineering",
    name: "National Diploma in Engineering",
    faculty: "Engineering",
    duration: "3 years",
    baseApsRequirement: 20,
    description: "Technical engineering education with practical focus.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "Physical Sciences", level: 4, isRequired: true },
      { name: "English", level: 4, isRequired: true },
    ],
    careerProspects: [
      "Engineering Technician",
      "Technical Officer",
      "Maintenance Engineer",
      "Production Supervisor",
      "Quality Controller",
    ],
    assignmentRule: parseRule("mostly at TUT, DUT, MUT, VUT"),
  },
  {
    id: "nd-information-technology",
    name: "National Diploma in Information Technology",
    faculty: "Information Technology",
    duration: "3 years",
    baseApsRequirement: 20,
    description: "Technical IT education with hands-on training.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 4, isRequired: true },
    ],
    careerProspects: [
      "IT Technician",
      "Network Administrator",
      "Help Desk Support",
      "System Operator",
      "Web Developer",
    ],
    assignmentRule: parseRule("mostly at TUT, DUT, MUT, VUT"),
  },
  {
    id: "nd-business-studies",
    name: "National Diploma in Business Studies",
    faculty: "Commerce",
    duration: "3 years",
    baseApsRequirement: 18,
    description: "Business studies with practical management focus.",
    subjects: [
      { name: "English", level: 4, isRequired: true },
      { name: "Mathematics", level: 3, isRequired: true },
    ],
    careerProspects: [
      "Business Administrator",
      "Office Manager",
      "Sales Representative",
      "Customer Service Manager",
      "Small Business Owner",
    ],
    assignmentRule: parseRule("mostly at TUT, DUT, MUT, VUT"),
  },
];
