import { Bursary } from "@/types/university";

export const ENHANCED_BURSARIES: Bursary[] = [
  // Government Bursaries
  {
    id: "nsfas",
    name: "NSFAS (National Student Financial Aid Scheme)",
    provider: "Department of Higher Education and Training",
    description:
      "Government financial aid for South African students from poor and working-class families.",
    amount:
      "Full tuition + accommodation + meal allowance + book allowance + transport allowance",
    eligibilityCriteria: [
      "South African citizen",
      "Combined annual household income ≤ R350,000",
      "SASSA grant recipient qualifies regardless of household income",
      "Must be studying at a public university or TVET college",
      "Must pass at least 75% of modules per year to continue funding",
    ],
    applicationDeadline: "31 January annually",
    applicationProcess: "Apply online at www.nsfas.org.za",
    contactInfo: "08000 67327 | info@nsfas.org.za",
    website: "https://www.nsfas.org.za",
    fieldsOfStudy: ["All fields"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "NSC pass with admission to higher education",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "funza-lushaka",
    name: "Funza Lushaka Bursary",
    provider: "Department of Basic Education",
    description:
      "Bursary for students studying to become teachers in public schools.",
    amount:
      "Full tuition + accommodation + meal allowance + book allowance + transport allowance",
    eligibilityCriteria: [
      "South African citizen",
      "Studying Initial Teacher Education qualifications",
      "Agree to teach in public schools for same number of years as bursary received",
      "Maintain good academic standing",
    ],
    applicationDeadline: "31 January annually",
    applicationProcess: "Apply online at www.funzalushaka.doe.gov.za",
    contactInfo: "0800 202 933 | bursaries@dbe.gov.za",
    website: "https://www.funzalushaka.doe.gov.za",
    fieldsOfStudy: ["Education", "Teaching"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "NSC pass with admission to education programs",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },

  // New Government Bursaries
  {
    id: "dme-mining-bursary",
    name: "Department of Mineral Resources Mining Bursary",
    provider: "Department of Mineral Resources and Energy",
    description:
      "Bursary for students pursuing mining and mineral-related qualifications.",
    amount: "Full tuition + accommodation + stipend + vacation work",
    eligibilityCriteria: [
      "South African citizen",
      "Studying mining engineering, geology, metallurgy, or related fields",
      "Academic excellence with minimum 65% average",
      "Commitment to work in mining industry after graduation",
      "Financial need consideration",
    ],
    applicationDeadline: "30 September annually",
    applicationProcess: "Apply through provincial DMRE offices",
    contactInfo: "012 444 3000 | bursaries@dmre.gov.za",
    website: "https://www.dmre.gov.za",
    fieldsOfStudy: [
      "Mining Engineering",
      "Geology",
      "Metallurgy",
      "Chemical Engineering",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "65% average in Grade 11 or university studies",
      financialNeed: true,
      workCommitment: true,
    },
    isActive: true,
    priority: "high",
  },

  {
    id: "dws-water-bursary",
    name: "Department of Water and Sanitation Bursary",
    provider: "Department of Water and Sanitation",
    description: "Bursary for water and sanitation related studies.",
    amount: "Full tuition + accommodation + stipend",
    eligibilityCriteria: [
      "South African citizen",
      "Studying water engineering, environmental engineering, chemistry",
      "Academic merit and financial need",
      "Commitment to water sector employment",
    ],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply online at www.dws.gov.za",
    contactInfo: "012 336 7500 | bursaries@dws.gov.za",
    website: "https://www.dws.gov.za",
    fieldsOfStudy: [
      "Civil Engineering",
      "Environmental Engineering",
      "Chemistry",
      "Environmental Science",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Good academic performance",
      financialNeed: true,
      workCommitment: true,
    },
    isActive: true,
    priority: "medium",
  },

  // Enhanced Corporate Bursaries
  {
    id: "shoprite-checkers-bursary",
    name: "Shoprite Group Bursary Programme",
    provider: "Shoprite Holdings",
    description:
      "Comprehensive bursary for retail, business, and technical studies.",
    amount: "Full tuition + accommodation + stipend + mentorship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying towards business, retail management, supply chain, IT, or accounting",
      "Academic excellence with minimum 65% average",
      "Leadership potential and community involvement",
      "Financial need",
    ],
    applicationDeadline: "30 September annually",
    applicationProcess: "Apply online at shopriteholdings.co.za",
    contactInfo: "021 980 4000 | bursaries@shoprite.co.za",
    website: "https://www.shopriteholdings.co.za",
    fieldsOfStudy: [
      "Commerce",
      "Business Management",
      "Supply Chain",
      "Information Technology",
      "Accounting",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },

  {
    id: "capitec-bank-bursary",
    name: "Capitec Bank Bursary Programme",
    provider: "Capitec Bank",
    description: "Bursary for banking, finance, and technology students.",
    amount:
      "Full tuition + accommodation + stipend + vacation work + graduate programme",
    eligibilityCriteria: [
      "South African citizen",
      "Studying BCom, IT, Computer Science, or related fields",
      "Academic excellence with minimum 70% average",
      "Strong mathematical and analytical skills",
      "Leadership potential",
    ],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply online at capitecbank.co.za/careers",
    contactInfo: "0860 102 043 | bursaries@capitecbank.co.za",
    website: "https://www.capitecbank.co.za",
    fieldsOfStudy: [
      "Commerce",
      "Information Technology",
      "Computer Science",
      "Mathematics",
      "Statistics",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },

  {
    id: "liberty-group-bursary",
    name: "Liberty Group Bursary Programme",
    provider: "Liberty Holdings",
    description:
      "Bursary for actuarial science, finance, and business students.",
    amount: "Full tuition + accommodation + stipend + mentorship + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying actuarial science, finance, economics, statistics, or mathematics",
      "Academic excellence with minimum 75% average",
      "Strong mathematical aptitude",
      "Leadership qualities",
    ],
    applicationDeadline: "30 September annually",
    applicationProcess: "Apply online at liberty.co.za",
    contactInfo: "011 408 2111 | bursaries@liberty.co.za",
    website: "https://www.liberty.co.za",
    fieldsOfStudy: [
      "Actuarial Science",
      "Finance",
      "Economics",
      "Statistics",
      "Mathematics",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "75% average with strong mathematics",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },

  {
    id: "discovery-bursary",
    name: "Discovery Foundation Bursary",
    provider: "Discovery Limited",
    description:
      "Bursary for health sciences, actuarial science, and business students.",
    amount:
      "Full tuition + accommodation + stipend + health benefits + mentorship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying medicine, actuarial science, health sciences, or business",
      "Academic excellence with minimum 70% average",
      "Commitment to health and wellness initiatives",
      "Leadership potential",
    ],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply online at discovery.co.za",
    contactInfo: "011 529 2888 | bursaries@discovery.co.za",
    website: "https://www.discovery.co.za",
    fieldsOfStudy: [
      "Medicine",
      "Actuarial Science",
      "Health Sciences",
      "Business Management",
      "Psychology",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },

  // Mining & Resources
  {
    id: "sibanye-stillwater-bursary",
    name: "Sibanye-Stillwater Bursary Programme",
    provider: "Sibanye-Stillwater",
    description: "Bursary for mining, engineering, and finance students.",
    amount: "Full tuition + accommodation + stipend + vacation work",
    eligibilityCriteria: [
      "South African citizen",
      "Studying mining engineering, metallurgical engineering, finance, or human resources",
      "Academic merit with minimum 65% average",
      "Commitment to mining industry",
      "From mining communities preferred",
    ],
    applicationDeadline: "30 September annually",
    applicationProcess: "Apply online at sibanyestillwater.com",
    contactInfo: "011 376 9111 | bursaries@sibanyestillwater.com",
    website: "https://www.sibanyestillwater.com",
    fieldsOfStudy: [
      "Mining Engineering",
      "Metallurgical Engineering",
      "Finance",
      "Human Resources",
    ],
    provinces: ["Gauteng", "North West", "Free State", "Mpumalanga"],
    requirements: {
      academicRequirement: "65% average",
      financialNeed: true,
      workCommitment: true,
    },
    isActive: true,
    priority: "medium",
  },

  {
    id: "african-rainbow-minerals-bursary",
    name: "African Rainbow Minerals Bursary",
    provider: "African Rainbow Minerals",
    description: "Bursary for mining and engineering excellence.",
    amount:
      "Full tuition + accommodation + stipend + mentorship + vacation work",
    eligibilityCriteria: [
      "South African citizen",
      "Studying mining engineering, metallurgy, geology, or mechanical engineering",
      "Academic excellence with minimum 70% average",
      "Leadership potential",
      "Commitment to mining industry development",
    ],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply online at arm.co.za",
    contactInfo: "011 779 1400 | bursaries@arm.co.za",
    website: "https://www.arm.co.za",
    fieldsOfStudy: [
      "Mining Engineering",
      "Metallurgy",
      "Geology",
      "Mechanical Engineering",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "70% average",
      financialNeed: false,
      workCommitment: true,
    },
    isActive: true,
    priority: "high",
  },

  // Technology & Innovation
  {
    id: "dimension-data-bursary",
    name: "Dimension Data Bursary Programme",
    provider: "Dimension Data",
    description: "ICT bursary for future technology leaders.",
    amount: "Full tuition + accommodation + stipend + mentorship + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying Computer Science, Information Systems, or related IT fields",
      "Academic excellence with minimum 70% average",
      "Passion for technology and innovation",
      "Leadership qualities",
    ],
    applicationDeadline: "30 September annually",
    applicationProcess: "Apply online at dimensiondata.com",
    contactInfo: "011 709 0000 | bursaries@dimensiondata.com",
    website: "https://www.dimensiondata.com",
    fieldsOfStudy: [
      "Computer Science",
      "Information Systems",
      "Information Technology",
      "Engineering",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },

  {
    id: "multichoice-bursary",
    name: "MultiChoice Bursary Programme",
    provider: "MultiChoice South Africa",
    description: "Bursary for media, technology, and business students.",
    amount: "Full tuition + accommodation + stipend + industry exposure",
    eligibilityCriteria: [
      "South African citizen",
      "Studying media, film, IT, business, or engineering",
      "Academic merit with minimum 65% average",
      "Creative and innovative thinking",
      "Passion for media and entertainment",
    ],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply online at multichoice.co.za",
    contactInfo: "011 289 3000 | bursaries@multichoice.co.za",
    website: "https://www.multichoice.co.za",
    fieldsOfStudy: [
      "Media Studies",
      "Film Studies",
      "Information Technology",
      "Business Management",
      "Engineering",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },

  // Healthcare & Pharmaceuticals
  {
    id: "aspen-pharmacare-bursary",
    name: "Aspen Pharmacare Bursary",
    provider: "Aspen Pharmacare Holdings",
    description: "Bursary for pharmaceutical and health sciences students.",
    amount: "Full tuition + accommodation + stipend + industry experience",
    eligibilityCriteria: [
      "South African citizen",
      "Studying pharmacy, medicine, chemical engineering, or chemistry",
      "Academic excellence with minimum 70% average",
      "Commitment to pharmaceutical industry",
      "Leadership potential",
    ],
    applicationDeadline: "30 September annually",
    applicationProcess: "Apply online at aspenpharma.com",
    contactInfo: "011 239 6100 | bursaries@aspenpharma.com",
    website: "https://www.aspenpharma.com",
    fieldsOfStudy: [
      "Pharmacy",
      "Medicine",
      "Chemical Engineering",
      "Chemistry",
      "Biochemistry",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "70% average",
      financialNeed: false,
      workCommitment: true,
    },
    isActive: true,
    priority: "high",
  },

  // Provincial Government Bursaries
  {
    id: "kwazulu-natal-bursary",
    name: "KwaZulu-Natal Provincial Bursary",
    provider: "KwaZulu-Natal Provincial Government",
    description: "Bursary for KZN residents in priority skills areas.",
    amount: "Full tuition + accommodation + stipend",
    eligibilityCriteria: [
      "South African citizen and KZN resident",
      "Studying in scarce skills areas",
      "Academic merit and financial need",
      "Commitment to work in KZN after graduation",
    ],
    applicationDeadline: "31 October annually",
    applicationProcess: "Apply through KZN Department of Education",
    contactInfo: "033 392 1063 | bursaries@kzneducation.gov.za",
    website: "https://www.kzneducation.gov.za",
    fieldsOfStudy: [
      "Engineering",
      "Health Sciences",
      "Education",
      "Agriculture",
      "Information Technology",
    ],
    provinces: ["KwaZulu-Natal"],
    requirements: {
      academicRequirement: "Good academic performance",
      financialNeed: true,
      workCommitment: true,
    },
    isActive: true,
    priority: "medium",
  },

  {
    id: "eastern-cape-bursary",
    name: "Eastern Cape Provincial Bursary",
    provider: "Eastern Cape Provincial Government",
    description: "Bursary for Eastern Cape residents in critical skills areas.",
    amount: "Full tuition + accommodation + stipend",
    eligibilityCriteria: [
      "South African citizen and Eastern Cape resident",
      "Studying in critical skills shortage areas",
      "Academic excellence and financial need",
      "Commitment to provincial development",
    ],
    applicationDeadline: "30 September annually",
    applicationProcess: "Apply through EC Department of Education",
    contactInfo: "040 608 4000 | bursaries@ecdoe.gov.za",
    website: "https://www.ecdoe.gov.za",
    fieldsOfStudy: [
      "Medicine",
      "Engineering",
      "Education",
      "Agriculture",
      "Social Work",
    ],
    provinces: ["Eastern Cape"],
    requirements: {
      academicRequirement: "Good academic performance",
      financialNeed: true,
      workCommitment: true,
    },
    isActive: true,
    priority: "medium",
  },

  // International & Study Abroad
  {
    id: "mandela-rhodes-scholarship",
    name: "Mandela Rhodes Scholarship",
    provider: "Mandela Rhodes Foundation",
    description: "Prestigious scholarship for exceptional African students.",
    amount:
      "Full tuition + accommodation + stipend + mentorship + leadership development",
    eligibilityCriteria: [
      "African citizenship",
      "Exceptional academic performance",
      "Leadership potential and community involvement",
      "Studying at participating South African universities",
      "Commitment to African development",
    ],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply online at mandelarhodes.org",
    contactInfo: "021 761 7776 | info@mandelarhodes.org",
    website: "https://www.mandelarhodes.org",
    fieldsOfStudy: ["All fields"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Exceptional academic excellence",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },

  // Specialized Fields
  {
    id: "aviation-industry-bursary",
    name: "South African Airways Aviation Bursary",
    provider: "SA Express / Private Airlines Consortium",
    description: "Bursary for aviation and aerospace studies.",
    amount: "Full tuition + accommodation + stipend + flight training",
    eligibilityCriteria: [
      "South African citizen",
      "Studying aeronautical engineering, aviation management, or pilot training",
      "Excellent academic performance with strong mathematics and science",
      "Medical fitness for aviation",
      "Commitment to aviation industry",
    ],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply through participating aviation schools",
    contactInfo: "011 978 9111 | aviation.bursaries@flyairlink.com",
    website: "https://www.flyairlink.com",
    fieldsOfStudy: [
      "Aeronautical Engineering",
      "Aviation Management",
      "Pilot Training",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Strong mathematics and science performance",
      financialNeed: true,
      workCommitment: true,
    },
    isActive: true,
    priority: "medium",
  },

  {
    id: "agricultural-development-bursary",
    name: "AgriSETA Agricultural Bursary",
    provider: "Agricultural Sector Education and Training Authority",
    description: "Bursary for agricultural and related studies.",
    amount: "Full tuition + accommodation + stipend + practical training",
    eligibilityCriteria: [
      "South African citizen",
      "Studying agriculture, veterinary science, food science, or related fields",
      "Academic merit and commitment to agricultural sector",
      "Rural development focus preferred",
    ],
    applicationDeadline: "30 September annually",
    applicationProcess: "Apply online at agriseta.co.za",
    contactInfo: "012 301 5600 | bursaries@agriseta.co.za",
    website: "https://www.agriseta.co.za",
    fieldsOfStudy: [
      "Agriculture",
      "Veterinary Science",
      "Food Science",
      "Animal Science",
      "Horticulture",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Good academic performance",
      financialNeed: true,
      workCommitment: true,
    },
    isActive: true,
    priority: "medium",
  },

  // Banking & Financial Services
  {
    id: "first-national-bank-bursary",
    name: "FNB Bursary Programme",
    provider: "First National Bank",
    description:
      "Comprehensive bursary for banking, finance, and technology students.",
    amount:
      "Full tuition + accommodation + stipend + mentorship + graduate programme",
    eligibilityCriteria: [
      "South African citizen",
      "Studying BCom (Finance, Accounting, Economics), IT, or Computer Science",
      "Academic excellence with minimum 70% average",
      "Leadership potential and community involvement",
      "Strong analytical and communication skills",
    ],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply online at fnb.co.za/careers",
    contactInfo: "087 736 2436 | bursaries@fnb.co.za",
    website: "https://www.fnb.co.za",
    fieldsOfStudy: [
      "Finance",
      "Accounting",
      "Economics",
      "Information Technology",
      "Computer Science",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },

  {
    id: "standard-bank-bursary",
    name: "Standard Bank Bursary Programme",
    provider: "Standard Bank Group",
    description: "Banking bursary with leadership development focus.",
    amount:
      "Full tuition + accommodation + stipend + leadership development + vacation work",
    eligibilityCriteria: [
      "South African citizen",
      "Studying Commerce, IT, Computer Science, or related fields",
      "Academic excellence with minimum 70% average",
      "Leadership qualities and community engagement",
      "Commitment to banking industry",
    ],
    applicationDeadline: "30 September annually",
    applicationProcess: "Apply online at standardbank.co.za",
    contactInfo: "011 636 9111 | bursaries@standardbank.co.za",
    website: "https://www.standardbank.co.za",
    fieldsOfStudy: [
      "Commerce",
      "Information Technology",
      "Computer Science",
      "Finance",
      "Accounting",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },

  {
    id: "absa-bursary",
    name: "Absa Group Bursary Programme",
    provider: "Absa Group Limited",
    description: "Banking and technology bursary with innovation focus.",
    amount:
      "Full tuition + accommodation + stipend + innovation labs + mentorship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying BCom, Computer Science, Data Science, or Engineering",
      "Academic excellence with minimum 70% average",
      "Innovation mindset and problem-solving skills",
      "Interest in financial technology",
    ],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply online at absa.africa/careers",
    contactInfo: "0860 111 717 | bursaries@absa.africa",
    website: "https://www.absa.africa",
    fieldsOfStudy: [
      "Commerce",
      "Computer Science",
      "Data Science",
      "Engineering",
      "Mathematics",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },

  // Insurance & Investment
  {
    id: "old-mutual-bursary",
    name: "Old Mutual Bursary Programme",
    provider: "Old Mutual Group",
    description: "Financial services bursary with actuarial focus.",
    amount:
      "Full tuition + accommodation + stipend + actuarial training + mentorship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying Actuarial Science, Mathematics, Statistics, or Finance",
      "Academic excellence with minimum 75% average",
      "Strong mathematical and analytical skills",
      "Leadership potential",
    ],
    applicationDeadline: "30 September annually",
    applicationProcess: "Apply online at oldmutual.com",
    contactInfo: "011 217 1000 | bursaries@oldmutual.com",
    website: "https://www.oldmutual.com",
    fieldsOfStudy: [
      "Actuarial Science",
      "Mathematics",
      "Statistics",
      "Finance",
      "Economics",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "75% average with strong mathematics",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },

  {
    id: "sanlam-bursary",
    name: "Sanlam Group Bursary Programme",
    provider: "Sanlam Limited",
    description: "Insurance and investment bursary programme.",
    amount: "Full tuition + accommodation + stipend + professional development",
    eligibilityCriteria: [
      "South African citizen",
      "Studying Actuarial Science, Finance, Investment Management, or related fields",
      "Academic excellence with minimum 70% average",
      "Interest in financial services industry",
      "Leadership and communication skills",
    ],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply online at sanlam.com",
    contactInfo: "021 916 5000 | bursaries@sanlam.co.za",
    website: "https://www.sanlam.com",
    fieldsOfStudy: [
      "Actuarial Science",
      "Finance",
      "Investment Management",
      "Economics",
      "Mathematics",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "medium",
  },

  // Telecommunications
  {
    id: "vodacom-bursary",
    name: "Vodacom Bursary Programme",
    provider: "Vodacom Group",
    description: "Telecommunications and technology bursary.",
    amount:
      "Full tuition + accommodation + stipend + technology training + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying Engineering, Computer Science, IT, or Business",
      "Academic excellence with minimum 70% average",
      "Passion for technology and innovation",
      "Leadership qualities",
    ],
    applicationDeadline: "30 September annually",
    applicationProcess: "Apply online at vodacom.co.za/careers",
    contactInfo: "082 135 | bursaries@vodacom.co.za",
    website: "https://www.vodacom.co.za",
    fieldsOfStudy: [
      "Engineering",
      "Computer Science",
      "Information Technology",
      "Business Management",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },

  {
    id: "mtn-bursary",
    name: "MTN Foundation Bursary",
    provider: "MTN Group",
    description: "Technology and business bursary with innovation focus.",
    amount: "Full tuition + accommodation + stipend + technology training",
    eligibilityCriteria: [
      "South African citizen",
      "Studying Engineering, Computer Science, Business, or related fields",
      "Academic merit with minimum 65% average",
      "Technology innovation interest",
      "Community involvement",
    ],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply online at mtn.co.za",
    contactInfo: "083 123 | bursaries@mtn.com",
    website: "https://www.mtn.co.za",
    fieldsOfStudy: [
      "Engineering",
      "Computer Science",
      "Business Management",
      "Information Technology",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },

  // Retail & Consumer Goods
  {
    id: "pick-n-pay-bursary",
    name: "Pick n Pay Bursary Programme",
    provider: "Pick n Pay Holdings",
    description: "Retail and business management bursary.",
    amount: "Full tuition + accommodation + stipend + retail training",
    eligibilityCriteria: [
      "South African citizen",
      "Studying Business Management, Supply Chain, Marketing, or related fields",
      "Academic merit with minimum 65% average",
      "Interest in retail industry",
      "Leadership potential",
    ],
    applicationDeadline: "30 September annually",
    applicationProcess: "Apply online at picknpay.co.za",
    contactInfo: "021 658 1000 | bursaries@pnp.co.za",
    website: "https://www.picknpay.co.za",
    fieldsOfStudy: [
      "Business Management",
      "Supply Chain",
      "Marketing",
      "Commerce",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },

  {
    id: "woolworths-bursary",
    name: "Woolworths Holdings Bursary",
    provider: "Woolworths Holdings Limited",
    description: "Retail, fashion, and sustainability focused bursary.",
    amount: "Full tuition + accommodation + stipend + industry exposure",
    eligibilityCriteria: [
      "South African citizen",
      "Studying Business, Fashion Design, Sustainability, or related fields",
      "Academic excellence with minimum 65% average",
      "Sustainability mindset",
      "Creative and innovative thinking",
    ],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply online at woolworthsholdings.co.za",
    contactInfo: "021 407 9111 | bursaries@woolworths.co.za",
    website: "https://www.woolworthsholdings.co.za",
    fieldsOfStudy: [
      "Business Management",
      "Fashion Design",
      "Environmental Science",
      "Marketing",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },

  // Energy & Utilities
  {
    id: "eskom-bursary",
    name: "Eskom Development Foundation Bursary",
    provider: "Eskom Holdings SOC Ltd",
    description: "Engineering bursary for energy sector development.",
    amount:
      "Full tuition + accommodation + stipend + practical training + employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying Electrical, Mechanical, Civil, or Nuclear Engineering",
      "Academic excellence with minimum 70% average",
      "Commitment to energy sector",
      "Work-back obligation after graduation",
    ],
    applicationDeadline: "30 September annually",
    applicationProcess: "Apply online at eskom.co.za",
    contactInfo: "011 800 8111 | bursaries@eskom.co.za",
    website: "https://www.eskom.co.za",
    fieldsOfStudy: [
      "Electrical Engineering",
      "Mechanical Engineering",
      "Civil Engineering",
      "Nuclear Engineering",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "70% average",
      financialNeed: false,
      workCommitment: true,
    },
    isActive: true,
    priority: "high",
  },

  {
    id: "sasol-bursary",
    name: "Sasol Bursary Programme",
    provider: "Sasol Limited",
    description: "Chemical and engineering bursary for energy and chemicals.",
    amount:
      "Full tuition + accommodation + stipend + vacation work + graduate programme",
    eligibilityCriteria: [
      "South African citizen",
      "Studying Chemical, Mechanical, Electrical Engineering, or Chemistry",
      "Academic excellence with minimum 70% average",
      "Interest in energy and chemical industries",
      "Work commitment after graduation",
    ],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply online at sasol.com",
    contactInfo: "011 441 3000 | bursaries@sasol.com",
    website: "https://www.sasol.com",
    fieldsOfStudy: [
      "Chemical Engineering",
      "Mechanical Engineering",
      "Electrical Engineering",
      "Chemistry",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "70% average",
      financialNeed: false,
      workCommitment: true,
    },
    isActive: true,
    priority: "high",
  },

  // Healthcare & Pharmaceuticals (Additional)
  {
    id: "clicks-group-bursary",
    name: "Clicks Group Healthcare Bursary",
    provider: "Clicks Group Limited",
    description: "Healthcare and pharmacy bursary programme.",
    amount: "Full tuition + accommodation + stipend + practical training",
    eligibilityCriteria: [
      "South African citizen",
      "Studying Pharmacy, Medicine, Nursing, or Healthcare Management",
      "Academic merit with minimum 65% average",
      "Commitment to healthcare industry",
      "Community service orientation",
    ],
    applicationDeadline: "30 September annually",
    applicationProcess: "Apply online at clicksgroup.co.za",
    contactInfo: "021 460 1911 | bursaries@clicks.co.za",
    website: "https://www.clicksgroup.co.za",
    fieldsOfStudy: ["Pharmacy", "Medicine", "Nursing", "Healthcare Management"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },

  // Professional Services
  {
    id: "pwc-bursary",
    name: "PwC South Africa Bursary Programme",
    provider: "PricewaterhouseCoopers",
    description: "Professional services bursary with global exposure.",
    amount:
      "Full tuition + accommodation + stipend + international opportunities + mentorship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying Accounting, Finance, Economics, Law, or related fields",
      "Academic excellence with minimum 75% average",
      "Leadership potential and analytical skills",
      "Professional service career interest",
    ],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply online at pwc.co.za",
    contactInfo: "011 797 4000 | bursaries@pwc.com",
    website: "https://www.pwc.co.za",
    fieldsOfStudy: [
      "Accounting",
      "Finance",
      "Economics",
      "Law",
      "Business Management",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "75% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },

  {
    id: "deloitte-bursary",
    name: "Deloitte South Africa Bursary",
    provider: "Deloitte Africa",
    description: "Consulting and professional services bursary.",
    amount:
      "Full tuition + accommodation + stipend + consulting exposure + leadership development",
    eligibilityCriteria: [
      "South African citizen",
      "Studying Accounting, Finance, IT, Engineering, or related fields",
      "Academic excellence with minimum 70% average",
      "Problem-solving and analytical skills",
      "Consulting career aspirations",
    ],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply online at deloitte.com",
    contactInfo: "011 806 5000 | bursaries@deloitte.co.za",
    website: "https://www.deloitte.com",
    fieldsOfStudy: [
      "Accounting",
      "Finance",
      "Information Technology",
      "Engineering",
      "Business Management",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
];

export const BURSARY_FIELDS_OF_STUDY = [
  "All fields",
  "Accounting",
  "Actuarial Science",
  "Agriculture",
  "Architecture",
  "Arts and Design",
  "Aviation",
  "Biological Sciences",
  "Business Management",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Computer Science",
  "Criminology",
  "Economics",
  "Education",
  "Electrical Engineering",
  "Engineering",
  "Environmental Science",
  "Finance",
  "Geology",
  "Health Sciences",
  "Information Technology",
  "Journalism",
  "Law",
  "Mathematics",
  "Mechanical Engineering",
  "Medicine",
  "Metallurgy",
  "Mining Engineering",
  "Nursing",
  "Pharmacy",
  "Physics",
  "Psychology",
  "Public Administration",
  "Social Work",
  "Statistics",
  "Teaching",
  "Veterinary Science",
];

// For backward compatibility, export as BURSARIES
export const BURSARIES = ENHANCED_BURSARIES;
