import { Bursary } from "@/types/university";

export const ENHANCED_BURSARIES: Bursary[] = [
  // Updated Government Bursaries (1-15)
  {
    id: "nsfas-2024",
    name: "NSFAS (National Student Financial Aid Scheme)",
    provider: "Department of Higher Education and Training",
    description:
      "Government financial aid for South African students from poor and working-class families.",
    amount:
      "Full tuition + accommodation + meal allowance + book allowance + transport allowance",
    eligibilityCriteria: [
      "South African citizen",
      "Combined annual household income ≤ R350,000",
      "SASSA grant recipient qualifies regardless of household income",
      "Must be studying at a public university or TVET college",
      "Must pass at least 75% of modules per year to continue funding",
    ],
    applicationDeadline: "31 January 2025",
    applicationProcess: "Apply online at www.nsfas.org.za",
    contactInfo: "08000 67327 | info@nsfas.org.za",
    website: "https://www.nsfas.org.za",
    fieldsOfStudy: ["All fields"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "NSC pass with admission to higher education",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "funza-lushaka-2024",
    name: "Funza Lushaka Teaching Bursary",
    provider: "Department of Basic Education",
    description:
      "Bursary for students studying to become teachers in public schools.",
    amount:
      "Full tuition + accommodation + meal allowance + book allowance + transport allowance",
    eligibilityCriteria: [
      "South African citizen",
      "Studying Initial Teacher Education qualifications",
      "Agree to teach in public schools for same number of years as bursary received",
      "Maintain good academic standing",
    ],
    applicationDeadline: "31 January 2025",
    applicationProcess: "Apply online at www.funzalushaka.doe.gov.za",
    contactInfo: "0800 202 933 | bursaries@dbe.gov.za",
    website: "https://www.funzalushaka.doe.gov.za",
    fieldsOfStudy: ["Education", "Teaching"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "NSC pass with admission to education programs",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "dpsa-public-admin-2024",
    name: "DPSA Public Administration Bursary",
    provider: "Department of Public Service and Administration",
    description:
      "Bursary for students pursuing public administration and related qualifications.",
    amount: "Full tuition + accommodation + stipend",
    eligibilityCriteria: [
      "South African citizen",
      "Studying public administration, public management, development studies",
      "Agree to work in public service after graduation",
      "Academic merit and financial need",
    ],
    applicationDeadline: "30 September 2024",
    applicationProcess: "Apply online at www.dpsa.gov.za",
    contactInfo: "012 336 1000 | info@dpsa.gov.za",
    website: "https://www.dpsa.gov.za",
    fieldsOfStudy: [
      "Public Administration",
      "Management",
      "Development Studies",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Good academic performance",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "doh-health-sciences-2024",
    name: "Department of Health Bursary",
    provider: "Department of Health",
    description: "Bursary for students in health sciences fields.",
    amount: "Full tuition + accommodation + stipend",
    eligibilityCriteria: [
      "South African citizen",
      "Studying medicine, nursing, pharmacy, dentistry, allied health",
      "Agree to work in public health sector after graduation",
      "Academic excellence and financial need",
    ],
    applicationDeadline: "31 August 2024",
    applicationProcess: "Apply through provincial health departments",
    contactInfo: "012 395 8000 | info@health.gov.za",
    website: "https://www.health.gov.za",
    fieldsOfStudy: [
      "Medicine",
      "Nursing",
      "Pharmacy",
      "Dentistry",
      "Health Sciences",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Strong academic performance",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "dsi-scarce-skills-2024",
    name: "DSI Scarce Skills Bursary",
    provider: "Department of Science and Innovation",
    description: "Bursary for STEM fields and scarce skills areas.",
    amount: "Full tuition + accommodation + stipend + research allowance",
    eligibilityCriteria: [
      "South African citizen",
      "Studying in STEM fields (Science, Technology, Engineering, Mathematics)",
      "Academic excellence",
      "Commitment to contribute to South Africa's innovation system",
    ],
    applicationDeadline: "31 July 2024",
    applicationProcess: "Apply online at www.dst.gov.za",
    contactInfo: "012 843 6300 | info@dst.gov.za",
    website: "https://www.dst.gov.za",
    fieldsOfStudy: [
      "Science",
      "Technology",
      "Engineering",
      "Mathematics",
      "Innovation",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic excellence",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },

  // Banking & Financial Services (16-35)
  {
    id: "absa-bursary-2024",
    name: "Absa Group Bursary Programme",
    provider: "Absa Group Limited",
    description:
      "Comprehensive bursary for commerce, IT, and risk management students.",
    amount: "Full tuition + accommodation + stipend + vacation work",
    eligibilityCriteria: [
      "South African citizen",
      "Studying commerce, accounting, economics, IT, risk management",
      "Academic excellence (minimum 65% average)",
      "Financial need",
      "Leadership potential",
    ],
    applicationDeadline: "31 May 2024",
    applicationProcess: "Apply online at www.absa.co.za/careers/bursaries",
    contactInfo: "bursaries@absa.co.za",
    website: "https://www.absa.co.za/careers/bursaries",
    fieldsOfStudy: [
      "Commerce",
      "Accounting",
      "Economics",
      "Information Technology",
      "Risk Management",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "standard-bank-2024",
    name: "Standard Bank Bursary Programme",
    provider: "Standard Bank Group",
    description: "Bursary for banking, finance, and technology students.",
    amount: "Full tuition + accommodation + allowances + mentorship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying commerce, accounting, economics, IT, mathematics",
      "Strong academic performance (minimum 60%)",
      "Financial need",
      "Previously disadvantaged individuals preferred",
    ],
    applicationDeadline: "30 June 2024",
    applicationProcess:
      "Apply online at www.standardbank.co.za/careers/bursaries",
    contactInfo: "bursaries@standardbank.co.za",
    website: "https://www.standardbank.co.za/careers/bursaries",
    fieldsOfStudy: [
      "Commerce",
      "Accounting",
      "Economics",
      "Information Technology",
      "Mathematics",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "firstrand-2024",
    name: "FirstRand Foundation Bursary",
    provider: "FirstRand Limited",
    description: "Bursary for commerce, mathematics, and technology students.",
    amount: "Full tuition + accommodation + stipend + leadership development",
    eligibilityCriteria: [
      "South African citizen",
      "Studying commerce, mathematics, actuarial science, IT",
      "Academic merit (minimum 65%)",
      "Financial need",
      "Leadership qualities",
    ],
    applicationDeadline: "31 July 2024",
    applicationProcess: "Apply online at www.firstrand.co.za/foundation",
    contactInfo: "foundation@firstrand.co.za",
    website: "https://www.firstrand.co.za/foundation",
    fieldsOfStudy: [
      "Commerce",
      "Mathematics",
      "Actuarial Science",
      "Information Technology",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "nedbank-2024",
    name: "Nedbank Foundation Bursary",
    provider: "Nedbank Group",
    description: "Bursary for commerce, IT, and finance students.",
    amount: "Full tuition + accommodation + allowances + mentorship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying commerce, accounting, IT, finance, economics",
      "Academic excellence (minimum 65%)",
      "Financial need",
      "Community involvement",
    ],
    applicationDeadline: "31 August 2024",
    applicationProcess: "Apply online at www.nedbank.co.za/foundation",
    contactInfo: "foundation@nedbank.co.za",
    website: "https://www.nedbank.co.za/foundation",
    fieldsOfStudy: [
      "Commerce",
      "Accounting",
      "Information Technology",
      "Finance",
      "Economics",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "investec-2024",
    name: "Investec Foundation Bursary",
    provider: "Investec Limited",
    description: "Bursary for finance, economics, and business students.",
    amount: "Full tuition + accommodation + stipend + internship opportunities",
    eligibilityCriteria: [
      "South African citizen",
      "Studying finance, economics, accounting, actuarial science",
      "Academic excellence (minimum 70%)",
      "Financial need",
      "Leadership potential",
    ],
    applicationDeadline: "31 May 2024",
    applicationProcess: "Apply online at www.investec.com/foundation",
    contactInfo: "foundation@investec.co.za",
    website: "https://www.investec.com/foundation",
    fieldsOfStudy: ["Finance", "Economics", "Accounting", "Actuarial Science"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 70% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },

  // Mining & Resources (36-50)
  {
    id: "anglo-american-2024",
    name: "Anglo American Bursary Programme",
    provider: "Anglo American plc",
    description:
      "Comprehensive bursary for mining, engineering, and related fields.",
    amount:
      "Full tuition + accommodation + stipend + vacation work + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying mining engineering, geology, metallurgy, mechanical/electrical engineering",
      "Academic excellence (minimum 65%)",
      "Leadership potential",
      "Agree to work for Anglo American after graduation",
    ],
    applicationDeadline: "31 March 2024",
    applicationProcess:
      "Apply online at www.angloamerican.com/careers/bursaries",
    contactInfo: "bursaries@angloamerican.com",
    website: "https://www.angloamerican.com/careers/bursaries",
    fieldsOfStudy: [
      "Mining Engineering",
      "Geology",
      "Metallurgy",
      "Mechanical Engineering",
      "Electrical Engineering",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "sasol-2024",
    name: "Sasol Bursary Programme",
    provider: "Sasol Limited",
    description:
      "Comprehensive bursary for engineering, science, and technology students.",
    amount:
      "Full tuition + accommodation + meals + books + transport + personal allowance + vacation work",
    eligibilityCriteria: [
      "South African citizen",
      "Studying chemical, mechanical, electrical, or industrial engineering",
      "Chemistry, Mathematics, Physics, Computer Science",
      "Minimum 65% average in Grade 11 and 12",
      "Agree to work for Sasol after graduation",
    ],
    applicationDeadline: "30 April 2024",
    applicationProcess: "Apply online at www.sasol.com/careers/bursaries",
    contactInfo: "bursaries@sasol.com",
    website: "https://www.sasol.com/careers/bursaries",
    fieldsOfStudy: [
      "Chemical Engineering",
      "Mechanical Engineering",
      "Electrical Engineering",
      "Chemistry",
      "Computer Science",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "gold-fields-2024",
    name: "Gold Fields Bursary Programme",
    provider: "Gold Fields Limited",
    description: "Bursary for mining and engineering students.",
    amount:
      "Full tuition + accommodation + stipend + vacation work + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying mining engineering, geology, metallurgy, electrical/mechanical engineering",
      "Academic excellence (minimum 65%)",
      "Agree to work for Gold Fields after graduation",
    ],
    applicationDeadline: "31 March 2024",
    applicationProcess: "Apply online at www.goldfields.com/careers/bursaries",
    contactInfo: "bursaries@goldfields.com",
    website: "https://www.goldfields.com/careers/bursaries",
    fieldsOfStudy: [
      "Mining Engineering",
      "Geology",
      "Metallurgy",
      "Electrical Engineering",
      "Mechanical Engineering",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "harmony-gold-2024",
    name: "Harmony Gold Mining Bursary",
    provider: "Harmony Gold Mining Company Limited",
    description: "Bursary for mining-related studies.",
    amount: "Full tuition + accommodation + allowances + vacation work",
    eligibilityCriteria: [
      "South African citizen",
      "Studying mining engineering, geology, metallurgy",
      "Strong academic performance (minimum 60%)",
      "From mining communities preferred",
      "Agree to work for Harmony Gold after graduation",
    ],
    applicationDeadline: "30 April 2024",
    applicationProcess: "Apply online at www.harmony.co.za/careers/bursaries",
    contactInfo: "bursaries@harmony.co.za",
    website: "https://www.harmony.co.za/careers/bursaries",
    fieldsOfStudy: ["Mining Engineering", "Geology", "Metallurgy"],
    provinces: ["Free State", "Gauteng", "North West"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "eskom-2024",
    name: "Eskom Development Foundation Bursary",
    provider: "Eskom Holdings SOC Ltd",
    description:
      "Bursary for students in engineering and scarce skills fields.",
    amount: "Tuition + accommodation + meals + books + transport + stipend",
    eligibilityCriteria: [
      "South African citizen",
      "Studying engineering (electrical, mechanical, civil, industrial)",
      "Science, technology, and other scarce skills",
      "Good academic performance (minimum 60%)",
      "Financial need",
    ],
    applicationDeadline: "31 March 2024",
    applicationProcess: "Apply online through university financial aid offices",
    contactInfo: "011 800 8111 | bursaries@eskom.co.za",
    website: "https://www.eskom.co.za/careers/bursaries",
    fieldsOfStudy: [
      "Electrical Engineering",
      "Mechanical Engineering",
      "Civil Engineering",
      "Industrial Engineering",
      "Science",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
];

// Continue with more bursaries to reach 100+...
export const ADDITIONAL_BURSARIES: Bursary[] = [
  // Government & Public Sector (Additional)
  {
    id: "nsfas-coid-2025",
    name: "NSFAS COID (Students with Disabilities)",
    provider: "National Student Financial Aid Scheme",
    description:
      "Specialized NSFAS funding for students with disabilities, covering additional support needs.",
    amount:
      "Full tuition + accommodation + assistive technology + specialized support + personal care allowance",
    eligibilityCriteria: [
      "South African citizen",
      "Diagnosed disability with supporting medical documentation",
      "Enrolled at public higher education institution",
      "Combined household income ≤ R350,000",
      "Academic progress requirements maintained",
    ],
    applicationDeadline: "30 November 2025",
    applicationProcess:
      "Apply through NSFAS online portal with disability documentation",
    contactInfo: "08000 67327 | disabilityunit@nsfas.org.za",
    website: "https://www.nsfas.org.za/content/disability-funding.html",
    fieldsOfStudy: ["All fields"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "NSC pass with admission to higher education",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "agriseta-2025",
    name: "AgriSETA Bursary Programme",
    provider: "Agriculture Sector Education and Training Authority",
    description:
      "Comprehensive bursary for agriculture, land reform, and rural development studies.",
    amount:
      "Full tuition + accommodation + stipend + research funding + practical training",
    eligibilityCriteria: [
      "South African citizen",
      "Studying agriculture, forestry, land surveying, rural development",
      "Academic merit (minimum 60%)",
      "Commitment to agricultural sector development",
      "Rural background preferred",
    ],
    applicationDeadline: "15 September 2025",
    applicationProcess: "Apply online at www.agriseta.co.za/bursaries",
    contactInfo: "012 301 5600 | bursaries@agriseta.co.za",
    website: "https://www.agriseta.co.za/programmes/bursaries",
    fieldsOfStudy: [
      "Agriculture",
      "Forestry",
      "Land Surveying",
      "Rural Development",
      "Agricultural Economics",
      "Veterinary Science",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },

  // Corporate & Industry (Additional)
  {
    id: "bmw-sa-2025",
    name: "BMW South Africa Bursary Programme",
    provider: "BMW South Africa",
    description:
      "Comprehensive bursary for engineering, business, and technology students.",
    amount:
      "Full tuition + accommodation + stipend + internship opportunities + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying engineering (mechanical, electrical, industrial), business, technology",
      "Academic excellence (minimum 65%)",
      "Leadership potential",
      "Agree to work for BMW SA after graduation",
    ],
    applicationDeadline: "30 June 2025",
    applicationProcess: "Apply online at www.bmw.co.za/careers/bursaries",
    contactInfo: "bursaries@bmw.co.za",
    website: "https://www.bmw.co.za/en/footer/careers/bursaries.html",
    fieldsOfStudy: [
      "Mechanical Engineering",
      "Electrical Engineering",
      "Industrial Engineering",
      "Business Management",
      "Technology",
      "Manufacturing Engineering",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "bridgestone-pe-2025",
    name: "Bridgestone Port Elizabeth Bursary",
    provider: "Bridgestone South Africa",
    description:
      "Bursary for students in business, IT, law, engineering, and medical fields.",
    amount: "Full tuition + accommodation + stipend + vacation work",
    eligibilityCriteria: [
      "South African citizen",
      "Studying business, IT, law, engineering, medical sciences",
      "Academic merit (minimum 60%)",
      "Eastern Cape residents preferred",
      "Financial need consideration",
    ],
    applicationDeadline: "12 April 2025",
    applicationProcess: "Apply online through university career centers",
    contactInfo: "info@bridgestone.co.za",
    website: "https://www.bridgestone.co.za/careers/bursaries",
    fieldsOfStudy: [
      "Business Management",
      "Information Technology",
      "Law",
      "Engineering",
      "Medical Sciences",
      "Commerce",
    ],
    provinces: ["Eastern Cape", "All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "mtn-telecoms-2025",
    name: "MTN Telecommunications Bursary",
    provider: "MTN South Africa",
    description:
      "Specialized bursary for telecommunications, engineering, and IT students.",
    amount:
      "Full tuition + accommodation + allowances + practical training + graduate opportunities",
    eligibilityCriteria: [
      "South African citizen",
      "Studying telecommunications, engineering, IT, computer science",
      "Academic excellence (minimum 65%)",
      "Leadership potential",
      "Interest in telecommunications industry",
    ],
    applicationDeadline: "31 May 2025",
    applicationProcess: "Apply online at www.mtn.co.za/careers/bursaries",
    contactInfo: "bursaries@mtn.co.za",
    website: "https://www.mtn.co.za/careers/bursaries",
    fieldsOfStudy: [
      "Telecommunications Engineering",
      "Electrical Engineering",
      "Information Technology",
      "Computer Science",
      "Data Science",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "standard-bank-comprehensive-2025",
    name: "Standard Bank Comprehensive Bursary",
    provider: "Standard Bank Group",
    description:
      "Multi-field bursary including engineering, data science, and commerce.",
    amount:
      "Full tuition + accommodation + stipend + mentorship + internship + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying engineering, data science, commerce, economics, actuarial science",
      "Academic excellence (minimum 65%)",
      "Leadership potential",
      "Previously disadvantaged candidates preferred",
    ],
    applicationDeadline: "30 September 2025",
    applicationProcess:
      "Apply online at www.standardbank.co.za/careers/bursaries",
    contactInfo: "graduate.recruitment@standardbank.co.za",
    website: "https://www.standardbank.co.za/careers/graduates-and-bursaries",
    fieldsOfStudy: [
      "Engineering",
      "Data Science",
      "Commerce",
      "Economics",
      "Actuarial Science",
      "Information Technology",
      "Mathematics",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "santam-insurance-2025",
    name: "Santam Insurance & Actuarial Bursary",
    provider: "Santam Limited",
    description:
      "Specialized bursary for insurance and actuarial science students.",
    amount:
      "Full tuition + accommodation + stipend + vacation work + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying actuarial science, risk management, commerce, mathematics, statistics",
      "Academic excellence (minimum 70%)",
      "Interest in insurance industry",
      "Strong mathematical aptitude",
    ],
    applicationDeadline: "30 September 2025",
    applicationProcess: "Apply online at www.santam.co.za/careers/bursaries",
    contactInfo: "bursaries@santam.co.za",
    website: "https://www.santam.co.za/careers/bursaries",
    fieldsOfStudy: [
      "Actuarial Science",
      "Risk Management",
      "Commerce",
      "Mathematics",
      "Statistics",
      "Economics",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "mercedes-benz-sa-2025",
    name: "Mercedes-Benz South Africa Engineering Bursary",
    provider: "Mercedes-Benz South Africa",
    description:
      "Premium engineering bursary with comprehensive development programme.",
    amount:
      "Full tuition + accommodation + generous stipend + international exposure + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying mechanical, electrical, industrial, or automotive engineering",
      "Academic excellence (minimum 70%)",
      "Leadership potential",
      "Passion for automotive industry",
    ],
    applicationDeadline: "12 October 2025",
    applicationProcess:
      "Apply online at www.mercedes-benz.co.za/careers/bursaries",
    contactInfo: "careers@mercedes-benz.co.za",
    website: "https://www.mercedes-benz.co.za/careers/students-graduates",
    fieldsOfStudy: [
      "Mechanical Engineering",
      "Electrical Engineering",
      "Industrial Engineering",
      "Automotive Engineering",
      "Manufacturing Engineering",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "sappi-comprehensive-2025",
    name: "Sappi Comprehensive Engineering Bursary",
    provider: "Sappi Limited",
    description:
      "Comprehensive bursary for engineering students in forestry and manufacturing.",
    amount:
      "Full tuition + accommodation + stipend + vacation work + overseas exposure + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying electrical, chemical, mechanical, or forestry engineering",
      "Academic excellence (minimum 65%)",
      "Interest in forestry/paper industry",
      "Environmental consciousness",
    ],
    applicationDeadline: "30 September 2025",
    applicationProcess: "Apply online at www.sappi.com/careers/bursaries",
    contactInfo: "bursaries@sappi.com",
    website: "https://www.sappi.com/careers/bursaries",
    fieldsOfStudy: [
      "Electrical Engineering",
      "Chemical Engineering",
      "Mechanical Engineering",
      "Forestry Engineering",
      "Environmental Engineering",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "takealot-tech-2025",
    name: "Takealot.com Technology Bursary",
    provider: "Takealot.com",
    description:
      "Technology-focused bursary for IT and computer engineering students.",
    amount:
      "Full tuition + accommodation + generous tech allowance + internship + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying IT, computer engineering, software development, data science",
      "Academic excellence (minimum 65%)",
      "Passion for e-commerce and technology",
      "Strong programming aptitude",
    ],
    applicationDeadline: "30 September 2025",
    applicationProcess: "Apply online at www.takealot.com/careers/bursaries",
    contactInfo: "careers@takealot.com",
    website: "https://www.takealot.com/careers/graduates",
    fieldsOfStudy: [
      "Information Technology",
      "Computer Engineering",
      "Software Development",
      "Data Science",
      "Computer Science",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "sibanye-stillwater-2025",
    name: "Sibanye-Stillwater Comprehensive Bursary",
    provider: "Sibanye-Stillwater",
    description:
      "Multi-disciplinary bursary for engineering, finance, and HR students.",
    amount:
      "Full tuition + accommodation + stipend + practical training + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying engineering (mining, mechanical, electrical), finance, HR, geology",
      "Academic excellence (minimum 65%)",
      "Leadership potential",
      "Interest in mining industry",
    ],
    applicationDeadline: "30 July 2025",
    applicationProcess:
      "Apply online at www.sibanyestillwater.com/careers/bursaries",
    contactInfo: "bursaries@sibanyestillwater.com",
    website: "https://www.sibanyestillwater.com/careers/bursaries",
    fieldsOfStudy: [
      "Mining Engineering",
      "Mechanical Engineering",
      "Electrical Engineering",
      "Finance",
      "Human Resources",
      "Geology",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "psg-finance-2025",
    name: "PSG Group Finance Sector Bursary",
    provider: "PSG Group",
    description:
      "Comprehensive finance sector bursary with extensive development opportunities.",
    amount:
      "Full tuition + accommodation + generous stipend + mentorship + internship + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying finance, commerce, economics, actuarial science, accounting",
      "Academic excellence (minimum 70%)",
      "Leadership potential",
      "Entrepreneurial mindset",
    ],
    applicationDeadline: "30 November 2025",
    applicationProcess: "Apply online at www.psg.co.za/careers/bursaries",
    contactInfo: "bursaries@psg.co.za",
    website: "https://www.psg.co.za/corporate/careers/bursaries",
    fieldsOfStudy: [
      "Finance",
      "Commerce",
      "Economics",
      "Actuarial Science",
      "Accounting",
      "Investment Management",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "shoprite-comprehensive-2025",
    name: "Shoprite Holdings Comprehensive Bursary",
    provider: "Shoprite Holdings",
    description:
      "Multi-field bursary covering data science, accounting, logistics, and pharmacy.",
    amount:
      "Full tuition + accommodation + stipend + practical training + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying data science, accounting, logistics, pharmacy, supply chain, retail management",
      "Academic merit (minimum 60%)",
      "Interest in retail industry",
      "Leadership potential",
    ],
    applicationDeadline: "31 August 2025",
    applicationProcess:
      "Apply online at www.shopriteholdings.co.za/careers/bursaries",
    contactInfo: "bursaries@shoprite.co.za",
    website: "https://www.shopriteholdings.co.za/careers/bursaries",
    fieldsOfStudy: [
      "Data Science",
      "Accounting",
      "Logistics",
      "Pharmacy",
      "Supply Chain Management",
      "Retail Management",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "wbho-construction-2025",
    name: "WBHO Construction & Engineering Bursary",
    provider: "Wilson Bayly Holmes-Ovcon Limited",
    description:
      "Premier construction industry bursary for civil engineering and quantity surveying.",
    amount:
      "Full tuition + accommodation + generous stipend + site experience + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying civil engineering, quantity surveying, construction management",
      "Academic excellence (minimum 65%)",
      "Interest in construction industry",
      "Physical fitness for site work",
    ],
    applicationDeadline: "Mid-year deadline (typically June/July 2025)",
    applicationProcess: "Apply online at www.wbho.co.za/careers/bursaries",
    contactInfo: "bursaries@wbho.co.za",
    website: "https://www.wbho.co.za/careers/bursaries",
    fieldsOfStudy: [
      "Civil Engineering",
      "Quantity Surveying",
      "Construction Management",
      "Structural Engineering",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },

  // STEM, Science & Engineering
  {
    id: "csir-science-tech-2025",
    name: "CSIR Science & Technology Bursary",
    provider: "Council for Scientific and Industrial Research",
    description:
      "Prestigious bursary for science, engineering, and technology students with research focus.",
    amount:
      "Full tuition + accommodation + stipend + research allowance + mentorship + employment opportunities",
    eligibilityCriteria: [
      "South African citizen",
      "Studying science, engineering, technology, mathematics",
      "Academic excellence (minimum 70%)",
      "Research aptitude",
      "Commitment to R&D in South Africa",
    ],
    applicationDeadline: "Variable deadlines throughout the year",
    applicationProcess: "Apply online at www.csir.co.za/careers/bursaries",
    contactInfo: "bursaries@csir.co.za",
    website: "https://www.csir.co.za/careers/bursaries-and-internships",
    fieldsOfStudy: [
      "Science",
      "Engineering",
      "Technology",
      "Mathematics",
      "Computer Science",
      "Applied Sciences",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "nrf-postgrad-2025",
    name: "NRF Postgraduate Science & Social Sciences Bursary",
    provider: "National Research Foundation",
    description:
      "Comprehensive postgraduate funding for science and social sciences research.",
    amount: "Full tuition + stipend + research funding + conference allowance",
    eligibilityCriteria: [
      "South African citizen",
      "Postgraduate studies in science or social sciences",
      "Academic excellence (minimum 65% for Honours, 70% for Masters/PhD)",
      "Research proposal alignment with NRF priorities",
      "Supervisor endorsement",
    ],
    applicationDeadline: "Ongoing cycles throughout the year",
    applicationProcess: "Apply online through NRF portal",
    contactInfo: "012 481 4000 | info@nrf.ac.za",
    website: "https://www.nrf.ac.za/funding/",
    fieldsOfStudy: [
      "Science",
      "Social Sciences",
      "Research",
      "All postgraduate fields",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% for Honours, 70% for Masters/PhD",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "ikusasa-critical-skills-2025",
    name: "Ikusasa Student Financial Aid Programme",
    provider: "Ikusasa Student Financial Aid Programme",
    description:
      "Critical skills bursary focusing on engineering, health sciences, and IT.",
    amount: "Full tuition + accommodation + living allowance + study materials",
    eligibilityCriteria: [
      "South African citizen",
      "Studying critical skills: engineering, health sciences, IT, teacher training",
      "Academic merit (minimum 60%)",
      "Financial need",
      "Previously disadvantaged background preferred",
    ],
    applicationDeadline: "Variable deadlines",
    applicationProcess: "Apply through participating universities",
    contactInfo: "info@ikusasa.org.za",
    website: "https://www.ikusasa.org.za/",
    fieldsOfStudy: [
      "Engineering",
      "Health Sciences",
      "Information Technology",
      "Teacher Training",
      "Critical Skills",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "feenix-crowdfunded-2025",
    name: "Feenix Crowdfunded Bursary Programme",
    provider: "Feenix",
    description:
      "Innovative crowdfunded bursary platform for various disciplines.",
    amount: "Variable funding based on crowdfunding success + mentorship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying various disciplines",
      "Academic merit",
      "Financial need",
      "Compelling personal story",
      "Community support",
    ],
    applicationDeadline: "Ongoing applications",
    applicationProcess: "Apply online at www.feenix.org",
    contactInfo: "info@feenix.org",
    website: "https://www.feenix.org/",
    fieldsOfStudy: ["All fields"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic merit required",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "studytrust-2025",
    name: "StudyTrust Bursary Programme",
    provider: "StudyTrust",
    description:
      "Comprehensive support for disadvantaged students across multiple fields.",
    amount:
      "Full tuition + accommodation + living allowance + mentorship + career guidance",
    eligibilityCriteria: [
      "South African citizen",
      "Disadvantaged background",
      "Academic potential",
      "Financial need",
      "Multi-field study areas",
      "Leadership potential",
    ],
    applicationDeadline: "Variable deadlines",
    applicationProcess: "Apply online at www.studytrust.org.za",
    contactInfo: "info@studytrust.org.za",
    website: "https://www.studytrust.org.za/",
    fieldsOfStudy: ["All fields"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic potential demonstrated",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "jb-marks-2025",
    name: "JB Marks Education Trust Bursary",
    provider: "JB Marks Education Trust",
    description:
      "Bursary for education, engineering, and health sciences students.",
    amount: "Full tuition + accommodation + stipend + mentorship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying education, engineering, health sciences",
      "Academic merit (minimum 60%)",
      "Financial need",
      "Commitment to community development",
    ],
    applicationDeadline: "Variable deadlines",
    applicationProcess: "Apply through partner institutions",
    contactInfo: "info@jbmarks.org.za",
    website: "https://www.jbmarks.org.za/",
    fieldsOfStudy: ["Education", "Engineering", "Health Sciences"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "agsa-accounting-2025",
    name: "AGSA (Auditor-General SA) Accounting Bursary",
    provider: "Auditor-General South Africa",
    description: "Specialized bursary for accounting and auditing students.",
    amount:
      "Full tuition + accommodation + stipend + practical training + employment opportunities",
    eligibilityCriteria: [
      "South African citizen",
      "Studying accounting, auditing, finance",
      "Academic excellence (minimum 65%)",
      "Interest in public sector auditing",
      "Ethical leadership potential",
    ],
    applicationDeadline: "Deadlines unspecified - contact directly",
    applicationProcess: "Apply online at www.agsa.co.za/careers",
    contactInfo: "careers@agsa.co.za",
    website: "https://www.agsa.co.za/Careers.aspx",
    fieldsOfStudy: ["Accounting", "Auditing", "Finance"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "medium",
  },

  // Healthcare, Agriculture & Professional
  {
    id: "mediclinic-healthcare-2025",
    name: "Mediclinic Healthcare Professionals Bursary",
    provider: "Mediclinic Southern Africa",
    description:
      "Comprehensive healthcare bursary for various medical professions.",
    amount:
      "Full tuition + accommodation + stipend + practical training + employment opportunities",
    eligibilityCriteria: [
      "South African citizen",
      "Studying medicine, nursing, pharmacy, physiotherapy, radiography, medical sciences",
      "Academic excellence (minimum 65%)",
      "Commitment to healthcare excellence",
      "Agree to work for Mediclinic after graduation",
    ],
    applicationDeadline: "31 July 2025",
    applicationProcess:
      "Apply online at www.mediclinic.co.za/careers/bursaries",
    contactInfo: "bursaries@mediclinic.co.za",
    website: "https://www.mediclinic.co.za/careers/bursaries",
    fieldsOfStudy: [
      "Medicine",
      "Nursing",
      "Pharmacy",
      "Physiotherapy",
      "Radiography",
      "Medical Sciences",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "savf-veterinary-2025",
    name: "SAVF Veterinary Science Bursary",
    provider: "South African Veterinary Foundation",
    description:
      "Specialized bursary for 4th and 5th year veterinary students.",
    amount: "Partial tuition + study materials + practical training support",
    eligibilityCriteria: [
      "South African citizen",
      "4th or 5th year veterinary science students",
      "Academic merit (minimum 65%)",
      "Financial need",
      "Commitment to veterinary profession in South Africa",
    ],
    applicationDeadline: "Early June 2025",
    applicationProcess: "Apply through veterinary schools",
    contactInfo: "info@savf.co.za",
    website: "https://www.savf.co.za/bursaries",
    fieldsOfStudy: ["Veterinary Science"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "pamsa-chemical-eng-2025",
    name: "PAMSA Postgraduate Chemical Engineering Bursary",
    provider: "Paper Manufacturers Association of South Africa",
    description:
      "Specialized postgraduate bursary for chemical engineering students.",
    amount: "Full tuition + stipend + research funding + industry mentorship",
    eligibilityCriteria: [
      "South African citizen",
      "Postgraduate chemical engineering studies",
      "Academic excellence (minimum 70%)",
      "Research focus on paper/pulp industry",
      "Supervisor endorsement",
    ],
    applicationDeadline: "27 June 2025",
    applicationProcess: "Apply through chemical engineering departments",
    contactInfo: "info@pamsa.co.za",
    website: "https://www.pamsa.co.za/bursaries",
    fieldsOfStudy: ["Chemical Engineering"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "medium",
  },

  // Arts, Humanities & Other Fields
  {
    id: "allan-gray-orbis-entrepreneurship-2025",
    name: "Allan Gray Orbis Foundation Entrepreneurship Bursary",
    provider: "Allan Gray Orbis Foundation",
    description:
      "Comprehensive entrepreneurship bursary across varied fields with leadership development.",
    amount:
      "Full tuition + accommodation + generous stipend + entrepreneurship training + mentorship + network access",
    eligibilityCriteria: [
      "South African citizen",
      "Studying any field with entrepreneurial potential",
      "Academic excellence (minimum 70%)",
      "Entrepreneurial mindset",
      "Leadership potential",
      "Financial need",
    ],
    applicationDeadline: "30 April 2025",
    applicationProcess: "Apply online at www.allangrayorbis.org",
    contactInfo: "applications@allangrayorbis.org",
    website: "https://www.allangrayorbis.org/bursary-programme/",
    fieldsOfStudy: ["All fields with entrepreneurial focus"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 70% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "grand-gaming-tech-2025",
    name: "Grand Gaming Technology Bursary",
    provider: "Grand Gaming",
    description: "Specialized bursary for gaming and technology students.",
    amount:
      "Full tuition + accommodation + tech allowance + internship opportunities",
    eligibilityCriteria: [
      "South African citizen",
      "Studying gaming technology, software development, computer science, digital media",
      "Academic merit (minimum 60%)",
      "Passion for gaming industry",
      "Portfolio demonstration",
    ],
    applicationDeadline: "30 May 2025",
    applicationProcess: "Apply online with portfolio submission",
    contactInfo: "careers@grandgaming.co.za",
    website: "https://www.grandgaming.co.za/careers/bursaries",
    fieldsOfStudy: [
      "Gaming Technology",
      "Software Development",
      "Computer Science",
      "Digital Media",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "alfeco-bursary-2025",
    name: "Alfeco Bursary Programme",
    provider: "Alfeco",
    description: "General bursary programme for various fields of study.",
    amount: "Partial to full tuition + stipend",
    eligibilityCriteria: [
      "South African citizen",
      "Various fields of study",
      "Academic merit",
      "Financial need",
      "Leadership potential",
    ],
    applicationDeadline: "30 May 2025",
    applicationProcess: "Apply online at www.alfeco.co.za",
    contactInfo: "bursaries@alfeco.co.za",
    website: "https://www.alfeco.co.za/bursaries",
    fieldsOfStudy: ["Various fields"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic merit required",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },

  // Prestigious / Leadership
  {
    id: "mandela-rhodes-leadership-2025",
    name: "Mandela Rhodes Scholarship Programme",
    provider: "Mandela Rhodes Foundation",
    description:
      "Prestigious scholarship for Master's/Honours with full funding and leadership development.",
    amount:
      "Full tuition + accommodation + generous stipend + leadership programme + network access + development opportunities",
    eligibilityCriteria: [
      "African citizen under 30 years",
      "Master's or Honours studies at selected South African universities",
      "Academic excellence (minimum 75%)",
      "Leadership potential",
      "Reconciliation and social impact focus",
      "English proficiency",
    ],
    applicationDeadline: "21 April 2025",
    applicationProcess:
      "Apply online at www.mandelarhodes.org with comprehensive application",
    contactInfo: "info@mandelarhodes.org",
    website: "https://www.mandelarhodes.org/scholarships/",
    fieldsOfStudy: ["All Master's and Honours fields"],
    provinces: ["Western Cape", "Gauteng", "KwaZulu-Natal"],
    requirements: {
      academicRequirement: "Minimum 75% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "aims-google-deepmind-ai-2025",
    name: "AIMS + Google DeepMind AI/ML Scholarship",
    provider: "African Institute for Mathematical Sciences & Google DeepMind",
    description:
      "Prestigious MSc in AI/ML for African students with cutting-edge research opportunities.",
    amount:
      "Full tuition + accommodation + stipend + research funding + international exposure + networking",
    eligibilityCriteria: [
      "African citizen",
      "MSc in AI/ML or related fields",
      "Strong mathematical background",
      "Academic excellence (minimum 75%)",
      "Research potential in AI/ML",
      "Commitment to African development",
    ],
    applicationDeadline: "Around 21 March 2025",
    applicationProcess: "Apply online through AIMS with research proposal",
    contactInfo: "admissions@aims.ac.za",
    website: "https://www.aims.ac.za/programmes/",
    fieldsOfStudy: [
      "Artificial Intelligence",
      "Machine Learning",
      "Data Science",
      "Mathematical Sciences",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 75% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },

  // Technology & Telecommunications (51-70)
  {
    id: "mtn-foundation-2024",
    name: "MTN Foundation Bursary",
    provider: "MTN South Africa",
    description: "Bursary for ICT, engineering, and mathematics students.",
    amount: "Full tuition + accommodation + allowances + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying ICT, engineering, mathematics, science",
      "Academic excellence (minimum 65%)",
      "Financial need",
      "Leadership potential",
    ],
    applicationDeadline: "30 June 2024",
    applicationProcess: "Apply online at www.mtn.co.za/foundation",
    contactInfo: "foundation@mtn.co.za",
    website: "https://www.mtn.co.za/foundation",
    fieldsOfStudy: [
      "Information Technology",
      "Engineering",
      "Mathematics",
      "Science",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "vodacom-foundation-2024",
    name: "Vodacom Foundation Bursary",
    provider: "Vodacom Group Limited",
    description: "Bursary for ICT and related technical fields.",
    amount: "Full tuition + accommodation + stipend + mentorship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying ICT, telecommunications, engineering, mathematics",
      "Academic merit (minimum 60%)",
      "Financial need",
      "Previously disadvantaged individuals preferred",
    ],
    applicationDeadline: "31 July 2024",
    applicationProcess: "Apply online at www.vodacom.co.za/foundation",
    contactInfo: "foundation@vodacom.co.za",
    website: "https://www.vodacom.co.za/foundation",
    fieldsOfStudy: [
      "Information Technology",
      "Telecommunications",
      "Engineering",
      "Mathematics",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "telkom-foundation-2024",
    name: "Telkom Foundation Bursary",
    provider: "Telkom SA SOC Limited",
    description:
      "Bursary for telecommunications, ICT, and engineering students.",
    amount: "Full tuition + accommodation + allowances + vacation work",
    eligibilityCriteria: [
      "South African citizen",
      "Studying telecommunications, ICT, electrical engineering",
      "Strong academic performance (minimum 65%)",
      "Financial need",
      "Agree to work for Telkom after graduation",
    ],
    applicationDeadline: "31 August 2024",
    applicationProcess: "Apply online at www.telkom.co.za/foundation",
    contactInfo: "foundation@telkom.co.za",
    website: "https://www.telkom.co.za/foundation",
    fieldsOfStudy: [
      "Telecommunications",
      "Information Technology",
      "Electrical Engineering",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
];

// Import additional valid bursaries
import {
  ADDITIONAL_VALID_BURSARIES,
  COMPREHENSIVE_FIELDS_OF_STUDY,
  BURSARY_PROVIDERS,
} from "./validBursaries";

// Combine all bursaries
export const ALL_BURSARIES: Bursary[] = [
  ...ENHANCED_BURSARIES,
  ...ADDITIONAL_BURSARIES,
  ...ADDITIONAL_VALID_BURSARIES,
];

// Export as BURSARIES for backward compatibility
export const BURSARIES = ALL_BURSARIES;

export const BURSARY_CATEGORIES = [
  "Government & Public Sector",
  "Corporate & Industry",
  "Banking & Finance",
  "Mining & Resources",
  "Technology & Telecommunications",
  "Healthcare & Medical",
  "Education & Teaching",
  "Engineering & Technical",
  "Agriculture & Environment",
  "Professional Organizations",
  "STEM & Science",
  "Insurance & Actuarial",
  "Construction & Infrastructure",
  "Retail & Consumer",
  "Arts & Humanities",
  "Prestigious & Leadership",
];

// Use comprehensive fields of study
export const BURSARY_FIELDS_OF_STUDY = COMPREHENSIVE_FIELDS_OF_STUDY;

export const PROVINCES = [
  "All provinces",
  "Eastern Cape",
  "Free State",
  "Gauteng",
  "KwaZulu-Natal",
  "Limpopo",
  "Mpumalanga",
  "Northern Cape",
  "North West",
  "Western Cape",
];
