import { Bursary } from "@/types/university";

export const ENHANCED_BURSARIES: Bursary[] = [
  // Updated Government Bursaries (1-15)
  {
    id: "nsfas-2024",
    name: "NSFAS (National Student Financial Aid Scheme)",
    provider: "Department of Higher Education and Training",
    description:
      "Government financial aid for South African students from poor and working-class families.",
    amount:
      "Full tuition + accommodation + meal allowance + book allowance + transport allowance",
    eligibilityCriteria: [
      "South African citizen",
      "Combined annual household income ≤ R350,000",
      "SASSA grant recipient qualifies regardless of household income",
      "Must be studying at a public university or TVET college",
      "Must pass at least 75% of modules per year to continue funding",
    ],
    applicationDeadline: "31 January 2025",
    applicationProcess: "Apply online at www.nsfas.org.za",
    contactInfo: "08000 67327 | info@nsfas.org.za",
    website: "https://www.nsfas.org.za",
    fieldsOfStudy: ["All fields"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "NSC pass with admission to higher education",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "funza-lushaka-2024",
    name: "Funza Lushaka Teaching Bursary",
    provider: "Department of Basic Education",
    description:
      "Bursary for students studying to become teachers in public schools.",
    amount:
      "Full tuition + accommodation + meal allowance + book allowance + transport allowance",
    eligibilityCriteria: [
      "South African citizen",
      "Studying Initial Teacher Education qualifications",
      "Agree to teach in public schools for same number of years as bursary received",
      "Maintain good academic standing",
    ],
    applicationDeadline: "31 January 2025",
    applicationProcess: "Apply online at www.funzalushaka.doe.gov.za",
    contactInfo: "0800 202 933 | bursaries@dbe.gov.za",
    website: "https://www.funzalushaka.doe.gov.za",
    fieldsOfStudy: ["Education", "Teaching"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "NSC pass with admission to education programs",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "dpsa-public-admin-2024",
    name: "DPSA Public Administration Bursary",
    provider: "Department of Public Service and Administration",
    description:
      "Bursary for students pursuing public administration and related qualifications.",
    amount: "Full tuition + accommodation + stipend",
    eligibilityCriteria: [
      "South African citizen",
      "Studying public administration, public management, development studies",
      "Agree to work in public service after graduation",
      "Academic merit and financial need",
    ],
    applicationDeadline: "30 September 2024",
    applicationProcess: "Apply online at www.dpsa.gov.za",
    contactInfo: "012 336 1000 | info@dpsa.gov.za",
    website: "https://www.dpsa.gov.za",
    fieldsOfStudy: [
      "Public Administration",
      "Management",
      "Development Studies",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Good academic performance",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "doh-health-sciences-2024",
    name: "Department of Health Bursary",
    provider: "Department of Health",
    description: "Bursary for students in health sciences fields.",
    amount: "Full tuition + accommodation + stipend",
    eligibilityCriteria: [
      "South African citizen",
      "Studying medicine, nursing, pharmacy, dentistry, allied health",
      "Agree to work in public health sector after graduation",
      "Academic excellence and financial need",
    ],
    applicationDeadline: "31 August 2024",
    applicationProcess: "Apply through provincial health departments",
    contactInfo: "012 395 8000 | info@health.gov.za",
    website: "https://www.health.gov.za",
    fieldsOfStudy: [
      "Medicine",
      "Nursing",
      "Pharmacy",
      "Dentistry",
      "Health Sciences",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Strong academic performance",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "dsi-scarce-skills-2024",
    name: "DSI Scarce Skills Bursary",
    provider: "Department of Science and Innovation",
    description: "Bursary for STEM fields and scarce skills areas.",
    amount: "Full tuition + accommodation + stipend + research allowance",
    eligibilityCriteria: [
      "South African citizen",
      "Studying in STEM fields (Science, Technology, Engineering, Mathematics)",
      "Academic excellence",
      "Commitment to contribute to South Africa's innovation system",
    ],
    applicationDeadline: "31 July 2024",
    applicationProcess: "Apply online at www.dst.gov.za",
    contactInfo: "012 843 6300 | info@dst.gov.za",
    website: "https://www.dst.gov.za",
    fieldsOfStudy: [
      "Science",
      "Technology",
      "Engineering",
      "Mathematics",
      "Innovation",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic excellence",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },

  // Banking & Financial Services (16-35)
  {
    id: "absa-bursary-2024",
    name: "Absa Group Bursary Programme",
    provider: "Absa Group Limited",
    description:
      "Comprehensive bursary for commerce, IT, and risk management students.",
    amount: "Full tuition + accommodation + stipend + vacation work",
    eligibilityCriteria: [
      "South African citizen",
      "Studying commerce, accounting, economics, IT, risk management",
      "Academic excellence (minimum 65% average)",
      "Financial need",
      "Leadership potential",
    ],
    applicationDeadline: "31 May 2024",
    applicationProcess: "Apply online at www.absa.co.za/careers/bursaries",
    contactInfo: "bursaries@absa.co.za",
    website: "https://www.absa.co.za/careers/bursaries",
    fieldsOfStudy: [
      "Commerce",
      "Accounting",
      "Economics",
      "Information Technology",
      "Risk Management",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "standard-bank-2024",
    name: "Standard Bank Bursary Programme",
    provider: "Standard Bank Group",
    description: "Bursary for banking, finance, and technology students.",
    amount: "Full tuition + accommodation + allowances + mentorship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying commerce, accounting, economics, IT, mathematics",
      "Strong academic performance (minimum 60%)",
      "Financial need",
      "Previously disadvantaged individuals preferred",
    ],
    applicationDeadline: "30 June 2024",
    applicationProcess:
      "Apply online at www.standardbank.co.za/careers/bursaries",
    contactInfo: "bursaries@standardbank.co.za",
    website: "https://www.standardbank.co.za/careers/bursaries",
    fieldsOfStudy: [
      "Commerce",
      "Accounting",
      "Economics",
      "Information Technology",
      "Mathematics",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "firstrand-2024",
    name: "FirstRand Foundation Bursary",
    provider: "FirstRand Limited",
    description: "Bursary for commerce, mathematics, and technology students.",
    amount: "Full tuition + accommodation + stipend + leadership development",
    eligibilityCriteria: [
      "South African citizen",
      "Studying commerce, mathematics, actuarial science, IT",
      "Academic merit (minimum 65%)",
      "Financial need",
      "Leadership qualities",
    ],
    applicationDeadline: "31 July 2024",
    applicationProcess: "Apply online at www.firstrand.co.za/foundation",
    contactInfo: "foundation@firstrand.co.za",
    website: "https://www.firstrand.co.za/foundation",
    fieldsOfStudy: [
      "Commerce",
      "Mathematics",
      "Actuarial Science",
      "Information Technology",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "nedbank-2024",
    name: "Nedbank Foundation Bursary",
    provider: "Nedbank Group",
    description: "Bursary for commerce, IT, and finance students.",
    amount: "Full tuition + accommodation + allowances + mentorship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying commerce, accounting, IT, finance, economics",
      "Academic excellence (minimum 65%)",
      "Financial need",
      "Community involvement",
    ],
    applicationDeadline: "31 August 2024",
    applicationProcess: "Apply online at www.nedbank.co.za/foundation",
    contactInfo: "foundation@nedbank.co.za",
    website: "https://www.nedbank.co.za/foundation",
    fieldsOfStudy: [
      "Commerce",
      "Accounting",
      "Information Technology",
      "Finance",
      "Economics",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "investec-2024",
    name: "Investec Foundation Bursary",
    provider: "Investec Limited",
    description: "Bursary for finance, economics, and business students.",
    amount: "Full tuition + accommodation + stipend + internship opportunities",
    eligibilityCriteria: [
      "South African citizen",
      "Studying finance, economics, accounting, actuarial science",
      "Academic excellence (minimum 70%)",
      "Financial need",
      "Leadership potential",
    ],
    applicationDeadline: "31 May 2024",
    applicationProcess: "Apply online at www.investec.com/foundation",
    contactInfo: "foundation@investec.co.za",
    website: "https://www.investec.com/foundation",
    fieldsOfStudy: ["Finance", "Economics", "Accounting", "Actuarial Science"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 70% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },

  // Mining & Resources (36-50)
  {
    id: "anglo-american-2024",
    name: "Anglo American Bursary Programme",
    provider: "Anglo American plc",
    description:
      "Comprehensive bursary for mining, engineering, and related fields.",
    amount:
      "Full tuition + accommodation + stipend + vacation work + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying mining engineering, geology, metallurgy, mechanical/electrical engineering",
      "Academic excellence (minimum 65%)",
      "Leadership potential",
      "Agree to work for Anglo American after graduation",
    ],
    applicationDeadline: "31 March 2024",
    applicationProcess:
      "Apply online at www.angloamerican.com/careers/bursaries",
    contactInfo: "bursaries@angloamerican.com",
    website: "https://www.angloamerican.com/careers/bursaries",
    fieldsOfStudy: [
      "Mining Engineering",
      "Geology",
      "Metallurgy",
      "Mechanical Engineering",
      "Electrical Engineering",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "sasol-2024",
    name: "Sasol Bursary Programme",
    provider: "Sasol Limited",
    description:
      "Comprehensive bursary for engineering, science, and technology students.",
    amount:
      "Full tuition + accommodation + meals + books + transport + personal allowance + vacation work",
    eligibilityCriteria: [
      "South African citizen",
      "Studying chemical, mechanical, electrical, or industrial engineering",
      "Chemistry, Mathematics, Physics, Computer Science",
      "Minimum 65% average in Grade 11 and 12",
      "Agree to work for Sasol after graduation",
    ],
    applicationDeadline: "30 April 2024",
    applicationProcess: "Apply online at www.sasol.com/careers/bursaries",
    contactInfo: "bursaries@sasol.com",
    website: "https://www.sasol.com/careers/bursaries",
    fieldsOfStudy: [
      "Chemical Engineering",
      "Mechanical Engineering",
      "Electrical Engineering",
      "Chemistry",
      "Computer Science",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "gold-fields-2024",
    name: "Gold Fields Bursary Programme",
    provider: "Gold Fields Limited",
    description: "Bursary for mining and engineering students.",
    amount:
      "Full tuition + accommodation + stipend + vacation work + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying mining engineering, geology, metallurgy, electrical/mechanical engineering",
      "Academic excellence (minimum 65%)",
      "Agree to work for Gold Fields after graduation",
    ],
    applicationDeadline: "31 March 2024",
    applicationProcess: "Apply online at www.goldfields.com/careers/bursaries",
    contactInfo: "bursaries@goldfields.com",
    website: "https://www.goldfields.com/careers/bursaries",
    fieldsOfStudy: [
      "Mining Engineering",
      "Geology",
      "Metallurgy",
      "Electrical Engineering",
      "Mechanical Engineering",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "harmony-gold-2024",
    name: "Harmony Gold Mining Bursary",
    provider: "Harmony Gold Mining Company Limited",
    description: "Bursary for mining-related studies.",
    amount: "Full tuition + accommodation + allowances + vacation work",
    eligibilityCriteria: [
      "South African citizen",
      "Studying mining engineering, geology, metallurgy",
      "Strong academic performance (minimum 60%)",
      "From mining communities preferred",
      "Agree to work for Harmony Gold after graduation",
    ],
    applicationDeadline: "30 April 2024",
    applicationProcess: "Apply online at www.harmony.co.za/careers/bursaries",
    contactInfo: "bursaries@harmony.co.za",
    website: "https://www.harmony.co.za/careers/bursaries",
    fieldsOfStudy: ["Mining Engineering", "Geology", "Metallurgy"],
    provinces: ["Free State", "Gauteng", "North West"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "eskom-2024",
    name: "Eskom Development Foundation Bursary",
    provider: "Eskom Holdings SOC Ltd",
    description:
      "Bursary for students in engineering and scarce skills fields.",
    amount: "Tuition + accommodation + meals + books + transport + stipend",
    eligibilityCriteria: [
      "South African citizen",
      "Studying engineering (electrical, mechanical, civil, industrial)",
      "Science, technology, and other scarce skills",
      "Good academic performance (minimum 60%)",
      "Financial need",
    ],
    applicationDeadline: "31 March 2024",
    applicationProcess: "Apply online through university financial aid offices",
    contactInfo: "011 800 8111 | bursaries@eskom.co.za",
    website: "https://www.eskom.co.za/careers/bursaries",
    fieldsOfStudy: [
      "Electrical Engineering",
      "Mechanical Engineering",
      "Civil Engineering",
      "Industrial Engineering",
      "Science",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
];

// Continue with more bursaries to reach 100+...
export const ADDITIONAL_BURSARIES: Bursary[] = [
  // Technology & Telecommunications (51-70)
  {
    id: "mtn-foundation-2024",
    name: "MTN Foundation Bursary",
    provider: "MTN South Africa",
    description: "Bursary for ICT, engineering, and mathematics students.",
    amount: "Full tuition + accommodation + allowances + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying ICT, engineering, mathematics, science",
      "Academic excellence (minimum 65%)",
      "Financial need",
      "Leadership potential",
    ],
    applicationDeadline: "30 June 2024",
    applicationProcess: "Apply online at www.mtn.co.za/foundation",
    contactInfo: "foundation@mtn.co.za",
    website: "https://www.mtn.co.za/foundation",
    fieldsOfStudy: [
      "Information Technology",
      "Engineering",
      "Mathematics",
      "Science",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "vodacom-foundation-2024",
    name: "Vodacom Foundation Bursary",
    provider: "Vodacom Group Limited",
    description: "Bursary for ICT and related technical fields.",
    amount: "Full tuition + accommodation + stipend + mentorship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying ICT, telecommunications, engineering, mathematics",
      "Academic merit (minimum 60%)",
      "Financial need",
      "Previously disadvantaged individuals preferred",
    ],
    applicationDeadline: "31 July 2024",
    applicationProcess: "Apply online at www.vodacom.co.za/foundation",
    contactInfo: "foundation@vodacom.co.za",
    website: "https://www.vodacom.co.za/foundation",
    fieldsOfStudy: [
      "Information Technology",
      "Telecommunications",
      "Engineering",
      "Mathematics",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "telkom-foundation-2024",
    name: "Telkom Foundation Bursary",
    provider: "Telkom SA SOC Limited",
    description:
      "Bursary for telecommunications, ICT, and engineering students.",
    amount: "Full tuition + accommodation + allowances + vacation work",
    eligibilityCriteria: [
      "South African citizen",
      "Studying telecommunications, ICT, electrical engineering",
      "Strong academic performance (minimum 65%)",
      "Financial need",
      "Agree to work for Telkom after graduation",
    ],
    applicationDeadline: "31 August 2024",
    applicationProcess: "Apply online at www.telkom.co.za/foundation",
    contactInfo: "foundation@telkom.co.za",
    website: "https://www.telkom.co.za/foundation",
    fieldsOfStudy: [
      "Telecommunications",
      "Information Technology",
      "Electrical Engineering",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
];

// Import additional valid bursaries
import {
  ADDITIONAL_VALID_BURSARIES,
  COMPREHENSIVE_FIELDS_OF_STUDY,
  BURSARY_PROVIDERS,
} from "./validBursaries";

// Combine all bursaries
export const ALL_BURSARIES: Bursary[] = [
  ...ENHANCED_BURSARIES,
  ...ADDITIONAL_BURSARIES,
  ...ADDITIONAL_VALID_BURSARIES,
];

// Export as BURSARIES for backward compatibility
export const BURSARIES = ALL_BURSARIES;

export const BURSARY_CATEGORIES = [
  "Government Bursaries",
  "Corporate Bursaries",
  "Banking & Finance",
  "Mining & Resources",
  "Technology & Telecommunications",
  "Healthcare & Medical",
  "Education & Teaching",
  "Engineering & Technical",
  "Agriculture & Environment",
  "Professional Organizations",
];

export const BURSARY_FIELDS_OF_STUDY = [
  "All fields",
  "Accounting",
  "Actuarial Science",
  "Agriculture",
  "Business",
  "Commerce",
  "Computer Science",
  "Counselling",
  "Economics",
  "Education",
  "Engineering",
  "Finance",
  "Forestry",
  "Health Sciences",
  "Information Technology",
  "Law",
  "Logistics",
  "Mathematics",
  "Medicine",
  "Mining Engineering",
  "Nursing",
  "Psychology",
  "Science",
  "Teaching",
  "Technology",
];

export const PROVINCES = [
  "All provinces",
  "Eastern Cape",
  "Free State",
  "Gauteng",
  "KwaZulu-Natal",
  "Limpopo",
  "Mpumalanga",
  "Northern Cape",
  "North West",
  "Western Cape",
];
