import { Bursary } from "@/types/university";

export const BURSARIES: Bursary[] = [
  // Government Bursaries
  {
    id: "nsfas",
    name: "NSFAS (National Student Financial Aid Scheme)",
    provider: "Department of Higher Education and Training",
    description:
      "Government financial aid for South African students from poor and working-class families.",
    amount:
      "Full tuition + accommodation + meal allowance + book allowance + transport allowance",
    eligibilityCriteria: [
      "South African citizen",
      "Combined annual household income ≤ R350,000",
      "SASSA grant recipient qualifies regardless of household income",
      "Must be studying at a public university or TVET college",
      "Must pass at least 75% of modules per year to continue funding",
    ],
    applicationDeadline: "31 January annually",
    applicationProcess: "Apply online at www.nsfas.org.za",
    contactInfo: "08000 67327 | info@nsfas.org.za",
    website: "https://www.nsfas.org.za",
    fieldsOfStudy: ["All fields"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "NSC pass with admission to higher education",
      financialNeed: true,
    },
  },
  {
    id: "funza-lushaka",
    name: "Funza Lushaka Bursary",
    provider: "Department of Basic Education",
    description:
      "Bursary for students studying to become teachers in public schools.",
    amount:
      "Full tuition + accommodation + meal allowance + book allowance + transport allowance",
    eligibilityCriteria: [
      "South African citizen",
      "Studying Initial Teacher Education qualifications",
      "Agree to teach in public schools for same number of years as bursary received",
      "Maintain good academic standing",
    ],
    applicationDeadline: "31 January annually",
    applicationProcess: "Apply online at www.funzalushaka.doe.gov.za",
    contactInfo: "0800 202 933 | bursaries@dbe.gov.za",
    website: "https://www.funzalushaka.doe.gov.za",
    fieldsOfStudy: ["Education", "Teaching"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "NSC pass with admission to education programs",
      financialNeed: false,
    },
  },
  {
    id: "dpsa-bursary",
    name: "DPSA Public Administration Bursary",
    provider: "Department of Public Service and Administration",
    description:
      "Bursary for students pursuing public administration and related qualifications.",
    amount: "Full tuition + accommodation + stipend",
    eligibilityCriteria: [
      "South African citizen",
      "Studying public administration, public management, development studies",
      "Agree to work in public service after graduation",
      "Academic merit and financial need",
    ],
    applicationDeadline: "30 September annually",
    applicationProcess: "Apply online at www.dpsa.gov.za",
    contactInfo: "012 336 1000 | info@dpsa.gov.za",
    website: "https://www.dpsa.gov.za",
    fieldsOfStudy: [
      "Public Administration",
      "Management",
      "Development Studies",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Good academic performance",
      financialNeed: true,
    },
  },
  {
    id: "doh-health-bursary",
    name: "Department of Health Bursary",
    provider: "Department of Health",
    description: "Bursary for students in health sciences fields.",
    amount: "Full tuition + accommodation + stipend",
    eligibilityCriteria: [
      "South African citizen",
      "Studying medicine, nursing, pharmacy, dentistry, allied health",
      "Agree to work in public health sector after graduation",
      "Academic excellence and financial need",
    ],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply through provincial health departments",
    contactInfo: "012 395 8000 | info@health.gov.za",
    website: "https://www.health.gov.za",
    fieldsOfStudy: [
      "Medicine",
      "Nursing",
      "Pharmacy",
      "Dentistry",
      "Health Sciences",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Strong academic performance",
      financialNeed: true,
    },
  },
  {
    id: "dsi-scarce-skills",
    name: "DSI Scarce Skills Bursary",
    provider: "Department of Science and Innovation",
    description: "Bursary for STEM fields and scarce skills areas.",
    amount: "Full tuition + accommodation + stipend + research allowance",
    eligibilityCriteria: [
      "South African citizen",
      "Studying in STEM fields (Science, Technology, Engineering, Mathematics)",
      "Academic excellence",
      "Commitment to contribute to South Africa's innovation system",
    ],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply online at www.dst.gov.za",
    contactInfo: "012 843 6300 | info@dst.gov.za",
    website: "https://www.dst.gov.za",
    fieldsOfStudy: [
      "Science",
      "Technology",
      "Engineering",
      "Mathematics",
      "Innovation",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic excellence",
      financialNeed: false,
    },
  },
  {
    id: "daff-agriculture",
    name: "DAFF Agriculture Bursary",
    provider: "Department of Agriculture, Forestry and Fisheries",
    description: "Bursary for agriculture, forestry, and fisheries students.",
    amount: "Full tuition + accommodation + stipend",
    eligibilityCriteria: [
      "South African citizen",
      "Studying agriculture, forestry, fisheries, veterinary science",
      "Agree to work in agricultural sector after graduation",
      "Rural background preferred",
    ],
    applicationDeadline: "30 June annually",
    applicationProcess: "Apply online at www.daff.gov.za",
    contactInfo: "012 319 7000 | info@daff.gov.za",
    website: "https://www.daff.gov.za",
    fieldsOfStudy: [
      "Agriculture",
      "Forestry",
      "Fisheries",
      "Veterinary Science",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Good academic performance",
      financialNeed: true,
    },
  },
  {
    id: "sars-bursary",
    name: "SARS Tax Administration Bursary",
    provider: "South African Revenue Service",
    description: "Bursary for students in tax, accounting, and related fields.",
    amount: "Full tuition + accommodation + stipend",
    eligibilityCriteria: [
      "South African citizen",
      "Studying accounting, economics, law, mathematics, IT",
      "Agree to work for SARS after graduation",
      "Academic merit",
    ],
    applicationDeadline: "31 October annually",
    applicationProcess: "Apply online at www.sars.gov.za",
    contactInfo: "0800 00 7277 | info@sars.gov.za",
    website: "https://www.sars.gov.za",
    fieldsOfStudy: [
      "Accounting",
      "Economics",
      "Law",
      "Mathematics",
      "Information Technology",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Good academic performance",
      financialNeed: false,
    },
  },

  // Corporate Bursaries
  {
    id: "sasol-bursary",
    name: "Sasol Bursary Programme",
    provider: "Sasol",
    description:
      "Comprehensive bursary for engineering, science, and technology students.",
    amount:
      "Full tuition + accommodation + meals + books + transport + personal allowance",
    eligibilityCriteria: [
      "South African citizen",
      "Studying chemical, mechanical, electrical, or industrial engineering",
      "Chemistry, Mathematics, Physics, Computer Science",
      "Minimum 65% average in Grade 11 and 12",
      "Agree to work for Sasol after graduation",
    ],
    applicationDeadline: "30 April annually",
    applicationProcess: "Apply online at www.sasol.com/careers/bursaries",
    contactInfo: "bursaries@sasol.com",
    website: "https://www.sasol.com",
    fieldsOfStudy: ["Engineering", "Science", "Technology", "Chemistry"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
  },
  {
    id: "anglo-american",
    name: "Anglo American Bursary",
    provider: "Anglo American",
    description: "Bursary for mining, engineering, and related fields.",
    amount: "Full tuition + accommodation + stipend + vacation work",
    eligibilityCriteria: [
      "South African citizen",
      "Studying mining engineering, geology, metallurgy, mechanical engineering",
      "Strong academic performance",
      "Leadership potential",
      "Agree to work for Anglo American after graduation",
    ],
    applicationDeadline: "31 March annually",
    applicationProcess:
      "Apply online at www.angloamerican.com/careers/bursaries",
    contactInfo: "bursaries@angloamerican.com",
    website: "https://www.angloamerican.com",
    fieldsOfStudy: [
      "Mining Engineering",
      "Geology",
      "Metallurgy",
      "Engineering",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Strong academic performance",
      financialNeed: false,
    },
  },
  {
    id: "eskom-bursary",
    name: "Eskom Development Foundation Bursary",
    provider: "Eskom",
    description:
      "Bursary for students in engineering and scarce skills fields.",
    amount: "Tuition + accommodation + meals + books + transport",
    eligibilityCriteria: [
      "South African citizen",
      "Studying engineering (electrical, mechanical, civil, industrial)",
      "Science, technology, and other scarce skills",
      "Good academic performance",
      "Financial need",
    ],
    applicationDeadline: "31 March annually",
    applicationProcess: "Apply online through university financial aid offices",
    contactInfo: "011 800 8111 | bursaries@eskom.co.za",
    website: "https://www.eskom.co.za",
    fieldsOfStudy: ["Engineering", "Science", "Technology"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Good academic performance",
      financialNeed: true,
    },
  },
  {
    id: "mtn-bursary",
    name: "MTN Foundation Bursary",
    provider: "MTN South Africa",
    description: "Bursary for ICT, engineering, and mathematics students.",
    amount: "Full tuition + accommodation + allowances",
    eligibilityCriteria: [
      "South African citizen",
      "Studying ICT, engineering, mathematics, science",
      "Academic excellence",
      "Financial need",
      "Leadership potential",
    ],
    applicationDeadline: "30 June annually",
    applicationProcess: "Apply online at www.mtn.co.za/foundation",
    contactInfo: "foundation@mtn.co.za",
    website: "https://www.mtn.co.za",
    fieldsOfStudy: [
      "Information Technology",
      "Engineering",
      "Mathematics",
      "Science",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic excellence",
      financialNeed: true,
    },
  },
  {
    id: "vodacom-bursary",
    name: "Vodacom Foundation Bursary",
    provider: "Vodacom",
    description: "Bursary for ICT and related technical fields.",
    amount: "Full tuition + accommodation + stipend",
    eligibilityCriteria: [
      "South African citizen",
      "Studying ICT, telecommunications, engineering, mathematics",
      "Academic merit",
      "Financial need",
      "Previously disadvantaged individuals preferred",
    ],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply online at www.vodacom.co.za/foundation",
    contactInfo: "foundation@vodacom.co.za",
    website: "https://www.vodacom.co.za",
    fieldsOfStudy: [
      "Information Technology",
      "Telecommunications",
      "Engineering",
      "Mathematics",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic merit",
      financialNeed: true,
    },
  },
  {
    id: "telkom-bursary",
    name: "Telkom Foundation Bursary",
    provider: "Telkom",
    description:
      "Bursary for telecommunications, ICT, and engineering students.",
    amount: "Full tuition + accommodation + allowances",
    eligibilityCriteria: [
      "South African citizen",
      "Studying telecommunications, ICT, electrical engineering",
      "Strong academic performance",
      "Financial need",
      "Agree to work for Telkom after graduation",
    ],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply online at www.telkom.co.za/foundation",
    contactInfo: "foundation@telkom.co.za",
    website: "https://www.telkom.co.za",
    fieldsOfStudy: [
      "Telecommunications",
      "Information Technology",
      "Electrical Engineering",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Strong academic performance",
      financialNeed: true,
    },
  },
  {
    id: "transnet-bursary",
    name: "Transnet Bursary Programme",
    provider: "Transnet",
    description: "Bursary for engineering and logistics students.",
    amount: "Full tuition + accommodation + stipend + vacation work",
    eligibilityCriteria: [
      "South African citizen",
      "Studying mechanical, electrical, civil, industrial engineering",
      "Logistics, supply chain management",
      "Academic excellence",
      "Agree to work for Transnet after graduation",
    ],
    applicationDeadline: "30 September annually",
    applicationProcess: "Apply online at www.transnet.net/careers/bursaries",
    contactInfo: "bursaries@transnet.net",
    website: "https://www.transnet.net",
    fieldsOfStudy: ["Engineering", "Logistics", "Supply Chain Management"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic excellence",
      financialNeed: false,
    },
  },

  // Banking Sector Bursaries
  {
    id: "absa-bursary",
    name: "Absa Group Bursary",
    provider: "Absa Group",
    description: "Bursary for commerce, IT, and risk management students.",
    amount: "Full tuition + accommodation + stipend",
    eligibilityCriteria: [
      "South African citizen",
      "Studying commerce, accounting, economics, IT, risk management",
      "Academic excellence",
      "Financial need",
      "Leadership potential",
    ],
    applicationDeadline: "31 May annually",
    applicationProcess: "Apply online at www.absa.co.za/careers/bursaries",
    contactInfo: "bursaries@absa.co.za",
    website: "https://www.absa.co.za",
    fieldsOfStudy: [
      "Commerce",
      "Accounting",
      "Economics",
      "Information Technology",
      "Risk Management",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic excellence",
      financialNeed: true,
    },
  },
  {
    id: "standard-bank",
    name: "Standard Bank Bursary",
    provider: "Standard Bank",
    description: "Bursary for banking, finance, and technology students.",
    amount: "Full tuition + accommodation + allowances",
    eligibilityCriteria: [
      "South African citizen",
      "Studying commerce, accounting, economics, IT, mathematics",
      "Strong academic performance",
      "Financial need",
      "Previously disadvantaged individuals preferred",
    ],
    applicationDeadline: "30 June annually",
    applicationProcess:
      "Apply online at www.standardbank.co.za/careers/bursaries",
    contactInfo: "bursaries@standardbank.co.za",
    website: "https://www.standardbank.co.za",
    fieldsOfStudy: [
      "Commerce",
      "Accounting",
      "Economics",
      "Information Technology",
      "Mathematics",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Strong academic performance",
      financialNeed: true,
    },
  },
  {
    id: "firstrand-bursary",
    name: "FirstRand Foundation Bursary",
    provider: "FirstRand",
    description: "Bursary for commerce, mathematics, and technology students.",
    amount: "Full tuition + accommodation + stipend",
    eligibilityCriteria: [
      "South African citizen",
      "Studying commerce, mathematics, actuarial science, IT",
      "Academic merit",
      "Financial need",
      "Leadership qualities",
    ],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply online at www.firstrand.co.za/foundation",
    contactInfo: "foundation@firstrand.co.za",
    website: "https://www.firstrand.co.za",
    fieldsOfStudy: [
      "Commerce",
      "Mathematics",
      "Actuarial Science",
      "Information Technology",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic merit",
      financialNeed: true,
    },
  },
  {
    id: "nedbank-bursary",
    name: "Nedbank Foundation Bursary",
    provider: "Nedbank",
    description: "Bursary for commerce, IT, and finance students.",
    amount: "Full tuition + accommodation + allowances",
    eligibilityCriteria: [
      "South African citizen",
      "Studying commerce, accounting, IT, finance, economics",
      "Academic excellence",
      "Financial need",
      "Community involvement",
    ],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply online at www.nedbank.co.za/foundation",
    contactInfo: "foundation@nedbank.co.za",
    website: "https://www.nedbank.co.za",
    fieldsOfStudy: [
      "Commerce",
      "Accounting",
      "Information Technology",
      "Finance",
      "Economics",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic excellence",
      financialNeed: true,
    },
  },

  // Retail and Consumer Bursaries
  {
    id: "shoprite-bursary",
    name: "Shoprite Foundation Bursary",
    provider: "Shoprite Holdings",
    description: "Bursary for commerce, retail management, and related fields.",
    amount: "Full tuition + accommodation + stipend",
    eligibilityCriteria: [
      "South African citizen",
      "Studying commerce, retail management, supply chain, marketing",
      "Academic merit",
      "Financial need",
      "Interest in retail industry",
    ],
    applicationDeadline: "30 September annually",
    applicationProcess: "Apply online at www.shopriteholdings.co.za/foundation",
    contactInfo: "foundation@shoprite.co.za",
    website: "https://www.shopriteholdings.co.za",
    fieldsOfStudy: [
      "Commerce",
      "Retail Management",
      "Supply Chain",
      "Marketing",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic merit",
      financialNeed: true,
    },
  },
  {
    id: "woolworths-bursary",
    name: "Woolworths Foundation Bursary",
    provider: "Woolworths",
    description: "Bursary for fashion, retail, and business students.",
    amount: "Full tuition + accommodation + allowances",
    eligibilityCriteria: [
      "South African citizen",
      "Studying fashion design, retail management, business, marketing",
      "Academic excellence",
      "Creative potential",
      "Financial need",
    ],
    applicationDeadline: "31 July annually",
    applicationProcess:
      "Apply online at www.woolworthsholdings.co.za/foundation",
    contactInfo: "foundation@woolworths.co.za",
    website: "https://www.woolworthsholdings.co.za",
    fieldsOfStudy: [
      "Fashion Design",
      "Retail Management",
      "Business",
      "Marketing",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic excellence",
      financialNeed: true,
    },
  },

  // Mining Industry Bursaries
  {
    id: "gold-fields-bursary",
    name: "Gold Fields Bursary",
    provider: "Gold Fields",
    description: "Bursary for mining and engineering students.",
    amount: "Full tuition + accommodation + stipend + vacation work",
    eligibilityCriteria: [
      "South African citizen",
      "Studying mining engineering, geology, metallurgy, electrical engineering",
      "Academic excellence",
      "Agree to work for Gold Fields after graduation",
    ],
    applicationDeadline: "31 March annually",
    applicationProcess: "Apply online at www.goldfields.com/careers/bursaries",
    contactInfo: "bursaries@goldfields.com",
    website: "https://www.goldfields.com",
    fieldsOfStudy: [
      "Mining Engineering",
      "Geology",
      "Metallurgy",
      "Electrical Engineering",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic excellence",
      financialNeed: false,
    },
  },
  {
    id: "harmony-gold-bursary",
    name: "Harmony Gold Bursary",
    provider: "Harmony Gold Mining",
    description: "Bursary for mining-related studies.",
    amount: "Full tuition + accommodation + allowances",
    eligibilityCriteria: [
      "South African citizen",
      "Studying mining engineering, geology, metallurgy",
      "Strong academic performance",
      "From mining communities preferred",
      "Agree to work for Harmony Gold after graduation",
    ],
    applicationDeadline: "30 April annually",
    applicationProcess: "Apply online at www.harmony.co.za/careers/bursaries",
    contactInfo: "bursaries@harmony.co.za",
    website: "https://www.harmony.co.za",
    fieldsOfStudy: ["Mining Engineering", "Geology", "Metallurgy"],
    provinces: ["Free State", "Gauteng", "North West"],
    requirements: {
      academicRequirement: "Strong academic performance",
      financialNeed: false,
    },
  },

  // Investment and Financial Services
  {
    id: "allan-gray-bursary",
    name: "Allan Gray Orbis Foundation Bursary",
    provider: "Allan Gray Orbis Foundation",
    description: "Comprehensive bursary for academically talented students.",
    amount:
      "Full tuition + accommodation + stipend + mentorship + leadership development",
    eligibilityCriteria: [
      "South African citizen",
      "Studying any field at university level",
      "Academic excellence",
      "Leadership potential",
      "Financial need",
      "Entrepreneurial spirit",
    ],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply online at www.allangrayorbis.org",
    contactInfo: "bursaries@allangray.co.za",
    website: "https://www.allangrayorbis.org",
    fieldsOfStudy: ["All fields"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic excellence",
      financialNeed: true,
    },
  },
  {
    id: "investec-bursary",
    name: "Investec Foundation Bursary",
    provider: "Investec",
    description: "Bursary for finance, economics, and business students.",
    amount: "Full tuition + accommodation + stipend",
    eligibilityCriteria: [
      "South African citizen",
      "Studying finance, economics, accounting, actuarial science",
      "Academic excellence",
      "Financial need",
      "Leadership potential",
    ],
    applicationDeadline: "31 May annually",
    applicationProcess: "Apply online at www.investec.com/foundation",
    contactInfo: "foundation@investec.co.za",
    website: "https://www.investec.com",
    fieldsOfStudy: ["Finance", "Economics", "Accounting", "Actuarial Science"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic excellence",
      financialNeed: true,
    },
  },

  // Insurance Industry
  {
    id: "old-mutual-bursary",
    name: "Old Mutual Foundation Bursary",
    provider: "Old Mutual",
    description: "Bursary for actuarial science, finance, and related fields.",
    amount: "Full tuition + accommodation + allowances",
    eligibilityCriteria: [
      "South African citizen",
      "Studying actuarial science, finance, mathematics, statistics",
      "Academic merit",
      "Financial need",
      "Previously disadvantaged individuals preferred",
    ],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply online at www.oldmutual.co.za/foundation",
    contactInfo: "foundation@oldmutual.com",
    website: "https://www.oldmutual.co.za",
    fieldsOfStudy: [
      "Actuarial Science",
      "Finance",
      "Mathematics",
      "Statistics",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic merit",
      financialNeed: true,
    },
  },
  {
    id: "santam-bursary",
    name: "Santam Foundation Bursary",
    provider: "Santam",
    description:
      "Bursary for insurance, risk management, and actuarial students.",
    amount: "Full tuition + accommodation + stipend",
    eligibilityCriteria: [
      "South African citizen",
      "Studying actuarial science, risk management, commerce, law",
      "Academic excellence",
      "Interest in insurance industry",
      "Financial need",
    ],
    applicationDeadline: "30 June annually",
    applicationProcess: "Apply online at www.santam.co.za/foundation",
    contactInfo: "foundation@santam.co.za",
    website: "https://www.santam.co.za",
    fieldsOfStudy: ["Actuarial Science", "Risk Management", "Commerce", "Law"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic excellence",
      financialNeed: true,
    },
  },

  // Manufacturing and Industrial
  {
    id: "imperial-bursary",
    name: "Imperial Holdings Bursary",
    provider: "Imperial Holdings",
    description: "Bursary for logistics, engineering, and business students.",
    amount: "Full tuition + accommodation + allowances",
    eligibilityCriteria: [
      "South African citizen",
      "Studying logistics, supply chain, engineering, business",
      "Academic merit",
      "Interest in logistics industry",
      "Financial need",
    ],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply online at www.imperialholdings.co.za/careers",
    contactInfo: "bursaries@imperial.co.za",
    website: "https://www.imperialholdings.co.za",
    fieldsOfStudy: ["Logistics", "Supply Chain", "Engineering", "Business"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic merit",
      financialNeed: true,
    },
  },
  {
    id: "barloworld-bursary",
    name: "Barloworld Foundation Bursary",
    provider: "Barloworld",
    description: "Bursary for engineering and technical students.",
    amount: "Full tuition + accommodation + stipend",
    eligibilityCriteria: [
      "South African citizen",
      "Studying mechanical, electrical, industrial engineering",
      "Technical and vocational fields",
      "Academic excellence",
      "Financial need",
    ],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply online at www.barloworld.com/foundation",
    contactInfo: "foundation@barloworld.com",
    website: "https://www.barloworld.com",
    fieldsOfStudy: [
      "Engineering",
      "Technical Studies",
      "Mechanical Engineering",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic excellence",
      financialNeed: true,
    },
  },

  // International and Specialized Bursaries
  {
    id: "mandela-rhodes-scholarship",
    name: "Mandela Rhodes Scholarship",
    provider: "Mandela Rhodes Foundation",
    description:
      "Prestigious scholarship for African students pursuing postgraduate studies.",
    amount: "Full tuition + accommodation + stipend + development programmes",
    eligibilityCriteria: [
      "African citizen under 30 years",
      "Postgraduate studies at selected South African universities",
      "Academic excellence",
      "Leadership potential",
      "Reconciliation and social impact focus",
    ],
    applicationDeadline: "30 June annually",
    applicationProcess: "Apply online at www.mandelarhodes.org",
    contactInfo: "info@mandelarhodes.org",
    website: "https://www.mandelarhodes.org",
    fieldsOfStudy: ["All postgraduate fields"],
    provinces: ["Western Cape", "Gauteng", "KwaZulu-Natal"],
    requirements: {
      academicRequirement: "Academic excellence",
      financialNeed: false,
    },
  },
  {
    id: "mastercard-foundation",
    name: "Mastercard Foundation Scholars Program",
    provider: "Mastercard Foundation",
    description:
      "Comprehensive scholarship for academically talented students from disadvantaged backgrounds.",
    amount:
      "Full tuition + accommodation + stipend + leadership development + career support",
    eligibilityCriteria: [
      "South African citizen from disadvantaged background",
      "Academic excellence",
      "Leadership potential",
      "Commitment to giving back to community",
      "Financial need",
    ],
    applicationDeadline: "Variable (university-specific)",
    applicationProcess: "Apply through participating universities",
    contactInfo: "scholars@mastercardfdn.org",
    website: "https://mastercardfdn.org/scholars",
    fieldsOfStudy: ["All fields"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic excellence",
      financialNeed: true,
    },
  },

  // Provincial and Local Government Bursaries
  {
    id: "gauteng-provincial-bursary",
    name: "Gauteng Provincial Bursary",
    provider: "Gauteng Provincial Government",
    description: "Bursary for Gauteng residents in priority skills areas.",
    amount: "Full tuition + accommodation + allowances",
    eligibilityCriteria: [
      "South African citizen",
      "Gauteng resident",
      "Studying in priority skills areas",
      "Academic merit",
      "Financial need",
      "Agree to work in Gauteng after graduation",
    ],
    applicationDeadline: "31 October annually",
    applicationProcess: "Apply online at www.gauteng.gov.za/bursaries",
    contactInfo: "bursaries@gauteng.gov.za",
    website: "https://www.gauteng.gov.za",
    fieldsOfStudy: [
      "Education",
      "Health",
      "Engineering",
      "Information Technology",
    ],
    provinces: ["Gauteng"],
    requirements: {
      academicRequirement: "Academic merit",
      financialNeed: true,
    },
  },
  {
    id: "western-cape-bursary",
    name: "Western Cape Government Bursary",
    provider: "Western Cape Government",
    description: "Bursary for Western Cape residents in scarce skills areas.",
    amount: "Full tuition + accommodation + stipend",
    eligibilityCriteria: [
      "South African citizen",
      "Western Cape resident",
      "Studying in scarce skills areas",
      "Academic excellence",
      "Financial need",
      "Agree to work in Western Cape after graduation",
    ],
    applicationDeadline: "30 September annually",
    applicationProcess: "Apply online at www.westerncape.gov.za/bursaries",
    contactInfo: "bursaries@westerncape.gov.za",
    website: "https://www.westerncape.gov.za",
    fieldsOfStudy: [
      "Health",
      "Education",
      "Engineering",
      "Agriculture",
      "Social Work",
    ],
    provinces: ["Western Cape"],
    requirements: {
      academicRequirement: "Academic excellence",
      financialNeed: true,
    },
  },

  // Professional Associations and Organizations
  {
    id: "saica-bursary",
    name: "SAICA (South African Institute of Chartered Accountants) Bursary",
    provider: "SAICA",
    description:
      "Bursary for accounting students pursuing CA(SA) qualification.",
    amount: "Partial tuition + study materials + mentorship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying accounting towards CA(SA) qualification",
      "Academic excellence",
      "Financial need",
      "Commitment to accounting profession",
    ],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply online at www.saica.co.za/bursaries",
    contactInfo: "bursaries@saica.co.za",
    website: "https://www.saica.co.za",
    fieldsOfStudy: ["Accounting", "Chartered Accountancy"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic excellence",
      financialNeed: true,
    },
  },
  {
    id: "sacap-psychology",
    name: "SACAP Psychology Bursary",
    provider: "South African College of Applied Psychology",
    description: "Bursary for psychology students.",
    amount: "Partial tuition + mentorship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying psychology at SACAP",
      "Academic merit",
      "Financial need",
      "Passion for psychology field",
    ],
    applicationDeadline: "31 December annually",
    applicationProcess: "Apply online at www.sacap.edu.za/bursaries",
    contactInfo: "bursaries@sacap.edu.za",
    website: "https://www.sacap.edu.za",
    fieldsOfStudy: ["Psychology", "Counselling"],
    provinces: ["Gauteng", "Western Cape", "KwaZulu-Natal"],
    requirements: {
      academicRequirement: "Academic merit",
      financialNeed: true,
    },
  },
];

export const BURSARY_FIELDS_OF_STUDY = [
  "All fields",
  "Accounting",
  "Actuarial Science",
  "Agriculture",
  "Business",
  "Commerce",
  "Computer Science",
  "Counselling",
  "Economics",
  "Education",
  "Engineering",
  "Finance",
  "Forestry",
  "Health Sciences",
  "Information Technology",
  "Law",
  "Logistics",
  "Mathematics",
  "Medicine",
  "Mining Engineering",
  "Nursing",
  "Psychology",
  "Science",
  "Teaching",
  "Technology",
];

export const PROVINCES = [
  "All provinces",
  "Eastern Cape",
  "Free State",
  "Gauteng",
  "KwaZulu-Natal",
  "Limpopo",
  "Mpumalanga",
  "Northern Cape",
  "North West",
  "Western Cape",
];
