import { University } from "@/types/university";

/**
 * COMPLETE AUDIT: ALL 26 PUBLIC UNIVERSITIES IN SOUTH AFRICA
 *
 * This file contains the complete, official list of all 26 public universities
 * in South Africa as recognized by the Department of Higher Education and Training.
 *
 * Classification:
 * - 11 Traditional Universities (research-focused)
 * - 6 Universities of Technology (applied sciences and technology)
 * - 6 Comprehensive Universities (both traditional and technological programs)
 * - 3 Specialized Universities (single focus institutions)
 *
 * Source: South African Department of Higher Education and Training
 */

// Base faculty structure for consistent application
const createBaseFaculty = (id: string, name: string, description: string) => ({
  id,
  name,
  description,
  degrees: [],
});

// TRADITIONAL UNIVERSITIES (11)
export const COMPLETE_TRADITIONAL_UNIVERSITIES: University[] = [
  {
    id: "uct",
    name: "University of Cape Town",
    abbreviation: "UCT",
    fullName: "University of Cape Town",
    location: "Cape Town",
    province: "Western Cape",
    logo: "/logos/universities/uct.svg",
    overview:
      "Africa's leading research university, ranked #1 in Africa. Known for academic excellence and research innovation.",
    website: "https://www.uct.ac.za",
    studentPortal: "https://students.uct.ac.za",
    admissionsContact: "admissions@uct.ac.za",
    establishedYear: 1829,
    studentPopulation: 29000,
    faculties: [
      createBaseFaculty(
        "commerce",
        "Commerce",
        "Business and economic sciences programs",
      ),
      createBaseFaculty(
        "engineering",
        "Engineering & Built Environment",
        "Engineering and construction programs",
      ),
      createBaseFaculty(
        "health-sciences",
        "Health Sciences",
        "Medical and health-related programs",
      ),
      createBaseFaculty(
        "humanities",
        "Humanities",
        "Arts, languages, and social sciences",
      ),
      createBaseFaculty("law", "Law", "Legal studies and jurisprudence"),
      createBaseFaculty(
        "science",
        "Science",
        "Natural sciences and mathematics",
      ),
    ],
    applicationInfo: {
      isOpen: true,
      openingDate: "April 1",
      closingDate: "July 31",
      academicYear: "2025",
      applicationMethod: "Online",
    },
  },
  {
    id: "wits",
    name: "University of the Witwatersrand",
    abbreviation: "Wits",
    fullName: "University of the Witwatersrand, Johannesburg",
    location: "Johannesburg",
    province: "Gauteng",
    logo: "/logos/universities/university-of-witwatersrand.svg",
    overview:
      "Leading research university known for engineering, medicine, and business programs. Strong industry connections.",
    website: "https://www.wits.ac.za",
    studentPortal: "https://students.wits.ac.za",
    admissionsContact: "admissions@wits.ac.za",
    establishedYear: 1922,
    studentPopulation: 40000,
    faculties: [
      createBaseFaculty(
        "commerce",
        "Commerce, Law & Management",
        "Business, law, and management programs",
      ),
      createBaseFaculty(
        "engineering",
        "Engineering & Built Environment",
        "Engineering and construction programs",
      ),
      createBaseFaculty(
        "health-sciences",
        "Health Sciences",
        "Medical and health-related programs",
      ),
      createBaseFaculty(
        "humanities",
        "Humanities",
        "Arts, languages, and social sciences",
      ),
      createBaseFaculty(
        "science",
        "Science",
        "Natural sciences and mathematics",
      ),
    ],
    applicationInfo: {
      isOpen: true,
      openingDate: "April 1",
      closingDate: "August 31",
      academicYear: "2025",
      applicationMethod: "Online",
    },
  },
  {
    id: "stellenbosch",
    name: "Stellenbosch University",
    abbreviation: "SU",
    fullName: "Stellenbosch University",
    location: "Stellenbosch",
    province: "Western Cape",
    logo: "/logos/universities/stellenbosch-university.svg",
    overview:
      "Premier research university known for agriculture, engineering, and medical programs. Beautiful campus in wine country.",
    website: "https://www.sun.ac.za",
    studentPortal: "https://students.sun.ac.za",
    admissionsContact: "admissions@sun.ac.za",
    establishedYear: 1918,
    studentPopulation: 32000,
    faculties: [
      createBaseFaculty(
        "agriculture",
        "AgriSciences",
        "Agricultural and food sciences",
      ),
      createBaseFaculty(
        "arts",
        "Arts & Social Sciences",
        "Humanities and social sciences",
      ),
      createBaseFaculty(
        "economic",
        "Economic & Management Sciences",
        "Business and economics",
      ),
      createBaseFaculty(
        "education",
        "Education",
        "Teacher training and educational studies",
      ),
      createBaseFaculty(
        "engineering",
        "Engineering",
        "Engineering and technology",
      ),
      createBaseFaculty("law", "Law", "Legal studies"),
      createBaseFaculty(
        "medicine",
        "Medicine & Health Sciences",
        "Medical and health programs",
      ),
      createBaseFaculty(
        "science",
        "Science",
        "Natural sciences and mathematics",
      ),
      createBaseFaculty("theology", "Theology", "Religious studies"),
    ],
    applicationInfo: {
      isOpen: true,
      openingDate: "March 1",
      closingDate: "August 31",
      academicYear: "2025",
      applicationMethod: "Online",
    },
  },
  {
    id: "up",
    name: "University of Pretoria",
    abbreviation: "UP",
    fullName: "University of Pretoria",
    location: "Pretoria",
    province: "Gauteng",
    logo: "/logos/universities/university-of-pretoria.svg",
    overview:
      "One of South Africa's largest universities, offering comprehensive programs across all disciplines.",
    website: "https://www.up.ac.za",
    studentPortal: "https://students.up.ac.za",
    admissionsContact: "admissions@up.ac.za",
    establishedYear: 1908,
    studentPopulation: 53000,
    faculties: [
      createBaseFaculty(
        "economic",
        "Economic & Management Sciences",
        "Business and economics",
      ),
      createBaseFaculty(
        "education",
        "Education",
        "Teacher training and educational studies",
      ),
      createBaseFaculty(
        "engineering",
        "Engineering, Built Environment & IT",
        "Engineering and technology",
      ),
      createBaseFaculty(
        "health-sciences",
        "Health Sciences",
        "Medical and health programs",
      ),
      createBaseFaculty("humanities", "Humanities", "Arts and social sciences"),
      createBaseFaculty("law", "Law", "Legal studies"),
      createBaseFaculty(
        "natural-agriculture",
        "Natural & Agricultural Sciences",
        "Science and agriculture",
      ),
      createBaseFaculty("theology", "Theology & Religion", "Religious studies"),
      createBaseFaculty(
        "veterinary",
        "Veterinary Science",
        "Animal health and veterinary medicine",
      ),
    ],
    applicationInfo: {
      isOpen: true,
      openingDate: "April 1",
      closingDate: "July 31",
      academicYear: "2025",
      applicationMethod: "Online",
    },
  },
  {
    id: "ukzn",
    name: "University of KwaZulu-Natal",
    abbreviation: "UKZN",
    fullName: "University of KwaZulu-Natal",
    location: "Durban",
    province: "KwaZulu-Natal",
    logo: "/logos/universities/ukzn.svg",
    overview:
      "Major research university with multiple campuses, strong in medicine, engineering, and social sciences.",
    website: "https://www.ukzn.ac.za",
    studentPortal: "https://students.ukzn.ac.za",
    admissionsContact: "admissions@ukzn.ac.za",
    establishedYear: 2004,
    studentPopulation: 47000,
    faculties: [
      createBaseFaculty(
        "agriculture",
        "Agriculture, Engineering & Science",
        "Agriculture, engineering, and science",
      ),
      createBaseFaculty(
        "education",
        "Education",
        "Teacher training and educational studies",
      ),
      createBaseFaculty(
        "health-sciences",
        "Health Sciences",
        "Medical and health programs",
      ),
      createBaseFaculty(
        "humanities",
        "Humanities, Development & Social Sciences",
        "Arts and social sciences",
      ),
      createBaseFaculty(
        "law",
        "Law & Management Studies",
        "Law and management",
      ),
    ],
    applicationInfo: {
      isOpen: true,
      openingDate: "April 1",
      closingDate: "August 31",
      academicYear: "2025",
      applicationMethod: "Online",
    },
  },
  {
    id: "ru",
    name: "Rhodes University",
    abbreviation: "RU",
    fullName: "Rhodes University",
    location: "Grahamstown",
    province: "Eastern Cape",
    logo: "/logos/universities/rhodes.svg",
    overview:
      "Prestigious small university known for high academic standards and excellent student experience.",
    website: "https://www.ru.ac.za",
    studentPortal: "https://students.ru.ac.za",
    admissionsContact: "admissions@ru.ac.za",
    establishedYear: 1904,
    studentPopulation: 8500,
    faculties: [
      createBaseFaculty("commerce", "Commerce", "Business and commerce"),
      createBaseFaculty("education", "Education", "Teacher training"),
      createBaseFaculty("humanities", "Humanities", "Arts and humanities"),
      createBaseFaculty("law", "Law", "Legal studies"),
      createBaseFaculty("pharmacy", "Pharmacy", "Pharmaceutical sciences"),
      createBaseFaculty("science", "Science", "Natural sciences"),
    ],
    applicationInfo: {
      isOpen: true,
      openingDate: "April 1",
      closingDate: "August 31",
      academicYear: "2025",
      applicationMethod: "Online",
    },
  },
  {
    id: "nwu",
    name: "North-West University",
    abbreviation: "NWU",
    fullName: "North-West University",
    location: "Potchefstroom",
    province: "North West",
    logo: "/logos/universities/university-of-north-west.svg",
    overview:
      "Multi-campus university offering comprehensive programs with strong community engagement.",
    website: "https://www.nwu.ac.za",
    studentPortal: "https://students.nwu.ac.za",
    admissionsContact: "admissions@nwu.ac.za",
    establishedYear: 2004,
    studentPopulation: 38000,
    faculties: [
      createBaseFaculty(
        "commerce",
        "Economic & Management Sciences",
        "Business and economics",
      ),
      createBaseFaculty("education", "Education", "Teacher training"),
      createBaseFaculty("engineering", "Engineering", "Engineering programs"),
      createBaseFaculty(
        "health-sciences",
        "Health Sciences",
        "Medical and health programs",
      ),
      createBaseFaculty("humanities", "Humanities", "Arts and humanities"),
      createBaseFaculty("law", "Law", "Legal studies"),
      createBaseFaculty(
        "natural",
        "Natural & Agricultural Sciences",
        "Science and agriculture",
      ),
      createBaseFaculty("theology", "Theology", "Religious studies"),
    ],
    applicationInfo: {
      isOpen: true,
      openingDate: "April 1",
      closingDate: "August 31",
      academicYear: "2025",
      applicationMethod: "Online",
    },
  },
  {
    id: "ufs",
    name: "University of the Free State",
    abbreviation: "UFS",
    fullName: "University of the Free State",
    location: "Bloemfontein",
    province: "Free State",
    logo: "/logos/universities/ufs.svg",
    overview:
      "Central university known for agriculture, medicine, and social sciences with multi-campus structure.",
    website: "https://www.ufs.ac.za",
    studentPortal: "https://students.ufs.ac.za",
    admissionsContact: "admissions@ufs.ac.za",
    establishedYear: 1904,
    studentPopulation: 37000,
    faculties: [
      createBaseFaculty(
        "agriculture",
        "Natural & Agricultural Sciences",
        "Agriculture and natural sciences",
      ),
      createBaseFaculty(
        "economic",
        "Economic & Management Sciences",
        "Business and economics",
      ),
      createBaseFaculty("education", "Education", "Teacher training"),
      createBaseFaculty(
        "health-sciences",
        "Health Sciences",
        "Medical and health programs",
      ),
      createBaseFaculty("humanities", "Humanities", "Arts and humanities"),
      createBaseFaculty("law", "Law", "Legal studies"),
      createBaseFaculty("theology", "Theology & Religion", "Religious studies"),
    ],
    applicationInfo: {
      isOpen: true,
      openingDate: "April 1",
      closingDate: "August 31",
      academicYear: "2025",
      applicationMethod: "Online",
    },
  },
  {
    id: "uwc",
    name: "University of the Western Cape",
    abbreviation: "UWC",
    fullName: "University of the Western Cape",
    location: "Bellville",
    province: "Western Cape",
    logo: "/logos/universities/uwc.svg",
    overview:
      "Historically disadvantaged university now a leading institution for social justice and academic excellence.",
    website: "https://www.uwc.ac.za",
    studentPortal: "https://students.uwc.ac.za",
    admissionsContact: "admissions@uwc.ac.za",
    establishedYear: 1960,
    studentPopulation: 20000,
    faculties: [
      createBaseFaculty("arts", "Arts", "Arts and humanities"),
      createBaseFaculty(
        "community",
        "Community & Health Sciences",
        "Health and community sciences",
      ),
      createBaseFaculty("dentistry", "Dentistry", "Dental sciences"),
      createBaseFaculty(
        "economic",
        "Economic & Management Sciences",
        "Business and economics",
      ),
      createBaseFaculty("education", "Education", "Teacher training"),
      createBaseFaculty("law", "Law", "Legal studies"),
      createBaseFaculty("natural", "Natural Sciences", "Natural sciences"),
    ],
    applicationInfo: {
      isOpen: true,
      openingDate: "April 1",
      closingDate: "August 31",
      academicYear: "2025",
      applicationMethod: "Online",
    },
  },
  {
    id: "ufh",
    name: "University of Fort Hare",
    abbreviation: "UFH",
    fullName: "University of Fort Hare",
    location: "Alice",
    province: "Eastern Cape",
    logo: "/logos/universities/ufh.svg",
    overview:
      "Historic university that educated many African leaders, known for humanities and social sciences.",
    website: "https://www.ufh.ac.za",
    studentPortal: "https://students.ufh.ac.za",
    admissionsContact: "admissions@ufh.ac.za",
    establishedYear: 1916,
    studentPopulation: 13000,
    faculties: [
      createBaseFaculty(
        "agriculture",
        "Science & Agriculture",
        "Science and agriculture",
      ),
      createBaseFaculty("education", "Education", "Teacher training"),
      createBaseFaculty("law", "Law", "Legal studies"),
      createBaseFaculty(
        "management",
        "Management & Commerce",
        "Business and management",
      ),
      createBaseFaculty(
        "social",
        "Social Sciences & Humanities",
        "Arts and social sciences",
      ),
    ],
    applicationInfo: {
      isOpen: true,
      openingDate: "April 1",
      closingDate: "August 31",
      academicYear: "2025",
      applicationMethod: "Online",
    },
  },
  {
    id: "ul",
    name: "University of Limpopo",
    abbreviation: "UL",
    fullName: "University of Limpopo",
    location: "Sovenga",
    province: "Limpopo",
    logo: "/logos/universities/university-of-limpopo.svg",
    overview:
      "Rural university focused on agriculture, health sciences, and development studies.",
    website: "https://www.ul.ac.za",
    studentPortal: "https://students.ul.ac.za",
    admissionsContact: "admissions@ul.ac.za",
    establishedYear: 2005,
    studentPopulation: 19000,
    faculties: [
      createBaseFaculty(
        "agriculture",
        "Science & Agriculture",
        "Science and agriculture",
      ),
      createBaseFaculty(
        "health-sciences",
        "Health Sciences",
        "Medical and health programs",
      ),
      createBaseFaculty("humanities", "Humanities", "Arts and humanities"),
      createBaseFaculty("management", "Management & Law", "Business and law"),
    ],
    applicationInfo: {
      isOpen: true,
      openingDate: "April 1",
      closingDate: "August 31",
      academicYear: "2025",
      applicationMethod: "Online",
    },
  },
];

// UNIVERSITIES OF TECHNOLOGY (6)
export const COMPLETE_UNIVERSITIES_OF_TECHNOLOGY: University[] = [
  {
    id: "cput",
    name: "Cape Peninsula University of Technology",
    abbreviation: "CPUT",
    fullName: "Cape Peninsula University of Technology",
    location: "Cape Town",
    province: "Western Cape",
    logo: "/logos/universities/cput.svg",
    overview:
      "Leading university of technology providing quality education in applied sciences and technology.",
    website: "https://www.cput.ac.za",
    studentPortal: "https://students.cput.ac.za",
    admissionsContact: "admissions@cput.ac.za",
    establishedYear: 2005,
    studentPopulation: 32000,
    faculties: [
      createBaseFaculty(
        "applied",
        "Applied Sciences",
        "Applied sciences and technology",
      ),
      createBaseFaculty(
        "business",
        "Business & Management Sciences",
        "Business and management",
      ),
      createBaseFaculty(
        "education",
        "Education & Social Work",
        "Education and social work",
      ),
      createBaseFaculty(
        "engineering",
        "Engineering & Built Environment",
        "Engineering and construction",
      ),
      createBaseFaculty(
        "health",
        "Health & Wellness Sciences",
        "Health and wellness",
      ),
      createBaseFaculty("informatics", "Informatics & Design", "IT and design"),
    ],
    applicationInfo: {
      isOpen: true,
      openingDate: "April 1",
      closingDate: "August 31",
      academicYear: "2025",
      applicationMethod: "Online",
    },
  },
  {
    id: "dut",
    name: "Durban University of Technology",
    abbreviation: "DUT",
    fullName: "Durban University of Technology",
    location: "Durban",
    province: "KwaZulu-Natal",
    logo: "/logos/universities/dut.svg",
    overview:
      "Premier university of technology focusing on applied research and industry-relevant programs.",
    website: "https://www.dut.ac.za",
    studentPortal: "https://students.dut.ac.za",
    admissionsContact: "admissions@dut.ac.za",
    establishedYear: 2002,
    studentPopulation: 31000,
    faculties: [
      createBaseFaculty(
        "accounting",
        "Accounting & Informatics",
        "Accounting and information systems",
      ),
      createBaseFaculty("applied", "Applied Sciences", "Applied sciences"),
      createBaseFaculty("arts", "Arts & Design", "Arts and design"),
      createBaseFaculty(
        "engineering",
        "Engineering & Built Environment",
        "Engineering and construction",
      ),
      createBaseFaculty("health", "Health Sciences", "Health sciences"),
      createBaseFaculty(
        "management",
        "Management Sciences",
        "Management and business",
      ),
    ],
    applicationInfo: {
      isOpen: true,
      openingDate: "April 1",
      closingDate: "August 31",
      academicYear: "2025",
      applicationMethod: "Online",
    },
  },
  {
    id: "tut",
    name: "Tshwane University of Technology",
    abbreviation: "TUT",
    fullName: "Tshwane University of Technology",
    location: "Pretoria",
    province: "Gauteng",
    logo: "/logos/universities/tshwane-university-of-technology.svg",
    overview:
      "Largest university of technology in South Africa, known for engineering and technology programs.",
    website: "https://www.tut.ac.za",
    studentPortal: "https://students.tut.ac.za",
    admissionsContact: "admissions@tut.ac.za",
    establishedYear: 2004,
    studentPopulation: 60000,
    faculties: [
      createBaseFaculty("arts", "Arts & Design", "Arts and design"),
      createBaseFaculty(
        "economic",
        "Economic & Finance Sciences",
        "Economics and finance",
      ),
      createBaseFaculty("education", "Education", "Teacher training"),
      createBaseFaculty(
        "engineering",
        "Engineering & Built Environment",
        "Engineering and construction",
      ),
      createBaseFaculty(
        "ict",
        "Information & Communication Technology",
        "IT and communications",
      ),
      createBaseFaculty(
        "management",
        "Management Sciences",
        "Management and business",
      ),
      createBaseFaculty("science", "Science", "Applied sciences"),
    ],
    applicationInfo: {
      isOpen: true,
      openingDate: "April 1",
      closingDate: "August 31",
      academicYear: "2025",
      applicationMethod: "Online",
    },
  },
  {
    id: "vut",
    name: "Vaal University of Technology",
    abbreviation: "VUT",
    fullName: "Vaal University of Technology",
    location: "Vanderbijlpark",
    province: "Gauteng",
    logo: "/logos/universities/vut.svg",
    overview:
      "Technology-focused university serving the Vaal Triangle region with practical, industry-oriented programs.",
    website: "https://www.vut.ac.za",
    studentPortal: "https://students.vut.ac.za",
    admissionsContact: "admissions@vut.ac.za",
    establishedYear: 1966,
    studentPopulation: 20000,
    faculties: [
      createBaseFaculty(
        "applied",
        "Applied & Computer Sciences",
        "Applied and computer sciences",
      ),
      createBaseFaculty(
        "engineering",
        "Engineering Technology",
        "Engineering technology",
      ),
      createBaseFaculty("human", "Human Sciences", "Human sciences"),
      createBaseFaculty(
        "management",
        "Management Sciences",
        "Management sciences",
      ),
    ],
    applicationInfo: {
      isOpen: true,
      openingDate: "April 1",
      closingDate: "August 31",
      academicYear: "2025",
      applicationMethod: "Online",
    },
  },
  {
    id: "cut",
    name: "Central University of Technology",
    abbreviation: "CUT",
    fullName: "Central University of Technology, Free State",
    location: "Bloemfontein",
    province: "Free State",
    logo: "/logos/universities/cut.svg",
    overview:
      "University of technology focused on career-oriented education and applied research.",
    website: "https://www.cut.ac.za",
    studentPortal: "https://students.cut.ac.za",
    admissionsContact: "admissions@cut.ac.za",
    establishedYear: 1981,
    studentPopulation: 13000,
    faculties: [
      createBaseFaculty(
        "engineering",
        "Engineering & Information Technology",
        "Engineering and IT",
      ),
      createBaseFaculty(
        "health",
        "Health & Environmental Sciences",
        "Health and environmental sciences",
      ),
      createBaseFaculty("humanities", "Humanities", "Arts and humanities"),
      createBaseFaculty(
        "management",
        "Management Sciences",
        "Management and business",
      ),
    ],
    applicationInfo: {
      isOpen: true,
      openingDate: "April 1",
      closingDate: "August 31",
      academicYear: "2025",
      applicationMethod: "Online",
    },
  },
  {
    id: "mut",
    name: "Mangosuthu University of Technology",
    abbreviation: "MUT",
    fullName: "Mangosuthu University of Technology",
    location: "Umlazi",
    province: "KwaZulu-Natal",
    logo: "/logos/universities/mut.svg",
    overview:
      "University of technology serving the greater Durban area with focus on practical and technological education.",
    website: "https://www.mut.ac.za",
    studentPortal: "https://students.mut.ac.za",
    admissionsContact: "admissions@mut.ac.za",
    establishedYear: 1979,
    studentPopulation: 13000,
    faculties: [
      createBaseFaculty("engineering", "Engineering", "Engineering programs"),
      createBaseFaculty(
        "management",
        "Management Sciences",
        "Management and business",
      ),
      createBaseFaculty("natural", "Natural Sciences", "Natural sciences"),
    ],
    applicationInfo: {
      isOpen: true,
      openingDate: "April 1",
      closingDate: "August 31",
      academicYear: "2025",
      applicationMethod: "Online",
    },
  },
];

// COMPREHENSIVE UNIVERSITIES (6)
export const COMPLETE_COMPREHENSIVE_UNIVERSITIES: University[] = [
  {
    id: "uj",
    name: "University of Johannesburg",
    abbreviation: "UJ",
    fullName: "University of Johannesburg",
    location: "Johannesburg",
    province: "Gauteng",
    logo: "/logos/universities/university-of-johannesburg.svg",
    overview:
      "Large comprehensive university offering both traditional and technological programs across multiple campuses.",
    website: "https://www.uj.ac.za",
    studentPortal: "https://students.uj.ac.za",
    admissionsContact: "admissions@uj.ac.za",
    establishedYear: 2005,
    studentPopulation: 50000,
    faculties: [
      createBaseFaculty("art", "Art, Design & Architecture", "Art and design"),
      createBaseFaculty(
        "economic",
        "Economic & Financial Sciences",
        "Economics and finance",
      ),
      createBaseFaculty("education", "Education", "Teacher training"),
      createBaseFaculty(
        "engineering",
        "Engineering & Built Environment",
        "Engineering and construction",
      ),
      createBaseFaculty("health", "Health Sciences", "Health sciences"),
      createBaseFaculty("humanities", "Humanities", "Arts and humanities"),
      createBaseFaculty("law", "Law", "Legal studies"),
      createBaseFaculty("science", "Science", "Natural sciences"),
    ],
    applicationInfo: {
      isOpen: true,
      openingDate: "April 1",
      closingDate: "August 31",
      academicYear: "2025",
      applicationMethod: "Online",
    },
  },
  {
    id: "unizulu",
    name: "University of Zululand",
    abbreviation: "UNIZULU",
    fullName: "University of Zululand",
    location: "KwaDlangezwa",
    province: "KwaZulu-Natal",
    logo: "/logos/universities/university-of-zululand.svg",
    overview:
      "Comprehensive university serving rural KwaZulu-Natal with diverse academic programs.",
    website: "https://www.unizulu.ac.za",
    studentPortal: "https://students.unizulu.ac.za",
    admissionsContact: "admissions@unizulu.ac.za",
    establishedYear: 1960,
    studentPopulation: 16000,
    faculties: [
      createBaseFaculty(
        "agriculture",
        "Science, Agriculture & Engineering",
        "Science, agriculture, and engineering",
      ),
      createBaseFaculty("arts", "Arts", "Arts and humanities"),
      createBaseFaculty(
        "commerce",
        "Commerce, Administration & Law",
        "Commerce and law",
      ),
      createBaseFaculty("education", "Education", "Teacher training"),
    ],
    applicationInfo: {
      isOpen: true,
      openingDate: "April 1",
      closingDate: "August 31",
      academicYear: "2025",
      applicationMethod: "Online",
    },
  },
  {
    id: "wsu",
    name: "Walter Sisulu University",
    abbreviation: "WSU",
    fullName: "Walter Sisulu University",
    location: "Mthatha",
    province: "Eastern Cape",
    logo: "/logos/universities/wsu.svg",
    overview:
      "Multi-campus comprehensive university serving the Eastern Cape region.",
    website: "https://www.wsu.ac.za",
    studentPortal: "https://students.wsu.ac.za",
    admissionsContact: "admissions@wsu.ac.za",
    establishedYear: 2005,
    studentPopulation: 28000,
    faculties: [
      createBaseFaculty(
        "business",
        "Business, Management Sciences & Law",
        "Business and law",
      ),
      createBaseFaculty("education", "Education", "Teacher training"),
      createBaseFaculty("health", "Health Sciences", "Health sciences"),
      createBaseFaculty(
        "science",
        "Science, Engineering & Technology",
        "Science and technology",
      ),
    ],
    applicationInfo: {
      isOpen: true,
      openingDate: "April 1",
      closingDate: "August 31",
      academicYear: "2025",
      applicationMethod: "Online",
    },
  },
  {
    id: "univen",
    name: "University of Venda",
    abbreviation: "UNIVEN",
    fullName: "University of Venda",
    location: "Thohoyandou",
    province: "Limpopo",
    logo: "/logos/universities/university-of-venda.svg",
    overview:
      "Comprehensive university focused on agriculture, health sciences, and rural development.",
    website: "https://www.univen.ac.za",
    studentPortal: "https://students.univen.ac.za",
    admissionsContact: "admissions@univen.ac.za",
    establishedYear: 1982,
    studentPopulation: 16000,
    faculties: [
      createBaseFaculty(
        "agriculture",
        "Science, Engineering & Agriculture",
        "Science and agriculture",
      ),
      createBaseFaculty("education", "Education", "Teacher training"),
      createBaseFaculty("health", "Health Sciences", "Health sciences"),
      createBaseFaculty(
        "humanities",
        "Humanities, Social Sciences & Education",
        "Humanities and education",
      ),
      createBaseFaculty("law", "Law", "Legal studies"),
      createBaseFaculty(
        "management",
        "Management Sciences",
        "Management and business",
      ),
    ],
    applicationInfo: {
      isOpen: true,
      openingDate: "April 1",
      closingDate: "August 31",
      academicYear: "2025",
      applicationMethod: "Online",
    },
  },
  {
    id: "ump",
    name: "University of Mpumalanga",
    abbreviation: "UMP",
    fullName: "University of Mpumalanga",
    location: "Nelspruit",
    province: "Mpumalanga",
    logo: "/logos/universities/university-of-mpumalanga.svg",
    overview:
      "Newest university in South Africa, focusing on agriculture, education, and health sciences.",
    website: "https://www.ump.ac.za",
    studentPortal: "https://students.ump.ac.za",
    admissionsContact: "admissions@ump.ac.za",
    establishedYear: 2014,
    studentPopulation: 5000,
    faculties: [
      createBaseFaculty(
        "agriculture",
        "Agriculture & Natural Sciences",
        "Agriculture and natural sciences",
      ),
      createBaseFaculty("education", "Education", "Teacher training"),
      createBaseFaculty("health", "Health Sciences", "Health sciences"),
      createBaseFaculty(
        "management",
        "Economic & Management Sciences",
        "Economics and management",
      ),
    ],
    applicationInfo: {
      isOpen: true,
      openingDate: "April 1",
      closingDate: "August 31",
      academicYear: "2025",
      applicationMethod: "Online",
    },
  },
  {
    id: "sol",
    name: "Sol Plaatje University",
    abbreviation: "SPU",
    fullName: "Sol Plaatje University",
    location: "Kimberley",
    province: "Northern Cape",
    logo: "/logos/universities/sol-plaatje.svg",
    overview:
      "New comprehensive university focusing on teacher education and humanities.",
    website: "https://www.spu.ac.za",
    studentPortal: "https://students.spu.ac.za",
    admissionsContact: "admissions@spu.ac.za",
    establishedYear: 2014,
    studentPopulation: 3000,
    faculties: [
      createBaseFaculty(
        "education",
        "Education",
        "Teacher training and educational studies",
      ),
      createBaseFaculty("humanities", "Humanities", "Arts and humanities"),
      createBaseFaculty(
        "natural",
        "Natural & Applied Sciences",
        "Natural and applied sciences",
      ),
    ],
    applicationInfo: {
      isOpen: true,
      openingDate: "April 1",
      closingDate: "August 31",
      academicYear: "2025",
      applicationMethod: "Online",
    },
  },
];

// SPECIALIZED UNIVERSITIES (3)
export const SPECIALIZED_UNIVERSITIES: University[] = [
  {
    id: "unisa",
    name: "University of South Africa",
    abbreviation: "UNISA",
    fullName: "University of South Africa",
    location: "Pretoria",
    province: "Gauteng",
    logo: "/logos/universities/unisa.svg",
    overview:
      "Africa's largest distance education university, offering comprehensive programs through correspondence.",
    website: "https://www.unisa.ac.za",
    studentPortal: "https://students.unisa.ac.za",
    admissionsContact: "admissions@unisa.ac.za",
    establishedYear: 1873,
    studentPopulation: 400000,
    faculties: [
      createBaseFaculty(
        "agriculture",
        "Agriculture & Environmental Sciences",
        "Agriculture and environmental sciences",
      ),
      createBaseFaculty(
        "economic",
        "Economic & Management Sciences",
        "Economics and management",
      ),
      createBaseFaculty("education", "Education", "Teacher training"),
      createBaseFaculty(
        "engineering",
        "Science, Engineering & Technology",
        "Science and technology",
      ),
      createBaseFaculty("health", "Health Sciences", "Health sciences"),
      createBaseFaculty("humanities", "Humanities", "Arts and humanities"),
      createBaseFaculty("law", "Law", "Legal studies"),
      createBaseFaculty("theology", "Theology & Religion", "Religious studies"),
    ],
    applicationInfo: {
      isOpen: true,
      openingDate: "February 1",
      closingDate: "October 31",
      academicYear: "2025",
      applicationMethod: "Online",
    },
  },
  {
    id: "smu",
    name: "Sefako Makgatho Health Sciences University",
    abbreviation: "SMU",
    fullName: "Sefako Makgatho Health Sciences University",
    location: "Ga-Rankuwa",
    province: "Gauteng",
    logo: "/logos/universities/smu.svg",
    overview:
      "Specialized health sciences university focused on medical education and health research.",
    website: "https://www.smu.ac.za",
    studentPortal: "https://students.smu.ac.za",
    admissionsContact: "admissions@smu.ac.za",
    establishedYear: 2014,
    studentPopulation: 4000,
    faculties: [
      createBaseFaculty(
        "health",
        "Health Sciences",
        "Medical and health sciences",
      ),
      createBaseFaculty(
        "science",
        "Science & Technology",
        "Science and technology",
      ),
    ],
    applicationInfo: {
      isOpen: true,
      openingDate: "April 1",
      closingDate: "August 31",
      academicYear: "2025",
      applicationMethod: "Online",
    },
  },
];

// COMPLETE LIST OF ALL 26 PUBLIC UNIVERSITIES
export const ALL_26_SA_UNIVERSITIES: University[] = [
  ...COMPLETE_TRADITIONAL_UNIVERSITIES,
  ...COMPLETE_UNIVERSITIES_OF_TECHNOLOGY,
  ...COMPLETE_COMPREHENSIVE_UNIVERSITIES,
  ...SPECIALIZED_UNIVERSITIES,
];

export const UNIVERSITY_COUNT_SUMMARY = {
  traditional: COMPLETE_TRADITIONAL_UNIVERSITIES.length,
  technology: COMPLETE_UNIVERSITIES_OF_TECHNOLOGY.length,
  comprehensive: COMPLETE_COMPREHENSIVE_UNIVERSITIES.length,
  specialized: SPECIALIZED_UNIVERSITIES.length,
  total: ALL_26_SA_UNIVERSITIES.length,
};
