import { University } from "@/types/university";
import { getUniversityFaculties } from "./comprehensive-course-database";

/**
 * COMPLETE 26 SOUTH AFRICAN PUBLIC UNIVERSITIES
 *
 * This is the definitive list of all 26 public universities in South Africa
 * with comprehensive program allocation based on the massive course database.
 * Faculties are populated dynamically using the assignment rules.
 */

// Base universities without programs (will be populated dynamically)
const BASE_UNIVERSITIES: University[] = [
  // TRADITIONAL UNIVERSITIES (11)
  {
    id: "uct",
    name: "UCT",
    abbreviation: "UCT",
    fullName: "University of Cape Town",
    location: "Cape Town",
    province: "Western Cape",
    logo: "https://cdn.builder.io/api/v1/assets/aa876bee812e456d8594f765f547fed4/uct-f42185?format=webp&width=800",
    overview:
      "Africa's leading university, globally ranked for academic excellence and research innovation.",
    website: "https://www.uct.ac.za",
    studentPortal: "https://www.uct.ac.za/students",
    admissionsContact: "admissions@uct.ac.za",
    faculties: [],
    establishedYear: 1829,
    studentPopulation: 29000,
    type: "Traditional University",
    scoringSystem: "uct-fps",
    applicationInfo: {
      isOpen: true,
      openingDate: "1 April 2025",
      closingDate: "31 July 2025",
      academicYear: "2026",
      applicationFee: "R100",
      applicationMethod: "Online via UCT Application Portal",
    },
  },
  {
    id: "wits",
    name: "Wits",
    abbreviation: "Wits",
    fullName: "University of the Witwatersrand",
    location: "Johannesburg",
    province: "Gauteng",
    logo: "https://cdn.builder.io/api/v1/assets/aa876bee812e456d8594f765f547fed4/wits-b10802?format=webp&width=800",
    overview:
      "Leading African research university with a global reputation for academic excellence and innovation.",
    website: "https://www.wits.ac.za",
    studentPortal: "https://www.wits.ac.za/students",
    admissionsContact: "admissions@wits.ac.za",
    faculties: [],
    establishedYear: 1922,
    studentPopulation: 40000,
    type: "Traditional University",
    scoringSystem: "wits-composite",
    applicationInfo: {
      isOpen: true,
      openingDate: "1 April 2025",
      closingDate: "30 September 2025",
      academicYear: "2026",
      applicationFee: "R100",
      applicationMethod: "Online via Wits Student Portal",
    },
  },
  {
    id: "stellenbosch",
    name: "Stellenbosch University",
    abbreviation: "SU",
    fullName: "Stellenbosch University",
    location: "Stellenbosch",
    province: "Western Cape",
    logo: "https://cdn.builder.io/api/v1/assets/aa876bee812e456d8594f765f547fed4/stellenbosh-51a11b?format=webp&width=800",
    overview:
      "Research-intensive university with a tradition of academic excellence and innovation in South Africa.",
    website: "https://www.sun.ac.za",
    studentPortal: "https://www.sun.ac.za/students",
    admissionsContact: "admissions@sun.ac.za",
    faculties: [],
    establishedYear: 1918,
    studentPopulation: 32000,
    type: "Traditional University",
    scoringSystem: "stellenbosch-tpt",
    applicationInfo: {
      isOpen: true,
      openingDate: "1 March 2025",
      closingDate: "31 August 2025",
      academicYear: "2026",
      applicationFee: "R100",
      applicationMethod: "Online via SU Student Portal",
    },
  },
  {
    id: "up",
    name: "UP",
    abbreviation: "UP",
    fullName: "University of Pretoria",
    location: "Pretoria",
    province: "Gauteng",
    logo: "https://cdn.builder.io/api/v1/assets/aa876bee812e456d8594f765f547fed4/up-dd56d2?format=webp&width=800",
    overview:
      "Top research university in South Africa with comprehensive academic programs and research excellence.",
    website: "https://www.up.ac.za",
    studentPortal: "https://www.up.ac.za/students",
    admissionsContact: "admissions@up.ac.za",
    faculties: [],
    establishedYear: 1908,
    studentPopulation: 56000,
    type: "Traditional University",
    scoringSystem: "standard",
    applicationInfo: {
      isOpen: true,
      openingDate: "1 April 2025",
      closingDate: "30 September 2025",
      academicYear: "2026",
      applicationFee: "R100",
      applicationMethod: "Online via UP Student Portal",
    },
  },
  {
    id: "ukzn",
    name: "UKZN",
    abbreviation: "UKZN",
    fullName: "University of KwaZulu-Natal",
    location: "Durban",
    province: "KwaZulu-Natal",
    logo: "https://cdn.builder.io/api/v1/assets/aa876bee812e456d8594f765f547fed4/ukzn-bb1a92?format=webp&width=800",
    overview:
      "Leading research university with strong community engagement and academic excellence.",
    website: "https://www.ukzn.ac.za",
    studentPortal: "https://www.ukzn.ac.za/students",
    admissionsContact: "admissions@ukzn.ac.za",
    faculties: [],
    establishedYear: 2004,
    studentPopulation: 47000,
    type: "Traditional University",
    applicationInfo: {
      isOpen: true,
      openingDate: "1 April 2025",
      closingDate: "30 September 2025",
      academicYear: "2026",
      applicationFee: "R100",
      applicationMethod: "Online via UKZN Application Portal",
    },
  },
  {
    id: "ufs",
    name: "UFS",
    abbreviation: "UFS",
    fullName: "University of the Free State",
    location: "Bloemfontein",
    province: "Free State",
    logo: "https://cdn.builder.io/api/v1/assets/aa876bee812e456d8594f765f547fed4/ufs-2f8e7a?format=webp&width=800",
    overview:
      "Multi-campus university with strong research focus and comprehensive academic programs.",
    website: "https://www.ufs.ac.za",
    studentPortal: "https://www.ufs.ac.za/students",
    admissionsContact: "admissions@ufs.ac.za",
    faculties: [],
    establishedYear: 1904,
    studentPopulation: 38000,
    type: "Traditional University",
    applicationInfo: {
      isOpen: true,
      openingDate: "1 April 2025",
      closingDate: "30 September 2025",
      academicYear: "2026",
      applicationFee: "R100",
      applicationMethod: "Online via UFS Student Portal",
    },
  },
  {
    id: "ru",
    name: "Rhodes",
    abbreviation: "RU",
    fullName: "Rhodes University",
    location: "Makhanda",
    province: "Eastern Cape",
    logo: "https://cdn.builder.io/api/v1/assets/aa876bee812e456d8594f765f547fed4/rhodes-9ec680?format=webp&width=800",
    overview:
      "Prestigious small university known for academic excellence and high-quality research output.",
    website: "https://www.ru.ac.za",
    studentPortal: "https://www.ru.ac.za/students",
    admissionsContact: "admissions@ru.ac.za",
    faculties: [],
    establishedYear: 1904,
    studentPopulation: 8500,
    type: "Traditional University",
    scoringSystem: "rhodes-average",
    applicationInfo: {
      isOpen: true,
      openingDate: "1 April 2025",
      closingDate: "31 August 2025",
      academicYear: "2026",
      applicationFee: "R100",
      applicationMethod: "Online via Rhodes Student Portal",
    },
  },
  {
    id: "nwu",
    name: "NWU",
    abbreviation: "NWU",
    fullName: "North-West University",
    location: "Potchefstroom",
    province: "North West",
    logo: "https://cdn.builder.io/api/v1/assets/aa876bee812e456d8594f765f547fed4/nwu-dd57fc?format=webp&width=800",
    overview:
      "Multi-campus university providing quality education across diverse academic disciplines.",
    website: "https://www.nwu.ac.za",
    studentPortal: "https://www.nwu.ac.za/students",
    admissionsContact: "admissions@nwu.ac.za",
    faculties: [],
    establishedYear: 2004,
    studentPopulation: 68000,
    type: "Traditional University",
    applicationInfo: {
      isOpen: true,
      openingDate: "1 April 2025",
      closingDate: "30 September 2025",
      academicYear: "2026",
      applicationFee: "R100",
      applicationMethod: "Online via NWU Student Portal",
    },
  },
  {
    id: "uwc",
    name: "UWC",
    abbreviation: "UWC",
    fullName: "University of the Western Cape",
    location: "Cape Town",
    province: "Western Cape",
    logo: "https://cdn.builder.io/api/v1/assets/aa876bee812e456d8594f765f547fed4/cape-peninusla-f20516?format=webp&width=800",
    overview:
      "University committed to excellence, equality, and innovation in higher education.",
    website: "https://www.uwc.ac.za",
    studentPortal: "https://www.uwc.ac.za/students",
    admissionsContact: "admissions@uwc.ac.za",
    faculties: [],
    establishedYear: 1960,
    studentPopulation: 24000,
    type: "Traditional University",
    applicationInfo: {
      isOpen: true,
      openingDate: "1 April 2025",
      closingDate: "30 September 2025",
      academicYear: "2026",
      applicationFee: "R100",
      applicationMethod: "Online via UWC Student Portal",
    },
  },
  {
    id: "ufh",
    name: "UFH",
    abbreviation: "UFH",
    fullName: "University of Fort Hare",
    location: "Alice",
    province: "Eastern Cape",
    logo: "https://cdn.builder.io/api/v1/assets/aa876bee812e456d8594f765f547fed4/fort-hare-348944?format=webp&width=800",
    overview:
      "Historic university known for producing African leaders and academic excellence.",
    website: "https://www.ufh.ac.za",
    studentPortal: "https://www.ufh.ac.za/students",
    admissionsContact: "admissions@ufh.ac.za",
    faculties: [],
    establishedYear: 1916,
    studentPopulation: 12000,
    type: "Traditional University",
    applicationInfo: {
      isOpen: true,
      openingDate: "1 April 2025",
      closingDate: "30 September 2025",
      academicYear: "2026",
      applicationFee: "R100",
      applicationMethod: "Online via UFH Student Portal",
    },
  },
  {
    id: "ul",
    name: "UL",
    abbreviation: "UL",
    fullName: "University of Limpopo",
    location: "Polokwane",
    province: "Limpopo",
    logo: "https://cdn.builder.io/api/v1/assets/aa876bee812e456d8594f765f547fed4/limpopo-67f4c6?format=webp&width=800",
    overview:
      "University serving the Limpopo province with focus on African Renaissance and development.",
    website: "https://www.ul.ac.za",
    studentPortal: "https://www.ul.ac.za/students",
    admissionsContact: "admissions@ul.ac.za",
    faculties: [],
    establishedYear: 2005,
    studentPopulation: 20000,
    type: "Traditional University",
    applicationInfo: {
      isOpen: true,
      openingDate: "1 April 2025",
      closingDate: "30 September 2025",
      academicYear: "2026",
      applicationFee: "R100",
      applicationMethod: "Online via UL Student Portal",
    },
  },

  // UNIVERSITIES OF TECHNOLOGY (6)
  {
    id: "cput",
    name: "CPUT",
    abbreviation: "CPUT",
    fullName: "Cape Peninsula University of Technology",
    location: "Cape Town",
    province: "Western Cape",
    logo: "https://cdn.builder.io/api/v1/assets/aa876bee812e456d8594f765f547fed4/cape-peninusla-f20516?format=webp&width=800",
    overview:
      "Technology university providing practical education and skills development in the Western Cape.",
    website: "https://www.cput.ac.za",
    studentPortal: "https://www.cput.ac.za/students",
    admissionsContact: "admissions@cput.ac.za",
    faculties: [],
    establishedYear: 2005,
    studentPopulation: 33000,
    type: "University of Technology",
    applicationInfo: {
      isOpen: true,
      openingDate: "1 May 2025",
      closingDate: "30 September 2025",
      academicYear: "2026",
      applicationFee: "R100",
      applicationMethod: "Online via CPUT Student Portal",
    },
  },
  {
    id: "dut",
    name: "DUT",
    abbreviation: "DUT",
    fullName: "Durban University of Technology",
    location: "Durban",
    province: "KwaZulu-Natal",
    logo: "https://cdn.builder.io/api/v1/assets/aa876bee812e456d8594f765f547fed4/dut-4bf2b1?format=webp&width=800",
    overview:
      "Technology university providing career-focused education and innovation in KwaZulu-Natal.",
    website: "https://www.dut.ac.za",
    studentPortal: "https://www.dut.ac.za/students",
    admissionsContact: "admissions@dut.ac.za",
    faculties: [],
    establishedYear: 2002,
    studentPopulation: 32000,
    type: "University of Technology",
    applicationInfo: {
      isOpen: true,
      openingDate: "1 April 2025",
      closingDate: "30 September 2025",
      academicYear: "2026",
      applicationFee: "R100",
      applicationMethod: "Online via DUT Student Portal",
    },
  },
  {
    id: "tut",
    name: "TUT",
    abbreviation: "TUT",
    fullName: "Tshwane University of Technology",
    location: "Pretoria",
    province: "Gauteng",
    logo: "https://cdn.builder.io/api/v1/assets/aa876bee812e456d8594f765f547fed4/tut-c6fe5f?format=webp&width=800",
    overview:
      "Large technology university providing practical skills and professional development.",
    website: "https://www.tut.ac.za",
    studentPortal: "https://www.tut.ac.za/students",
    admissionsContact: "admissions@tut.ac.za",
    faculties: [],
    establishedYear: 2004,
    studentPopulation: 60000,
    type: "University of Technology",
    applicationInfo: {
      isOpen: true,
      openingDate: "1 April 2025",
      closingDate: "30 September 2025",
      academicYear: "2026",
      applicationFee: "R100",
      applicationMethod: "Online via TUT Student Portal",
    },
  },
  {
    id: "cut",
    name: "CUT",
    abbreviation: "CUT",
    fullName: "Central University of Technology",
    location: "Bloemfontein",
    province: "Free State",
    logo: "https://cdn.builder.io/api/v1/assets/aa876bee812e456d8594f765f547fed4/cut-f0d7c6?format=webp&width=800",
    overview:
      "Technology university focusing on career-oriented education and innovation in the Free State.",
    website: "https://www.cut.ac.za",
    studentPortal: "https://www.cut.ac.za/students",
    admissionsContact: "admissions@cut.ac.za",
    faculties: [],
    establishedYear: 1981,
    studentPopulation: 13000,
    type: "University of Technology",
    applicationInfo: {
      isOpen: true,
      openingDate: "1 April 2025",
      closingDate: "30 September 2025",
      academicYear: "2026",
      applicationFee: "R100",
      applicationMethod: "Online via CUT Student Portal",
    },
  },
  {
    id: "vut",
    name: "VUT",
    abbreviation: "VUT",
    fullName: "Vaal University of Technology",
    location: "Vanderbijlpark",
    province: "Gauteng",
    logo: "https://cdn.builder.io/api/v1/assets/aa876bee812e456d8594f765f547fed4/val-ef4837?format=webp&width=800",
    overview:
      "Technology university providing practical education and skills development for the Vaal region.",
    website: "https://www.vut.ac.za",
    studentPortal: "https://www.vut.ac.za/students",
    admissionsContact: "admissions@vut.ac.za",
    faculties: [],
    establishedYear: 1966,
    studentPopulation: 20000,
    type: "University of Technology",
    applicationInfo: {
      isOpen: true,
      openingDate: "1 April 2025",
      closingDate: "30 September 2025",
      academicYear: "2026",
      applicationFee: "R100",
      applicationMethod: "Online via VUT Student Portal",
    },
  },
  {
    id: "mut",
    name: "MUT",
    abbreviation: "MUT",
    fullName: "Mangosuthu University of Technology",
    location: "Durban",
    province: "KwaZulu-Natal",
    logo: "https://cdn.builder.io/api/v1/assets/aa876bee812e456d8594f765f547fed4/mut-3286f2?format=webp&width=800",
    overview:
      "Technology university serving KwaZulu-Natal with focus on practical skills and community development.",
    website: "https://www.mut.ac.za",
    studentPortal: "https://www.mut.ac.za/students",
    admissionsContact: "admissions@mut.ac.za",
    faculties: [],
    establishedYear: 1979,
    studentPopulation: 13000,
    type: "University of Technology",
    applicationInfo: {
      isOpen: true,
      openingDate: "1 April 2025",
      closingDate: "30 September 2025",
      academicYear: "2026",
      applicationFee: "R100",
      applicationMethod: "Online via MUT Student Portal",
    },
  },

  // COMPREHENSIVE UNIVERSITIES (6)
  {
    id: "uj",
    name: "UJ",
    abbreviation: "UJ",
    fullName: "University of Johannesburg",
    location: "Johannesburg",
    province: "Gauteng",
    logo: "https://cdn.builder.io/api/v1/assets/aa876bee812e456d8594f765f547fed4/uj-689637?format=webp&width=800",
    overview:
      "Large comprehensive university offering diverse academic and technological programs.",
    website: "https://www.uj.ac.za",
    studentPortal: "https://www.uj.ac.za/students",
    admissionsContact: "admissions@uj.ac.za",
    faculties: [],
    establishedYear: 2005,
    studentPopulation: 50000,
    type: "Comprehensive University",
    applicationInfo: {
      isOpen: true,
      openingDate: "1 April 2025",
      closingDate: "30 September 2025",
      academicYear: "2026",
      applicationFee: "R100",
      applicationMethod: "Online via UJ Student Portal",
    },
  },
  {
    id: "unisa",
    name: "UNISA",
    abbreviation: "UNISA",
    fullName: "University of South Africa",
    location: "Pretoria",
    province: "Gauteng",
    logo: "https://cdn.builder.io/api/v1/assets/aa876bee812e456d8594f765f547fed4/unisa-28cb4a?format=webp&width=800",
    overview:
      "Africa's largest distance education university with comprehensive academic programs.",
    website: "https://www.unisa.ac.za",
    studentPortal: "https://www.unisa.ac.za/students",
    admissionsContact: "admissions@unisa.ac.za",
    faculties: [],
    establishedYear: 1873,
    studentPopulation: 300000,
    type: "Comprehensive University",
    scoringSystem: "unisa-custom",
    applicationInfo: {
      isOpen: true,
      openingDate: "1 August 2025",
      closingDate: "15 October 2025",
      academicYear: "2026",
      applicationFee: "R100",
      applicationMethod: "Online via myUnisa Student Portal",
    },
  },
  {
    id: "unizulu",
    name: "UNIZULU",
    abbreviation: "UNIZULU",
    fullName: "University of Zululand",
    location: "Richards Bay",
    province: "KwaZulu-Natal",
    logo: "https://cdn.builder.io/api/v1/assets/aa876bee812e456d8594f765f547fed4/zululand-708c2a?format=webp&width=800",
    overview:
      "Comprehensive university serving rural KwaZulu-Natal with focus on community development.",
    website: "https://www.unizulu.ac.za",
    studentPortal: "https://www.unizulu.ac.za/students",
    admissionsContact: "admissions@unizulu.ac.za",
    faculties: [],
    establishedYear: 1960,
    studentPopulation: 16000,
    type: "Comprehensive University",
    applicationInfo: {
      isOpen: true,
      openingDate: "1 April 2025",
      closingDate: "30 September 2025",
      academicYear: "2026",
      applicationFee: "R100",
      applicationMethod: "Online via UNIZUL Student Portal",
    },
  },
  {
    id: "univen",
    name: "UNIVEN",
    abbreviation: "UNIVEN",
    fullName: "University of Venda",
    location: "Thohoyandou",
    province: "Limpopo",
    logo: "https://cdn.builder.io/api/v1/assets/aa876bee812e456d8594f765f547fed4/venda-170b3b?format=webp&width=800",
    overview:
      "Comprehensive university serving the Venda region with focus on rural development.",
    website: "https://www.univen.ac.za",
    studentPortal: "https://www.univen.ac.za/students",
    admissionsContact: "admissions@univen.ac.za",
    faculties: [],
    establishedYear: 1982,
    studentPopulation: 15000,
    type: "Comprehensive University",
    applicationInfo: {
      isOpen: true,
      openingDate: "1 April 2025",
      closingDate: "30 September 2025",
      academicYear: "2026",
      applicationFee: "R100",
      applicationMethod: "Online via UV Student Portal",
    },
  },
  {
    id: "nmu",
    name: "NMU",
    abbreviation: "NMU",
    fullName: "Nelson Mandela University",
    location: "Port Elizabeth",
    province: "Eastern Cape",
    logo: "https://cdn.builder.io/api/v1/assets/aa876bee812e456d8594f765f547fed4/nelson-4ddaa3?format=webp&width=800",
    overview:
      "Comprehensive university known for academic excellence and community engagement in the Eastern Cape.",
    website: "https://www.mandela.ac.za",
    studentPortal: "https://www.mandela.ac.za/students",
    admissionsContact: "admissions@mandela.ac.za",
    faculties: [],
    establishedYear: 2005,
    studentPopulation: 27000,
    type: "Comprehensive University",
    applicationInfo: {
      isOpen: true,
      openingDate: "1 April 2025",
      closingDate: "30 June (Health), 30 Sept (others)",
      academicYear: "2026",
      applicationFee: "Free SA",
      applicationMethod: "Online via NMU Student Portal",
    },
  },
  {
    id: "wsu",
    name: "WSU",
    abbreviation: "WSU",
    fullName: "Walter Sisulu University",
    location: "Mthatha",
    province: "Eastern Cape",
    logo: "https://cdn.builder.io/api/v1/assets/aa876bee812e456d8594f765f547fed4/wsu-147edd?format=webp&width=800",
    overview:
      "Multi-campus comprehensive university serving the Eastern Cape with focus on social justice.",
    website: "https://www.wsu.ac.za",
    studentPortal: "https://www.wsu.ac.za/students",
    admissionsContact: "admissions@wsu.ac.za",
    faculties: [],
    establishedYear: 2005,
    studentPopulation: 27000,
    type: "Comprehensive University",
    applicationInfo: {
      isOpen: true,
      openingDate: "1 April 2025",
      closingDate: "30 September 2025",
      academicYear: "2026",
      applicationFee: "R100",
      applicationMethod: "Online via WSU Student Portal",
    },
  },

  // NEW GENERATION UNIVERSITIES (3)
  {
    id: "smu",
    name: "SMU",
    abbreviation: "SMU",
    fullName: "Sefako Makgatho Health Sciences University",
    location: "Pretoria",
    province: "Gauteng",
    logo: "https://cdn.builder.io/api/v1/assets/aa876bee812e456d8594f765f547fed4/sefako-3351db?format=webp&width=800",
    overview:
      "Health sciences university dedicated to training healthcare professionals and medical research.",
    website: "https://www.smu.ac.za",
    studentPortal: "https://www.smu.ac.za/students",
    admissionsContact: "admissions@smu.ac.za",
    faculties: [],
    establishedYear: 2014,
    studentPopulation: 4000,
    type: "Traditional University",
    applicationInfo: {
      isOpen: true,
      openingDate: "1 April 2025",
      closingDate: "31 July 2025",
      academicYear: "2026",
      applicationFee: "R100",
      applicationMethod: "Online via SMU Student Portal",
    },
  },
  {
    id: "spu",
    name: "SPU",
    abbreviation: "SPU",
    fullName: "Sol Plaatje University",
    location: "Kimberley",
    province: "Northern Cape",
    logo: "https://cdn.builder.io/api/v1/assets/aa876bee812e456d8594f765f547fed4/sol-plaatje-f6051b?format=webp&width=800",
    overview:
      "New university established to serve the Northern Cape region with innovative programs.",
    website: "https://www.spu.ac.za",
    studentPortal: "https://www.spu.ac.za/students",
    admissionsContact: "admissions@spu.ac.za",
    faculties: [],
    establishedYear: 2013,
    studentPopulation: 3000,
    type: "Traditional University",
    applicationInfo: {
      isOpen: true,
      openingDate: "1 April 2025",
      closingDate: "30 September 2025",
      academicYear: "2026",
      applicationFee: "R100",
      applicationMethod: "Online via SPU Student Portal",
    },
  },
  {
    id: "ump",
    name: "UMP",
    abbreviation: "UMP",
    fullName: "University of Mpumalanga",
    location: "Nelspruit",
    province: "Mpumalanga",
    logo: "https://cdn.builder.io/api/v1/assets/aa876bee812e456d8594f765f547fed4/mpumalanga-bfd8c3?format=webp&width=800",
    overview:
      "New university serving Mpumalanga province with focus on regional development needs.",
    website: "https://www.ump.ac.za",
    studentPortal: "https://www.ump.ac.za/students",
    admissionsContact: "admissions@ump.ac.za",
    faculties: [],
    establishedYear: 2013,
    studentPopulation: 4000,
    type: "Traditional University",
    applicationInfo: {
      isOpen: true,
      openingDate: "1 April 2025",
      closingDate: "30 September 2025",
      academicYear: "2026",
      applicationFee: "R100",
      applicationMethod: "Online via UMP Student Portal",
    },
  },
];

/**
 * Populate university faculties using the massive course database
 */
function populateUniversityFaculties(): University[] {
  return BASE_UNIVERSITIES.map((university) => ({
    ...university,
    faculties: getUniversityFaculties(university.id),
  }));
}

/**
 * FINAL EXPORT: All 26 universities with comprehensive program assignment
 */
export const ALL_SOUTH_AFRICAN_UNIVERSITIES = populateUniversityFaculties();

// University counts by type
export const UNIVERSITY_STATISTICS = {
  traditional: ALL_SOUTH_AFRICAN_UNIVERSITIES.filter(
    (u) => u.type === "Traditional University",
  ).length,
  technology: ALL_SOUTH_AFRICAN_UNIVERSITIES.filter(
    (u) => u.type === "University of Technology",
  ).length,
  comprehensive: ALL_SOUTH_AFRICAN_UNIVERSITIES.filter(
    (u) => u.type === "Comprehensive University",
  ).length,
  total: ALL_SOUTH_AFRICAN_UNIVERSITIES.length,
};

if (import.meta.env.DEV) {
  console.log(
    `✅ Complete database loaded: ${ALL_SOUTH_AFRICAN_UNIVERSITIES.length} South African universities`,
  );
  console.log(
    `📊 Statistics: ${UNIVERSITY_STATISTICS.traditional} Traditional, ${UNIVERSITY_STATISTICS.technology} Technology, ${UNIVERSITY_STATISTICS.comprehensive} Comprehensive`,
  );
}
