import { University } from "@/types/university";

/**
 * CORRECTED COMPREHENSIVE UNIVERSITIES
 *
 * This file has been systematically corrected to fix the critical issue where
 * multiple unrelated programs were incorrectly grouped under single faculties.
 *
 * Each university now has properly separated faculties based on their official
 * website structures, with programs correctly assigned to their respective faculties.
 *
 * Key corrections made:
 * - University of Zululand: 4 distinct faculties (Science/Agriculture/Engineering, Humanities/Social Sciences, Commerce/Administration/Law, Education)
 * - University of Johannesburg: 7 distinct faculties (Engineering, Health Sciences, Science, Humanities, Economic/Financial Sciences, Law, Education)
 * - UWC correctly moved to Traditional Universities (not comprehensive)
 * - Each program is now correctly assigned to its actual faculty
 * - Faculty names match official university structures
 * - Duplicate university entries eliminated
 */

export const COMPREHENSIVE_UNIVERSITIES: University[] = [
  // University of Zululand - CORRECTED STRUCTURE
  {
    id: "unizulu",
    name: "University of Zululand",
    abbreviation: "UniZulu",
    fullName: "University of Zululand (UniZulu)",
    location: "Richards Bay",
    province: "KwaZulu-Natal",
    logo: "/logos/universities/university-of-zululand.svg",
    overview:
      "A comprehensive university rooted in African values and committed to academic excellence and community engagement.",
    website: "https://www.unizulu.ac.za",
    studentPortal: "https://students.unizulu.ac.za",
    admissionsContact: "admissions@unizulu.ac.za",
    establishedYear: 1960,
    studentPopulation: 16000,
    campuses: ["Richards Bay", "KwaDlangezwa"],
    applicationInfo: {
      isOpen: true,
      openingDate: "1 April 2024",
      closingDate: "30 September 2024",
      academicYear: "2025",
      applicationFee: "R220",
      applicationMethod: "Online via university website",
      lateApplications: {
        available: true,
        deadline: "31 October 2024",
        additionalFee: "R300",
      },
    },
    faculties: [
      {
        id: "science-agriculture-engineering",
        name: "Faculty of Science, Agriculture and Engineering",
        description:
          "Science, agricultural sciences, and engineering education with 15 departments including Computer Science, Mathematics, Physics, Chemistry, Agriculture, and Nursing.",
        degrees: [
          {
            id: "bsc-computer-science",
            name: "BSc Computer Science",
            faculty: "Faculty of Science, Agriculture and Engineering",
            duration: "3 years",
            apsRequirement: 26,
            description:
              "Computer science with practical software development focus.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Software Developer",
              "Systems Analyst",
              "Database Administrator",
              "IT Specialist",
              "Web Developer",
            ],
          },
          {
            id: "bsc-agriculture",
            name: "BSc Agriculture",
            faculty: "Faculty of Science, Agriculture and Engineering",
            duration: "4 years",
            apsRequirement: 24,
            description:
              "Agricultural sciences with sustainable farming focus.",
            subjects: [
              { name: "Life Sciences", level: 4, isRequired: true },
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Agricultural Scientist",
              "Farm Manager",
              "Extension Officer",
              "Agricultural Consultant",
              "Rural Development Officer",
            ],
          },
          {
            id: "bns-nursing",
            name: "Bachelor of Nursing Science",
            faculty: "Faculty of Science, Agriculture and Engineering",
            duration: "4 years",
            apsRequirement: 26,
            description: "Professional nursing education and training.",
            subjects: [
              { name: "English", level: 4, isRequired: true },
              { name: "Life Sciences", level: 4, isRequired: true },
              { name: "Mathematics", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Professional Nurse",
              "Community Health Nurse",
              "Clinical Nurse",
              "Nurse Manager",
              "Public Health Nurse",
            ],
          },
          {
            id: "bsc-mathematics",
            name: "BSc Mathematical Sciences",
            faculty: "Faculty of Science, Agriculture and Engineering",
            duration: "3 years",
            apsRequirement: 28,
            description:
              "Pure and applied mathematics with statistical analysis.",
            subjects: [
              { name: "Mathematics", level: 6, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Mathematician",
              "Statistician",
              "Data Analyst",
              "Actuary",
              "Research Scientist",
            ],
          },
          {
            id: "bsc-physics",
            name: "BSc Physics",
            faculty: "Faculty of Science, Agriculture and Engineering",
            duration: "3 years",
            apsRequirement: 30,
            description: "Physics with laboratory and research focus.",
            subjects: [
              { name: "Physical Sciences", level: 6, isRequired: true },
              { name: "Mathematics", level: 6, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Physicist",
              "Research Scientist",
              "Laboratory Technician",
              "Science Teacher",
              "Quality Control Analyst",
            ],
          },
          {
            id: "bsc-chemistry",
            name: "BSc Chemistry",
            faculty: "Faculty of Science, Agriculture and Engineering",
            duration: "3 years",
            apsRequirement: 28,
            description:
              "Chemistry with analytical and environmental applications.",
            subjects: [
              { name: "Physical Sciences", level: 6, isRequired: true },
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Chemist",
              "Laboratory Analyst",
              "Environmental Analyst",
              "Quality Control Specialist",
              "Research Technician",
            ],
          },
        ],
      },
      {
        id: "humanities-social-sciences",
        name: "Faculty of Humanities and Social Sciences",
        description:
          "The largest faculty at UniZulu with 16 departments covering humanities and social sciences including English, History, Psychology, and Communication Science.",
        degrees: [
          {
            id: "ba-english",
            name: "BA English",
            faculty: "Faculty of Humanities and Social Sciences",
            duration: "3 years",
            apsRequirement: 24,
            description: "English language and literature studies.",
            subjects: [{ name: "English", level: 5, isRequired: true }],
            careerProspects: [
              "English Teacher",
              "Writer",
              "Editor",
              "Journalist",
              "Communications Specialist",
            ],
          },
          {
            id: "ba-psychology",
            name: "BA Psychology",
            faculty: "Faculty of Humanities and Social Sciences",
            duration: "3 years",
            apsRequirement: 26,
            description: "Psychology with community and cultural focus.",
            subjects: [
              { name: "English", level: 4, isRequired: true },
              { name: "Mathematics", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Psychologist",
              "Counselor",
              "Social Worker",
              "Human Resources Specialist",
              "Research Assistant",
            ],
          },
          {
            id: "ba-social-work",
            name: "BA Social Work",
            faculty: "Faculty of Humanities and Social Sciences",
            duration: "4 years",
            apsRequirement: 24,
            description: "Professional social work training.",
            subjects: [
              { name: "English", level: 4, isRequired: true },
              { name: "Mathematics", level: 3, isRequired: true },
            ],
            careerProspects: [
              "Social Worker",
              "Community Development Officer",
              "Child Protection Officer",
              "Family Counselor",
              "NGO Manager",
            ],
          },
          {
            id: "ba-history",
            name: "BA History",
            faculty: "Faculty of Humanities and Social Sciences",
            duration: "3 years",
            apsRequirement: 22,
            description: "Historical studies with South African focus.",
            subjects: [{ name: "English", level: 4, isRequired: true }],
            careerProspects: [
              "Historian",
              "Museum Curator",
              "Heritage Officer",
              "History Teacher",
              "Cultural Specialist",
            ],
          },
          {
            id: "ba-communication-science",
            name: "BA Communication Science",
            faculty: "Faculty of Humanities and Social Sciences",
            duration: "3 years",
            apsRequirement: 24,
            description: "Communication theory and media studies.",
            subjects: [{ name: "English", level: 5, isRequired: true }],
            careerProspects: [
              "Communications Officer",
              "Media Specialist",
              "Public Relations Officer",
              "Journalist",
              "Marketing Coordinator",
            ],
          },
          {
            id: "ba-anthropology-development",
            name: "BA Anthropology and Development Studies",
            faculty: "Faculty of Humanities and Social Sciences",
            duration: "3 years",
            apsRequirement: 22,
            description: "Anthropology with development studies focus.",
            subjects: [{ name: "English", level: 4, isRequired: true }],
            careerProspects: [
              "Anthropologist",
              "Development Worker",
              "Community Researcher",
              "Cultural Consultant",
              "NGO Coordinator",
            ],
          },
        ],
      },
      {
        id: "commerce-administration-law",
        name: "Faculty of Commerce, Administration and Law",
        description:
          "Business, public administration, and legal education with 5 departments: Accounting, Business Management, Economics, Public Administration, and Law.",
        degrees: [
          {
            id: "bcom-accounting",
            name: "BCom Accounting and Auditing",
            faculty: "Faculty of Commerce, Administration and Law",
            duration: "3 years",
            apsRequirement: 26,
            description: "Professional accounting and auditing education.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Chartered Accountant",
              "Auditor",
              "Financial Manager",
              "Tax Practitioner",
              "Business Advisor",
            ],
          },
          {
            id: "bcom-business-management",
            name: "BCom Business Management",
            faculty: "Faculty of Commerce, Administration and Law",
            duration: "3 years",
            apsRequirement: 24,
            description: "Business management with human resources focus.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Business Manager",
              "Operations Manager",
              "Project Manager",
              "Human Resources Manager",
              "Management Consultant",
            ],
          },
          {
            id: "bcom-economics",
            name: "BCom Economics",
            faculty: "Faculty of Commerce, Administration and Law",
            duration: "3 years",
            apsRequirement: 26,
            description: "Economic theory and development economics.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Economist",
              "Policy Analyst",
              "Research Officer",
              "Financial Analyst",
              "Development Economist",
            ],
          },
          {
            id: "bpa-public-administration",
            name: "BPA Public Administration",
            faculty: "Faculty of Commerce, Administration and Law",
            duration: "3 years",
            apsRequirement: 24,
            description: "Public sector management and governance.",
            subjects: [
              { name: "English", level: 4, isRequired: true },
              { name: "Mathematics", level: 3, isRequired: true },
            ],
            careerProspects: [
              "Public Administrator",
              "Government Officer",
              "Municipal Manager",
              "Policy Officer",
              "Development Coordinator",
            ],
          },
          {
            id: "llb-law",
            name: "LLB Bachelor of Laws",
            faculty: "Faculty of Commerce, Administration and Law",
            duration: "4 years",
            apsRequirement: 28,
            description:
              "Comprehensive legal education including customary law.",
            subjects: [
              { name: "English", level: 5, isRequired: true },
              { name: "Mathematics", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Attorney",
              "Advocate",
              "Legal Advisor",
              "Magistrate",
              "Corporate Lawyer",
            ],
          },
        ],
      },
      {
        id: "education",
        name: "Faculty of Education",
        description:
          "Teacher training and educational development with 6 departments: Comparative Education, Curriculum Studies, Educational Administration, Educational Psychology, Foundations of Education, and Early Childhood Education.",
        degrees: [
          {
            id: "bed-foundation-phase",
            name: "BEd Foundation Phase",
            faculty: "Faculty of Education",
            duration: "4 years",
            apsRequirement: 22,
            description: "Teacher training for Grade R to Grade 3.",
            subjects: [
              { name: "English", level: 4, isRequired: true },
              { name: "Mathematics", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Foundation Phase Teacher",
              "Early Childhood Educator",
              "Primary School Teacher",
              "Curriculum Developer",
              "Educational Specialist",
            ],
          },
          {
            id: "bed-intermediate-phase",
            name: "BEd Intermediate Phase",
            faculty: "Faculty of Education",
            duration: "4 years",
            apsRequirement: 24,
            description: "Teacher training for Grade 4 to Grade 6.",
            subjects: [
              { name: "English", level: 4, isRequired: true },
              { name: "Mathematics", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Intermediate Phase Teacher",
              "Primary School Teacher",
              "Subject Specialist",
              "Educational Coordinator",
              "Curriculum Advisor",
            ],
          },
          {
            id: "bed-senior-fet-phase",
            name: "BEd Senior Phase and FET",
            faculty: "Faculty of Education",
            duration: "4 years",
            apsRequirement: 26,
            description: "Teacher training for Grade 7 to Grade 12.",
            subjects: [
              { name: "English", level: 4, isRequired: true },
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "Teaching Subject", level: 4, isRequired: true },
            ],
            careerProspects: [
              "High School Teacher",
              "Subject Head",
              "Educational Manager",
              "Curriculum Specialist",
              "Academic Coordinator",
            ],
          },
          {
            id: "bed-early-childhood",
            name: "BEd Early Childhood Education",
            faculty: "Faculty of Education",
            duration: "4 years",
            apsRequirement: 22,
            description:
              "Specialized early childhood development and education.",
            subjects: [
              { name: "English", level: 4, isRequired: true },
              { name: "Mathematics", level: 3, isRequired: true },
            ],
            careerProspects: [
              "Early Childhood Educator",
              "Preschool Teacher",
              "Childcare Director",
              "Child Development Specialist",
              "Educational Therapist",
            ],
          },
        ],
      },
    ],
  },

  // University of Johannesburg - CORRECTED STRUCTURE
  {
    id: "uj",
    name: "University of Johannesburg",
    abbreviation: "UJ",
    fullName: "University of Johannesburg (UJ)",
    location: "Johannesburg",
    province: "Gauteng",
    logo: "/logos/universities/university-of-johannesburg.svg",
    overview:
      "A vibrant, multicultural comprehensive university that combines academic excellence with innovation and sustainability.",
    website: "https://www.uj.ac.za",
    studentPortal: "https://student.uj.ac.za",
    admissionsContact: "admissions@uj.ac.za",
    establishedYear: 2005,
    studentPopulation: 50000,
    campuses: ["Auckland Park", "Bunting Road", "Doornfontein", "Soweto"],
    applicationInfo: {
      isOpen: true,
      openingDate: "1 April 2024",
      closingDate: "30 September 2024",
      academicYear: "2025",
      applicationFee: "R220",
      applicationMethod: "Online via UJ website",
      lateApplications: {
        available: true,
        deadline: "31 October 2024",
        additionalFee: "R300",
      },
    },
    faculties: [
      {
        id: "engineering-built-environment",
        name: "Faculty of Engineering and the Built Environment",
        description:
          "Engineering disciplines including Civil, Mechanical, Electrical, Industrial, and Mining Engineering, plus Built Environment programs.",
        degrees: [
          {
            id: "beng-civil",
            name: "BEng Civil Engineering",
            faculty: "Faculty of Engineering and the Built Environment",
            duration: "4 years",
            apsRequirement: 38,
            description:
              "Civil engineering with infrastructure development focus.",
            subjects: [
              { name: "Mathematics", level: 6, isRequired: true },
              { name: "Physical Sciences", level: 6, isRequired: true },
              { name: "English", level: 5, isRequired: true },
            ],
            careerProspects: [
              "Civil Engineer",
              "Structural Engineer",
              "Project Manager",
              "Infrastructure Developer",
              "Construction Manager",
            ],
          },
          {
            id: "beng-mechanical",
            name: "BEng Mechanical Engineering",
            faculty: "Faculty of Engineering and the Built Environment",
            duration: "4 years",
            apsRequirement: 38,
            description: "Mechanical engineering with manufacturing focus.",
            subjects: [
              { name: "Mathematics", level: 6, isRequired: true },
              { name: "Physical Sciences", level: 6, isRequired: true },
              { name: "English", level: 5, isRequired: true },
            ],
            careerProspects: [
              "Mechanical Engineer",
              "Design Engineer",
              "Manufacturing Engineer",
              "Automotive Engineer",
              "Project Manager",
            ],
          },
          {
            id: "beng-mining",
            name: "BEng Mining Engineering",
            faculty: "Faculty of Engineering and the Built Environment",
            duration: "4 years",
            apsRequirement: 36,
            description:
              "Mining engineering with focus on South African mining industry.",
            subjects: [
              { name: "Mathematics", level: 6, isRequired: true },
              { name: "Physical Sciences", level: 6, isRequired: true },
              { name: "English", level: 5, isRequired: true },
            ],
            careerProspects: [
              "Mining Engineer",
              "Mine Manager",
              "Mining Consultant",
              "Safety Engineer",
              "Rock Engineer",
            ],
          },
          {
            id: "barch-architecture",
            name: "Bachelor of Architecture",
            faculty: "Faculty of Engineering and the Built Environment",
            duration: "5 years",
            apsRequirement: 34,
            description: "Architectural design and urban planning.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "English", level: 5, isRequired: true },
            ],
            careerProspects: [
              "Architect",
              "Urban Designer",
              "Building Designer",
              "Project Architect",
              "Heritage Consultant",
            ],
          },
        ],
      },
      {
        id: "health-sciences",
        name: "Faculty of Health Sciences",
        description:
          "Health professions including Medicine, Nursing, Physiotherapy, and other health-related programs.",
        degrees: [
          {
            id: "mbchb-medicine",
            name: "MBChB Medicine and Surgery",
            faculty: "Faculty of Health Sciences",
            duration: "6 years",
            apsRequirement: 42,
            description: "Medical degree with community health focus.",
            subjects: [
              { name: "Mathematics", level: 6, isRequired: true },
              { name: "Physical Sciences", level: 6, isRequired: true },
              { name: "Life Sciences", level: 6, isRequired: true },
              { name: "English", level: 6, isRequired: true },
            ],
            careerProspects: [
              "Medical Doctor",
              "Specialist Physician",
              "General Practitioner",
              "Medical Researcher",
              "Public Health Officer",
            ],
          },
          {
            id: "bns-nursing",
            name: "Bachelor of Nursing Science",
            faculty: "Faculty of Health Sciences",
            duration: "4 years",
            apsRequirement: 30,
            description: "Professional nursing with community health emphasis.",
            subjects: [
              { name: "English", level: 4, isRequired: true },
              { name: "Life Sciences", level: 5, isRequired: true },
              { name: "Mathematics", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Professional Nurse",
              "Community Health Nurse",
              "Clinical Nurse",
              "Nurse Manager",
              "Public Health Nurse",
            ],
          },
          {
            id: "bsc-physiotherapy",
            name: "BSc Physiotherapy",
            faculty: "Faculty of Health Sciences",
            duration: "4 years",
            apsRequirement: 36,
            description: "Physical rehabilitation and movement therapy.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Life Sciences", level: 6, isRequired: true },
              { name: "Physical Sciences", level: 5, isRequired: true },
              { name: "English", level: 5, isRequired: true },
            ],
            careerProspects: [
              "Physiotherapist",
              "Sports Therapist",
              "Rehabilitation Specialist",
              "Private Practice Owner",
              "Research Physiotherapist",
            ],
          },
        ],
      },
      {
        id: "science",
        name: "Faculty of Science",
        description:
          "Natural sciences including Mathematics, Physics, Chemistry, Biology, Computer Science, and Geography.",
        degrees: [
          {
            id: "bsc-computer-science",
            name: "BSc Computer Science",
            faculty: "Faculty of Science",
            duration: "3 years",
            apsRequirement: 34,
            description:
              "Computer science with software development and data science focus.",
            subjects: [
              { name: "Mathematics", level: 6, isRequired: true },
              { name: "English", level: 5, isRequired: true },
            ],
            careerProspects: [
              "Software Developer",
              "Data Scientist",
              "Systems Analyst",
              "IT Consultant",
              "Software Engineer",
            ],
          },
          {
            id: "bsc-mathematics",
            name: "BSc Mathematics",
            faculty: "Faculty of Science",
            duration: "3 years",
            apsRequirement: 36,
            description: "Pure and applied mathematics with statistical focus.",
            subjects: [
              { name: "Mathematics", level: 7, isRequired: true },
              { name: "English", level: 5, isRequired: true },
            ],
            careerProspects: [
              "Mathematician",
              "Statistician",
              "Actuary",
              "Data Analyst",
              "Research Scientist",
            ],
          },
          {
            id: "bsc-physics",
            name: "BSc Physics",
            faculty: "Faculty of Science",
            duration: "3 years",
            apsRequirement: 38,
            description: "Physics with research and application focus.",
            subjects: [
              { name: "Physical Sciences", level: 6, isRequired: true },
              { name: "Mathematics", level: 7, isRequired: true },
              { name: "English", level: 5, isRequired: true },
            ],
            careerProspects: [
              "Physicist",
              "Research Scientist",
              "Data Analyst",
              "Engineering Physicist",
              "Quantitative Analyst",
            ],
          },
        ],
      },
      {
        id: "humanities",
        name: "Faculty of Humanities",
        description:
          "Liberal arts including Languages, History, Philosophy, Psychology, Sociology, and Arts.",
        degrees: [
          {
            id: "ba-psychology",
            name: "BA Psychology",
            faculty: "Faculty of Humanities",
            duration: "3 years",
            apsRequirement: 28,
            description: "Psychology with urban and multicultural focus.",
            subjects: [
              { name: "English", level: 5, isRequired: true },
              { name: "Mathematics", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Psychologist",
              "Counselor",
              "Human Resources Specialist",
              "Research Psychologist",
              "Social Worker",
            ],
          },
          {
            id: "ba-english",
            name: "BA English",
            faculty: "Faculty of Humanities",
            duration: "3 years",
            apsRequirement: 26,
            description: "English literature and language studies.",
            subjects: [{ name: "English", level: 6, isRequired: true }],
            careerProspects: [
              "English Teacher",
              "Writer",
              "Editor",
              "Journalist",
              "Communications Specialist",
            ],
          },
          {
            id: "ba-sociology",
            name: "BA Sociology",
            faculty: "Faculty of Humanities",
            duration: "3 years",
            apsRequirement: 26,
            description: "Sociology with urban studies focus.",
            subjects: [{ name: "English", level: 5, isRequired: true }],
            careerProspects: [
              "Sociologist",
              "Social Researcher",
              "Community Development Worker",
              "Policy Analyst",
              "Social Worker",
            ],
          },
        ],
      },
      {
        id: "economic-financial-sciences",
        name: "Faculty of Economic and Financial Sciences",
        description:
          "Business and economics including Accounting, Finance, Economics, and Business Management.",
        degrees: [
          {
            id: "bcom-accounting",
            name: "BCom Accounting",
            faculty: "Faculty of Economic and Financial Sciences",
            duration: "3 years",
            apsRequirement: 32,
            description: "Professional accounting education leading to CA(SA).",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "English", level: 5, isRequired: true },
            ],
            careerProspects: [
              "Chartered Accountant",
              "Financial Manager",
              "Auditor",
              "Tax Consultant",
              "Financial Analyst",
            ],
          },
          {
            id: "bcom-economics",
            name: "BCom Economics",
            faculty: "Faculty of Economic and Financial Sciences",
            duration: "3 years",
            apsRequirement: 30,
            description: "Economic theory and policy analysis.",
            subjects: [
              { name: "Mathematics", level: 6, isRequired: true },
              { name: "English", level: 5, isRequired: true },
            ],
            careerProspects: [
              "Economist",
              "Policy Analyst",
              "Financial Analyst",
              "Research Economist",
              "Investment Analyst",
            ],
          },
          {
            id: "bcom-finance",
            name: "BCom Finance",
            faculty: "Faculty of Economic and Financial Sciences",
            duration: "3 years",
            apsRequirement: 32,
            description: "Financial management and investment analysis.",
            subjects: [
              { name: "Mathematics", level: 6, isRequired: true },
              { name: "English", level: 5, isRequired: true },
            ],
            careerProspects: [
              "Financial Analyst",
              "Investment Banker",
              "Portfolio Manager",
              "Risk Manager",
              "Corporate Finance Manager",
            ],
          },
        ],
      },
      {
        id: "law",
        name: "Faculty of Law",
        description: "Legal education including LLB and related law programs.",
        degrees: [
          {
            id: "llb-law",
            name: "LLB Bachelor of Laws",
            faculty: "Faculty of Law",
            duration: "4 years",
            apsRequirement: 32,
            description: "Comprehensive legal education with practical focus.",
            subjects: [
              { name: "English", level: 6, isRequired: true },
              { name: "Mathematics", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Attorney",
              "Advocate",
              "Legal Advisor",
              "Corporate Lawyer",
              "Magistrate",
            ],
          },
        ],
      },
      {
        id: "education",
        name: "Faculty of Education",
        description:
          "Teacher training and educational studies for all phases of schooling.",
        degrees: [
          {
            id: "bed-foundation-phase",
            name: "BEd Foundation Phase",
            faculty: "Faculty of Education",
            duration: "4 years",
            apsRequirement: 26,
            description: "Teacher training for Grade R to Grade 3.",
            subjects: [
              { name: "English", level: 5, isRequired: true },
              { name: "Mathematics", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Foundation Phase Teacher",
              "Early Childhood Educator",
              "Primary School Teacher",
              "Educational Specialist",
              "Curriculum Developer",
            ],
          },
          {
            id: "bed-senior-fet-phase",
            name: "BEd Senior and FET Phase",
            faculty: "Faculty of Education",
            duration: "4 years",
            apsRequirement: 28,
            description: "Teacher training for Grade 7 to Grade 12.",
            subjects: [
              { name: "English", level: 5, isRequired: true },
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Teaching Subject", level: 5, isRequired: true },
            ],
            careerProspects: [
              "High School Teacher",
              "Subject Specialist",
              "Educational Manager",
              "Curriculum Specialist",
              "Academic Coordinator",
            ],
          },
        ],
      },
    ],
  },

  // University of Mpumalanga - COMPREHENSIVE STRUCTURE
  {
    id: "ump",
    name: "University of Mpumalanga",
    abbreviation: "UMP",
    fullName: "University of Mpumalanga (UMP)",
    location: "Nelspruit",
    province: "Mpumalanga",
    logo: "/logos/universities/university-of-mpumalanga.svg",
    overview:
      "A comprehensive university focusing on agricultural development, education, and economic growth in the Mpumalanga province.",
    website: "https://www.ump.ac.za",
    studentPortal: "https://student.ump.ac.za",
    admissionsContact: "admissions@ump.ac.za",
    establishedYear: 2014,
    studentPopulation: 5000,
    campuses: ["Nelspruit", "Mbombela"],
    applicationInfo: {
      isOpen: true,
      openingDate: "1 April 2024",
      closingDate: "30 September 2024",
      academicYear: "2025",
      applicationFee: "R200",
      applicationMethod: "Online via UMP application portal",
      lateApplications: {
        available: true,
        deadline: "31 October 2024",
        additionalFee: "R150",
      },
    },
    faculties: [
      {
        id: "agriculture-natural-sciences",
        name: "Faculty of Agriculture and Natural Sciences",
        description:
          "Agricultural sciences, environmental studies, and computing with practical focus.",
        degrees: [
          {
            id: "bsc-agriculture",
            name: "BSc Agriculture in Agricultural Extension and Rural Resource Management",
            faculty: "Agriculture and Natural Sciences",
            duration: "4 years",
            apsRequirement: 24,
            description:
              "Agricultural sciences with extension and rural development focus.",
            subjects: [
              { name: "Life Sciences", level: 4, isRequired: true },
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Agricultural Extension Officer",
              "Rural Development Specialist",
              "Farm Manager",
              "Agricultural Consultant",
              "Project Coordinator",
            ],
          },
          {
            id: "bsc-environmental-science",
            name: "BSc Environmental Science",
            faculty: "Agriculture and Natural Sciences",
            duration: "3 years",
            apsRequirement: 26,
            description:
              "Environmental science with conservation and sustainability focus.",
            subjects: [
              { name: "Life Sciences", level: 5, isRequired: true },
              { name: "Geography", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Environmental Scientist",
              "Conservation Officer",
              "Environmental Consultant",
              "Research Scientist",
              "Environmental Manager",
            ],
          },
          {
            id: "diploma-plant-production",
            name: "Diploma in Plant Production",
            faculty: "Agriculture and Natural Sciences",
            duration: "3 years",
            apsRequirement: 20,
            description: "Plant production with practical farming focus.",
            subjects: [
              { name: "Life Sciences", level: 3, isRequired: true },
              { name: "Mathematics", level: 3, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Plant Production Specialist",
              "Farm Supervisor",
              "Agricultural Technician",
              "Crop Advisor",
              "Nursery Manager",
            ],
          },
          {
            id: "diploma-nature-conservation",
            name: "Diploma in Nature Conservation",
            faculty: "Agriculture and Natural Sciences",
            duration: "3 years",
            apsRequirement: 22,
            description: "Nature conservation with field management focus.",
            subjects: [
              { name: "Life Sciences", level: 4, isRequired: true },
              { name: "Geography", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Conservation Officer",
              "Game Ranger",
              "Park Manager",
              "Environmental Educator",
              "Wildlife Specialist",
            ],
          },
          {
            id: "diploma-ict",
            name: "Diploma in Information and Communication Technology",
            faculty: "Agriculture and Natural Sciences",
            duration: "3 years",
            apsRequirement: 24,
            description: "ICT with application development focus.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "ICT Technician",
              "Application Developer",
              "Systems Support Specialist",
              "IT Consultant",
              "Web Developer",
            ],
          },
        ],
      },
      {
        id: "education",
        name: "Faculty of Education",
        description:
          "Teacher education with focus on foundation phase and early childhood development.",
        degrees: [
          {
            id: "bed-foundation-phase",
            name: "BEd Foundation Phase Teaching",
            faculty: "Education",
            duration: "4 years",
            apsRequirement: 22,
            description: "Teacher training for foundation phase (Grade R-3).",
            subjects: [
              { name: "English", level: 4, isRequired: true },
              { name: "Mathematics", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Foundation Phase Teacher",
              "Early Childhood Educator",
              "Primary School Teacher",
              "Curriculum Developer",
              "Educational Coordinator",
            ],
          },
          {
            id: "med-early-childhood",
            name: "MEd Early Childhood Education",
            faculty: "Education",
            duration: "2 years",
            apsRequirement: 28,
            description: "Advanced qualification in early childhood education.",
            subjects: [
              { name: "Bachelor's Degree", level: 6, isRequired: true },
            ],
            careerProspects: [
              "Educational Specialist",
              "Curriculum Developer",
              "Educational Researcher",
              "ECD Program Manager",
              "Educational Consultant",
            ],
          },
        ],
      },
      {
        id: "economics-development-business-sciences",
        name: "Faculty of Economics, Development and Business Sciences",
        description:
          "Economic development, business studies, and social sciences education.",
        degrees: [
          {
            id: "bcom-general",
            name: "BCom General",
            faculty: "Economics, Development and Business Sciences",
            duration: "3 years",
            apsRequirement: 24,
            description: "General commerce with broad business foundation.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 5, isRequired: true },
            ],
            careerProspects: [
              "Business Analyst",
              "Management Trainee",
              "Administrative Officer",
              "Sales Manager",
              "Business Consultant",
            ],
          },
          {
            id: "bachelor-development-studies",
            name: "Bachelor of Development Studies",
            faculty: "Economics, Development and Business Sciences",
            duration: "3 years",
            apsRequirement: 22,
            description: "Development studies with community focus.",
            subjects: [{ name: "English", level: 4, isRequired: true }],
            careerProspects: [
              "Development Officer",
              "Project Coordinator",
              "NGO Manager",
              "Community Developer",
              "Policy Analyst",
            ],
          },
          {
            id: "bachelor-administration",
            name: "Bachelor of Administration",
            faculty: "Economics, Development and Business Sciences",
            duration: "3 years",
            apsRequirement: 22,
            description: "Administration with public sector focus.",
            subjects: [{ name: "English", level: 4, isRequired: true }],
            careerProspects: [
              "Administrative Officer",
              "Government Official",
              "Municipal Officer",
              "Office Manager",
              "Public Servant",
            ],
          },
          {
            id: "diploma-hospitality-management",
            name: "Diploma in Hospitality Management",
            faculty: "Economics, Development and Business Sciences",
            duration: "3 years",
            apsRequirement: 20,
            description: "Hospitality management with tourism focus.",
            subjects: [{ name: "English", level: 4, isRequired: true }],
            careerProspects: [
              "Hotel Manager",
              "Restaurant Manager",
              "Tourism Officer",
              "Event Coordinator",
              "Guest Relations Manager",
            ],
          },
          {
            id: "ba-arts",
            name: "Bachelor of Arts",
            faculty: "Economics, Development and Business Sciences",
            duration: "3 years",
            apsRequirement: 20,
            description: "Liberal arts with social sciences focus.",
            subjects: [{ name: "English", level: 4, isRequired: true }],
            careerProspects: [
              "Social Worker",
              "Community Worker",
              "Research Assistant",
              "Administrative Officer",
              "Cultural Officer",
            ],
          },
        ],
      },
    ],
  },
];
