import { Degree } from "@/types/university";

// Comprehensive database of all university programs with APS scores
// Based on 2024/2025 admission requirements across South African universities

export const ENGINEERING_PROGRAMS: Degree[] = [
  // Faculty of Engineering / Engineering and Built Environment
  {
    id: "bsc-eng-civil",
    name: "BSc Engineering - Civil Engineering",
    faculty: "Engineering",
    duration: "4 years",
    apsRequirement: 38,
    description:
      "Design and construction of infrastructure including roads, bridges, buildings, and water systems.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Civil Engineer",
      "Structural Engineer",
      "Water Resources Engineer",
      "Transportation Engineer",
      "Construction Manager",
    ],
  },
  {
    id: "bsc-eng-mechanical",
    name: "BSc Engineering - Mechanical Engineering",
    faculty: "Engineering",
    duration: "4 years",
    apsRequirement: 40,
    description:
      "Design, development, and manufacturing of mechanical systems and machines.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Mechanical Engineer",
      "Design Engineer",
      "Manufacturing Engineer",
      "Automotive Engineer",
      "Aerospace Engineer",
    ],
  },
  {
    id: "bsc-eng-electrical",
    name: "BSc Engineering - Electrical Engineering",
    faculty: "Engineering",
    duration: "4 years",
    apsRequirement: 40,
    description:
      "Electrical systems, power generation, electronics, and telecommunications.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Electrical Engineer",
      "Electronics Engineer",
      "Power Systems Engineer",
      "Control Systems Engineer",
      "Telecommunications Engineer",
    ],
  },
  {
    id: "bsc-eng-chemical",
    name: "BSc Engineering - Chemical Engineering",
    faculty: "Engineering",
    duration: "4 years",
    apsRequirement: 40,
    description:
      "Chemical processes, material design, and industrial applications.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Chemical Engineer",
      "Process Engineer",
      "Environmental Engineer",
      "Materials Engineer",
      "Petroleum Engineer",
    ],
  },
  {
    id: "bsc-eng-industrial",
    name: "BSc Engineering - Industrial Engineering",
    faculty: "Engineering",
    duration: "4 years",
    apsRequirement: 38,
    description:
      "Optimization of complex systems, processes, and organizations.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Industrial Engineer",
      "Operations Manager",
      "Quality Engineer",
      "Supply Chain Manager",
      "Management Consultant",
    ],
  },
  {
    id: "bsc-eng-computer",
    name: "BSc Engineering - Computer Engineering",
    faculty: "Engineering",
    duration: "4 years",
    apsRequirement: 42,
    description:
      "Hardware and software integration, embedded systems, and computer architecture.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Computer Engineer",
      "Software Engineer",
      "Hardware Engineer",
      "Systems Engineer",
      "Embedded Systems Developer",
    ],
  },
  {
    id: "bsc-eng-mechatronics",
    name: "BSc Engineering - Mechatronics",
    faculty: "Engineering",
    duration: "4 years",
    apsRequirement: 40,
    description:
      "Integration of mechanical, electrical, and computer engineering for automated systems.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Mechatronics Engineer",
      "Robotics Engineer",
      "Automation Engineer",
      "Control Systems Engineer",
      "Product Development Engineer",
    ],
  },
  {
    id: "bsc-eng-mining",
    name: "BSc Engineering - Mining Engineering",
    faculty: "Engineering",
    duration: "4 years",
    apsRequirement: 36,
    description: "Extraction of minerals and management of mining operations.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Mining Engineer",
      "Mine Manager",
      "Mineral Processing Engineer",
      "Geological Engineer",
      "Safety Engineer",
    ],
  },
  {
    id: "bsc-eng-environmental",
    name: "BSc Engineering - Environmental Engineering",
    faculty: "Engineering",
    duration: "4 years",
    apsRequirement: 36,
    description:
      "Environmental protection and sustainable development solutions.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Environmental Engineer",
      "Water Treatment Engineer",
      "Air Quality Engineer",
      "Waste Management Engineer",
      "Sustainability Consultant",
    ],
  },
  {
    id: "bsc-eng-agricultural",
    name: "BSc Engineering - Agricultural Engineering",
    faculty: "Engineering",
    duration: "4 years",
    apsRequirement: 34,
    description:
      "Engineering solutions for agricultural production and food processing.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Agricultural Engineer",
      "Food Processing Engineer",
      "Irrigation Engineer",
      "Farm Equipment Designer",
      "Agricultural Consultant",
    ],
  },
  {
    id: "bsc-structural-engineering",
    name: "BSc Structural Engineering",
    faculty: "Engineering",
    duration: "4 years",
    apsRequirement: 38,
    description:
      "Design and analysis of buildings, bridges, and other structures.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Structural Engineer",
      "Bridge Engineer",
      "Building Designer",
      "Earthquake Engineer",
      "Forensic Engineer",
    ],
  },
  {
    id: "bsc-transport-engineering",
    name: "BSc Transport Engineering",
    faculty: "Engineering",
    duration: "4 years",
    apsRequirement: 36,
    description: "Transportation systems design and traffic management.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Transportation Engineer",
      "Traffic Engineer",
      "Public Transport Planner",
      "Highway Engineer",
      "Logistics Engineer",
    ],
  },
  {
    id: "bsc-water-resources-engineering",
    name: "BSc Water Resources Engineering",
    faculty: "Engineering",
    duration: "4 years",
    apsRequirement: 36,
    description:
      "Water supply, distribution, and environmental water management.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Water Resources Engineer",
      "Hydraulic Engineer",
      "Dam Engineer",
      "Irrigation Engineer",
      "Water Quality Engineer",
    ],
  },
  {
    id: "bsc-geotechnical-engineering",
    name: "BSc Geotechnical Engineering",
    faculty: "Engineering",
    duration: "4 years",
    apsRequirement: 36,
    description: "Soil and rock mechanics for foundation and earthwork design.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Geotechnical Engineer",
      "Foundation Engineer",
      "Soil Mechanics Engineer",
      "Earthquake Engineer",
      "Tunnel Engineer",
    ],
  },
  {
    id: "bsc-construction-management",
    name: "BSc Construction Management",
    faculty: "Engineering",
    duration: "4 years",
    apsRequirement: 32,
    description:
      "Project management and coordination of construction projects.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "Physical Sciences", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Construction Manager",
      "Project Manager",
      "Site Manager",
      "Building Contractor",
      "Construction Consultant",
    ],
  },
  {
    id: "bsc-quantity-surveying",
    name: "BSc Quantity Surveying",
    faculty: "Engineering",
    duration: "4 years",
    apsRequirement: 32,
    description:
      "Cost management and financial control of construction projects.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Accounting", level: 4, isRequired: false },
    ],
    careerProspects: [
      "Quantity Surveyor",
      "Cost Estimator",
      "Project Cost Manager",
      "Construction Economist",
      "Contract Administrator",
    ],
  },
  {
    id: "bsc-urban-regional-planning",
    name: "BSc Urban and Regional Planning",
    faculty: "Engineering",
    duration: "4 years",
    apsRequirement: 30,
    description:
      "City planning, land use management, and regional development.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Geography", level: 4, isRequired: false },
    ],
    careerProspects: [
      "Urban Planner",
      "Regional Planner",
      "Land Use Planner",
      "Municipal Planner",
      "Development Consultant",
    ],
  },
  {
    id: "barch-architecture",
    name: "Bachelor of Architecture",
    faculty: "Engineering",
    duration: "5 years",
    apsRequirement: 34,
    description: "Architectural design and building planning.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Visual Arts", level: 4, isRequired: false },
    ],
    careerProspects: [
      "Architect",
      "Building Designer",
      "Project Architect",
      "Urban Designer",
      "Heritage Consultant",
    ],
  },
  {
    id: "bsc-building-science",
    name: "BSc Building Science",
    faculty: "Engineering",
    duration: "4 years",
    apsRequirement: 32,
    description:
      "Building technology, materials science, and construction methods.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "Physical Sciences", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Building Scientist",
      "Building Inspector",
      "Materials Specialist",
      "Building Performance Analyst",
      "Construction Technologist",
    ],
  },
  {
    id: "bsc-interior-architecture",
    name: "BSc Interior Architecture",
    faculty: "Engineering",
    duration: "4 years",
    apsRequirement: 30,
    description: "Interior space design and environmental planning.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Visual Arts", level: 4, isRequired: false },
    ],
    careerProspects: [
      "Interior Architect",
      "Interior Designer",
      "Space Planner",
      "Furniture Designer",
      "Design Consultant",
    ],
  },
  {
    id: "bsc-landscape-architecture",
    name: "BSc Landscape Architecture",
    faculty: "Engineering",
    duration: "4 years",
    apsRequirement: 30,
    description: "Outdoor space design and environmental landscape planning.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Life Sciences", level: 4, isRequired: false },
    ],
    careerProspects: [
      "Landscape Architect",
      "Environmental Designer",
      "Park Planner",
      "Garden Designer",
      "Conservation Planner",
    ],
  },
  {
    id: "bsc-urban-design",
    name: "BSc Urban Design",
    faculty: "Engineering",
    duration: "4 years",
    apsRequirement: 32,
    description: "Urban environment design and city planning principles.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Geography", level: 4, isRequired: false },
    ],
    careerProspects: [
      "Urban Designer",
      "City Planner",
      "Development Planner",
      "Public Space Designer",
      "Transportation Planner",
    ],
  },
];

export const HEALTH_SCIENCES_PROGRAMS: Degree[] = [
  // Faculty of Health Sciences / Medicine and Health
  {
    id: "mbchb-medicine-surgery",
    name: "MBChB Medicine and Surgery",
    faculty: "Health Sciences",
    duration: "6 years",
    apsRequirement: 42,
    description:
      "Comprehensive medical training leading to medical doctor qualification.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "English", level: 6, isRequired: true },
    ],
    careerProspects: [
      "Medical Doctor",
      "Specialist Physician",
      "Surgeon",
      "General Practitioner",
      "Medical Researcher",
    ],
  },
  {
    id: "bds-dental-surgery",
    name: "BDS Dental Surgery",
    faculty: "Health Sciences",
    duration: "5 years",
    apsRequirement: 40,
    description: "Comprehensive dental education and training.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Dentist",
      "Oral Surgeon",
      "Orthodontist",
      "Dental Specialist",
      "Dental Researcher",
    ],
  },
  {
    id: "bpharm-pharmacy",
    name: "BPharm Pharmacy",
    faculty: "Health Sciences",
    duration: "4 years",
    apsRequirement: 38,
    description: "Pharmaceutical sciences and pharmacy practice.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Pharmacist",
      "Clinical Pharmacist",
      "Hospital Pharmacist",
      "Community Pharmacist",
      "Pharmaceutical Researcher",
    ],
  },
  {
    id: "bsc-physiotherapy",
    name: "BSc Physiotherapy",
    faculty: "Health Sciences",
    duration: "4 years",
    apsRequirement: 36,
    description: "Physical rehabilitation and movement therapy.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Physiotherapist",
      "Sports Therapist",
      "Rehabilitation Specialist",
      "Pediatric Physiotherapist",
      "Neurological Physiotherapist",
    ],
  },
  {
    id: "bsc-occupational-therapy",
    name: "BSc Occupational Therapy",
    faculty: "Health Sciences",
    duration: "4 years",
    apsRequirement: 34,
    description:
      "Helping people participate in daily activities through therapy.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Occupational Therapist",
      "Rehabilitation Specialist",
      "Pediatric Therapist",
      "Mental Health Therapist",
      "Community Health Worker",
    ],
  },
  {
    id: "bsc-radiography",
    name: "BSc Radiography",
    faculty: "Health Sciences",
    duration: "4 years",
    apsRequirement: 34,
    description: "Medical imaging and radiation therapy.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "Life Sciences", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Radiographer",
      "Medical Imaging Technologist",
      "Radiation Therapist",
      "Nuclear Medicine Technologist",
      "Ultrasound Technologist",
    ],
  },
  {
    id: "bns-nursing-science",
    name: "BNS Nursing Science",
    faculty: "Health Sciences",
    duration: "4 years",
    apsRequirement: 32,
    description: "Professional nursing education with clinical practice.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "Life Sciences", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Professional Nurse",
      "Nurse Manager",
      "Clinical Nurse Specialist",
      "Community Health Nurse",
      "Nursing Educator",
    ],
  },
  {
    id: "bcmp-clinical-medical-practice",
    name: "BCMP Clinical Medical Practice",
    faculty: "Health Sciences",
    duration: "3 years",
    apsRequirement: 36,
    description: "Clinical medical practice for healthcare assistants.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Clinical Medical Practitioner",
      "Healthcare Assistant",
      "Medical Technician",
      "Clinical Officer",
      "Primary Healthcare Worker",
    ],
  },
  {
    id: "bemc-emergency-medical-care",
    name: "BEMC Emergency Medical Care",
    faculty: "Health Sciences",
    duration: "4 years",
    apsRequirement: 34,
    description: "Emergency medical services and paramedic training.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Paramedic",
      "Emergency Medical Technician",
      "Emergency Room Technician",
      "Flight Paramedic",
      "Emergency Services Manager",
    ],
  },
  {
    id: "bmedsci-medical-science",
    name: "BMedSci Medical Science",
    faculty: "Health Sciences",
    duration: "3 years",
    apsRequirement: 38,
    description: "Medical sciences foundation for healthcare careers.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Medical Researcher",
      "Laboratory Scientist",
      "Clinical Research Coordinator",
      "Biomedical Scientist",
      "Medical Writer",
    ],
  },
  {
    id: "bsc-biomedical-science",
    name: "BSc Biomedical Science",
    faculty: "Health Sciences",
    duration: "3 years",
    apsRequirement: 36,
    description: "Study of human biology and disease mechanisms.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "Physical Sciences", level: 5, isRequired: true },
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Biomedical Scientist",
      "Medical Laboratory Scientist",
      "Research Scientist",
      "Clinical Laboratory Technologist",
      "Pharmaceutical Researcher",
    ],
  },
  {
    id: "bmls-medical-laboratory-science",
    name: "BMLS Medical Laboratory Science",
    faculty: "Health Sciences",
    duration: "4 years",
    apsRequirement: 34,
    description: "Laboratory diagnostics and medical testing.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Medical Laboratory Scientist",
      "Laboratory Manager",
      "Quality Control Specialist",
      "Research Technologist",
      "Clinical Laboratory Director",
    ],
  },
  {
    id: "boptom-optometry",
    name: "BOptom Optometry",
    faculty: "Health Sciences",
    duration: "4 years",
    apsRequirement: 36,
    description: "Eye care and vision health services.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Optometrist",
      "Eye Care Specialist",
      "Vision Therapist",
      "Contact Lens Specialist",
      "Low Vision Specialist",
    ],
  },
  {
    id: "bsc-speech-language-pathology",
    name: "BSc Speech-Language Pathology",
    faculty: "Health Sciences",
    duration: "4 years",
    apsRequirement: 32,
    description: "Communication disorders assessment and treatment.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "Life Sciences", level: 5, isRequired: true },
      { name: "English", level: 6, isRequired: true },
    ],
    careerProspects: [
      "Speech-Language Pathologist",
      "Communication Therapist",
      "Speech Therapist",
      "Language Development Specialist",
      "Swallowing Specialist",
    ],
  },
  {
    id: "bsc-audiology",
    name: "BSc Audiology",
    faculty: "Health Sciences",
    duration: "4 years",
    apsRequirement: 32,
    description: "Hearing and balance disorders assessment and treatment.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "Physical Sciences", level: 5, isRequired: true },
      { name: "Life Sciences", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Audiologist",
      "Hearing Aid Specialist",
      "Balance Disorder Specialist",
      "Pediatric Audiologist",
      "Industrial Audiologist",
    ],
  },
  {
    id: "bsc-dietetics",
    name: "BSc Dietetics",
    faculty: "Health Sciences",
    duration: "4 years",
    apsRequirement: 34,
    description: "Nutrition science and dietary therapy for health promotion.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Dietitian",
      "Nutritionist",
      "Sports Nutritionist",
      "Clinical Dietitian",
      "Public Health Nutritionist",
    ],
  },
  {
    id: "bsc-environmental-health",
    name: "BSc Environmental Health",
    faculty: "Health Sciences",
    duration: "4 years",
    apsRequirement: 30,
    description: "Environmental factors affecting human health.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "Life Sciences", level: 5, isRequired: true },
      { name: "Physical Sciences", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Environmental Health Officer",
      "Public Health Inspector",
      "Environmental Consultant",
      "Occupational Health Specialist",
      "Food Safety Inspector",
    ],
  },
  {
    id: "bsc-public-health",
    name: "BSc Public Health",
    faculty: "Health Sciences",
    duration: "4 years",
    apsRequirement: 30,
    description: "Population health promotion and disease prevention.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "Life Sciences", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Public Health Officer",
      "Health Promotion Specialist",
      "Epidemiologist",
      "Health Policy Analyst",
      "Community Health Manager",
    ],
  },
  {
    id: "bsc-medical-imaging",
    name: "BSc Medical Imaging",
    faculty: "Health Sciences",
    duration: "4 years",
    apsRequirement: 34,
    description: "Advanced medical imaging technologies and techniques.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "Life Sciences", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Medical Imaging Technologist",
      "MRI Technologist",
      "CT Scan Technologist",
      "Ultrasound Technologist",
      "Nuclear Medicine Technologist",
    ],
  },
  {
    id: "bsc-clinical-technology",
    name: "BSc Clinical Technology",
    faculty: "Health Sciences",
    duration: "4 years",
    apsRequirement: 32,
    description: "Clinical technology and medical equipment management.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "Physical Sciences", level: 5, isRequired: true },
      { name: "Life Sciences", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Clinical Technologist",
      "Medical Equipment Technician",
      "Biomedical Engineer",
      "Clinical Laboratory Technologist",
      "Medical Device Specialist",
    ],
  },
];

export const HUMANITIES_PROGRAMS: Degree[] = [
  // Faculty of Humanities / Arts and Social Sciences
  {
    id: "ba-english",
    name: "BA English",
    faculty: "Humanities",
    duration: "3 years",
    apsRequirement: 28,
    description: "Literature, language studies, and communication skills.",
    subjects: [
      { name: "English", level: 6, isRequired: true },
      { name: "Mathematics", level: 3, isRequired: true },
    ],
    careerProspects: [
      "English Teacher",
      "Editor",
      "Journalist",
      "Writer",
      "Communications Specialist",
    ],
  },
  {
    id: "ba-history",
    name: "BA History",
    faculty: "Humanities",
    duration: "3 years",
    apsRequirement: 26,
    description: "Historical research, analysis, and interpretation.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 3, isRequired: true },
      { name: "History", level: 5, isRequired: false },
    ],
    careerProspects: [
      "Historian",
      "Museum Curator",
      "Archivist",
      "History Teacher",
      "Cultural Heritage Officer",
    ],
  },
  {
    id: "ba-philosophy",
    name: "BA Philosophy",
    faculty: "Humanities",
    duration: "3 years",
    apsRequirement: 28,
    description: "Critical thinking, ethics, and philosophical inquiry.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
    ],
    careerProspects: [
      "Philosophy Teacher",
      "Ethics Consultant",
      "Policy Analyst",
      "Writer",
      "Legal Advisor",
    ],
  },
  {
    id: "ba-sociology",
    name: "BA Sociology",
    faculty: "Humanities",
    duration: "3 years",
    apsRequirement: 26,
    description: "Study of society, social behavior, and social structures.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 3, isRequired: true },
    ],
    careerProspects: [
      "Sociologist",
      "Social Researcher",
      "Community Development Officer",
      "Policy Analyst",
      "Social Worker",
    ],
  },
  {
    id: "ba-psychology",
    name: "BA Psychology",
    faculty: "Humanities",
    duration: "3 years",
    apsRequirement: 30,
    description: "Study of human behavior, cognition, and mental processes.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "Life Sciences", level: 4, isRequired: false },
    ],
    careerProspects: [
      "Psychologist",
      "Counselor",
      "Human Resources Specialist",
      "Research Psychologist",
      "Educational Psychologist",
    ],
  },
  {
    id: "ba-political-science",
    name: "BA Political Science",
    faculty: "Humanities",
    duration: "3 years",
    apsRequirement: 28,
    description: "Political systems, governance, and public policy analysis.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 3, isRequired: true },
      { name: "History", level: 4, isRequired: false },
    ],
    careerProspects: [
      "Political Analyst",
      "Government Officer",
      "Diplomat",
      "Journalist",
      "Policy Researcher",
    ],
  },
  {
    id: "ba-anthropology",
    name: "BA Anthropology",
    faculty: "Humanities",
    duration: "3 years",
    apsRequirement: 26,
    description: "Study of human societies, cultures, and evolution.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 3, isRequired: true },
    ],
    careerProspects: [
      "Anthropologist",
      "Cultural Researcher",
      "Museum Curator",
      "Social Development Officer",
      "Heritage Consultant",
    ],
  },
  {
    id: "ba-archaeology",
    name: "BA Archaeology",
    faculty: "Humanities",
    duration: "3 years",
    apsRequirement: 26,
    description: "Study of human history through material remains.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 3, isRequired: true },
      { name: "History", level: 4, isRequired: false },
    ],
    careerProspects: [
      "Archaeologist",
      "Museum Curator",
      "Heritage Specialist",
      "Cultural Resource Manager",
      "Historical Researcher",
    ],
  },
  {
    id: "ba-linguistics",
    name: "BA Linguistics",
    faculty: "Humanities",
    duration: "3 years",
    apsRequirement: 28,
    description: "Scientific study of language structure and development.",
    subjects: [
      { name: "English", level: 6, isRequired: true },
      { name: "Mathematics", level: 3, isRequired: true },
    ],
    careerProspects: [
      "Linguist",
      "Language Teacher",
      "Translator",
      "Speech Therapist",
      "Language Researcher",
    ],
  },
  {
    id: "ba-geography",
    name: "BA Geography",
    faculty: "Humanities",
    duration: "3 years",
    apsRequirement: 26,
    description: "Physical and human geography, spatial analysis.",
    subjects: [
      { name: "English", level: 4, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "Geography", level: 5, isRequired: false },
    ],
    careerProspects: [
      "Geographer",
      "Urban Planner",
      "GIS Specialist",
      "Environmental Consultant",
      "Geography Teacher",
    ],
  },
  {
    id: "ba-fine-arts",
    name: "BA Fine Arts",
    faculty: "Humanities",
    duration: "3 years",
    apsRequirement: 24,
    description: "Visual arts, painting, sculpture, and art theory.",
    subjects: [
      { name: "English", level: 4, isRequired: true },
      { name: "Visual Arts", level: 5, isRequired: false },
    ],
    careerProspects: [
      "Fine Artist",
      "Art Teacher",
      "Gallery Curator",
      "Art Therapist",
      "Art Critic",
    ],
  },
  {
    id: "ba-music",
    name: "BA Music",
    faculty: "Humanities",
    duration: "3 years",
    apsRequirement: 24,
    description: "Music theory, performance, and composition.",
    subjects: [
      { name: "English", level: 4, isRequired: true },
      { name: "Music", level: 5, isRequired: false },
    ],
    careerProspects: [
      "Musician",
      "Music Teacher",
      "Composer",
      "Music Producer",
      "Music Therapist",
    ],
  },
  {
    id: "ba-theatre-arts",
    name: "BA Theatre Arts",
    faculty: "Humanities",
    duration: "3 years",
    apsRequirement: 24,
    description: "Theatre performance, directing, and production.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Dramatic Arts", level: 5, isRequired: false },
    ],
    careerProspects: [
      "Actor",
      "Theatre Director",
      "Drama Teacher",
      "Theatre Producer",
      "Arts Administrator",
    ],
  },
  {
    id: "ba-film-media-studies",
    name: "BA Film and Media Studies",
    faculty: "Humanities",
    duration: "3 years",
    apsRequirement: 26,
    description:
      "Film production, media analysis, and digital content creation.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 3, isRequired: true },
    ],
    careerProspects: [
      "Film Director",
      "Media Producer",
      "Film Critic",
      "Content Creator",
      "Cinematographer",
    ],
  },
  {
    id: "ba-religious-studies",
    name: "BA Religious Studies",
    faculty: "Humanities",
    duration: "3 years",
    apsRequirement: 24,
    description: "Comparative religion, theology, and spiritual studies.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 3, isRequired: true },
    ],
    careerProspects: [
      "Religious Leader",
      "Chaplain",
      "Religious Education Teacher",
      "Interfaith Coordinator",
      "Community Minister",
    ],
  },
  {
    id: "ba-gender-studies",
    name: "BA Gender Studies",
    faculty: "Humanities",
    duration: "3 years",
    apsRequirement: 26,
    description: "Gender theory, equality studies, and social justice.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 3, isRequired: true },
    ],
    careerProspects: [
      "Gender Equality Officer",
      "Social Researcher",
      "NGO Worker",
      "Policy Analyst",
      "Human Rights Advocate",
    ],
  },
  {
    id: "ba-african-studies",
    name: "BA African Studies",
    faculty: "Humanities",
    duration: "3 years",
    apsRequirement: 24,
    description: "African history, culture, politics, and development.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 3, isRequired: true },
      { name: "History", level: 4, isRequired: false },
    ],
    careerProspects: [
      "African Studies Researcher",
      "Cultural Consultant",
      "Development Worker",
      "Diplomat",
      "Heritage Officer",
    ],
  },
  {
    id: "ba-development-studies",
    name: "BA Development Studies",
    faculty: "Humanities",
    duration: "3 years",
    apsRequirement: 26,
    description:
      "Economic development, poverty alleviation, and social change.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
    ],
    careerProspects: [
      "Development Officer",
      "NGO Manager",
      "Project Coordinator",
      "Policy Analyst",
      "Community Development Worker",
    ],
  },
  {
    id: "ba-international-relations",
    name: "BA International Relations",
    faculty: "Humanities",
    duration: "3 years",
    apsRequirement: 30,
    description: "Global politics, diplomacy, and international affairs.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "History", level: 4, isRequired: false },
    ],
    careerProspects: [
      "Diplomat",
      "International Relations Analyst",
      "Foreign Affairs Officer",
      "Journalist",
      "NGO International Officer",
    ],
  },
  {
    id: "ba-communication-science",
    name: "BA Communication Science",
    faculty: "Humanities",
    duration: "3 years",
    apsRequirement: 28,
    description: "Communication theory, media studies, and public relations.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 3, isRequired: true },
    ],
    careerProspects: [
      "Communications Specialist",
      "Public Relations Officer",
      "Media Consultant",
      "Corporate Communications Manager",
      "Social Media Manager",
    ],
  },
  {
    id: "ba-journalism",
    name: "BA Journalism",
    faculty: "Humanities",
    duration: "3 years",
    apsRequirement: 28,
    description: "News reporting, investigative journalism, and media ethics.",
    subjects: [
      { name: "English", level: 6, isRequired: true },
      { name: "Mathematics", level: 3, isRequired: true },
    ],
    careerProspects: [
      "Journalist",
      "News Reporter",
      "Editor",
      "News Anchor",
      "Investigative Reporter",
    ],
  },
  {
    id: "ba-public-relations",
    name: "BA Public Relations",
    faculty: "Humanities",
    duration: "3 years",
    apsRequirement: 26,
    description:
      "Public relations strategy, crisis communication, and brand management.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 3, isRequired: true },
    ],
    careerProspects: [
      "Public Relations Manager",
      "Communications Consultant",
      "Event Manager",
      "Marketing Communications Specialist",
      "Crisis Communications Manager",
    ],
  },
  {
    id: "ba-publishing",
    name: "BA Publishing",
    faculty: "Humanities",
    duration: "3 years",
    apsRequirement: 26,
    description: "Book publishing, editorial work, and literary production.",
    subjects: [
      { name: "English", level: 6, isRequired: true },
      { name: "Mathematics", level: 3, isRequired: true },
    ],
    careerProspects: [
      "Publisher",
      "Editor",
      "Literary Agent",
      "Book Designer",
      "Publishing Manager",
    ],
  },
  {
    id: "ba-translation-interpreting",
    name: "BA Translation and Interpreting",
    faculty: "Humanities",
    duration: "3 years",
    apsRequirement: 28,
    description: "Language translation and interpretation services.",
    subjects: [
      { name: "English", level: 6, isRequired: true },
      { name: "Additional Language", level: 5, isRequired: true },
      { name: "Mathematics", level: 3, isRequired: true },
    ],
    careerProspects: [
      "Translator",
      "Interpreter",
      "Language Services Manager",
      "Localization Specialist",
      "Court Interpreter",
    ],
  },
  {
    id: "ba-creative-writing",
    name: "BA Creative Writing",
    faculty: "Humanities",
    duration: "3 years",
    apsRequirement: 26,
    description:
      "Fiction writing, poetry, screenwriting, and literary creation.",
    subjects: [
      { name: "English", level: 6, isRequired: true },
      { name: "Mathematics", level: 3, isRequired: true },
    ],
    careerProspects: [
      "Author",
      "Screenwriter",
      "Poet",
      "Content Writer",
      "Literary Editor",
    ],
  },
];

export const COMMERCE_PROGRAMS: Degree[] = [
  // Faculty of Commerce / Business and Management
  {
    id: "bcom-accounting",
    name: "BCom Accounting",
    faculty: "Commerce",
    duration: "3 years",
    apsRequirement: 34,
    description: "Professional accounting education with CA(SA) pathway.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Accounting", level: 5, isRequired: false },
    ],
    careerProspects: [
      "Chartered Accountant",
      "Financial Manager",
      "Auditor",
      "Tax Consultant",
      "Financial Analyst",
    ],
  },
  {
    id: "bcom-finance",
    name: "BCom Finance",
    faculty: "Commerce",
    duration: "3 years",
    apsRequirement: 32,
    description:
      "Financial management, investment analysis, and corporate finance.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Financial Analyst",
      "Investment Banker",
      "Portfolio Manager",
      "Financial Planner",
      "Risk Manager",
    ],
  },
  {
    id: "bcom-economics",
    name: "BCom Economics",
    faculty: "Commerce",
    duration: "3 years",
    apsRequirement: 32,
    description:
      "Economic theory and analysis for policy and business applications.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Economist",
      "Policy Analyst",
      "Financial Analyst",
      "Research Economist",
      "Investment Analyst",
    ],
  },
  {
    id: "bcom-marketing",
    name: "BCom Marketing",
    faculty: "Commerce",
    duration: "3 years",
    apsRequirement: 28,
    description:
      "Marketing strategy, consumer behavior, and digital marketing.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Marketing Manager",
      "Brand Manager",
      "Digital Marketing Specialist",
      "Market Research Analyst",
      "Advertising Executive",
    ],
  },
  {
    id: "bcom-human-resource-management",
    name: "BCom Human Resource Management",
    faculty: "Commerce",
    duration: "3 years",
    apsRequirement: 28,
    description: "Human resource management and organizational behavior.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "HR Manager",
      "Recruitment Specialist",
      "Training Manager",
      "Employee Relations Specialist",
      "Organizational Development Consultant",
    ],
  },
  {
    id: "bcom-business-management",
    name: "BCom Business Management",
    faculty: "Commerce",
    duration: "3 years",
    apsRequirement: 30,
    description: "Comprehensive business management and leadership training.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Business Manager",
      "Operations Manager",
      "Project Manager",
      "Management Consultant",
      "Entrepreneur",
    ],
  },
  {
    id: "bcom-supply-chain-management",
    name: "BCom Supply Chain Management",
    faculty: "Commerce",
    duration: "3 years",
    apsRequirement: 30,
    description: "Supply chain optimization and logistics management.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Supply Chain Manager",
      "Logistics Manager",
      "Procurement Manager",
      "Operations Analyst",
      "Distribution Manager",
    ],
  },
  {
    id: "bcom-logistics",
    name: "BCom Logistics",
    faculty: "Commerce",
    duration: "3 years",
    apsRequirement: 28,
    description: "Transportation, warehousing, and distribution management.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Logistics Manager",
      "Transportation Manager",
      "Warehouse Manager",
      "Distribution Coordinator",
      "Freight Manager",
    ],
  },
  {
    id: "bcom-risk-management",
    name: "BCom Risk Management",
    faculty: "Commerce",
    duration: "3 years",
    apsRequirement: 32,
    description: "Financial risk assessment and management strategies.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Risk Manager",
      "Risk Analyst",
      "Insurance Specialist",
      "Compliance Officer",
      "Credit Risk Manager",
    ],
  },
  {
    id: "bcom-tourism-management",
    name: "BCom Tourism Management",
    faculty: "Commerce",
    duration: "3 years",
    apsRequirement: 26,
    description: "Tourism industry management and hospitality services.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Tourism Manager",
      "Travel Agent",
      "Hotel Manager",
      "Event Coordinator",
      "Tourism Consultant",
    ],
  },
  {
    id: "bcom-hospitality-management",
    name: "BCom Hospitality Management",
    faculty: "Commerce",
    duration: "3 years",
    apsRequirement: 26,
    description: "Hotel, restaurant, and hospitality industry management.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Hotel Manager",
      "Restaurant Manager",
      "Event Manager",
      "Guest Relations Manager",
      "Food Service Manager",
    ],
  },
  {
    id: "bpa-public-administration",
    name: "BPA Public Administration",
    faculty: "Commerce",
    duration: "3 years",
    apsRequirement: 26,
    description: "Government administration and public policy management.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Public Administrator",
      "Government Officer",
      "Policy Analyst",
      "Municipal Manager",
      "Civil Servant",
    ],
  },
  {
    id: "bcom-labour-relations",
    name: "BCom Labour Relations",
    faculty: "Commerce",
    duration: "3 years",
    apsRequirement: 28,
    description:
      "Employment law, industrial relations, and workplace mediation.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Labour Relations Specialist",
      "Industrial Relations Officer",
      "Union Representative",
      "Workplace Mediator",
      "Employment Law Consultant",
    ],
  },
  {
    id: "bcom-entrepreneurship",
    name: "BCom Entrepreneurship",
    faculty: "Commerce",
    duration: "3 years",
    apsRequirement: 28,
    description: "Business development, innovation, and startup management.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Entrepreneur",
      "Business Developer",
      "Startup Consultant",
      "Innovation Manager",
      "Small Business Owner",
    ],
  },
  {
    id: "bcom-banking",
    name: "BCom Banking",
    faculty: "Commerce",
    duration: "3 years",
    apsRequirement: 30,
    description:
      "Banking operations, financial services, and credit management.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Bank Manager",
      "Credit Analyst",
      "Loan Officer",
      "Investment Advisor",
      "Financial Services Manager",
    ],
  },
  {
    id: "bcom-insurance",
    name: "BCom Insurance",
    faculty: "Commerce",
    duration: "3 years",
    apsRequirement: 30,
    description: "Insurance products, risk assessment, and claims management.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Insurance Broker",
      "Claims Manager",
      "Underwriter",
      "Risk Assessor",
      "Insurance Sales Manager",
    ],
  },
  {
    id: "bcom-auditing",
    name: "BCom Auditing",
    faculty: "Commerce",
    duration: "3 years",
    apsRequirement: 34,
    description: "Financial auditing, compliance, and assurance services.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Accounting", level: 5, isRequired: false },
    ],
    careerProspects: [
      "Auditor",
      "Internal Auditor",
      "Compliance Officer",
      "Risk Auditor",
      "Forensic Auditor",
    ],
  },
  {
    id: "bsc-actuarial-science",
    name: "BSc Actuarial Science",
    faculty: "Commerce",
    duration: "3 years",
    apsRequirement: 40,
    description:
      "Mathematical and statistical analysis of risk and uncertainty.",
    subjects: [
      { name: "Mathematics", level: 7, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Actuary",
      "Risk Analyst",
      "Insurance Analyst",
      "Pension Fund Manager",
      "Investment Analyst",
    ],
  },
  {
    id: "bcom-taxation",
    name: "BCom Taxation",
    faculty: "Commerce",
    duration: "3 years",
    apsRequirement: 32,
    description: "Tax law, tax planning, and compliance management.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Accounting", level: 4, isRequired: false },
    ],
    careerProspects: [
      "Tax Consultant",
      "Tax Advisor",
      "Tax Specialist",
      "Revenue Officer",
      "Tax Compliance Manager",
    ],
  },
  {
    id: "bcom-investment-management",
    name: "BCom Investment Management",
    faculty: "Commerce",
    duration: "3 years",
    apsRequirement: 34,
    description:
      "Portfolio management, investment analysis, and wealth management.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Investment Manager",
      "Portfolio Manager",
      "Wealth Manager",
      "Financial Advisor",
      "Asset Manager",
    ],
  },
];

export const LAW_PROGRAMS: Degree[] = [
  // Faculty of Law
  {
    id: "llb-law",
    name: "LLB Bachelor of Laws",
    faculty: "Law",
    duration: "4 years",
    apsRequirement: 36,
    description: "Comprehensive legal education covering all areas of law.",
    subjects: [
      { name: "English", level: 6, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
    ],
    careerProspects: [
      "Advocate",
      "Attorney",
      "Legal Advisor",
      "Magistrate",
      "Corporate Lawyer",
    ],
  },
  {
    id: "bcj-criminal-justice",
    name: "Bachelor of Criminal Justice",
    faculty: "Law",
    duration: "3 years",
    apsRequirement: 30,
    description: "Criminal law, law enforcement, and justice administration.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
    ],
    careerProspects: [
      "Police Officer",
      "Detective",
      "Criminal Investigator",
      "Court Administrator",
      "Probation Officer",
    ],
  },
  {
    id: "bsc-forensic-science",
    name: "Bachelor of Forensic Science",
    faculty: "Law",
    duration: "3 years",
    apsRequirement: 34,
    description: "Scientific investigation of criminal evidence.",
    subjects: [
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Forensic Scientist",
      "Crime Scene Investigator",
      "Forensic Analyst",
      "Expert Witness",
      "Laboratory Technician",
    ],
  },
  {
    id: "ba-international-law",
    name: "Bachelor of International Law",
    faculty: "Law",
    duration: "4 years",
    apsRequirement: 34,
    description: "International legal systems and diplomatic law.",
    subjects: [
      { name: "English", level: 6, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "History", level: 4, isRequired: false },
    ],
    careerProspects: [
      "International Lawyer",
      "Diplomat",
      "Legal Consultant",
      "Human Rights Lawyer",
      "Trade Law Specialist",
    ],
  },
  {
    id: "ba-environmental-law",
    name: "Bachelor of Environmental Law",
    faculty: "Law",
    duration: "4 years",
    apsRequirement: 32,
    description: "Environmental legislation and conservation law.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "Life Sciences", level: 4, isRequired: false },
    ],
    careerProspects: [
      "Environmental Lawyer",
      "Conservation Legal Advisor",
      "Environmental Consultant",
      "Policy Advisor",
      "Regulatory Affairs Specialist",
    ],
  },
  {
    id: "ba-labour-law",
    name: "Bachelor of Labour Law",
    faculty: "Law",
    duration: "4 years",
    apsRequirement: 32,
    description: "Employment law, industrial relations, and workplace rights.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
    ],
    careerProspects: [
      "Labour Lawyer",
      "Employment Law Specialist",
      "Industrial Relations Advisor",
      "Union Representative",
      "Human Rights Advocate",
    ],
  },
  {
    id: "ba-tax-law",
    name: "Bachelor of Tax Law",
    faculty: "Law",
    duration: "4 years",
    apsRequirement: 34,
    description: "Tax legislation, compliance, and fiscal policy.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "Accounting", level: 4, isRequired: false },
    ],
    careerProspects: [
      "Tax Lawyer",
      "Tax Consultant",
      "Revenue Legal Advisor",
      "Fiscal Policy Analyst",
      "Tax Compliance Specialist",
    ],
  },
  {
    id: "ba-commercial-law",
    name: "Bachelor of Commercial Law",
    faculty: "Law",
    duration: "4 years",
    apsRequirement: 34,
    description: "Business law, contracts, and corporate legislation.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "Business Studies", level: 4, isRequired: false },
    ],
    careerProspects: [
      "Commercial Lawyer",
      "Corporate Legal Advisor",
      "Contract Specialist",
      "Business Legal Consultant",
      "Mergers & Acquisitions Lawyer",
    ],
  },
  {
    id: "ba-constitutional-law",
    name: "Bachelor of Constitutional Law",
    faculty: "Law",
    duration: "4 years",
    apsRequirement: 34,
    description: "Constitutional principles, governance, and public law.",
    subjects: [
      { name: "English", level: 6, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "History", level: 4, isRequired: false },
    ],
    careerProspects: [
      "Constitutional Lawyer",
      "Government Legal Advisor",
      "Public Interest Lawyer",
      "Policy Legal Analyst",
      "Constitutional Court Clerk",
    ],
  },
  {
    id: "ba-human-rights-law",
    name: "Bachelor of Human Rights Law",
    faculty: "Law",
    duration: "4 years",
    apsRequirement: 32,
    description: "Human rights legislation and advocacy.",
    subjects: [
      { name: "English", level: 6, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "History", level: 4, isRequired: false },
    ],
    careerProspects: [
      "Human Rights Lawyer",
      "Human Rights Advocate",
      "NGO Legal Advisor",
      "International Human Rights Officer",
      "Social Justice Lawyer",
    ],
  },
];

export const SCIENCE_PROGRAMS: Degree[] = [
  // Faculty of Science / Natural Sciences
  {
    id: "bsc-biological-sciences",
    name: "BSc Biological Sciences",
    faculty: "Science",
    duration: "3 years",
    apsRequirement: 34,
    description:
      "Comprehensive study of living organisms from molecular to ecosystem levels.",
    subjects: [
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Biologist",
      "Research Scientist",
      "Conservation Scientist",
      "Biotechnologist",
      "Environmental Consultant",
    ],
  },
  {
    id: "bsc-chemistry",
    name: "BSc Chemistry",
    faculty: "Science",
    duration: "3 years",
    apsRequirement: 36,
    description: "Study of matter, its properties, and chemical reactions.",
    subjects: [
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Chemist",
      "Pharmaceutical Researcher",
      "Quality Control Analyst",
      "Chemical Engineer",
      "Forensic Scientist",
    ],
  },
  {
    id: "bsc-physics",
    name: "BSc Physics",
    faculty: "Science",
    duration: "3 years",
    apsRequirement: 38,
    description: "Study of fundamental laws governing the universe.",
    subjects: [
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "Mathematics", level: 7, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Physicist",
      "Research Scientist",
      "Data Analyst",
      "Engineering Physicist",
      "Quantitative Analyst",
    ],
  },
  {
    id: "bsc-mathematics",
    name: "BSc Mathematics",
    faculty: "Science",
    duration: "3 years",
    apsRequirement: 36,
    description: "Pure and applied mathematics with analytical focus.",
    subjects: [
      { name: "Mathematics", level: 7, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Mathematician",
      "Actuary",
      "Data Scientist",
      "Financial Analyst",
      "Research Scientist",
    ],
  },
  {
    id: "bsc-computer-science",
    name: "BSc Computer Science",
    faculty: "Science",
    duration: "3 years",
    apsRequirement: 38,
    description: "Programming, algorithms, and computational thinking.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Information Technology", level: 5, isRequired: false },
    ],
    careerProspects: [
      "Software Developer",
      "Data Scientist",
      "Systems Analyst",
      "IT Consultant",
      "Research Scientist",
    ],
  },
  {
    id: "bsc-environmental-science",
    name: "BSc Environmental Science",
    faculty: "Science",
    duration: "3 years",
    apsRequirement: 32,
    description: "Study of environmental systems and sustainability.",
    subjects: [
      { name: "Life Sciences", level: 5, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 4, isRequired: true },
    ],
    careerProspects: [
      "Environmental Consultant",
      "Conservation Scientist",
      "Environmental Officer",
      "Sustainability Specialist",
      "Climate Change Analyst",
    ],
  },
  {
    id: "bsc-geology",
    name: "BSc Geology",
    faculty: "Science",
    duration: "3 years",
    apsRequirement: 34,
    description: "Study of Earth's structure, composition, and processes.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "Physical Sciences", level: 5, isRequired: true },
      { name: "English", level: 4, isRequired: true },
    ],
    careerProspects: [
      "Geologist",
      "Mining Geologist",
      "Environmental Geologist",
      "Hydrogeologist",
      "Petroleum Geologist",
    ],
  },
  {
    id: "bsc-geography",
    name: "BSc Geography",
    faculty: "Science",
    duration: "3 years",
    apsRequirement: 30,
    description: "Physical and human geography with spatial analysis.",
    subjects: [
      { name: "Geography", level: 5, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 4, isRequired: true },
    ],
    careerProspects: [
      "Geographer",
      "GIS Specialist",
      "Urban Planner",
      "Environmental Consultant",
      "Cartographer",
    ],
  },
  {
    id: "bsc-statistics",
    name: "BSc Statistics",
    faculty: "Science",
    duration: "3 years",
    apsRequirement: 36,
    description: "Statistical analysis and data science methods.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "English", level: 4, isRequired: true },
    ],
    careerProspects: [
      "Statistician",
      "Data Analyst",
      "Market Researcher",
      "Quality Control Analyst",
      "Biostatistician",
    ],
  },
  {
    id: "bsc-biochemistry",
    name: "BSc Biochemistry",
    faculty: "Science",
    duration: "3 years",
    apsRequirement: 36,
    description: "Chemical processes in living organisms.",
    subjects: [
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Biochemist",
      "Research Scientist",
      "Pharmaceutical Researcher",
      "Clinical Biochemist",
      "Biotechnologist",
    ],
  },
  {
    id: "bsc-microbiology",
    name: "BSc Microbiology",
    faculty: "Science",
    duration: "3 years",
    apsRequirement: 34,
    description: "Study of microorganisms and their applications.",
    subjects: [
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 5, isRequired: true },
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Microbiologist",
      "Medical Microbiologist",
      "Quality Control Specialist",
      "Research Scientist",
      "Biotechnologist",
    ],
  },
  {
    id: "bsc-genetics",
    name: "BSc Genetics",
    faculty: "Science",
    duration: "3 years",
    apsRequirement: 36,
    description: "Study of heredity and genetic variation.",
    subjects: [
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Geneticist",
      "Genetic Counselor",
      "Research Scientist",
      "Biotechnologist",
      "Molecular Biologist",
    ],
  },
  {
    id: "bsc-botany",
    name: "BSc Botany",
    faculty: "Science",
    duration: "3 years",
    apsRequirement: 32,
    description: "Study of plant life and ecosystems.",
    subjects: [
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Botanist",
      "Plant Researcher",
      "Conservation Scientist",
      "Environmental Consultant",
      "Agricultural Scientist",
    ],
  },
  {
    id: "bsc-zoology",
    name: "BSc Zoology",
    faculty: "Science",
    duration: "3 years",
    apsRequirement: 32,
    description: "Study of animal life and behavior.",
    subjects: [
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Zoologist",
      "Animal Researcher",
      "Conservation Scientist",
      "Wildlife Manager",
      "Marine Biologist",
    ],
  },
  {
    id: "bsc-astronomy",
    name: "BSc Astronomy",
    faculty: "Science",
    duration: "3 years",
    apsRequirement: 40,
    description: "Study of celestial objects and space phenomena.",
    subjects: [
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "Mathematics", level: 7, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Astronomer",
      "Astrophysicist",
      "Space Scientist",
      "Planetarium Director",
      "Research Scientist",
    ],
  },
  {
    id: "bsc-meteorology",
    name: "BSc Meteorology",
    faculty: "Science",
    duration: "3 years",
    apsRequirement: 34,
    description: "Study of weather patterns and atmospheric science.",
    subjects: [
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Meteorologist",
      "Weather Forecaster",
      "Climate Scientist",
      "Atmospheric Researcher",
      "Environmental Consultant",
    ],
  },
  {
    id: "bsc-marine-biology",
    name: "BSc Marine Biology",
    faculty: "Science",
    duration: "3 years",
    apsRequirement: 34,
    description: "Study of marine organisms and ecosystems.",
    subjects: [
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Marine Biologist",
      "Marine Researcher",
      "Aquatic Scientist",
      "Conservation Scientist",
      "Fisheries Scientist",
    ],
  },
  {
    id: "bsc-biotechnology",
    name: "BSc Biotechnology",
    faculty: "Science",
    duration: "3 years",
    apsRequirement: 36,
    description: "Application of biological systems in technology.",
    subjects: [
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 5, isRequired: true },
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Biotechnologist",
      "Research Scientist",
      "Product Development Scientist",
      "Quality Control Analyst",
      "Bioinformatics Specialist",
    ],
  },
  {
    id: "bsc-ecology",
    name: "BSc Ecology",
    faculty: "Science",
    duration: "3 years",
    apsRequirement: 32,
    description: "Study of relationships between organisms and environment.",
    subjects: [
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Ecologist",
      "Environmental Consultant",
      "Conservation Scientist",
      "Research Scientist",
      "Wildlife Manager",
    ],
  },
];

export const EDUCATION_PROGRAMS: Degree[] = [
  // Faculty of Education
  {
    id: "bed-foundation-phase",
    name: "BEd Foundation Phase",
    faculty: "Education",
    duration: "4 years",
    apsRequirement: 26,
    description: "Teacher training for Grade R to Grade 3.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
    ],
    careerProspects: [
      "Foundation Phase Teacher",
      "Early Childhood Educator",
      "Curriculum Developer",
      "Educational Consultant",
      "School Principal",
    ],
  },
  {
    id: "bed-intermediate-phase",
    name: "BEd Intermediate Phase",
    faculty: "Education",
    duration: "4 years",
    apsRequirement: 26,
    description: "Teacher training for Grade 4 to Grade 6.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Intermediate Phase Teacher",
      "Subject Specialist",
      "Curriculum Developer",
      "Educational Consultant",
      "School Principal",
    ],
  },
  {
    id: "bed-senior-phase",
    name: "BEd Senior Phase",
    faculty: "Education",
    duration: "4 years",
    apsRequirement: 28,
    description: "Teacher training for Grade 7 to Grade 9.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "Teaching Subject", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Senior Phase Teacher",
      "Subject Head",
      "Curriculum Developer",
      "Educational Consultant",
      "School Principal",
    ],
  },
  {
    id: "bed-fet-phase",
    name: "BEd Further Education and Training Phase",
    faculty: "Education",
    duration: "4 years",
    apsRequirement: 30,
    description: "Teacher training for Grade 10 to Grade 12.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "Teaching Subject", level: 6, isRequired: true },
    ],
    careerProspects: [
      "High School Teacher",
      "Subject Specialist",
      "Curriculum Developer",
      "Educational Consultant",
      "School Principal",
    ],
  },
  {
    id: "bed-special-education",
    name: "BEd Special Education",
    faculty: "Education",
    duration: "4 years",
    apsRequirement: 28,
    description: "Teaching learners with special educational needs.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
    ],
    careerProspects: [
      "Special Needs Teacher",
      "Inclusive Education Specialist",
      "Educational Therapist",
      "Special Education Coordinator",
      "Remedial Teacher",
    ],
  },
  {
    id: "bed-adult-education",
    name: "BEd Adult Education",
    faculty: "Education",
    duration: "4 years",
    apsRequirement: 26,
    description: "Teaching and training adult learners.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
    ],
    careerProspects: [
      "Adult Educator",
      "Training Manager",
      "Corporate Trainer",
      "Skills Development Facilitator",
      "Literacy Coordinator",
    ],
  },
  {
    id: "bed-educational-psychology",
    name: "BEd Educational Psychology",
    faculty: "Education",
    duration: "4 years",
    apsRequirement: 30,
    description: "Psychology applied to educational settings.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "Life Sciences", level: 4, isRequired: false },
    ],
    careerProspects: [
      "Educational Psychologist",
      "School Counselor",
      "Learning Support Specialist",
      "Educational Researcher",
      "Student Support Services Manager",
    ],
  },
  {
    id: "bed-educational-management",
    name: "BEd Educational Management",
    faculty: "Education",
    duration: "4 years",
    apsRequirement: 28,
    description: "Leadership and management in educational institutions.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
    ],
    careerProspects: [
      "School Principal",
      "Education Administrator",
      "District Education Manager",
      "Educational Consultant",
      "Policy Manager",
    ],
  },
];

export const AGRICULTURE_PROGRAMS: Degree[] = [
  // Faculty of Agriculture / Agricultural Sciences
  {
    id: "bsc-agriculture-animal-science",
    name: "BSc Agriculture - Animal Science",
    faculty: "Agriculture",
    duration: "4 years",
    apsRequirement: 30,
    description: "Animal production, breeding, and livestock management.",
    subjects: [
      { name: "Life Sciences", level: 5, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Animal Scientist",
      "Livestock Manager",
      "Animal Nutritionist",
      "Veterinary Technician",
      "Farm Manager",
    ],
  },
  {
    id: "bsc-agriculture-plant-production",
    name: "BSc Agriculture - Plant Production",
    faculty: "Agriculture",
    duration: "4 years",
    apsRequirement: 30,
    description: "Crop production, plant breeding, and agronomy.",
    subjects: [
      { name: "Life Sciences", level: 5, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Agronomist",
      "Crop Specialist",
      "Plant Breeder",
      "Farm Manager",
      "Agricultural Consultant",
    ],
  },
  {
    id: "bsc-soil-science",
    name: "BSc Soil Science",
    faculty: "Agriculture",
    duration: "3 years",
    apsRequirement: 30,
    description: "Soil composition, fertility, and conservation.",
    subjects: [
      { name: "Life Sciences", level: 5, isRequired: true },
      { name: "Physical Sciences", level: 4, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Soil Scientist",
      "Environmental Consultant",
      "Agricultural Advisor",
      "Research Scientist",
      "Land Use Planner",
    ],
  },
  {
    id: "bcom-agricultural-economics",
    name: "BCom Agricultural Economics",
    faculty: "Agriculture",
    duration: "3 years",
    apsRequirement: 28,
    description:
      "Economic principles applied to agricultural production and markets.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Economics", level: 4, isRequired: false },
    ],
    careerProspects: [
      "Agricultural Economist",
      "Farm Financial Advisor",
      "Agricultural Policy Analyst",
      "Commodity Trader",
      "Rural Development Officer",
    ],
  },
  {
    id: "bsc-agricultural-extension",
    name: "BSc Agricultural Extension",
    faculty: "Agriculture",
    duration: "4 years",
    apsRequirement: 28,
    description: "Technology transfer and farmer education.",
    subjects: [
      { name: "Life Sciences", level: 4, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Extension Officer",
      "Agricultural Advisor",
      "Rural Development Worker",
      "Training Coordinator",
      "Project Manager",
    ],
  },
  {
    id: "bsc-horticulture",
    name: "BSc Horticulture",
    faculty: "Agriculture",
    duration: "4 years",
    apsRequirement: 30,
    description: "Production of fruits, vegetables, and ornamental plants.",
    subjects: [
      { name: "Life Sciences", level: 5, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Horticulturist",
      "Garden Manager",
      "Greenhouse Manager",
      "Landscape Designer",
      "Plant Propagator",
    ],
  },
  {
    id: "bsc-viticulture-oenology",
    name: "BSc Viticulture and Oenology",
    faculty: "Agriculture",
    duration: "4 years",
    apsRequirement: 32,
    description: "Grape growing and wine making.",
    subjects: [
      { name: "Life Sciences", level: 5, isRequired: true },
      { name: "Physical Sciences", level: 4, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Viticulturist",
      "Winemaker",
      "Vineyard Manager",
      "Wine Consultant",
      "Wine Marketing Specialist",
    ],
  },
  {
    id: "bsc-food-science-technology",
    name: "BSc Food Science and Technology",
    faculty: "Agriculture",
    duration: "4 years",
    apsRequirement: 34,
    description: "Food processing, safety, and product development.",
    subjects: [
      { name: "Life Sciences", level: 5, isRequired: true },
      { name: "Physical Sciences", level: 5, isRequired: true },
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Food Scientist",
      "Food Technologist",
      "Quality Control Manager",
      "Product Development Specialist",
      "Food Safety Inspector",
    ],
  },
  {
    id: "bsc-forestry",
    name: "BSc Forestry",
    faculty: "Agriculture",
    duration: "4 years",
    apsRequirement: 30,
    description: "Forest management and conservation.",
    subjects: [
      { name: "Life Sciences", level: 5, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Forester",
      "Forest Manager",
      "Conservation Officer",
      "Timber Specialist",
      "Environmental Consultant",
    ],
  },
];

export const VETERINARY_PROGRAMS: Degree[] = [
  // Faculty of Veterinary Science
  {
    id: "bvsc-veterinary-science",
    name: "BVSc Veterinary Science",
    faculty: "Veterinary Science",
    duration: "6 years",
    apsRequirement: 38,
    description: "Comprehensive veterinary medical education.",
    subjects: [
      { name: "Life Sciences", level: 6, isRequired: true },
      { name: "Physical Sciences", level: 6, isRequired: true },
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Veterinarian",
      "Animal Health Specialist",
      "Wildlife Veterinarian",
      "Research Veterinarian",
      "Veterinary Surgeon",
    ],
  },
  {
    id: "bsc-veterinary-nursing",
    name: "BSc Veterinary Nursing",
    faculty: "Veterinary Science",
    duration: "4 years",
    apsRequirement: 32,
    description: "Veterinary nursing and animal care.",
    subjects: [
      { name: "Life Sciences", level: 5, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Veterinary Nurse",
      "Animal Care Technician",
      "Veterinary Practice Manager",
      "Animal Welfare Officer",
      "Wildlife Care Specialist",
    ],
  },
  {
    id: "bsc-animal-health",
    name: "BSc Animal Health",
    faculty: "Veterinary Science",
    duration: "3 years",
    apsRequirement: 30,
    description: "Animal health and disease prevention.",
    subjects: [
      { name: "Life Sciences", level: 5, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Animal Health Technician",
      "Livestock Health Advisor",
      "Animal Welfare Inspector",
      "Veterinary Sales Representative",
      "Animal Health Researcher",
    ],
  },
];

export const THEOLOGY_PROGRAMS: Degree[] = [
  // Faculty of Theology and Religious Studies
  {
    id: "bth-theology",
    name: "BTh Theology",
    faculty: "Theology",
    duration: "4 years",
    apsRequirement: 24,
    description: "Theological studies and religious education.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 3, isRequired: true },
    ],
    careerProspects: [
      "Minister",
      "Pastor",
      "Chaplain",
      "Religious Education Teacher",
      "Missionary",
    ],
  },
  {
    id: "bdiv-divinity",
    name: "BDiv Divinity",
    faculty: "Theology",
    duration: "4 years",
    apsRequirement: 26,
    description: "Advanced theological and ministerial studies.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 3, isRequired: true },
    ],
    careerProspects: [
      "Senior Pastor",
      "Theological Educator",
      "Church Administrator",
      "Religious Counselor",
      "Interfaith Leader",
    ],
  },
];

export const DESIGN_PROGRAMS: Degree[] = [
  // Faculty of Design / Creative Arts
  {
    id: "bdes-graphic-design",
    name: "BDes Graphic Design",
    faculty: "Design",
    duration: "3 years",
    apsRequirement: 26,
    description: "Visual communication and graphic design.",
    subjects: [
      { name: "English", level: 4, isRequired: true },
      { name: "Visual Arts", level: 5, isRequired: false },
    ],
    careerProspects: [
      "Graphic Designer",
      "Creative Director",
      "Brand Designer",
      "Web Designer",
      "Art Director",
    ],
  },
  {
    id: "bdes-industrial-design",
    name: "BDes Industrial Design",
    faculty: "Design",
    duration: "4 years",
    apsRequirement: 28,
    description: "Product design and manufacturing.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 4, isRequired: true },
      { name: "Visual Arts", level: 4, isRequired: false },
    ],
    careerProspects: [
      "Industrial Designer",
      "Product Designer",
      "Design Engineer",
      "User Experience Designer",
      "Design Consultant",
    ],
  },
  {
    id: "bdes-fashion-design",
    name: "BDes Fashion Design",
    faculty: "Design",
    duration: "3 years",
    apsRequirement: 24,
    description: "Fashion design and textile development.",
    subjects: [
      { name: "English", level: 4, isRequired: true },
      { name: "Visual Arts", level: 4, isRequired: false },
    ],
    careerProspects: [
      "Fashion Designer",
      "Textile Designer",
      "Fashion Stylist",
      "Fashion Merchandiser",
      "Fashion Consultant",
    ],
  },
];

export const MUSIC_PROGRAMS: Degree[] = [
  // Faculty of Music and Performing Arts
  {
    id: "bmus-music",
    name: "BMus Music",
    faculty: "Music",
    duration: "4 years",
    apsRequirement: 24,
    description: "Music theory, performance, and composition.",
    subjects: [
      { name: "English", level: 4, isRequired: true },
      { name: "Music", level: 6, isRequired: false },
    ],
    careerProspects: [
      "Musician",
      "Music Teacher",
      "Composer",
      "Music Producer",
      "Conductor",
    ],
  },
  {
    id: "ba-dance",
    name: "BA Dance",
    faculty: "Music",
    duration: "3 years",
    apsRequirement: 22,
    description: "Dance performance and choreography.",
    subjects: [
      { name: "English", level: 4, isRequired: true },
      { name: "Dramatic Arts", level: 4, isRequired: false },
    ],
    careerProspects: [
      "Dancer",
      "Choreographer",
      "Dance Teacher",
      "Dance Therapist",
      "Performance Director",
    ],
  },
];

export const SPORTS_SCIENCE_PROGRAMS: Degree[] = [
  // Faculty of Sports Science
  {
    id: "bsc-sports-science",
    name: "BSc Sports Science",
    faculty: "Sports Science",
    duration: "3 years",
    apsRequirement: 28,
    description: "Exercise physiology and sports performance.",
    subjects: [
      { name: "Life Sciences", level: 5, isRequired: true },
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Sports Scientist",
      "Exercise Physiologist",
      "Fitness Trainer",
      "Sports Analyst",
      "Athletic Performance Coach",
    ],
  },
  {
    id: "bcom-sports-management",
    name: "BCom Sports Management",
    faculty: "Sports Science",
    duration: "3 years",
    apsRequirement: 26,
    description: "Sports business and facility management.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Sports Manager",
      "Event Manager",
      "Sports Marketing Manager",
      "Facility Manager",
      "Sports Agent",
    ],
  },
];

export const SOCIAL_WORK_PROGRAMS: Degree[] = [
  // Faculty of Social Work
  {
    id: "bsw-social-work",
    name: "BSW Social Work",
    faculty: "Social Work",
    duration: "4 years",
    apsRequirement: 26,
    description: "Professional social work practice and community development.",
    subjects: [
      { name: "English", level: 5, isRequired: true },
      { name: "Mathematics", level: 3, isRequired: true },
    ],
    careerProspects: [
      "Social Worker",
      "Community Development Officer",
      "Child Protection Officer",
      "Family Counselor",
      "NGO Manager",
    ],
  },
];

export const INFORMATION_TECHNOLOGY_PROGRAMS: Degree[] = [
  // Faculty of Information Technology / Computer Science
  {
    id: "bit-information-technology",
    name: "BIT Information Technology",
    faculty: "Information Technology",
    duration: "3 years",
    apsRequirement: 34,
    description: "Comprehensive information technology and systems management.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Information Technology", level: 5, isRequired: false },
    ],
    careerProspects: [
      "IT Manager",
      "Systems Administrator",
      "Database Administrator",
      "IT Consultant",
      "Technology Analyst",
    ],
  },
  {
    id: "bsc-software-engineering",
    name: "BSc Software Engineering",
    faculty: "Information Technology",
    duration: "4 years",
    apsRequirement: 38,
    description: "Software development lifecycle and engineering principles.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Information Technology", level: 5, isRequired: false },
    ],
    careerProspects: [
      "Software Engineer",
      "Software Developer",
      "Software Architect",
      "Technical Lead",
      "DevOps Engineer",
    ],
  },
  {
    id: "bis-information-systems",
    name: "BIS Information Systems",
    faculty: "Information Technology",
    duration: "3 years",
    apsRequirement: 32,
    description: "Business-focused IT solutions and systems analysis.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Information Technology", level: 4, isRequired: false },
    ],
    careerProspects: [
      "Business Analyst",
      "Systems Analyst",
      "IT Project Manager",
      "Information Systems Manager",
      "Digital Transformation Consultant",
    ],
  },
  {
    id: "bsc-cybersecurity",
    name: "BSc Cybersecurity",
    faculty: "Information Technology",
    duration: "3 years",
    apsRequirement: 36,
    description:
      "Information security, threat analysis, and digital forensics.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Information Technology", level: 5, isRequired: false },
    ],
    careerProspects: [
      "Cybersecurity Analyst",
      "Information Security Manager",
      "Ethical Hacker",
      "Digital Forensics Specialist",
      "Security Consultant",
    ],
  },
  {
    id: "bsc-data-science",
    name: "BSc Data Science",
    faculty: "Information Technology",
    duration: "3 years",
    apsRequirement: 38,
    description:
      "Big data analytics, machine learning, and statistical analysis.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Information Technology", level: 5, isRequired: false },
    ],
    careerProspects: [
      "Data Scientist",
      "Data Analyst",
      "Machine Learning Engineer",
      "Business Intelligence Analyst",
      "Research Scientist",
    ],
  },
  {
    id: "bsc-artificial-intelligence",
    name: "BSc Artificial Intelligence",
    faculty: "Information Technology",
    duration: "3 years",
    apsRequirement: 40,
    description: "AI algorithms, machine learning, and intelligent systems.",
    subjects: [
      { name: "Mathematics", level: 6, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Information Technology", level: 5, isRequired: false },
    ],
    careerProspects: [
      "AI Engineer",
      "Machine Learning Specialist",
      "AI Researcher",
      "Robotics Engineer",
      "AI Product Manager",
    ],
  },
  {
    id: "bsc-game-development",
    name: "BSc Game Development",
    faculty: "Information Technology",
    duration: "3 years",
    apsRequirement: 34,
    description: "Video game design, programming, and development.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Information Technology", level: 5, isRequired: false },
    ],
    careerProspects: [
      "Game Developer",
      "Game Designer",
      "Game Programmer",
      "Level Designer",
      "Game Producer",
    ],
  },
  {
    id: "bsc-web-development",
    name: "BSc Web Development",
    faculty: "Information Technology",
    duration: "3 years",
    apsRequirement: 32,
    description: "Web technologies, front-end and back-end development.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Information Technology", level: 4, isRequired: false },
    ],
    careerProspects: [
      "Web Developer",
      "Full Stack Developer",
      "Front-End Developer",
      "Back-End Developer",
      "Web Designer",
    ],
  },
  {
    id: "bsc-mobile-app-development",
    name: "BSc Mobile Application Development",
    faculty: "Information Technology",
    duration: "3 years",
    apsRequirement: 34,
    description: "Mobile app design and development for various platforms.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Information Technology", level: 5, isRequired: false },
    ],
    careerProspects: [
      "Mobile App Developer",
      "iOS Developer",
      "Android Developer",
      "Mobile UX Designer",
      "Mobile Product Manager",
    ],
  },
  {
    id: "bsc-network-engineering",
    name: "BSc Network Engineering",
    faculty: "Information Technology",
    duration: "3 years",
    apsRequirement: 34,
    description: "Computer networks, telecommunications, and infrastructure.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "Physical Sciences", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
    ],
    careerProspects: [
      "Network Engineer",
      "Network Administrator",
      "Telecommunications Engineer",
      "Infrastructure Specialist",
      "Network Security Specialist",
    ],
  },
  {
    id: "bsc-cloud-computing",
    name: "BSc Cloud Computing",
    faculty: "Information Technology",
    duration: "3 years",
    apsRequirement: 36,
    description: "Cloud infrastructure, services, and distributed computing.",
    subjects: [
      { name: "Mathematics", level: 5, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Information Technology", level: 5, isRequired: false },
    ],
    careerProspects: [
      "Cloud Engineer",
      "Cloud Architect",
      "DevOps Engineer",
      "Cloud Security Specialist",
      "Cloud Solutions Consultant",
    ],
  },
  {
    id: "bsc-digital-media",
    name: "BSc Digital Media",
    faculty: "Information Technology",
    duration: "3 years",
    apsRequirement: 30,
    description:
      "Digital content creation, multimedia design, and interactive media.",
    subjects: [
      { name: "Mathematics", level: 4, isRequired: true },
      { name: "English", level: 5, isRequired: true },
      { name: "Information Technology", level: 4, isRequired: false },
    ],
    careerProspects: [
      "Digital Media Specialist",
      "Multimedia Designer",
      "Content Creator",
      "Digital Marketing Specialist",
      "UX/UI Designer",
    ],
  },
];

// Helper function to combine all programs into faculty groups
export const getAllProgramsByFaculty = () => {
  return {
    engineering: ENGINEERING_PROGRAMS,
    healthSciences: HEALTH_SCIENCES_PROGRAMS,
    humanities: HUMANITIES_PROGRAMS,
    commerce: COMMERCE_PROGRAMS,
    law: LAW_PROGRAMS,
    science: SCIENCE_PROGRAMS,
    education: EDUCATION_PROGRAMS,
    informationTechnology: INFORMATION_TECHNOLOGY_PROGRAMS,
    agriculture: AGRICULTURE_PROGRAMS,
    veterinary: VETERINARY_PROGRAMS,
    theology: THEOLOGY_PROGRAMS,
    design: DESIGN_PROGRAMS,
    music: MUSIC_PROGRAMS,
    sportsScience: SPORTS_SCIENCE_PROGRAMS,
    socialWork: SOCIAL_WORK_PROGRAMS,
  };
};

// Export all programs as a single array
export const ALL_COMPREHENSIVE_PROGRAMS: Degree[] = [
  ...ENGINEERING_PROGRAMS,
  ...HEALTH_SCIENCES_PROGRAMS,
  ...HUMANITIES_PROGRAMS,
  ...COMMERCE_PROGRAMS,
  ...LAW_PROGRAMS,
  ...SCIENCE_PROGRAMS,
  ...EDUCATION_PROGRAMS,
  ...INFORMATION_TECHNOLOGY_PROGRAMS,
  ...AGRICULTURE_PROGRAMS,
  ...VETERINARY_PROGRAMS,
  ...THEOLOGY_PROGRAMS,
  ...DESIGN_PROGRAMS,
  ...MUSIC_PROGRAMS,
  ...SPORTS_SCIENCE_PROGRAMS,
  ...SOCIAL_WORK_PROGRAMS,
];
