import { University } from "@/types/university";

// University of Zululand with CORRECT faculty structure
// Based on official unizulu.ac.za faculty organization
export const UNIZULU_CORRECTED: University = {
  id: "unizulu",
  name: "University of Zululand",
  abbreviation: "UniZulu",
  fullName: "University of Zululand (UniZulu)",
  location: "Richards Bay",
  province: "KwaZulu-Natal",
  logo: "/logos/universities/university-of-zululand.svg",
  overview:
    "A comprehensive university rooted in African values and committed to academic excellence and community engagement.",
  website: "https://www.unizulu.ac.za",
  studentPortal: "https://students.unizulu.ac.za",
  admissionsContact: "admissions@unizulu.ac.za",
  establishedYear: 1960,
  studentPopulation: 16000,
  campuses: ["Richards Bay", "KwaDlangezwa"],
  applicationInfo: {
    isOpen: true,
    openingDate: "1 April 2024",
    closingDate: "30 September 2024",
    academicYear: "2025",
    applicationFee: "R220",
    applicationMethod: "Online via university website",
    lateApplications: {
      available: true,
      deadline: "31 October 2024",
      additionalFee: "R300",
    },
  },
  faculties: [
    {
      id: "science-agriculture-engineering",
      name: "Faculty of Science, Agriculture and Engineering",
      description:
        "Comprehensive science, agricultural sciences, and engineering education with 15 departments.",
      degrees: [
        {
          id: "bsc-computer-science",
          name: "BSc Computer Science",
          faculty: "Faculty of Science, Agriculture and Engineering",
          duration: "3 years",
          apsRequirement: 26,
          description:
            "Computer science with practical software development focus.",
          subjects: [
            { name: "Mathematics", level: 5, isRequired: true },
            { name: "English", level: 4, isRequired: true },
            { name: "Physical Sciences", level: 4, isRequired: false },
          ],
          careerProspects: [
            "Software Developer",
            "Systems Analyst",
            "Database Administrator",
            "IT Specialist",
            "Web Developer",
          ],
        },
        {
          id: "bsc-mathematics",
          name: "BSc Mathematical Sciences",
          faculty: "Faculty of Science, Agriculture and Engineering",
          duration: "3 years",
          apsRequirement: 28,
          description:
            "Pure and applied mathematics with statistical analysis.",
          subjects: [
            { name: "Mathematics", level: 6, isRequired: true },
            { name: "English", level: 4, isRequired: true },
          ],
          careerProspects: [
            "Mathematician",
            "Statistician",
            "Data Analyst",
            "Actuary",
            "Research Scientist",
          ],
        },
        {
          id: "bsc-physics",
          name: "BSc Physics",
          faculty: "Faculty of Science, Agriculture and Engineering",
          duration: "3 years",
          apsRequirement: 30,
          description: "Physics with laboratory and research focus.",
          subjects: [
            { name: "Physical Sciences", level: 6, isRequired: true },
            { name: "Mathematics", level: 6, isRequired: true },
            { name: "English", level: 4, isRequired: true },
          ],
          careerProspects: [
            "Physicist",
            "Research Scientist",
            "Laboratory Technician",
            "Science Teacher",
            "Quality Control Analyst",
          ],
        },
        {
          id: "bsc-chemistry",
          name: "BSc Chemistry",
          faculty: "Faculty of Science, Agriculture and Engineering",
          duration: "3 years",
          apsRequirement: 28,
          description:
            "Chemistry with analytical and environmental applications.",
          subjects: [
            { name: "Physical Sciences", level: 6, isRequired: true },
            { name: "Mathematics", level: 5, isRequired: true },
            { name: "English", level: 4, isRequired: true },
          ],
          careerProspects: [
            "Chemist",
            "Laboratory Analyst",
            "Environmental Analyst",
            "Quality Control Specialist",
            "Research Technician",
          ],
        },
        {
          id: "bsc-botany",
          name: "BSc Botany",
          faculty: "Faculty of Science, Agriculture and Engineering",
          duration: "3 years",
          apsRequirement: 26,
          description: "Plant science and botanical research.",
          subjects: [
            { name: "Life Sciences", level: 5, isRequired: true },
            { name: "Mathematics", level: 4, isRequired: true },
            { name: "English", level: 4, isRequired: true },
          ],
          careerProspects: [
            "Botanist",
            "Plant Researcher",
            "Conservation Scientist",
            "Agricultural Scientist",
            "Environmental Consultant",
          ],
        },
        {
          id: "bsc-zoology",
          name: "BSc Zoology",
          faculty: "Faculty of Science, Agriculture and Engineering",
          duration: "3 years",
          apsRequirement: 26,
          description: "Animal science and zoological research.",
          subjects: [
            { name: "Life Sciences", level: 5, isRequired: true },
            { name: "Mathematics", level: 4, isRequired: true },
            { name: "English", level: 4, isRequired: true },
          ],
          careerProspects: [
            "Zoologist",
            "Wildlife Biologist",
            "Conservation Officer",
            "Animal Researcher",
            "Environmental Specialist",
          ],
        },
        {
          id: "bsc-biochemistry",
          name: "BSc Biochemistry and Microbiology",
          faculty: "Faculty of Science, Agriculture and Engineering",
          duration: "3 years",
          apsRequirement: 28,
          description:
            "Biochemistry and microbiology with medical applications.",
          subjects: [
            { name: "Life Sciences", level: 6, isRequired: true },
            { name: "Physical Sciences", level: 5, isRequired: true },
            { name: "Mathematics", level: 5, isRequired: true },
            { name: "English", level: 4, isRequired: true },
          ],
          careerProspects: [
            "Biochemist",
            "Microbiologist",
            "Medical Technologist",
            "Research Scientist",
            "Laboratory Manager",
          ],
        },
        {
          id: "bsc-agriculture",
          name: "BSc Agriculture",
          faculty: "Faculty of Science, Agriculture and Engineering",
          duration: "4 years",
          apsRequirement: 24,
          description: "Agricultural sciences with sustainable farming focus.",
          subjects: [
            { name: "Life Sciences", level: 4, isRequired: true },
            { name: "Mathematics", level: 4, isRequired: true },
            { name: "English", level: 4, isRequired: true },
          ],
          careerProspects: [
            "Agricultural Scientist",
            "Farm Manager",
            "Extension Officer",
            "Agricultural Consultant",
            "Rural Development Officer",
          ],
        },
        {
          id: "bsc-consumer-sciences",
          name: "BSc Consumer Sciences",
          faculty: "Faculty of Science, Agriculture and Engineering",
          duration: "3 years",
          apsRequirement: 24,
          description: "Consumer behavior and household sciences.",
          subjects: [
            { name: "English", level: 4, isRequired: true },
            { name: "Mathematics", level: 4, isRequired: true },
          ],
          careerProspects: [
            "Consumer Scientist",
            "Home Economist",
            "Community Development Officer",
            "Nutrition Consultant",
            "Extension Officer",
          ],
        },
        {
          id: "bns-nursing",
          name: "Bachelor of Nursing Science",
          faculty: "Faculty of Science, Agriculture and Engineering",
          duration: "4 years",
          apsRequirement: 26,
          description: "Professional nursing education and training.",
          subjects: [
            { name: "English", level: 4, isRequired: true },
            { name: "Life Sciences", level: 4, isRequired: true },
            { name: "Mathematics", level: 4, isRequired: true },
          ],
          careerProspects: [
            "Professional Nurse",
            "Community Health Nurse",
            "Clinical Nurse",
            "Nurse Manager",
            "Public Health Nurse",
          ],
        },
        {
          id: "bsc-hydrology",
          name: "BSc Hydrology",
          faculty: "Faculty of Science, Agriculture and Engineering",
          duration: "3 years",
          apsRequirement: 26,
          description: "Water resources and hydrological sciences.",
          subjects: [
            { name: "Mathematics", level: 5, isRequired: true },
            { name: "Physical Sciences", level: 5, isRequired: true },
            { name: "English", level: 4, isRequired: true },
          ],
          careerProspects: [
            "Hydrologist",
            "Water Resources Manager",
            "Environmental Consultant",
            "Water Quality Specialist",
            "Irrigation Engineer",
          ],
        },
      ],
    },
    {
      id: "humanities-social-sciences",
      name: "Faculty of Humanities and Social Sciences",
      description:
        "The largest faculty at UniZulu with 16 departments covering humanities and social sciences.",
      degrees: [
        {
          id: "ba-english",
          name: "BA English",
          faculty: "Faculty of Humanities and Social Sciences",
          duration: "3 years",
          apsRequirement: 24,
          description: "English language and literature studies.",
          subjects: [{ name: "English", level: 5, isRequired: true }],
          careerProspects: [
            "English Teacher",
            "Writer",
            "Editor",
            "Journalist",
            "Communications Specialist",
          ],
        },
        {
          id: "ba-history",
          name: "BA History",
          faculty: "Faculty of Humanities and Social Sciences",
          duration: "3 years",
          apsRequirement: 22,
          description: "Historical studies with South African focus.",
          subjects: [{ name: "English", level: 4, isRequired: true }],
          careerProspects: [
            "Historian",
            "Museum Curator",
            "Heritage Officer",
            "History Teacher",
            "Cultural Specialist",
          ],
        },
        {
          id: "ba-anthropology-development",
          name: "BA Anthropology and Development Studies",
          faculty: "Faculty of Humanities and Social Sciences",
          duration: "3 years",
          apsRequirement: 22,
          description: "Anthropology with development studies focus.",
          subjects: [{ name: "English", level: 4, isRequired: true }],
          careerProspects: [
            "Anthropologist",
            "Development Worker",
            "Community Researcher",
            "Cultural Consultant",
            "NGO Coordinator",
          ],
        },
        {
          id: "ba-communication-science",
          name: "BA Communication Science",
          faculty: "Faculty of Humanities and Social Sciences",
          duration: "3 years",
          apsRequirement: 24,
          description: "Communication theory and media studies.",
          subjects: [{ name: "English", level: 5, isRequired: true }],
          careerProspects: [
            "Communications Officer",
            "Media Specialist",
            "Public Relations Officer",
            "Journalist",
            "Marketing Coordinator",
          ],
        },
        {
          id: "ba-geography-environmental",
          name: "BA Geography and Environmental Studies",
          faculty: "Faculty of Humanities and Social Sciences",
          duration: "3 years",
          apsRequirement: 24,
          description: "Human geography and environmental studies.",
          subjects: [
            { name: "English", level: 4, isRequired: true },
            { name: "Mathematics", level: 3, isRequired: true },
          ],
          careerProspects: [
            "Geographer",
            "Environmental Planner",
            "GIS Specialist",
            "Urban Planner",
            "Environmental Consultant",
          ],
        },
        {
          id: "ba-linguistics",
          name: "BA General Linguistics and Modern Languages",
          faculty: "Faculty of Humanities and Social Sciences",
          duration: "3 years",
          apsRequirement: 24,
          description: "Linguistics and modern language studies.",
          subjects: [{ name: "English", level: 5, isRequired: true }],
          careerProspects: [
            "Linguist",
            "Language Teacher",
            "Translator",
            "Language Researcher",
            "Communications Specialist",
          ],
        },
        {
          id: "ba-psychology",
          name: "BA Psychology",
          faculty: "Faculty of Humanities and Social Sciences",
          duration: "3 years",
          apsRequirement: 26,
          description: "Psychology with community and cultural focus.",
          subjects: [
            { name: "English", level: 4, isRequired: true },
            { name: "Mathematics", level: 4, isRequired: true },
          ],
          careerProspects: [
            "Psychologist",
            "Counselor",
            "Social Worker",
            "Human Resources Specialist",
            "Research Assistant",
          ],
        },
        {
          id: "ba-recreation-tourism",
          name: "BA Recreation and Tourism",
          faculty: "Faculty of Humanities and Social Sciences",
          duration: "3 years",
          apsRequirement: 22,
          description: "Tourism and recreation management.",
          subjects: [{ name: "English", level: 4, isRequired: true }],
          careerProspects: [
            "Tourism Manager",
            "Recreation Officer",
            "Tour Guide",
            "Event Coordinator",
            "Tourism Consultant",
          ],
        },
        {
          id: "ba-social-work",
          name: "BA Social Work",
          faculty: "Faculty of Humanities and Social Sciences",
          duration: "4 years",
          apsRequirement: 24,
          description: "Professional social work training.",
          subjects: [
            { name: "English", level: 4, isRequired: true },
            { name: "Mathematics", level: 3, isRequired: true },
          ],
          careerProspects: [
            "Social Worker",
            "Community Development Officer",
            "Child Protection Officer",
            "Family Counselor",
            "NGO Manager",
          ],
        },
      ],
    },
    {
      id: "commerce-administration-law",
      name: "Faculty of Commerce, Administration and Law",
      description:
        "Business, public administration, and legal education with 5 specialized departments.",
      degrees: [
        {
          id: "bcom-accounting-auditing",
          name: "BCom Accounting and Auditing",
          faculty: "Faculty of Commerce, Administration and Law",
          duration: "3 years",
          apsRequirement: 26,
          description: "Professional accounting and auditing education.",
          subjects: [
            { name: "Mathematics", level: 5, isRequired: true },
            { name: "English", level: 4, isRequired: true },
          ],
          careerProspects: [
            "Chartered Accountant",
            "Auditor",
            "Financial Manager",
            "Tax Practitioner",
            "Business Advisor",
          ],
        },
        {
          id: "bcom-business-management",
          name: "BCom Business Management",
          faculty: "Faculty of Commerce, Administration and Law",
          duration: "3 years",
          apsRequirement: 24,
          description: "Business management with human resources focus.",
          subjects: [
            { name: "Mathematics", level: 4, isRequired: true },
            { name: "English", level: 4, isRequired: true },
          ],
          careerProspects: [
            "Business Manager",
            "Operations Manager",
            "Project Manager",
            "Human Resources Manager",
            "Management Consultant",
          ],
        },
        {
          id: "bcom-economics",
          name: "BCom Economics",
          faculty: "Faculty of Commerce, Administration and Law",
          duration: "3 years",
          apsRequirement: 26,
          description: "Economic theory and development economics.",
          subjects: [
            { name: "Mathematics", level: 5, isRequired: true },
            { name: "English", level: 4, isRequired: true },
          ],
          careerProspects: [
            "Economist",
            "Policy Analyst",
            "Research Officer",
            "Financial Analyst",
            "Development Economist",
          ],
        },
        {
          id: "bpa-public-administration",
          name: "BPA Public Administration",
          faculty: "Faculty of Commerce, Administration and Law",
          duration: "3 years",
          apsRequirement: 24,
          description: "Public sector management and governance.",
          subjects: [
            { name: "English", level: 4, isRequired: true },
            { name: "Mathematics", level: 3, isRequired: true },
          ],
          careerProspects: [
            "Public Administrator",
            "Government Officer",
            "Municipal Manager",
            "Policy Officer",
            "Development Coordinator",
          ],
        },
        {
          id: "llb-law",
          name: "LLB Bachelor of Laws",
          faculty: "Faculty of Commerce, Administration and Law",
          duration: "4 years",
          apsRequirement: 28,
          description: "Comprehensive legal education including customary law.",
          subjects: [
            { name: "English", level: 5, isRequired: true },
            { name: "Mathematics", level: 4, isRequired: true },
          ],
          careerProspects: [
            "Attorney",
            "Advocate",
            "Legal Advisor",
            "Magistrate",
            "Corporate Lawyer",
          ],
        },
      ],
    },
    {
      id: "education",
      name: "Faculty of Education",
      description:
        "Teacher training and educational development with 6 specialized departments.",
      degrees: [
        {
          id: "bed-foundation-phase",
          name: "BEd Foundation Phase",
          faculty: "Faculty of Education",
          duration: "4 years",
          apsRequirement: 22,
          description: "Teacher training for Grade R to Grade 3.",
          subjects: [
            { name: "English", level: 4, isRequired: true },
            { name: "Mathematics", level: 4, isRequired: true },
          ],
          careerProspects: [
            "Foundation Phase Teacher",
            "Early Childhood Educator",
            "Primary School Teacher",
            "Curriculum Developer",
            "Educational Specialist",
          ],
        },
        {
          id: "bed-intermediate-phase",
          name: "BEd Intermediate Phase",
          faculty: "Faculty of Education",
          duration: "4 years",
          apsRequirement: 24,
          description: "Teacher training for Grade 4 to Grade 6.",
          subjects: [
            { name: "English", level: 4, isRequired: true },
            { name: "Mathematics", level: 4, isRequired: true },
          ],
          careerProspects: [
            "Intermediate Phase Teacher",
            "Primary School Teacher",
            "Subject Specialist",
            "Educational Coordinator",
            "Curriculum Advisor",
          ],
        },
        {
          id: "bed-senior-fet-phase",
          name: "BEd Senior Phase and FET",
          faculty: "Faculty of Education",
          duration: "4 years",
          apsRequirement: 26,
          description: "Teacher training for Grade 7 to Grade 12.",
          subjects: [
            { name: "English", level: 4, isRequired: true },
            { name: "Mathematics", level: 4, isRequired: true },
            { name: "Teaching Subject", level: 4, isRequired: true },
          ],
          careerProspects: [
            "High School Teacher",
            "Subject Head",
            "Educational Manager",
            "Curriculum Specialist",
            "Academic Coordinator",
          ],
        },
        {
          id: "bed-early-childhood",
          name: "BEd Early Childhood Education",
          faculty: "Faculty of Education",
          duration: "4 years",
          apsRequirement: 22,
          description: "Specialized early childhood development and education.",
          subjects: [
            { name: "English", level: 4, isRequired: true },
            { name: "Mathematics", level: 3, isRequired: true },
          ],
          careerProspects: [
            "Early Childhood Educator",
            "Preschool Teacher",
            "Childcare Director",
            "Child Development Specialist",
            "Educational Therapist",
          ],
        },
        {
          id: "bed-educational-psychology",
          name: "BEd Educational Psychology",
          faculty: "Faculty of Education",
          duration: "4 years",
          apsRequirement: 26,
          description: "Educational psychology and learning support.",
          subjects: [
            { name: "English", level: 4, isRequired: true },
            { name: "Mathematics", level: 4, isRequired: true },
            { name: "Life Sciences", level: 4, isRequired: false },
          ],
          careerProspects: [
            "Educational Psychologist",
            "Learning Support Specialist",
            "School Counselor",
            "Educational Therapist",
            "Student Support Officer",
          ],
        },
      ],
    },
  ],
};
