import { University } from "@/types/university";

export const UNIVERSITIES_OF_TECHNOLOGY: University[] = [
  {
    id: "cput",
    name: "Cape Peninsula University of Technology",
    abbreviation: "CPUT",
    fullName: "Cape Peninsula University of Technology (CPUT)",
    location: "Cape Town",
    province: "Western Cape",
    logo: "/logos/universities/tshwane-university-of-technology.svg",
    overview:
      "A leading university of technology providing quality education and training in response to South Africa's skills needs.",
    website: "https://www.cput.ac.za",
    studentPortal: "https://students.cput.ac.za",
    admissionsContact: "admissions@cput.ac.za",
    faculties: [
      {
        id: "engineering",
        name: "Faculty of Engineering and the Built Environment",
        description:
          "Practical engineering education with strong industry connections.",
        degrees: [
          // BTech Engineering Programs
          {
            id: "btech-civil",
            name: "BTech Civil Engineering",
            faculty: "Engineering and the Built Environment",
            duration: "4 years",
            apsRequirement: 32,
            description:
              "Practical civil engineering education with hands-on training.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Civil Engineering Technologist",
              "Construction Manager",
              "Project Coordinator",
              "Infrastructure Specialist",
              "Quality Controller",
            ],
          },
          {
            id: "diploma-game-design",
            name: "Diploma in Game Design",
            faculty: "Arts and Design",
            duration: "3 years",
            apsRequirement: 26,
            description:
              "Game design and development specialization (DUT specialty).",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
              { name: "Information Technology", level: 4, isRequired: false },
            ],
            careerProspects: [
              "Game Designer",
              "Game Developer",
              "3D Artist",
              "Interactive Media Designer",
              "Mobile App Developer",
            ],
          },
          {
            id: "bachelor-health-sciences-radiography",
            name: "Bachelor of Health Sciences in Radiography",
            faculty: "Health Sciences",
            duration: "4 years",
            apsRequirement: 32,
            description:
              "Radiography and medical imaging specialization (DUT specialty).",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 5, isRequired: true },
              { name: "Life Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Radiographer",
              "Medical Imaging Technologist",
              "CT Scan Technologist",
              "MRI Technologist",
              "Nuclear Medicine Technologist",
            ],
          },
          {
            id: "diploma-clinical-technology",
            name: "Diploma in Clinical Technology",
            faculty: "Health Sciences",
            duration: "3 years",
            apsRequirement: 30,
            description: "Clinical technology specialization (DUT specialty).",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "Physical Sciences", level: 5, isRequired: true },
              { name: "Life Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Clinical Technologist",
              "Medical Equipment Technician",
              "Biomedical Engineer",
              "Hospital Technologist",
              "Medical Device Specialist",
            ],
          },
          {
            id: "bachelor-emergency-medical-care",
            name: "Bachelor of Emergency Medical Care",
            faculty: "Health and Wellness Sciences",
            duration: "4 years",
            apsRequirement: 30,
            description:
              "Emergency medical care specialization (CPUT specialty).",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "Life Sciences", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 4, isRequired: true },
              { name: "English", level: 5, isRequired: true },
            ],
            careerProspects: [
              "Paramedic",
              "Emergency Medical Technician",
              "Critical Care Paramedic",
              "Flight Paramedic",
              "Emergency Services Manager",
            ],
          },
          {
            id: "diploma-maritime-studies",
            name: "Diploma in Maritime Studies",
            faculty: "Engineering and the Built Environment",
            duration: "3 years",
            apsRequirement: 26,
            description: "Maritime industry education (CPUT specialty).",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "Physical Sciences", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Ship Officer",
              "Port Manager",
              "Marine Surveyor",
              "Maritime Consultant",
              "Shipping Coordinator",
            ],
          },
          {
            id: "btech-marine-engineering",
            name: "Bachelor of Engineering Technology in Marine Engineering",
            faculty: "Engineering and the Built Environment",
            duration: "4 years",
            apsRequirement: 30,
            description: "Marine engineering technology (CPUT specialty).",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Marine Engineer",
              "Ship Engineer",
              "Port Engineer",
              "Offshore Engineer",
              "Marine Systems Specialist",
            ],
          },
          {
            id: "bachelor-policing",
            name: "Bachelor of Policing",
            faculty: "Humanities",
            duration: "3 years",
            apsRequirement: 26,
            description: "Professional policing education (TUT specialty).",
            subjects: [
              { name: "English", level: 4, isRequired: true },
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "Life Orientation", level: 4, isRequired: false },
            ],
            careerProspects: [
              "Police Officer",
              "Detective",
              "Crime Analyst",
              "Security Manager",
              "Law Enforcement Specialist",
            ],
          },
          {
            id: "national-diploma-dance",
            name: "National Diploma in Dance",
            faculty: "Arts and Design",
            duration: "3 years",
            apsRequirement: 24,
            description: "Professional dance training (TUT specialty).",
            subjects: [
              { name: "English", level: 4, isRequired: true },
              { name: "Physical Education", level: 4, isRequired: false },
              { name: "Drama", level: 4, isRequired: false },
            ],
            careerProspects: [
              "Professional Dancer",
              "Choreographer",
              "Dance Teacher",
              "Performance Artist",
              "Dance Therapist",
            ],
          },
          {
            id: "bachelor-performing-arts-management",
            name: "Bachelor in Performing Arts Management",
            faculty: "Arts and Design",
            duration: "3 years",
            apsRequirement: 26,
            description: "Arts administration and management (TUT specialty).",
            subjects: [
              { name: "English", level: 5, isRequired: true },
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "Business Studies", level: 4, isRequired: false },
            ],
            careerProspects: [
              "Arts Manager",
              "Event Coordinator",
              "Theatre Manager",
              "Cultural Administrator",
              "Entertainment Industry Executive",
            ],
          },
          {
            id: "btech-electrical",
            name: "BTech Electrical Engineering",
            faculty: "Engineering and the Built Environment",
            duration: "4 years",
            apsRequirement: 32,
            description:
              "Electrical engineering technology with practical applications.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Electrical Engineering Technologist",
              "Power Systems Technician",
              "Control Systems Specialist",
              "Maintenance Engineer",
              "Technical Supervisor",
            ],
          },
          {
            id: "btech-mechanical",
            name: "BTech Mechanical Engineering",
            faculty: "Engineering and the Built Environment",
            duration: "4 years",
            apsRequirement: 32,
            description:
              "Mechanical engineering technology with manufacturing focus.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Mechanical Engineering Technologist",
              "Manufacturing Technician",
              "Maintenance Manager",
              "Quality Assurance Officer",
              "Production Supervisor",
            ],
          },
          {
            id: "btech-marine-engineering",
            name: "BTech Marine Engineering",
            faculty: "Engineering and the Built Environment",
            duration: "4 years",
            apsRequirement: 30,
            description:
              "Specialized marine engineering program (CPUT specialty).",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Marine Engineer",
              "Ship Engineering Officer",
              "Port Engineer",
              "Maritime Technical Specialist",
              "Naval Architect",
            ],
          },
          {
            id: "btech-industrial",
            name: "BTech Industrial Engineering",
            faculty: "Engineering and the Built Environment",
            duration: "4 years",
            apsRequirement: 30,
            description: "Industrial engineering with operations optimization.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Industrial Engineer",
              "Operations Manager",
              "Quality Manager",
              "Process Improvement Specialist",
              "Production Planner",
            ],
          },
          {
            id: "btech-chemical",
            name: "BTech Chemical Engineering",
            faculty: "Engineering and the Built Environment",
            duration: "4 years",
            apsRequirement: 32,
            description: "Chemical engineering technology with process focus.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 6, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Chemical Engineering Technologist",
              "Process Engineer",
              "Plant Operator",
              "Environmental Engineer",
              "Quality Control Analyst",
            ],
          },
          {
            id: "btech-surveying",
            name: "BTech Surveying",
            faculty: "Engineering and the Built Environment",
            duration: "4 years",
            apsRequirement: 28,
            description: "Land surveying and geomatics technology.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Land Surveyor",
              "GIS Specialist",
              "Geomatics Technologist",
              "Cartographer",
              "Mining Surveyor",
            ],
          },
          // Diploma Programs
          {
            id: "dip-civil-engineering",
            name: "Diploma in Civil Engineering",
            faculty: "Engineering and the Built Environment",
            duration: "3 years",
            apsRequirement: 26,
            description: "Foundation diploma in civil engineering technology.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "Physical Sciences", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Civil Engineering Technician",
              "Construction Supervisor",
              "Draughtsperson",
              "Site Inspector",
              "Project Assistant",
            ],
          },
          {
            id: "dip-electrical-engineering",
            name: "Diploma in Electrical Engineering",
            faculty: "Engineering and the Built Environment",
            duration: "3 years",
            apsRequirement: 26,
            description:
              "Foundation diploma in electrical engineering technology.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "Physical Sciences", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Electrical Technician",
              "Maintenance Technician",
              "Control Systems Technician",
              "Power Systems Operator",
              "Electrical Draughtsperson",
            ],
          },
          {
            id: "dip-mechanical-engineering",
            name: "Diploma in Mechanical Engineering",
            faculty: "Engineering and the Built Environment",
            duration: "3 years",
            apsRequirement: 26,
            description:
              "Foundation diploma in mechanical engineering technology.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "Physical Sciences", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Mechanical Technician",
              "Manufacturing Technician",
              "Maintenance Planner",
              "CAD Draughtsperson",
              "Quality Inspector",
            ],
          },
        ],
      },
      {
        id: "informatics",
        name: "Faculty of Informatics and Design",
        description: "Technology and design education for the digital age.",
        degrees: [
          {
            id: "btech-it",
            name: "BTech Information Technology",
            faculty: "Informatics and Design",
            duration: "4 years",
            apsRequirement: 30,
            description: "Comprehensive IT education with practical focus.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "IT Specialist",
              "Software Developer",
              "Network Administrator",
              "Database Administrator",
              "Systems Analyst",
            ],
          },
          {
            id: "btech-graphic-design",
            name: "BTech Graphic Design",
            faculty: "Informatics and Design",
            duration: "4 years",
            apsRequirement: 26,
            description: "Creative design education with digital focus.",
            subjects: [{ name: "English", level: 4, isRequired: true }],
            careerProspects: [
              "Graphic Designer",
              "Creative Director",
              "Digital Artist",
              "Brand Designer",
              "Web Designer",
            ],
          },
          {
            id: "diploma-it",
            name: "Diploma in Information Technology",
            faculty: "Informatics and Design",
            duration: "3 years",
            apsRequirement: 26,
            description: "Practical IT diploma program.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "IT Technician",
              "Help Desk Specialist",
              "Junior Developer",
              "Network Technician",
              "Database Operator",
            ],
          },
          {
            id: "bsc-information-systems",
            name: "BSc Information Systems",
            faculty: "Informatics and Design",
            duration: "3 years",
            apsRequirement: 28,
            description: "Information systems for business applications.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Systems Analyst",
              "Business Analyst",
              "IT Project Manager",
              "Database Designer",
              "Information Security Specialist",
            ],
          },
          {
            id: "diploma-nature-conservation",
            name: "Diploma in Nature Conservation",
            faculty: "Applied and Computer Sciences",
            duration: "3 years",
            apsRequirement: 24,
            description:
              "Nature conservation and wildlife management (MUT specialty).",
            subjects: [
              { name: "Life Sciences", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
              { name: "Geography", level: 4, isRequired: false },
            ],
            careerProspects: [
              "Conservation Officer",
              "Wildlife Researcher",
              "Game Ranger",
              "Environmental Educator",
              "Park Manager",
            ],
          },
          {
            id: "diploma-chemical-engineering",
            name: "Diploma in Chemical Engineering",
            faculty: "Engineering",
            duration: "3 years",
            apsRequirement: 28,
            description: "Chemical engineering technology (MUT specialty).",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Chemical Engineering Technician",
              "Process Technician",
              "Quality Control Technician",
              "Production Supervisor",
              "Plant Operator",
            ],
          },
          {
            id: "bachelor-computer-science",
            name: "Bachelor of Computer Science",
            faculty: "Informatics and Design",
            duration: "3 years",
            apsRequirement: 30,
            description: "Computer science with practical applications.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Software Developer",
              "Data Scientist",
              "Systems Programmer",
              "AI Developer",
              "Research Programmer",
            ],
          },
        ],
      },
      {
        id: "health",
        name: "Faculty of Health and Wellness Sciences",
        description: "Health sciences education with community focus.",
        degrees: [
          {
            id: "btech-nursing",
            name: "BTech Nursing",
            faculty: "Health and Wellness Sciences",
            duration: "4 years",
            apsRequirement: 28,
            description: "Practical nursing education with clinical training.",
            subjects: [
              { name: "English", level: 4, isRequired: true },
              { name: "Life Sciences", level: 4, isRequired: true },
              { name: "Mathematics", level: 3, isRequired: true },
            ],
            careerProspects: [
              "Registered Nurse",
              "Clinical Nurse",
              "Community Health Nurse",
              "Occupational Health Nurse",
              "Nurse Educator",
            ],
          },
          {
            id: "btech-emergency-medical-care",
            name: "BTech Emergency Medical Care",
            faculty: "Health and Wellness Sciences",
            duration: "4 years",
            apsRequirement: 30,
            description:
              "Emergency medical care specialization (CPUT specialty).",
            subjects: [
              { name: "English", level: 4, isRequired: true },
              { name: "Life Sciences", level: 5, isRequired: true },
              { name: "Mathematics", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Emergency Medical Technician",
              "Paramedic",
              "Emergency Room Technician",
              "Flight Medic",
              "Disaster Response Coordinator",
            ],
          },
          {
            id: "bsc-physiotherapy",
            name: "BSc Physiotherapy",
            faculty: "Health and Wellness Sciences",
            duration: "4 years",
            apsRequirement: 35,
            description: "Physiotherapy education with practical training.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "Life Sciences", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Physiotherapist",
              "Sports Physiotherapist",
              "Rehabilitation Specialist",
              "Private Practice Owner",
              "Hospital Physiotherapist",
            ],
          },
          {
            id: "bsc-occupational-therapy",
            name: "BSc Occupational Therapy",
            faculty: "Health and Wellness Sciences",
            duration: "4 years",
            apsRequirement: 33,
            description: "Occupational therapy with community focus.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "Life Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Occupational Therapist",
              "Rehabilitation Specialist",
              "Mental Health Therapist",
              "Pediatric Therapist",
              "Community Health Worker",
            ],
          },
        ],
      },
      {
        id: "business",
        name: "Faculty of Business and Management Sciences",
        description: "Business education with practical applications.",
        degrees: [
          {
            id: "btech-management",
            name: "BTech Management",
            faculty: "Business and Management Sciences",
            duration: "4 years",
            apsRequirement: 28,
            description: "Practical business management education.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Business Manager",
              "Operations Manager",
              "Project Manager",
              "Team Leader",
              "Business Analyst",
            ],
          },
          {
            id: "btech-marketing",
            name: "BTech Marketing",
            faculty: "Business and Management Sciences",
            duration: "4 years",
            apsRequirement: 26,
            description: "Marketing with digital focus.",
            subjects: [
              { name: "Mathematics", level: 3, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Marketing Coordinator",
              "Digital Marketing Specialist",
              "Brand Manager",
              "Sales Representative",
              "Market Researcher",
            ],
          },
          {
            id: "bcom-accounting",
            name: "BCom Accounting",
            faculty: "Business and Management Sciences",
            duration: "3 years",
            apsRequirement: 30,
            description: "Practical accounting education.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
              { name: "Accounting", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Accountant",
              "Bookkeeper",
              "Financial Administrator",
              "Tax Practitioner",
              "Audit Assistant",
            ],
          },
          {
            id: "bcom-hr-management",
            name: "BCom Human Resource Management",
            faculty: "Business and Management Sciences",
            duration: "3 years",
            apsRequirement: 28,
            description: "Human resource management with practical focus.",
            subjects: [
              { name: "Mathematics", level: 3, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "HR Officer",
              "Recruitment Specialist",
              "Training Coordinator",
              "Labor Relations Officer",
              "HR Administrator",
            ],
          },
        ],
      },
      {
        id: "applied-sciences",
        name: "Faculty of Applied Sciences",
        description: "Applied sciences with industry applications.",
        degrees: [
          {
            id: "diploma-maritime-studies",
            name: "Diploma in Maritime Studies",
            faculty: "Applied Sciences",
            duration: "3 years",
            apsRequirement: 24,
            description: "Maritime studies specialization (CPUT specialty).",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Marine Officer",
              "Port Operations Coordinator",
              "Shipping Agent",
              "Maritime Safety Inspector",
              "Naval Officer",
            ],
          },
          {
            id: "bsc-environmental-science",
            name: "BSc Environmental Science",
            faculty: "Applied Sciences",
            duration: "3 years",
            apsRequirement: 28,
            description: "Environmental science with practical applications.",
            subjects: [
              { name: "Life Sciences", level: 4, isRequired: true },
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Environmental Consultant",
              "Conservation Officer",
              "Environmental Specialist",
              "Sustainability Coordinator",
              "Environmental Technician",
            ],
          },
        ],
      },
      {
        id: "commerce",
        name: "Faculty of Management Sciences",
        description: "Business and management education.",
        degrees: [
          {
            id: "btech-accounting",
            name: "BTech Accounting",
            faculty: "Management Sciences",
            duration: "4 years",
            apsRequirement: 28,
            description: "Accounting technology with practical focus.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
              { name: "Accounting", level: 4, isRequired: false },
            ],
            careerProspects: [
              "Accounting Technician",
              "Financial Administrator",
              "Bookkeeper",
              "Tax Practitioner",
              "Audit Assistant",
            ],
          },
          {
            id: "btech-business-administration",
            name: "BTech Business Administration",
            faculty: "Management Sciences",
            duration: "4 years",
            apsRequirement: 26,
            description: "Business administration with management focus.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
              { name: "Business Studies", level: 4, isRequired: false },
            ],
            careerProspects: [
              "Business Administrator",
              "Office Manager",
              "Operations Coordinator",
              "Business Analyst",
              "Project Administrator",
            ],
          },
          {
            id: "btech-marketing",
            name: "BTech Marketing",
            faculty: "Management Sciences",
            duration: "4 years",
            apsRequirement: 26,
            description: "Marketing technology with digital focus.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
              { name: "Business Studies", level: 4, isRequired: false },
            ],
            careerProspects: [
              "Marketing Specialist",
              "Digital Marketing Coordinator",
              "Sales Representative",
              "Brand Assistant",
              "Market Research Assistant",
            ],
          },
        ],
      },
      {
        id: "information-technology",
        name: "Faculty of Applied and Computer Sciences",
        description: "Information technology and computer science education.",
        degrees: [
          {
            id: "btech-information-technology",
            name: "BTech Information Technology",
            faculty: "Applied and Computer Sciences",
            duration: "4 years",
            apsRequirement: 30,
            description: "Information technology with practical applications.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
              { name: "Physical Sciences", level: 4, isRequired: false },
            ],
            careerProspects: [
              "IT Specialist",
              "Systems Administrator",
              "Network Technician",
              "Software Developer",
              "Database Administrator",
            ],
          },
          {
            id: "diploma-information-technology",
            name: "Diploma in Information Technology",
            faculty: "Applied and Computer Sciences",
            duration: "3 years",
            apsRequirement: 26,
            description: "Foundation IT education.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
              { name: "Physical Sciences", level: 4, isRequired: false },
            ],
            careerProspects: [
              "IT Technician",
              "Help Desk Specialist",
              "Computer Technician",
              "Network Assistant",
              "Web Developer",
            ],
          },
        ],
      },
      {
        id: "humanities",
        name: "Faculty of Human Sciences",
        description: "Humanities and social sciences education.",
        degrees: [
          {
            id: "btech-language-practice",
            name: "BTech Language Practice",
            faculty: "Human Sciences",
            duration: "4 years",
            apsRequirement: 26,
            description: "Language services and translation studies.",
            subjects: [
              { name: "English", level: 5, isRequired: true },
              { name: "Second Language", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Translator",
              "Interpreter",
              "Language Editor",
              "Communications Specialist",
              "Language Consultant",
            ],
          },
          {
            id: "btech-public-relations",
            name: "BTech Public Relations",
            faculty: "Human Sciences",
            duration: "4 years",
            apsRequirement: 26,
            description: "Public relations and communications.",
            subjects: [
              { name: "English", level: 5, isRequired: true },
              { name: "Mathematics", level: 4, isRequired: true },
            ],
            careerProspects: [
              "PR Specialist",
              "Communications Manager",
              "Media Relations Officer",
              "Event Coordinator",
              "Marketing Communications Specialist",
            ],
          },
        ],
      },
    ],
  },
  {
    id: "dut",
    name: "Durban University of Technology",
    abbreviation: "DUT",
    fullName: "Durban University of Technology (DUT)",
    location: "Durban",
    province: "KwaZulu-Natal",
    logo: "https://images.unsplash.com/photo-1607013251379-e6eecfffe234?w=80&h=80&fit=crop&crop=center",
    overview:
      "A leading University of Technology committed to academic excellence and innovation in teaching, learning, research and engagement for the benefit of society.",
    website: "https://www.dut.ac.za",
    studentPortal: "https://students.dut.ac.za",
    admissionsContact: "admissions@dut.ac.za",
    faculties: [
      {
        id: "engineering",
        name: "Faculty of Engineering and the Built Environment",
        description:
          "Practical engineering education with industry partnerships.",
        degrees: [
          {
            id: "btech-civil",
            name: "BTech Civil Engineering",
            faculty: "Engineering and the Built Environment",
            duration: "4 years",
            apsRequirement: 30,
            description: "Civil engineering technology with practical focus.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Civil Engineering Technologist",
              "Construction Manager",
              "Project Coordinator",
              "Infrastructure Specialist",
              "Quality Controller",
            ],
          },
          {
            id: "btech-mechanical",
            name: "BTech Mechanical Engineering",
            faculty: "Engineering and the Built Environment",
            duration: "4 years",
            apsRequirement: 30,
            description:
              "Mechanical engineering with manufacturing applications.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Mechanical Engineering Technologist",
              "Manufacturing Technician",
              "Maintenance Manager",
              "Quality Assurance Officer",
              "Production Supervisor",
            ],
          },
          {
            id: "btech-electrical",
            name: "BTech Electrical Engineering",
            faculty: "Engineering and the Built Environment",
            duration: "4 years",
            apsRequirement: 30,
            description: "Electrical engineering technology applications.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Electrical Engineering Technologist",
              "Power Systems Technician",
              "Control Systems Specialist",
              "Maintenance Engineer",
              "Technical Supervisor",
            ],
          },
          {
            id: "beng-chemical",
            name: "BEng Chemical Engineering",
            faculty: "Engineering and the Built Environment",
            duration: "4 years",
            apsRequirement: 35,
            description: "Chemical engineering with process industry focus.",
            subjects: [
              { name: "Mathematics", level: 6, isRequired: true },
              { name: "Physical Sciences", level: 6, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Chemical Engineer",
              "Process Engineer",
              "Production Manager",
              "Quality Control Engineer",
              "Plant Manager",
            ],
          },
          {
            id: "beng-industrial",
            name: "BEng Industrial Engineering",
            faculty: "Engineering and the Built Environment",
            duration: "4 years",
            apsRequirement: 34,
            description: "Industrial engineering with operations focus.",
            subjects: [
              { name: "Mathematics", level: 6, isRequired: true },
              { name: "Physical Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Industrial Engineer",
              "Operations Research Analyst",
              "Quality Engineer",
              "Supply Chain Manager",
              "Process Improvement Specialist",
            ],
          },
        ],
      },
      {
        id: "management",
        name: "Faculty of Management Sciences",
        description: "Management education with entrepreneurship focus.",
        degrees: [
          {
            id: "btech-entrepreneurship",
            name: "BTech Entrepreneurship",
            faculty: "Management Sciences",
            duration: "4 years",
            apsRequirement: 26,
            description: "Entrepreneurship and business development education.",
            subjects: [
              { name: "Mathematics", level: 3, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Entrepreneur",
              "Business Developer",
              "Small Business Owner",
              "Business Consultant",
              "Innovation Manager",
            ],
          },
          {
            id: "btech-marketing",
            name: "BTech Marketing",
            faculty: "Management Sciences",
            duration: "4 years",
            apsRequirement: 26,
            description: "Marketing with digital and traditional approaches.",
            subjects: [
              { name: "Mathematics", level: 3, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Marketing Manager",
              "Digital Marketing Specialist",
              "Brand Manager",
              "Sales Manager",
              "Market Researcher",
            ],
          },
          {
            id: "bcom-accounting",
            name: "BCom Accounting",
            faculty: "Management Sciences",
            duration: "3 years",
            apsRequirement: 28,
            description: "Accounting education with technology integration.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
              { name: "Accounting", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Accountant",
              "Financial Administrator",
              "Bookkeeper",
              "Tax Practitioner",
              "Audit Assistant",
            ],
          },
          {
            id: "bcom-business-management",
            name: "BCom Business Management",
            faculty: "Management Sciences",
            duration: "3 years",
            apsRequirement: 26,
            description: "Business management with practical applications.",
            subjects: [
              { name: "Mathematics", level: 3, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Business Manager",
              "Operations Coordinator",
              "Project Administrator",
              "Team Leader",
              "Business Analyst",
            ],
          },
        ],
      },
      {
        id: "health",
        name: "Faculty of Health Sciences",
        description: "Health sciences with technology integration.",
        degrees: [
          {
            id: "bachelor-health-radiography",
            name: "Bachelor of Health Sciences in Radiography",
            faculty: "Health Sciences",
            duration: "4 years",
            apsRequirement: 32,
            description:
              "Medical imaging and radiography specialization (DUT specialty).",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "Physical Sciences", level: 5, isRequired: true },
              { name: "Life Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Radiographer",
              "Medical Imaging Technologist",
              "CT Technologist",
              "MRI Technologist",
              "Radiation Therapist",
            ],
          },
          {
            id: "diploma-clinical-technology",
            name: "Diploma in Clinical Technology",
            faculty: "Health Sciences",
            duration: "3 years",
            apsRequirement: 30,
            description: "Clinical technology specialization (DUT specialty).",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "Physical Sciences", level: 4, isRequired: true },
              { name: "Life Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Clinical Technologist",
              "Medical Equipment Technician",
              "Biomedical Engineer",
              "Hospital Technician",
              "Medical Device Specialist",
            ],
          },
          {
            id: "bnurs-nursing",
            name: "BCur/BNurs Nursing",
            faculty: "Health Sciences",
            duration: "4 years",
            apsRequirement: 28,
            description: "Nursing education with clinical excellence.",
            subjects: [
              { name: "English", level: 4, isRequired: true },
              { name: "Life Sciences", level: 4, isRequired: true },
              { name: "Mathematics", level: 3, isRequired: true },
            ],
            careerProspects: [
              "Registered Nurse",
              "Clinical Nurse Specialist",
              "Nurse Manager",
              "Community Health Nurse",
              "Critical Care Nurse",
            ],
          },
        ],
      },
      {
        id: "applied-sciences",
        name: "Faculty of Applied Sciences",
        description: "Applied sciences with industry focus.",
        degrees: [
          {
            id: "bsc-computer-science",
            name: "BSc Computer Science",
            faculty: "Applied Sciences",
            duration: "3 years",
            apsRequirement: 30,
            description: "Computer science with practical applications.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Software Developer",
              "Systems Analyst",
              "Database Administrator",
              "IT Consultant",
              "Web Developer",
            ],
          },
          {
            id: "diploma-game-design",
            name: "Diploma in Game Design",
            faculty: "Applied Sciences",
            duration: "3 years",
            apsRequirement: 24,
            description:
              "Game design and development specialization (DUT specialty).",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Game Designer",
              "Game Developer",
              "3D Artist",
              "Animation Specialist",
              "Interactive Media Designer",
            ],
          },
          {
            id: "bsc-information-systems",
            name: "BSc Information Systems",
            faculty: "Applied Sciences",
            duration: "3 years",
            apsRequirement: 28,
            description: "Information systems for business solutions.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Systems Analyst",
              "Business Analyst",
              "IT Project Manager",
              "Database Designer",
              "Information Security Specialist",
            ],
          },
        ],
      },
      {
        id: "arts-design",
        name: "Faculty of Arts and Design",
        description: "Creative arts and design education.",
        degrees: [
          {
            id: "diploma-graphic-design",
            name: "Diploma in Graphic Design",
            faculty: "Arts and Design",
            duration: "3 years",
            apsRequirement: 24,
            description: "Visual communication and graphic design.",
            subjects: [{ name: "English", level: 4, isRequired: true }],
            careerProspects: [
              "Graphic Designer",
              "Creative Director",
              "Brand Designer",
              "Web Designer",
              "Advertising Designer",
            ],
          },
          {
            id: "bachelor-fine-art",
            name: "Bachelor of Arts in Fine Art",
            faculty: "Arts and Design",
            duration: "4 years",
            apsRequirement: 25,
            description: "Fine arts with contemporary approaches.",
            subjects: [{ name: "English", level: 4, isRequired: true }],
            careerProspects: [
              "Artist",
              "Art Teacher",
              "Gallery Curator",
              "Art Therapist",
              "Creative Director",
            ],
          },
          {
            id: "bachelor-film-tv",
            name: "Bachelor of Film and Television Production",
            faculty: "Arts and Design",
            duration: "3 years",
            apsRequirement: 26,
            description: "Film and television production education.",
            subjects: [{ name: "English", level: 4, isRequired: true }],
            careerProspects: [
              "Film Director",
              "Video Producer",
              "Cinematographer",
              "Film Editor",
              "Television Producer",
            ],
          },
        ],
      },
    ],
  },
  {
    id: "tut",
    name: "Tshwane University of Technology",
    abbreviation: "TUT",
    fullName: "Tshwane University of Technology (TUT)",
    location: "Pretoria",
    province: "Gauteng",
    logo: "https://images.unsplash.com/photo-1607013251379-e6eecfffe234?w=80&h=80&fit=crop&crop=center",
    overview:
      "One of the largest universities of technology in South Africa, offering career-focused education with strong industry partnerships and practical training.",
    website: "https://www.tut.ac.za",
    studentPortal: "https://students.tut.ac.za",
    admissionsContact: "admissions@tut.ac.za",
    faculties: [
      {
        id: "engineering",
        name: "Faculty of Engineering and the Built Environment",
        description:
          "Comprehensive engineering education with practical focus.",
        degrees: [
          {
            id: "btech-civil",
            name: "BTech Civil Engineering",
            faculty: "Engineering and the Built Environment",
            duration: "4 years",
            apsRequirement: 30,
            description:
              "Civil engineering technology with infrastructure focus.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Civil Engineering Technologist",
              "Construction Manager",
              "Project Coordinator",
              "Infrastructure Specialist",
              "Quality Controller",
            ],
          },
          {
            id: "btech-electrical",
            name: "BTech Electrical Engineering",
            faculty: "Engineering and the Built Environment",
            duration: "4 years",
            apsRequirement: 30,
            description: "Electrical engineering with power systems focus.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Electrical Engineering Technologist",
              "Power Systems Technician",
              "Control Systems Specialist",
              "Maintenance Engineer",
              "Technical Supervisor",
            ],
          },
          {
            id: "btech-mechanical",
            name: "BTech Mechanical Engineering",
            faculty: "Engineering and the Built Environment",
            duration: "4 years",
            apsRequirement: 30,
            description:
              "Mechanical engineering with manufacturing applications.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Mechanical Engineering Technologist",
              "Manufacturing Technician",
              "Maintenance Manager",
              "Quality Assurance Officer",
              "Production Supervisor",
            ],
          },
          {
            id: "btech-chemical",
            name: "BTech Chemical Engineering",
            faculty: "Engineering and the Built Environment",
            duration: "4 years",
            apsRequirement: 32,
            description: "Chemical engineering technology applications.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Chemical Engineering Technologist",
              "Process Technician",
              "Production Supervisor",
              "Quality Control Technician",
              "Plant Operator",
            ],
          },
          {
            id: "btech-industrial",
            name: "BTech Industrial Engineering",
            faculty: "Engineering and the Built Environment",
            duration: "4 years",
            apsRequirement: 30,
            description: "Industrial engineering with operations focus.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Industrial Engineering Technologist",
              "Operations Coordinator",
              "Quality Supervisor",
              "Production Planner",
              "Process Improvement Specialist",
            ],
          },
        ],
      },
      {
        id: "ict",
        name: "Faculty of Information and Communication Technology",
        description: "ICT education with industry-relevant curriculum.",
        degrees: [
          {
            id: "btech-it",
            name: "BTech Information Technology",
            faculty: "Information and Communication Technology",
            duration: "4 years",
            apsRequirement: 28,
            description:
              "Comprehensive IT education with practical applications.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "IT Specialist",
              "Software Developer",
              "Network Administrator",
              "Database Administrator",
              "Systems Analyst",
            ],
          },
          {
            id: "bsc-computer-science",
            name: "BSc Computer Science",
            faculty: "Information and Communication Technology",
            duration: "3 years",
            apsRequirement: 30,
            description: "Computer science with programming focus.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Software Developer",
              "Systems Programmer",
              "Data Scientist",
              "AI Developer",
              "Research Programmer",
            ],
          },
          {
            id: "bsc-information-systems",
            name: "BSc Information Systems",
            faculty: "Information and Communication Technology",
            duration: "3 years",
            apsRequirement: 28,
            description: "Information systems for business applications.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Systems Analyst",
              "Business Analyst",
              "IT Project Manager",
              "Database Designer",
              "Information Security Specialist",
            ],
          },
          {
            id: "diploma-it",
            name: "Diploma in Information Technology",
            faculty: "Information and Communication Technology",
            duration: "3 years",
            apsRequirement: 24,
            description: "Practical IT diploma program.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "IT Technician",
              "Help Desk Specialist",
              "Junior Developer",
              "Network Technician",
              "Database Operator",
            ],
          },
        ],
      },
      {
        id: "management",
        name: "Faculty of Management Sciences",
        description:
          "Management education with practical business applications.",
        degrees: [
          {
            id: "bcom-accounting",
            name: "BCom Accounting",
            faculty: "Management Sciences",
            duration: "3 years",
            apsRequirement: 28,
            description:
              "Practical accounting education with technology integration.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
              { name: "Accounting", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Accountant",
              "Financial Administrator",
              "Bookkeeper",
              "Tax Practitioner",
              "Audit Assistant",
            ],
          },
          {
            id: "bcom-business-management",
            name: "BCom Business Management",
            faculty: "Management Sciences",
            duration: "3 years",
            apsRequirement: 26,
            description: "Business management with entrepreneurship focus.",
            subjects: [
              { name: "Mathematics", level: 3, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Business Manager",
              "Operations Coordinator",
              "Project Administrator",
              "Team Leader",
              "Business Analyst",
            ],
          },
          {
            id: "bcom-marketing",
            name: "BCom Marketing",
            faculty: "Management Sciences",
            duration: "3 years",
            apsRequirement: 25,
            description: "Marketing with digital and traditional strategies.",
            subjects: [
              { name: "Mathematics", level: 3, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Marketing Coordinator",
              "Digital Marketing Specialist",
              "Brand Manager",
              "Sales Representative",
              "Market Researcher",
            ],
          },
        ],
      },
      {
        id: "humanities",
        name: "Faculty of Humanities",
        description: "Humanities education with practical applications.",
        degrees: [
          {
            id: "bachelor-policing",
            name: "Bachelor of Policing",
            faculty: "Humanities",
            duration: "3 years",
            apsRequirement: 26,
            description:
              "Policing and criminal justice specialization (TUT specialty).",
            subjects: [
              { name: "English", level: 4, isRequired: true },
              { name: "Mathematics", level: 3, isRequired: true },
            ],
            careerProspects: [
              "Police Officer",
              "Detective",
              "Crime Prevention Officer",
              "Security Manager",
              "Criminal Justice Administrator",
            ],
          },
          {
            id: "diploma-dance",
            name: "National Diploma in Dance",
            faculty: "Humanities",
            duration: "3 years",
            apsRequirement: 22,
            description:
              "Dance performance and choreography specialization (TUT specialty).",
            subjects: [{ name: "English", level: 4, isRequired: true }],
            careerProspects: [
              "Professional Dancer",
              "Choreographer",
              "Dance Teacher",
              "Performance Artist",
              "Arts Administrator",
            ],
          },
          {
            id: "bachelor-performing-arts",
            name: "Bachelor in Performing Arts Management",
            faculty: "Humanities",
            duration: "3 years",
            apsRequirement: 24,
            description:
              "Performing arts management specialization (TUT specialty).",
            subjects: [{ name: "English", level: 4, isRequired: true }],
            careerProspects: [
              "Arts Manager",
              "Event Coordinator",
              "Theatre Manager",
              "Cultural Administrator",
              "Entertainment Producer",
            ],
          },
          {
            id: "ba-psychology",
            name: "BA Psychology",
            faculty: "Humanities",
            duration: "3 years",
            apsRequirement: 26,
            description: "Psychology with practical applications.",
            subjects: [
              { name: "English", level: 4, isRequired: true },
              { name: "Mathematics", level: 3, isRequired: true },
            ],
            careerProspects: [
              "Psychologist",
              "Counselor",
              "Human Resources Specialist",
              "Research Assistant",
              "Social Worker",
            ],
          },
        ],
      },
      {
        id: "health",
        name: "Faculty of Science",
        description: "Science education with health and environmental focus.",
        degrees: [
          {
            id: "bnurs-nursing",
            name: "BCur/BNurs Nursing",
            faculty: "Science",
            duration: "4 years",
            apsRequirement: 28,
            description: "Nursing education with clinical excellence.",
            subjects: [
              { name: "English", level: 4, isRequired: true },
              { name: "Life Sciences", level: 4, isRequired: true },
              { name: "Mathematics", level: 3, isRequired: true },
            ],
            careerProspects: [
              "Registered Nurse",
              "Clinical Nurse Specialist",
              "Nurse Manager",
              "Community Health Nurse",
              "Critical Care Nurse",
            ],
          },
          {
            id: "bsc-environmental-science",
            name: "BSc Environmental Science",
            faculty: "Science",
            duration: "3 years",
            apsRequirement: 28,
            description: "Environmental science with sustainability focus.",
            subjects: [
              { name: "Life Sciences", level: 4, isRequired: true },
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Environmental Consultant",
              "Conservation Officer",
              "Environmental Specialist",
              "Sustainability Coordinator",
              "Environmental Technician",
            ],
          },
        ],
      },
    ],
  },
  {
    id: "vut",
    name: "Vaal University of Technology",
    abbreviation: "VUT",
    fullName: "Vaal University of Technology (VUT)",
    location: "Vanderbijlpark",
    province: "Gauteng",
    logo: "https://images.unsplash.com/photo-1607013251379-e6eecfffe234?w=80&h=80&fit=crop&crop=center",
    overview:
      "A comprehensive University of Technology committed to teaching, learning, research and community engagement.",
    website: "https://www.vut.ac.za",
    studentPortal: "https://students.vut.ac.za",
    admissionsContact: "admissions@vut.ac.za",
    faculties: [
      {
        id: "engineering",
        name: "Faculty of Engineering and Technology",
        description:
          "Engineering and technology education with practical focus.",
        degrees: [
          {
            id: "btech-mechanical",
            name: "BTech Mechanical Engineering",
            faculty: "Engineering and Technology",
            duration: "4 years",
            apsRequirement: 28,
            description: "Mechanical engineering with manufacturing focus.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Mechanical Engineering Technologist",
              "Manufacturing Technician",
              "Maintenance Manager",
              "Quality Assurance Officer",
              "Production Supervisor",
            ],
          },
          {
            id: "btech-electrical",
            name: "BTech Electrical Engineering",
            faculty: "Engineering and Technology",
            duration: "4 years",
            apsRequirement: 28,
            description:
              "Electrical engineering with power systems applications.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Electrical Engineering Technologist",
              "Power Systems Technician",
              "Control Systems Specialist",
              "Maintenance Engineer",
              "Technical Supervisor",
            ],
          },
          {
            id: "btech-civil",
            name: "BTech Civil Engineering",
            faculty: "Engineering and Technology",
            duration: "4 years",
            apsRequirement: 28,
            description:
              "Civil engineering technology with construction focus.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Civil Engineering Technologist",
              "Construction Manager",
              "Project Coordinator",
              "Infrastructure Specialist",
              "Quality Controller",
            ],
          },
        ],
      },
      {
        id: "management",
        name: "Faculty of Management Sciences",
        description: "Management and business education.",
        degrees: [
          {
            id: "bcom-accounting",
            name: "BCom Accounting",
            faculty: "Management Sciences",
            duration: "3 years",
            apsRequirement: 26,
            description: "Accounting education with practical applications.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
              { name: "Accounting", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Accountant",
              "Financial Administrator",
              "Bookkeeper",
              "Tax Practitioner",
              "Audit Assistant",
            ],
          },
          {
            id: "bcom-business-management",
            name: "BCom Business Management",
            faculty: "Management Sciences",
            duration: "3 years",
            apsRequirement: 24,
            description: "Business management with entrepreneurship focus.",
            subjects: [
              { name: "Mathematics", level: 3, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Business Manager",
              "Operations Coordinator",
              "Project Administrator",
              "Team Leader",
              "Business Analyst",
            ],
          },
        ],
      },
      {
        id: "applied-sciences",
        name: "Faculty of Applied and Computer Sciences",
        description: "Applied sciences and computer science education.",
        degrees: [
          {
            id: "bsc-computer-science",
            name: "BSc Computer Science",
            faculty: "Applied and Computer Sciences",
            duration: "3 years",
            apsRequirement: 28,
            description: "Computer science with practical programming focus.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Software Developer",
              "Systems Analyst",
              "Database Administrator",
              "IT Consultant",
              "Web Developer",
            ],
          },
          {
            id: "bsc-information-systems",
            name: "BSc Information Systems",
            faculty: "Applied and Computer Sciences",
            duration: "3 years",
            apsRequirement: 26,
            description: "Information systems for business solutions.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Systems Analyst",
              "Business Analyst",
              "IT Project Manager",
              "Database Designer",
              "Information Security Specialist",
            ],
          },
        ],
      },
      {
        id: "commerce",
        name: "Faculty of Management Sciences",
        description: "Business and management education for the Vaal region.",
        degrees: [
          {
            id: "btech-accounting",
            name: "BTech Accounting",
            faculty: "Management Sciences",
            duration: "4 years",
            apsRequirement: 26,
            description: "Accounting technology with industrial focus.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
              { name: "Accounting", level: 4, isRequired: false },
            ],
            careerProspects: [
              "Industrial Accountant",
              "Cost Accountant",
              "Financial Administrator",
              "Bookkeeper",
              "Tax Practitioner",
            ],
          },
          {
            id: "btech-marketing",
            name: "BTech Marketing",
            faculty: "Management Sciences",
            duration: "4 years",
            apsRequirement: 24,
            description: "Marketing with industrial applications.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
              { name: "Business Studies", level: 4, isRequired: false },
            ],
            careerProspects: [
              "Industrial Marketing Specialist",
              "Sales Representative",
              "Marketing Coordinator",
              "Business Development Officer",
              "Product Manager",
            ],
          },
        ],
      },
      {
        id: "applied-sciences",
        name: "Faculty of Applied and Computer Sciences",
        description: "Applied sciences and information technology education.",
        degrees: [
          {
            id: "btech-information-technology",
            name: "BTech Information Technology",
            faculty: "Applied and Computer Sciences",
            duration: "4 years",
            apsRequirement: 28,
            description: "Information technology with industrial applications.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
              { name: "Physical Sciences", level: 4, isRequired: false },
            ],
            careerProspects: [
              "IT Specialist",
              "Systems Administrator",
              "Network Technician",
              "Software Developer",
              "Database Administrator",
            ],
          },
          {
            id: "diploma-information-technology",
            name: "Diploma in Information Technology",
            faculty: "Applied and Computer Sciences",
            duration: "3 years",
            apsRequirement: 24,
            description: "Foundation IT education.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "IT Technician",
              "Computer Operator",
              "Help Desk Support",
              "Web Developer",
              "Network Assistant",
            ],
          },
          {
            id: "bsc-computer-science",
            name: "BSc Computer Science",
            faculty: "Applied and Computer Sciences",
            duration: "3 years",
            apsRequirement: 28,
            description: "Computer science with programming focus.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
              { name: "Physical Sciences", level: 4, isRequired: false },
            ],
            careerProspects: [
              "Software Developer",
              "Systems Analyst",
              "Database Developer",
              "IT Consultant",
              "Web Application Developer",
            ],
          },
        ],
      },
      {
        id: "humanities",
        name: "Faculty of Human Sciences",
        description: "Human sciences and social development education.",
        degrees: [
          {
            id: "ba-psychology",
            name: "BA Psychology",
            faculty: "Human Sciences",
            duration: "3 years",
            apsRequirement: 24,
            description: "Psychology with community focus.",
            subjects: [
              { name: "English", level: 4, isRequired: true },
              { name: "Mathematics", level: 3, isRequired: true },
            ],
            careerProspects: [
              "Community Psychologist",
              "Counselor",
              "Human Resources Assistant",
              "Social Worker",
              "Research Assistant",
            ],
          },
          {
            id: "diploma-public-relations",
            name: "Diploma in Public Relations",
            faculty: "Human Sciences",
            duration: "3 years",
            apsRequirement: 22,
            description: "Public relations and communications.",
            subjects: [
              { name: "English", level: 4, isRequired: true },
              { name: "Mathematics", level: 3, isRequired: true },
            ],
            careerProspects: [
              "Public Relations Officer",
              "Communications Assistant",
              "Media Liaison",
              "Event Coordinator",
              "Marketing Assistant",
            ],
          },
        ],
      },
    ],
  },
  {
    id: "cut",
    name: "Central University of Technology",
    abbreviation: "CUT",
    fullName: "Central University of Technology (CUT)",
    location: "Bloemfontein",
    province: "Free State",
    logo: "https://images.unsplash.com/photo-1607013251379-e6eecfffe234?w=80&h=80&fit=crop&crop=center",
    overview:
      "A comprehensive University of Technology offering quality education and training in response to local and national skills needs.",
    website: "https://www.cut.ac.za",
    studentPortal: "https://students.cut.ac.za",
    admissionsContact: "admissions@cut.ac.za",
    faculties: [
      {
        id: "engineering",
        name: "Faculty of Engineering and Information Technology",
        description: "Engineering and IT education with practical focus.",
        degrees: [
          {
            id: "btech-civil",
            name: "BTech Civil Engineering",
            faculty: "Engineering and Information Technology",
            duration: "4 years",
            apsRequirement: 28,
            description:
              "Civil engineering technology with infrastructure development focus.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Civil Engineering Technologist",
              "Construction Manager",
              "Project Coordinator",
              "Infrastructure Specialist",
              "Quality Controller",
            ],
          },
          {
            id: "btech-electrical",
            name: "BTech Electrical Engineering",
            faculty: "Engineering and Information Technology",
            duration: "4 years",
            apsRequirement: 28,
            description: "Electrical engineering with power systems focus.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Electrical Engineering Technologist",
              "Power Systems Technician",
              "Control Systems Specialist",
              "Maintenance Engineer",
              "Technical Supervisor",
            ],
          },
          {
            id: "btech-it",
            name: "BTech Information Technology",
            faculty: "Engineering and Information Technology",
            duration: "4 years",
            apsRequirement: 26,
            description: "Information technology with business applications.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "IT Specialist",
              "Software Developer",
              "Network Administrator",
              "Database Administrator",
              "Systems Analyst",
            ],
          },
        ],
      },
      {
        id: "management",
        name: "Faculty of Management Sciences",
        description: "Management and business education.",
        degrees: [
          {
            id: "bcom-accounting",
            name: "BCom Accounting",
            faculty: "Management Sciences",
            duration: "3 years",
            apsRequirement: 26,
            description: "Accounting education with practical focus.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
              { name: "Accounting", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Accountant",
              "Financial Administrator",
              "Bookkeeper",
              "Tax Practitioner",
              "Audit Assistant",
            ],
          },
          {
            id: "bcom-business-management",
            name: "BCom Business Management",
            faculty: "Management Sciences",
            duration: "3 years",
            apsRequirement: 24,
            description: "Business management with regional development focus.",
            subjects: [
              { name: "Mathematics", level: 3, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Business Manager",
              "Operations Coordinator",
              "Project Administrator",
              "Team Leader",
              "Business Analyst",
            ],
          },
        ],
      },
      {
        id: "health",
        name: "Faculty of Health and Environmental Sciences",
        description: "Health and environmental sciences education.",
        degrees: [
          {
            id: "bnurs-nursing",
            name: "BCur/BNurs Nursing",
            faculty: "Health and Environmental Sciences",
            duration: "4 years",
            apsRequirement: 26,
            description: "Nursing education with community health focus.",
            subjects: [
              { name: "English", level: 4, isRequired: true },
              { name: "Life Sciences", level: 4, isRequired: true },
              { name: "Mathematics", level: 3, isRequired: true },
            ],
            careerProspects: [
              "Registered Nurse",
              "Clinical Nurse Specialist",
              "Nurse Manager",
              "Community Health Nurse",
              "Critical Care Nurse",
            ],
          },
          {
            id: "bsc-environmental-science",
            name: "BSc Environmental Science",
            faculty: "Health and Environmental Sciences",
            duration: "3 years",
            apsRequirement: 26,
            description: "Environmental science with regional applications.",
            subjects: [
              { name: "Life Sciences", level: 4, isRequired: true },
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Environmental Consultant",
              "Conservation Officer",
              "Environmental Specialist",
              "Sustainability Coordinator",
              "Environmental Technician",
            ],
          },
        ],
      },
      {
        id: "commerce",
        name: "Faculty of Management Sciences",
        description: "Business and management education for Free State region.",
        degrees: [
          {
            id: "btech-accounting",
            name: "BTech Accounting",
            faculty: "Management Sciences",
            duration: "4 years",
            apsRequirement: 26,
            description: "Accounting technology education.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
              { name: "Accounting", level: 4, isRequired: false },
            ],
            careerProspects: [
              "Accounting Technician",
              "Financial Administrator",
              "Bookkeeper",
              "Tax Assistant",
              "Audit Clerk",
            ],
          },
          {
            id: "btech-business-administration",
            name: "BTech Business Administration",
            faculty: "Management Sciences",
            duration: "4 years",
            apsRequirement: 24,
            description: "Business administration and management.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
              { name: "Business Studies", level: 4, isRequired: false },
            ],
            careerProspects: [
              "Business Administrator",
              "Operations Manager",
              "Project Coordinator",
              "Office Manager",
              "Small Business Owner",
            ],
          },
        ],
      },
      {
        id: "health-sciences",
        name: "Faculty of Health and Environmental Sciences",
        description: "Health sciences education.",
        degrees: [
          {
            id: "btech-environmental-health",
            name: "BTech Environmental Health",
            faculty: "Health and Environmental Sciences",
            duration: "4 years",
            apsRequirement: 26,
            description: "Environmental health and safety.",
            subjects: [
              { name: "Life Sciences", level: 4, isRequired: true },
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "Physical Sciences", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Environmental Health Officer",
              "Health and Safety Officer",
              "Environmental Specialist",
              "Public Health Inspector",
              "Occupational Health Specialist",
            ],
          },
          {
            id: "diploma-nursing",
            name: "Diploma in Nursing",
            faculty: "Health and Environmental Sciences",
            duration: "3 years",
            apsRequirement: 24,
            description: "Nursing education for community health.",
            subjects: [
              { name: "Life Sciences", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
              { name: "Mathematics", level: 3, isRequired: true },
            ],
            careerProspects: [
              "Enrolled Nurse",
              "Community Health Worker",
              "Clinical Assistant",
              "Healthcare Worker",
              "Primary Healthcare Nurse",
            ],
          },
        ],
      },
      {
        id: "humanities",
        name: "Faculty of Humanities",
        description: "Humanities and social sciences education.",
        degrees: [
          {
            id: "diploma-language-practice",
            name: "Diploma in Language Practice",
            faculty: "Humanities",
            duration: "3 years",
            apsRequirement: 22,
            description: "Language services and communication.",
            subjects: [
              { name: "English", level: 4, isRequired: true },
              { name: "Afrikaans", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Translator",
              "Language Editor",
              "Communications Assistant",
              "Administrative Officer",
              "Language Consultant",
            ],
          },
        ],
      },
    ],
  },
  {
    id: "mut",
    name: "Mangosuthu University of Technology",
    abbreviation: "MUT",
    fullName: "Mangosuthu University of Technology (MUT)",
    location: "Durban",
    province: "KwaZulu-Natal",
    logo: "https://images.unsplash.com/photo-1607013251379-e6eecfffe234?w=80&h=80&fit=crop&crop=center",
    overview:
      "A comprehensive University of Technology committed to providing quality higher education and research.",
    website: "https://www.mut.ac.za",
    studentPortal: "https://students.mut.ac.za",
    admissionsContact: "admissions@mut.ac.za",
    faculties: [
      {
        id: "engineering",
        name: "Faculty of Engineering",
        description: "Engineering education with industry partnerships.",
        degrees: [
          {
            id: "btech-civil",
            name: "BTech Civil Engineering",
            faculty: "Engineering",
            duration: "4 years",
            apsRequirement: 28,
            description:
              "Civil engineering technology with practical applications.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Civil Engineering Technologist",
              "Construction Manager",
              "Project Coordinator",
              "Infrastructure Specialist",
              "Quality Controller",
            ],
          },
          {
            id: "diploma-chemical-engineering",
            name: "Diploma in Chemical Engineering",
            faculty: "Engineering",
            duration: "3 years",
            apsRequirement: 26,
            description:
              "Chemical engineering technology specialization (MUT specialty).",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "Physical Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Chemical Engineering Technician",
              "Process Technician",
              "Quality Control Technician",
              "Plant Operator",
              "Production Assistant",
            ],
          },
          {
            id: "btech-electrical",
            name: "BTech Electrical Engineering",
            faculty: "Engineering",
            duration: "4 years",
            apsRequirement: 28,
            description: "Electrical engineering with power systems focus.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "Physical Sciences", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Electrical Engineering Technologist",
              "Power Systems Technician",
              "Control Systems Specialist",
              "Maintenance Engineer",
              "Technical Supervisor",
            ],
          },
        ],
      },
      {
        id: "management",
        name: "Faculty of Management Sciences",
        description: "Management education with business focus.",
        degrees: [
          {
            id: "bcom-accounting",
            name: "BCom Accounting",
            faculty: "Management Sciences",
            duration: "3 years",
            apsRequirement: 26,
            description: "Accounting education with practical applications.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
              { name: "Accounting", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Accountant",
              "Financial Administrator",
              "Bookkeeper",
              "Tax Practitioner",
              "Audit Assistant",
            ],
          },
          {
            id: "bcom-business-management",
            name: "BCom Business Management",
            faculty: "Management Sciences",
            duration: "3 years",
            apsRequirement: 24,
            description: "Business management with entrepreneurship focus.",
            subjects: [
              { name: "Mathematics", level: 3, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Business Manager",
              "Operations Coordinator",
              "Project Administrator",
              "Team Leader",
              "Business Analyst",
            ],
          },
        ],
      },
      {
        id: "natural-sciences",
        name: "Faculty of Natural Sciences",
        description: "Natural sciences with environmental focus.",
        degrees: [
          {
            id: "diploma-nature-conservation",
            name: "Diploma in Nature Conservation",
            faculty: "Natural Sciences",
            duration: "3 years",
            apsRequirement: 24,
            description: "Nature conservation specialization (MUT specialty).",
            subjects: [
              { name: "Life Sciences", level: 4, isRequired: true },
              { name: "Mathematics", level: 3, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Conservation Officer",
              "Game Ranger",
              "Environmental Educator",
              "Wildlife Technician",
              "Park Ranger",
            ],
          },
          {
            id: "bsc-computer-science",
            name: "BSc Computer Science",
            faculty: "Natural Sciences",
            duration: "3 years",
            apsRequirement: 28,
            description: "Computer science with practical applications.",
            subjects: [
              { name: "Mathematics", level: 5, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Software Developer",
              "Systems Analyst",
              "Database Administrator",
              "IT Consultant",
              "Web Developer",
            ],
          },
          {
            id: "bsc-information-systems",
            name: "BSc Information Systems",
            faculty: "Natural Sciences",
            duration: "3 years",
            apsRequirement: 26,
            description: "Information systems for business solutions.",
            subjects: [
              { name: "Mathematics", level: 4, isRequired: true },
              { name: "English", level: 4, isRequired: true },
            ],
            careerProspects: [
              "Systems Analyst",
              "Business Analyst",
              "IT Project Manager",
              "Database Designer",
              "Information Security Specialist",
            ],
          },
        ],
      },
      {
        id: "humanities",
        name: "Faculty of Humanities",
        description: "Humanities education with cultural focus.",
        degrees: [
          {
            id: "ba-psychology",
            name: "BA Psychology",
            faculty: "Humanities",
            duration: "3 years",
            apsRequirement: 24,
            description: "Psychology with community applications.",
            subjects: [
              { name: "English", level: 4, isRequired: true },
              { name: "Mathematics", level: 3, isRequired: true },
            ],
            careerProspects: [
              "Psychologist",
              "Counselor",
              "Human Resources Specialist",
              "Research Assistant",
              "Social Worker",
            ],
          },
        ],
      },
    ],
  },
];
